### ISSUE TITLE
 set the GOOGLE_APPLICATION_CREDENTIALS environment variable to the path to the key file

### ISSUE THREAD

**Issue by scripter-win** [GoogleCloudPlatform/python-docs-samples#1008]
## Describe the issue
sorry , I am a noob and I use windows 10 system
Here is my question
How can I  set the GOOGLE_APPLICATION_CREDENTIALS environment variable to the path to the key file, just create a new  environment variable named GOOGLE_APPLICATION_CREDENTIALS point to the file?
and what dose the export in description mean?

**Comment by jonparrott** [comment]
Yep, you can use `set GOOGLE_APPLICATION_CREDENTIALS="C:\..."`.
