### ISSUE TITLE
empty firefox browser

### ISSUE THREAD

**Issue by samsammurphy** [GoogleCloudPlatform/python-docs-samples#1014]
## In which file did you encounter the issue?

python-docs-samples/appengine/standard/flask/tutorial/templates/form.html
python-docs-samples/appengine/standard/flask/tutorial/templates/submitted_form.html

### Did you change the file? If so, how?

```
<html>
  <head>
    <meta charset="utf-8"/>
    ...
```

## Describe the issue

The app does not render the html templates in firefox (although they do render when opened up by the browser outside of the app). This is what the FireFox Developer Tools console said:

> The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

**Comment by jonparrott** [comment]
@andrewsg can you take a look at this?

**Comment by andrewsg** [comment]
I was unable to reproduce this issue on GAE Standard, even after submitting non-ASCII character responses in the form. On inspection of the response, I can see that the response headers  include Content-Type: "text/html; charset=utf-8" as expected, which should prevent any confusion on the browser side.

@samsammurphy, do you have any idea what might be specific about your deployment that would cause the Content-Type header to not include an encoding?

**Comment by samsammurphy** [comment]
kind of embarrassing..I didn't read the error msg telling me the couldn't find flask.
![browser and error msg](https://user-images.githubusercontent.com/16657983/28353681-8d4aa6fc-6bf8-11e7-987d-b1774a3fac71.png)
(sorry)

**Comment by samsammurphy** [comment]
after installing flask into lib
![install flask in lib](https://user-images.githubusercontent.com/16657983/28353710-a9bc7e1e-6bf8-11e7-9f8a-5d10675762be.png)

**Comment by samsammurphy** [comment]
I seem to get sandoxed in?
![sandboxed](https://user-images.githubusercontent.com/16657983/28353722-bd00e258-6bf8-11e7-9f21-cab587c974e9.png)
(sorry if this is another obvious mistake)

**Comment by jonparrott** [comment]
@samsammurphy that's.. unusual. What happens if you run `dev_appserver.py app.yaml`?

**Comment by samsammurphy** [comment]
![dev_appserver_appyaml](https://user-images.githubusercontent.com/16657983/28387369-7edad19c-6c6a-11e7-9d75-8451c9a80979.png)

I do not have this path 'lib/cacerts/urlfetch_cacerts.txt' inside my site-packages for python 2.7. 

running python 2.7.11

I am not really sure what Sandbox is..

The WSGI select exception goes away if I increase timeout..
_READINESS_TIMEOUT_SECONDS = 4
_SECONDS_TO_MILLISECONDS = 1000
