### ISSUE TITLE
Many .yaml files are using 'module', 'service' should now be used

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/python-docs-samples#1016]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/taskqueue/counter/app.yaml#L4
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/taskqueue/counter/worker.yaml#L4

As we can read here: https://cloud.google.com/appengine/docs/standard/python/config/appref
Note: Modules are now named Services.

I suggest to use 'service' in all .yaml files to avoid confusion. Our docs are talking about Services, we should be coherent.

**Comment by jonparrott** [comment]
Thanks for reporting, @steren
