### ISSUE TITLE
Need to add region to 'parent' definition

### ISSUE THREAD

**Issue by swainjo** [GoogleCloudPlatform/python-docs-samples#10173]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/dlp/snippets/triggers.py

## Did you change the file? If so, how?
no

## Describe the issue
to get the list triggers to work I had to change the project assignment to include the region.
from
parent = f"projects/{project}"
to
parent = f"projects/{project}/locations/{region}"

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by dandhlee** [comment]
Sorry for getting back to this late.

Soumya, can you help take a look at this issue?

**Comment by jping0220** [comment]
Hi, I have verified the problem with running the test case and it works without adding region for me. If the problem resistant for you, please feel free to reopen the ticket. Thank you
