### ISSUE TITLE
generative_ai: streaming

### ISSUE THREAD

**Issue by louis030195** [GoogleCloudPlatform/python-docs-samples#10213]
## Is your feature request related to a problem? Please describe.

a llm without streaming is like a computer without screen

i can't switch from openai to google because there is no streaming

## Describe the solution you'd like.
same as openai
```py
for resp in openai.Completion.create(model='text-davinci-003',
  prompt=user_input,
  max_tokens=120, 
  temperature = 0.5,
  stream = True):
  print(resp)
```
but for google
```py
for resp in google.chat(model='x.y.z',
  prompt=user_input,
  max_tokens=120, 
  temperature = 0.5,
  stream = True):
  print(resp)
```
## Describe alternatives you've considered.

n.a

**Comment by m-strzelczyk** [comment]
Streaming is supported in Vertex SDK: https://cloud.google.com/vertex-ai/docs/generative-ai/learn/streaming#sdk
