### ISSUE TITLE
failed to deploy the Django example 

### ISSUE THREAD

**Issue by kkx** [GoogleCloudPlatform/python-docs-samples#1032]
all set according to this [example](https://cloud.google.com/python/django/flexible-environment). worked in local, the deploy went ok, but the app engine instance failed to connect to the database instance. the following error is shown: 
OperationalError at /admin/login/
(2002, "Can't connect to local MySQL server through socket '/cloudsql/**connectionName**' (2)")

we tested this example because recently we are started to be unable to deploy our application in production without any configuration changes(get a 502 error when we visit a page with some database queries ) which worked before.

the 502 error shows something below:
 jsonPayload: {
  @type: "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry"   
  statusDetails: "failed_to_pick_backend"   
 }
and our gae instances continue to restart and increment.

**Comment by andrewsg** [comment]
Hi, just to clarify, you were successful in using this configuration at one time, but it started failing suddenly absent any changes, is that correct? Does the problem persist now, and if not, when did it start working again?

**Comment by gakeseaton** [comment]
The tutorial uses PostgreSQL, have you changed all of the necessary settings for it to work with MySQL?

**Comment by engelke** [comment]
The tutorial as written is working.
