### ISSUE TITLE
Speech API - streaming transcriber

### ISSUE THREAD

**Issue by jopedroliveira** [GoogleCloudPlatform/python-docs-samples#1040]
## In which file did you encounter the issue?
In this path, we can see the files to perform speech recognition through Google Cloud Speech API
```python-docs-samples/speech/cloud-client/```

My point in this issues is that sometimes, developers wants to develop a real-time streaming transcriber solution. In fact, this repo already provides a script with solution for that.
However, for test purposes, it's not productive to be always speaking into the microphone.

### Did you change the file? If so, how?
So, in order to test the streaming transcribe scenario, I've edited the script so it can read an audio file and simulate the streaming transcription, by sending chunks of data instead of the full file or the microphone data.

## Describe the issue

```
def _fill_buffer2(buff, in_data):
    buff.put(in_data)
    return True

def read_chunks(buff):
    f = wave.open('fala_teste.wav','rb')
    for frame in range(f.getnframes()-1):
        #frames.append(f.readframes(frame))
        a = f.readframes(frame)
        _fill_buffer2(buff, a)
    _fill_buffer2(buff,None)
    f.close()


# [START audio_stream]
@contextlib.contextmanager
def record_audio(rate, chunk):
    # Create a thread-safe buffer of audio data
    buff = queue.Queue()
    t = threading.Thread(name='read_chunks', target=read_chunks, args=(buff,))
    t.start()
    yield _audio_data_generator(buff)

```

**Comment by jerjou** [comment]
That's great! Did you have any particular issue with the sample code? It sounds like it's working as intended - ie it got you most of the way there, and you extended it to fit your need. Also note, that there is an associated test (`transcritbe_streaming_mic_test.py`) that demonstrates another way you can test, if you're looking for automated tests.

**Comment by jopedroliveira** [comment]
Well, in fact it's not an issue @jerjou. I was oppening this issue to prepare a merge request. However, I didn't see the ```transcritbe_streaming_mic_test.py``` script. So... Unless you want a second version of the ```transcritbe_streaming_mic_test.py```, you can close this issue

**Comment by jerjou** [comment]
Ah - cool. Thanks!
