### ISSUE TITLE
Add a new sample to support c.g.c docs for internal HTTP endpoints in Eventarc

### ISSUE THREAD

**Issue by camiekim** [GoogleCloudPlatform/python-docs-samples#10580]
## Is your feature request related to a problem? Please describe.
Opening an issue per Contributing Guide to request assistance in adding a new sample.

## Describe the solution you'd like.
See: https://github.com/camiekim/python-docs-samples/blob/internal-http-endpoints/eventarc/internal-http-endpoints/server.py

## Describe alternatives you've considered.
Is there an existing sample that could be used instead?

## Additional context.
This is per b/289404393 and the sample is used here: https://cloud.devsite.corp.google.com/eventarc/docs/vpc-endpoints/receive-vpc-events

Pls note that the preview launch date is Sept 13.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by rsamborski** [comment]
@iennae Can you please reassign to a person on your team working with EventArc?

**Comment by iennae** [comment]
closing as per b//298484052 update
