### ISSUE TITLE
There is no "README.md under /bigquery"

### ISSUE THREAD

**Issue by noroozimn** [GoogleCloudPlatform/python-docs-samples#1059]
Several places in your [README file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/README.rst) you have referred to

> the README.md under /bigquery

while there is no such a file here: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigquery

Are you referring to somewhere else or the file is moved to another place?

**Comment by jonparrott** [comment]
The file's been moved, I'll update those samples.

**Comment by jonparrott** [comment]
Fixed in I05013e56

**Comment by noroozimn** [comment]
Thank you so much @jonparrott 
The same applies to [api](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/api/README.rst)

**Comment by jonparrott** [comment]
I updated all references to README within the bigquery folder, including api. :)

**Comment by noroozimn** [comment]
In my opinion it would have been better to remove that line, instead of referring to itself! :-)

**Comment by jonparrott** [comment]
It's a little misleading, but the readmes are generated from the `help` output of the samples. So they reference each other. :)
