### ISSUE TITLE
In generate_signed_urls.py header values should not be lower-cased.

### ISSUE THREAD

**Issue by kevin-pietsch** [GoogleCloudPlatform/python-docs-samples#10638]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## Is your feature request related to a problem? Please describe.

The code sample on request signing is incorrect which leads to requests failing (https://cloud.google.com/storage/docs/access-control/signing-urls-manually)

Namely, base-64 encoded md5 checksum should not be lower-cased as this changes the value.

## Describe the solution you'd like.

Remove `.lower()` from header values in example code: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/storage/signed_urls/generate_signed_urls.py#L76

## Describe alternatives you've considered.
 - Modify copied code locally. This is fine, but would be good to have example code work out of the box
 - Don't sign problem headers -- also OK, but shouldn't be required.

## Additional context.
Example code was extremely helpful in general

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by engelke** [comment]
Lower-casing a base64 encoded value does change that value and would break things. However, the value referenced here is for an obsolete header (MD5-content) that should no longer be used. Removing it if found should work fine.
