### ISSUE TITLE
Service extension callouts add_header sample - code cleanup

### ISSUE THREAD

**Issue by msampathkumar** [GoogleCloudPlatform/python-docs-samples#10788]
This is a request for code clean-up service extensions plugins

Major issues/concerns
* Service extension sample's private and publish keys (both) are shared in Github. This is not the general practise followed in this Github Repo and this private key file sharing need to be re-evaluated. (preferred options is No).
* Similar to above, a proto file is shared in this sample. This also need to be re-evaluated. (preferred options is No).

Minor issues
* Service Extension python samples are using region tags like `serviceextension_add_header` for callouts. Similar headers is used for service extensions plugs in GoogleCloudPlatform/service-extensions-samples.  This needs to be updated to use prefix like `serviceextension_callouts_`
* The docker file needs to be updated to update port-mappring. Use 8443 instead of 443, similaly 8000 instead of 80.  (Docker file, try `EXPOSE 8443 433` instead of `EXPOSE 433`)

**Comment by msampathkumar** [comment]
Couple of updates
1. For the above mentioned issues, I need to engaged with product team. 
2. Current expectations is that product SWE's will own this clean-up.

Hi @leahecole, this issues is created just as a tracker. No immediate actions is excepted.

**Comment by leahecole** [comment]
@msampathkumar I reassigned to you given that you've done some of the legwork about reaching out - this way it'll show up in your buganizer! :)
