### ISSUE TITLE
How to get taskqueue? - ModuleNotFoundError: No module named 'google.appengine'

### ISSUE THREAD

**Issue by robertjchristian** [GoogleCloudPlatform/python-docs-samples#1080]
What is the proper way to make this library available to the Python 3.4 runtime?  It is not installable via requirements.txt nor pip install google-cloud as some other references suggest.  Where is this lib?  

**Tasks pull queues are not usable without this lib.**

**There is seemingly no documentation from Google or others on how to make this lib available.  In 20+ examples and documents that say "import taskqueue", not one explains how to make this available.**

## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/taskqueue/pull-counter

### Did you change the file? If so, how?

No.

## Describe the issue

    from google.appengine.api import taskqueue
ModuleNotFoundError: No module named 'google.appengine'

**Comment by jonparrott** [comment]
Cloud Tasks is not yet available for app engine flexible. See here: https://cloud.google.com/appengine/docs/flexible/python/migrating#task_queue

**Comment by adriancast** [comment]
@theacodes I really need to add some kind of async task in my app. I am using google app engine flexible with Python 3.5.

Do I have any way to run task queues, async functions or something like this ? 

Thanks

**Comment by theacodes** [comment]
@adriancast you can sign up for the [Cloud Tasks Alpha](https://cloud.google.com/tasks/), use Pub/Sub, or run RabbitMQ and use Celery.
