### ISSUE TITLE
appengine flask - bigquery - no module found error

### ISSUE THREAD

**Issue by bharadwaj509** [GoogleCloudPlatform/python-docs-samples#1083]
I'm using the Flask Framework which works fine in the standard appengine. I am trying to connect to Big Query and that's where I am having trouble.

So I have used:
`pip install -t lib -r requirements.txt`

The requirements are
Flask
google-cloud-bigquery

I am facing the following issue:

https://stackoverflow.com/questions/42502479/google-app-engine-big-query-python-cant-find-libraries-google-cloud/42510474#42510474

**Comment by jonparrott** [comment]
The cloud client libraries do not currently work on App Engine. You'll need to use the Google API Client LIbrary.

See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893#issuecomment-322512490 for more information.
