### ISSUE TITLE
"Getting started with App Engine" fails with error 500

### ISSUE THREAD

**Issue by ralfgautschi** [GoogleCloudPlatform/python-docs-samples#10892]
I went through [Getting started with App Engine](https://codelabs.developers.google.com/codelabs/cloud-app-engine-python3), but after deployment the app was returning a server error. Looking at the logs I found this error message:

`ImportError: cannot import name 'url_quote' from 'werkzeug.urls'`

I was able to fix this by setting `Werkzeug==2.2.2` in the requirements.txt.

**Comment by ralfgautschi** [comment]
I did not work with this repo directly, just went through the tutorial which resulted in an error. I was assuming the repos here is related to the tutorial. If that's not the case, then this issue can be closed I guess.

**Comment by msampathkumar** [comment]
@ralfgautschi Unfortunately, this is not right place for reporting this error.  After I have re-tested this codelab, I have raise an internal bug reports. Thank you for the bug report. 

@dandhlee: You may check these details at at b/309929813 & b/309929859
