### ISSUE TITLE
503 DNS resolution failed for ('us',)-documentai.googleapis.com:443: UNAVAILABLE: WSA Error

### ISSUE THREAD

**Issue by rodrigomartinsvmc** [GoogleCloudPlatform/python-docs-samples#10913]
Hello, when I try to run my python code to OCR a document I am receiving this error message

    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 DNS resolution failed for ('us',)-documentai.googleapis.com:443: UNAVAILABLE: WSA Error

My processor is already trained and deployed, I am using a service account for the authentication process, this code was working and now I simply get this error frequently, is this a known failure?

**Comment by rsamborski** [comment]
@holtskinner PTAL

**Comment by holtskinner** [comment]
Looks like the location in the API Endpoint is structured incorrectly. It should be structured as `us-documentai.googleapis.com` or `eu-documentai.googleapis.com`.

Make sure that the `location` parameter is a string with value `us`.
