### ISSUE TITLE
Firestore collection deletion

### ISSUE THREAD

**Issue by jmorenobrasero** [GoogleCloudPlatform/python-docs-samples#10983]
I'm using the following code snippet to delete a collection using batches:
```python
def delete_collection(coll_ref, batch_size):
        docs = coll_ref.list_documents(page_size=batch_size)
        deleted = 0

        for doc in docs:
            print(f"Deleting doc {doc.id} => {doc.get().to_dict()}")
            doc.delete()
            deleted = deleted + 1

        if deleted >= batch_size:
            return delete_collection(coll_ref, batch_size)
``` 
If you call this function with the collection size you may have a inifite recursive function if you have an **empty collection** or the **collection doesn't exist**.

My custom call looks like that:
```python
    collection_ref = db.collection('collection-name')
    delete_collection(collection_ref, sum(1 for _ in collection_ref.stream()))
```
This is caused because if the collection doesn't have any document the deleted counter won't be incremented. So, the deleted counter and the batch_size variable will be **both equal 0**.

**Comment by daniel-sanche** [comment]
Opened a PR to address this here: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11204
