### ISSUE TITLE
Add missing test

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#11018]
Hi @koverholt  - it looks like this PR got merged without tests https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11015 - please add a test following the guidelines in the authoring guide! https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md

cc @msampathkumar

**Comment by koverholt** [comment]
My mistake, 🤦 thanks for the reminder @leahecole!
