### ISSUE TITLE
App Engine says "no module named cloud"

### ISSUE THREAD

**Issue by Praxiteles** [GoogleCloudPlatform/python-docs-samples#1102]
When trying to run the command "from google.cloud import bigquery" on AppEngine, we receive an error "no module named cloud" in the logs. 

Is this not designed to work on App Engine? Do we need to vendor in the libraries?

**Comment by michaelawyu** [comment]
Hi! BigQuery Client Library is available on App Engine, but you need to install it first. You could vendor in the library, or specify the package `google-cloud-bigquery` in requirements.txt.
