### ISSUE TITLE
search_hashes() always returns a empty list of threat hashes

### ISSUE THREAD

**Issue by jam182** [GoogleCloudPlatform/python-docs-samples#11030]
**Issue**:
following the test shown in [webrisk/snippets/test_basic_samples.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/webrisk/snippets/test_basic_samples.py#L57) I never get a threat list from search_hashes()

**Steps to reproduce:**
````python
import base64
import hashlib

url = 'http://testsafebrowsing.appspot.com/s/malware.html'  # If you try this on the web browser it is in fact detected as malware

def generate_hash_prefix(uri):
    sha256 = hashlib.sha256()
    sha256.update(base64.urlsafe_b64encode(bytes(uri, "utf-8")))
    hex_string = sha256.digest()
    return hex_string
    
from google.cloud import webrisk_v1

def search_hashes(hash_prefix: bytes, threat_type: webrisk_v1.ThreatType) -> list:
    webrisk_client = webrisk_v1.WebRiskServiceClient()

    request = webrisk_v1.SearchHashesRequest()
    request.hash_prefix = hash_prefix
    request.threat_types = [threat_type]

    response = webrisk_client.search_hashes(request)

    hash_list = []
    for threat_hash in response.threats:
        hash_list.append(threat_hash.hash)
    return hash_list

hash_prefix = generate_hash_prefix(url)
threats = search_hashes(hash_prefix, webrisk_v1.ThreatType.MALWARE)

assert len(threats) > 0  # fail!
````

it is the same with 
````python
url = 'testsafebrowsing.appspot.com/s/malware.html'  # no http:// as explained in how to generate canonical versions of the url.
````
I tested several other url's that google chrome detects as malware and prints the message:
```
Chrome has built-in safety features to protect you while you browse — like Google Safe Browsing, which [recently found malware](chrome-error://chromewebdata/#) on the site you're trying to visit.
```
but `search_hashes()` always returns an empty list of threats, so it does not seem to be possible to detect malware with it.
`search_uri(url)` actually returns `threatType = MALWARE`

**Environment:**
using python 3.11 and:
````
google-cloud-webrisk==1.12.2
`````

**Expected Behaviour:**
for known threats a list of full hashes that match the hash_prefix provided in the request should be returned instead of a empty list.

I suspect that the example provided to generate the `hash_prefix` included in this example as `generate_hash_prefix()` is not generating prefixes compatible with what full hash database `search_hashes()` is actually checking, or there might be a validation step in `request.hash_prefix = hash_prefix` that is tempering the value.

**Comment by BigBlackWolf** [comment]
It returns an empty list, because looks like you local database on a project is empty. As the [documentation](https://cloud.google.com/web-risk/docs/update-api#threat_hash_prefixes) states: 

> The hashPrefix field contains the hash prefix of the URL that you want to check. This field must contain the exact hash prefix that is present in the local database...

Before searching by hashes, you need to fill the database out, using Update API. More detailed information can be found here https://cloud.google.com/web-risk/docs/local-databases

**Comment by jam182** [comment]
hi @BigBlackWolf thanks for replying. 
We do check the local db, I should have mentioned it in the description. I didn't want to add too much code. I meant to show how we encode the url to get a hash and how we perform the request to search_hashes().

could you please show a working example that is returning a non empty list please? (ideally using that same url from the example above: `http://testsafebrowsing.appspot.com/s/malware.html`)
