### ISSUE TITLE
Pull Subscription acknowledge deadline

### ISSUE THREAD

**Issue by dexterchan** [GoogleCloudPlatform/python-docs-samples#1113]
## In which file did you encounter the issue?
Which api function is able to set acknowledge deadline in PULL subscription?

**Comment by jonparrott** [comment]
You can do it [when creating a subscription](https://google-cloud-python.readthedocs.io/en/latest/pubsub/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.create_subscription) or by [updating the subscription](https://google-cloud-python.readthedocs.io/en/latest/pubsub/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.update_subscription).
