### ISSUE TITLE
There is a typo in handle_response_sample_v1beta3.py that throws an error

### ISSUE THREAD

**Issue by tomgersic** [GoogleCloudPlatform/python-docs-samples#11203]
## In which file did you encounter the issue?
python-docs-samples/documentai/snippets/handle_response_sample_v1beta3.py

## Did you change the file? If so, how?
It's just a mis-spelling of the word Occurrence. It throws an error. It's fixed here:
https://github.com/tomgersic/python-docs-samples/commit/f779c5250f4a601a8fa9c160c3c34e0ba02b289c

## Describe the issue
Errors thrown:

AttributeError: type object 'Property' has no attribute 'OccurenceType'. Did you mean: 'OccurrenceType'?
ValueError: Unknown field for Property: occurence_type

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by m-strzelczyk** [comment]
The PR was merged into `main` manually. This issue should be now resolved.
