### ISSUE TITLE
Add an image to use models/gemini-pro-vision, or switch your model to a text model

### ISSUE THREAD

**Issue by jun0wanan** [GoogleCloudPlatform/python-docs-samples#11223]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## Describe the issue

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jping0220** [comment]
Hi, can you be more specific and provide more details/contexts about the issue/issues that you have encountered for a better understanding to help solve the problem? Thank you!

**Comment by iennae** [comment]
hey @jun0wanan, I'm going to go ahead and close this. Please feel free to reopen with additional context if this is still an issue.
