### ISSUE TITLE
Uploading multiple files to GCS

### ISSUE THREAD

**Issue by claudiadast** [GoogleCloudPlatform/python-docs-samples#1125]
## In which file did you encounter the issue?

python-docs-samples/dataproc/submit_job_to_cluster.py

## Describe the issue

I am a little confused about the following `submit_job_to_cluster.py` function:

```
def upload_pyspark_file(project_id, bucket_name, filename, file):
    """Uploads the PySpark file in this directory to the configured
    input bucket."""
    print('Uploading pyspark file to GCS')
    client = storage.Client(project=project_id)
    bucket = client.get_bucket(bucket_name)
    blob = bucket.blob(filename)
    blob.upload_from_file(file)
```
I've created an argument parsing function in my script that takes in multiple arguments (file names) to upload to a GCS bucket:

```
def parse_all_args():
    parser=ArgumentParser()
    parser.add_argument('--upload_files', nargs='*' , required=True, help= 'files that need to be uploaded to google storage (including hail script)')
    args= parser.parse_args()
    return args
```
 I'm trying to adapt the top-most function to upload all the files in the `--upload_files` Namespace, but am unsure how to proceed. My confusion is with the 'filename' and 'file' variables above. How can I adapt the function for my specific purpose?

**Comment by jonparrott** [comment]
@waprin can you take a look?

**Comment by waprin** [comment]
@claudiadast filename is the path on GCS. File object is the local opened filed to upload. I will make an update to these sampels to how multiple files but roughly you should just be able to upload multiple files in a loop.

**Comment by waprin** [comment]
Thinking about it more, I think multiple files muddles the sample up too much, it should be pretty clear how to get there from what's provided, if not people can always ask for help here, so I'm just going to close this.
