### ISSUE TITLE
Update discovery engine v1 code sample include `summary_with_metadata`

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/python-docs-samples#11258]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/discoveryengine/search_sample.py

Context: https://github.com/googleapis/google-cloud-python/issues/12358

**Comment by holtskinner** [comment]
@tpcgold Follow-up question to https://github.com/googleapis/google-cloud-python/issues/12358

How is this `summary_with_metadata` not included in the sample? It should be returned in the response from the `response = client.search(request)` call. Then the response is printed out, which should include `summary_with_metadata`.

**Comment by holtskinner** [comment]
No code changes are needed. Once the client library was updated, the code should work as expected.

**Comment by parthea** [comment]
I apologize for the confusion on my part. The issue was that the client library was not up to date. This has been addressed via https://github.com/googleapis/google-cloud-python/releases/tag/google-cloud-discoveryengine-v0.11.8
