### ISSUE TITLE
YAML missing name of the service configuration

### ISSUE THREAD

**Issue by jackwootton** [GoogleCloudPlatform/python-docs-samples#1129]
## In which file did you encounter the issue?

python-docs-samples/endpoints/bookstore-grpc/api_config_http.yaml

### Did you change the file? If so, how?

No

## Describe the issue

Why is there no name attribute in the yaml file? Other yaml files (api_config_auth.yaml and api_config.yaml) specify the name of the service configuration

```
#
# Name of the service configuration.
#
name: bookstore.endpoints.<MY_PROJECT_ID>.cloud.goog
```

**Comment by jonparrott** [comment]
@p-buse can you take a look?

**Comment by engelke** [comment]
Bumping this up. @simonz130 and @kryzthov have looked at this piece most recently. Please add a name field or comment as to why it should not be here.

**Comment by simonz130** [comment]
+ Dan
@DanSanche

**Comment by DanSanche** [comment]
This change seems reasonable to me. I staged a fix here, waiting on approval: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1902
