### ISSUE TITLE
No puedo vincular mi bucket a un modelo pre-entrenado de GPT-3

### ISSUE THREAD

**Issue by ncastagno-tgv** [GoogleCloudPlatform/python-docs-samples#11292]
Intenté hacerlo por AI Platform y por Vertex, pero no me ofrece la opción GPT-3 como modelo de texto.
Consultpe a Gemini y me responde lo siguiente. De hecho **mi proyecto está en us-central1** y uso la **versión Beta de AI Platform**

Si no ves GPT-3 como una opción de modelo de texto en Cloud AI Platform Training Jobs, puede deberse a una de las siguientes razones:

Tu proyecto no está habilitado para GPT-3: GPT-3 es un modelo premium que requiere que tu proyecto esté habilitado para usarlo. Puedes solicitar la habilitación [aquí](https://cloud.google.com/ai-platform-unified/docs/get-started-with-gpt-3#request-access).
Estás utilizando una región no compatible: GPT-3 solo está disponible en las siguientes regiones:
us-central1
europe-west4
asia-east1
Estás utilizando una versión anterior de Cloud AI Platform: GPT-3 solo está disponible en la versión beta de Cloud AI Platform. Asegúrate de estar utilizando la última versión.
Si has comprobado todas estas razones y sigues sin ver GPT-3 como una opción de modelo de texto, puedes [crear un problema](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/new) en el repositorio de muestras de Python de Google Cloud y proporcionar información sobre tu proyecto, región y versión de Cloud AI Platform.

**Comment by iennae** [comment]
Lo siento! Inglés es mi lenguaje principal.

I'm not sure whether you saw documentation that said file a bug here, or if Gemini gave you an answer that said to file a bug here. The page you linked to gave me a 404 error (https://cloud.google.com/ai-platform-unified/docs/get-started-with-gpt-3#request-access). 

Additionally, I couldn't find specific documentation that might correspond to what you mentioned. There is this page https://cloud.google.com/vertex-ai/generative-ai/docs/model-garden/explore-models. 

This repo is for samples that are embedded within our docs at cloud.google.com. If there is an issue with a sample you are trying to run, please reopen with a link to that sample and we can try to resolve the issue. 

Thank you!
