### ISSUE TITLE
HTTPError: Json returned "Job not found my-project/my-cluster"

### ISSUE THREAD

**Issue by claudiadast** [GoogleCloudPlatform/python-docs-samples#1131]
## Describe the issue

I have a python client library-based script that implements functions from `python-docs-samples/dataproc/submit_job_to_cluster.py`. When I tried running the full script, it returned the following error:

```
Waiting for job to finish...
Traceback (most recent call last):
  File "/Users/cdastmalchi/WGS_automation_python_SDK.py", line 174, in <module>
    main()
  File "/Users/cdastmalchi/WGS_automation_python_SDK.py", line 168, in main
    wait_for_job(dataproc, args.project_id, region, args.cluster_name)
  File "/Users/cdastmalchi/WGS_automation_python_SDK.py", line 132, in wait_for_job
    jobId=job_id).execute()
  File "/anaconda/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://dataproc.googleapis.com/v1/projects/my-project-id/regions/us-east4/jobs/my-cluster?alt=json returned "Job not found my-project-id/my-cluster"> 
```
The issue appears to occur when implementing the `wait_for_job()` function:

```
def wait_for_job(dataproc, project, region, job_id):
    print('Waiting for job to finish...')
    while True:
        result = dataproc.projects().regions().jobs().get(
            projectId=project,
            region=region,
            jobId=job_id).execute()
        # Handle exceptions
        if result['status']['state'] == 'ERROR':
            raise Exception(result['status']['details'])
        elif result['status']['state'] == 'DONE':
            print('Job finished.')
            return result
```

But I'm not sure what exactly is wrong. Do you think the problem has to do with regions/zones? my cluster is in `us-east4-b` and the attempted job submission was in `us-east4`.

**Comment by jonparrott** [comment]
@waprin can you take a look?

> Do you think the problem has to do with regions/zones? my cluster is in us-east4-b and the attempted job submission was in us-east4.

possibly.

**Comment by claudiadast** [comment]
@waprin: I've followed the code as outlined in `python-docs-samples/dataproc/submit_job_to_cluster.py`, so if it were a region/zone problem, wouldn't many others be having the same issue?

**Comment by waprin** [comment]
@claudiadast there were some recent refactors and it's possible you're just the first to report an issue, will take a look in a bit, thanks for report

**Comment by claudiadast** [comment]
@waprin: Have you had a chance to decipher the problem?

**Comment by waprin** [comment]
Looking now, are you setting project right? Your output says `my-project`, that probably isn't right?

**Comment by claudiadast** [comment]
@waprin: I've replaced the actual project ID with `my-project`

**Comment by claudiadast** [comment]
@waprin: I figured out the problem. I had put the arguments in the wrong order when I called to that function. Now the job runs for quite a bit but then it raises the following exception: `Exception: Task was not acquired`.

**Comment by claudiadast** [comment]
@waprin: I fixed the original problem, but now it still can't complete the job because it says `ImportError: no module named pandas`. And in my script from which the job runs, I import pandas, as well as many other modules.

**Comment by waprin** [comment]
@claudiadast glad first problem got worked out. Have you looked at [initialization actions](https://cloud.google.com/dataproc/docs/concepts/init-actions)? They might help you make sure the nodes have pandas installed

**Comment by waprin** [comment]
I'm giving it a try myself now

**Comment by claudiadast** [comment]
So I uploaded this initialization action script to my bucket:

```
#!/bin/bash

ROLE=$(/usr/share/google/get_metadata_value attributes/dataproc-role)
if [[ "${ROLE}" == 'Master' ]]; then 
  apt-get install python-pandas -y
fi
```

And then in my main script, added this function to run it (after `wait_for_cluster_creation()`):
```
def initialization_action(dataproc, project, region, cluster_name, bucket_name):
	"""Initializes the packages/modules you need to run the hail script"""
	job_details = {
        'projectId': project,
        'job': {
            'placement': {
                'clusterName': cluster_name
            },
            'pysparkJob': {
                'mainPythonFileUri': 'gs://{}/{}'.format(bucket_name, 'initialization_action.sh') 
            }
        }
    }
    result = dataproc.projects().regions().jobs().submit(projectId=project, region=region, body=job_details).execute()
    job_id = result['reference']['jobId']
    print('Submitted initialization action')
```
Is this the right way?

**Comment by waprin** [comment]
I don't think that looks right because you want to run the initializations script on cluster create rather than job submit. Make sure your initialization script is added to a GCS bucket. 

Then, if you are using `gcloud dataproc clusters create` then you want to use the `--initialization-actions` flag. If you create the cluster in the code you will want to add something like

    cluster_data = {
        'projectId': project,
        'clusterName': cluster_name,
        'config': {
            'initializationAction': {  "executableFile": 'gs://your-initialization-script-path'} 
            'gceClusterConfig': {
                'zoneUri': zone_uri
            }
        }
    }
```

See the cluster create API doc [here](https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.clusters#ClusterConfig). 

It's probably easier to just create the cluster with gcloud though. You will have to delete and recreate the cluster to make sure the initializatino scripts runs correctly.

As far as the script itself, I am trying to get one working now, yours might work too though, not sure

**Comment by claudiadast** [comment]
Okay I'll try that. I would just use `gcloud` but I'm trying to develop everything in Python because this script will come after a pipeline that has run in AWS, so it needs to be compatible with AWS Lambda.

**Comment by waprin** [comment]
Gotcha, so you only should need to create the cluster once, which you can do which gcloud or the console, and you just need to make sure the initialization script that installas Pandas is run then. After that, pandas should already be on the cluster so your pipeline won't need to worry about it.

To summarize above, I think what you should do is

* Delete your current cluster
* `gsutil cp initialize.sh gs://your-bucket/initialize.sh`
* `gcloud dataproc clusters create waprin-spark5 --initialization-actions=gs://your-bucket/initialize.sh`

Then submit your job. Again the `clusters create` could also be done via the console. Or the API call we have in the sample but honestly it's a bit misleading because you probably don't want to do the one-time cluster setup operation via the API when it's easier to do with gcloud or console.

**Comment by waprin** [comment]
Ok your initialization script let me install pandas successfully, so the instructions I'm giving you above should solve your problem. But I also wrote a lot and it may be confusing, so feel free to ask any followup questions.

**Comment by claudiadast** [comment]
@waprin: I'm just going with the `gcloud` and `cloudtools` commands for the whole script right now. What would be the best way to adapt the python client's `wait` functions? Should I just do `time.sleep(n)`?

**Comment by waprin** [comment]
I'm pretty sure the gcloud commands will wait themselves. If I'm wrong you can just do a `clusters list` and grep the output until you see your cluster.

**Comment by claudiadast** [comment]
@waprin: I'm struggling with the initialization action stuff still. In the bash script, I included a `apt-get install python-argparse`, but when I submit a pyspark job, it says: 

```
Waiting for job output...
17/09/25 16:36:56 INFO com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase: GHFS version: 1.6.1-hadoop2
Downloading gs://hail-common/builds/0.1/jars/hail-0.1-6f8598516c88-Spark-2.0.2.jar to /tmp/tmp5973503854824697066/builds/0.1/jars/hail-0.1-6f8598516c88-Spark-2.0.2.jar.
Traceback (most recent call last):
  File "/tmp/9f6d7b4f-adcb-4817-b402-da327f7f7d61/run_QC_hail_20170718.py", line 8, in <module>
    import hail
  File "/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/__init__.py", line 1, in <module>
  File "/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/expr.py", line 3, in <module>
  File "/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/representation/__init__.py", line 1, in <module>
  File "/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/representation/variant.py", line 2, in <module>
  File "/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/typecheck/__init__.py", line 1, in <module>
  File "/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/typecheck/check.py", line 1, in <module>
ImportError: cannot import name getargspec
```

**Comment by claudiadast** [comment]
You had said when you tried my first initialization script (below) that it worked, right?

```
#!/bin/bash

ROLE=$(/usr/share/google/get_metadata_value attributes/dataproc-role)
if [[ "${ROLE}" == 'Master' ]]; then 
  apt-get install python-pandas -y
fi
```
For me, when I run it for the cluster creation step, it appears to work successfully, but then when I submit a job, it still says `no module named Pandas`.

**Comment by waprin** [comment]
Mine was slightly different:

```
#!/bin/bash
apt get update && apt-get install python-pandas -y
```
I don't see why you would only want Pandas on your Master, you want it on your workers too which is likely why your job is failing.

**Comment by claudiadast** [comment]
I was successfully able to launch a dataproc cluster by manually creating one via `gcloud dataproc clusters create....` However, when I try to launch one through my automation script, it says `ERROR: (gcloud.dataproc.clusters.create) PERMISSION_DENIED: Permission denied on resource project hail-test-project (#0)`. I don't understand why, because the script uses the same command.

**Comment by waprin** [comment]
Can you show me the script? Is it bash or python?

Auth is a common point of confusion, definitely worth checking out our [auth docs](https://cloud.google.com/authentication).

When you do `gcloud dataproc create` it uses special credentials generated when you run `gcloud auth login`. However those credentials are only valid for gcloud. If you are using application code, you can generate credentials by running `gcloud auth application-default login`. 

However, while that should work, for scripts I'd instead highly recommend always using Service Account JSON keys. Create a service account, download the json file, then set `GOOGLE_APPLICATION_CREDENTIALS` to point to the JSON file.

**Comment by waprin** [comment]
Oh and I forgot to mention - if you want to use service accounts to automate gcloud commands (since you need a human to run `gcloud auth login`) you would want to use (`gcloud auth activate-service-account`). 

I know this is a big information dump but appreciate the dataproc feedback, if you want to block out 30 min to jump on Slack or something to just zone in on getting your cluster setup, happy to do so.

**Comment by claudiadast** [comment]
Hi @waprin: can we jump on slack so I can show you my code?

**Comment by waprin** [comment]
Sure:

https://googlecloud-community.slack.com

you might need to get an invite from here first:

https://gcp-slack.appspot.com/

You can message me on there, or we can do Hangout if that's more helpful to screenshare. My github username is both my name on slack and my email @ company I work at.
