### ISSUE TITLE
ndb Key Snippet is Incorrect

### ISSUE THREAD

**Issue by howinator** [GoogleCloudPlatform/python-docs-samples#1149]
## In which file did you encounter the issue?

[appengine/standard/ndb/entities/snippets.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/ndb/entities/snippets.py#L121)

### Did you change the file? If so, how?

I have a fix which properly describes that keys are an instance property and not a class property. [You can see this change here.](https://github.com/GoogleCloudPlatform/python-docs-samples/compare/master...howinator:howinator/fix-entity-key-snippet)

## Describe the issue

I may have already properly described the issue, but the snipped in one of the ndb snippets indicates that the key property is a class attribute. It is actually an instance attribute. My branch above fixes this and I can submit a PR once I get the 👍 on this issue.

**Comment by jonparrott** [comment]
Thanks, @howinator, would you be interested in sending a pull request to fix this?

**Comment by howinator** [comment]
Of course, @jonparrott. PR opened in #1150 😄
