### ISSUE TITLE
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 189.99941042508 second(s). Required at least: 196 second(s).)>

### ISSUE THREAD

**Issue by Jfeng3** [GoogleCloudPlatform/python-docs-samples#1153]
## In which file did you encounter the issue?
transcribe_streaming_mic.py

### Did you change the file? If so, how?
No.

## Describe the issue

grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 189.99941042508 second(s). Required at least: 196 second(s).)>

**Comment by jonparrott** [comment]
@gguuss @jerjou could one of you take a look?

**Comment by jerjou** [comment]
This error occurs when you've been streaming for about 60 seconds. Note that the streaming api currently [only supports](https://cloud.google.com/speech/quotas) up to 60 seconds of streaming. For an example of how to work around this, see [this sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/speech-continuous/speech/cloud-client/transcribe_streaming_indefinite.py) I just pushed (and haven't gotten to submit yet).
