### ISSUE TITLE
Bug in transcribe_streaming_infinite.py sample code

### ISSUE THREAD

**Issue by egrabs** [GoogleCloudPlatform/python-docs-samples#11541]
## In which file did you encounter the issue?

`speech/microphone/transcribe_streaming_infinite.py`

## Did you change the file? If so, how?

Yes. Remove [this return](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/22c43b7842b292b5896ee9f962c259000fd44ea5/speech/microphone/transcribe_streaming_infinite.py#L295)

## Describe the issue

The script does not properly overwrite interim results:

![Screenshot 2024-04-18 at 9 12 08 AM](https://github.com/GoogleCloudPlatform/python-docs-samples/assets/38090333/c12c6a49-73f9-4b83-9ef7-1ef7b149e6ce)

This is because of the `return` statement at the bottom of the `for` loop over the response generator in `listen_print_loop` [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/22c43b7842b292b5896ee9f962c259000fd44ea5/speech/microphone/transcribe_streaming_infinite.py#L295)

Removing this return statement and allowing the loop to keep iterating the generator until [the break statement](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/22c43b7842b292b5896ee9f962c259000fd44ea5/speech/microphone/transcribe_streaming_infinite.py#L240-L242) is encountered allows for properly overwriting interim results:

![Screenshot 2024-04-18 at 9 15 17 AM](https://github.com/GoogleCloudPlatform/python-docs-samples/assets/38090333/3540b515-0d75-47a3-996d-262c80353d57)

**Comment by BigBlackWolf** [comment]
Was done in scope of https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11775
