### ISSUE TITLE
python face detection: max_results parameter is not used

### ISSUE THREAD

**Issue by karolmajek** [GoogleCloudPlatform/python-docs-samples#1173]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/vision/cloud-client/face_detection/faces.py

### Did you change the file? If so, how?

no

## Describe the issue

The `max_results` parameter is not used, so code detects only 10 faces max:

```
def detect_face(face_file, max_results=4):
    """Uses the Vision API to detect faces in the given file.
    Args:
        face_file: A file-like object containing an image with faces.
    Returns:
        An array of Face objects with information about the picture.
    """
    # [START get_vision_service]
    client = vision.ImageAnnotatorClient()
    # [END get_vision_service]

    content = face_file.read()
    image = types.Image(content=content)

    return client.face_detection(image=image).face_annotations
```

**Comment by jonparrott** [comment]
@michaelawyu seems like an easy fix, can you take this on?

**Comment by michaelawyu** [comment]
Got it :)

**Comment by michaelawyu** [comment]
Have reported to client libraries repo and waiting for a fix now

**Comment by engelke** [comment]
See PR #1917 to pass parameter to API.
