### ISSUE TITLE
Token expired, generates an exception before 'claims'

### ISSUE THREAD

**Issue by AlvarDev** [GoogleCloudPlatform/python-docs-samples#1191]
## In which file did you encounter the issue?
python-docs-samples/appengine/standard/firebase/firenotes/backend/main.py 

### Did you change the file? If so, how?

I don't change the file

## Describe the issue
Token expired generates an exception:
An internal error occurred. Token expired, 1509541812 < 1509655907 [code 500]

The exception is before the 'if not claims:' so the code 401 is not sent

**Comment by michaelawyu** [comment]
Hi AlvarDev! Just as the error message implies, the token for authenticating your request has expired. Tokens usually live only for a short while for security reasons, so if you log in and leave the application idle for a long period of time your session might be invalidated. You could solve this by logging out and signing again; auth server will assign you a new token upon successful logins.
