### ISSUE TITLE
User FireStore instead of Cloud DataStore

### ISSUE THREAD

**Issue by essramos** [GoogleCloudPlatform/python-docs-samples#1200]
I am not entirely sure if this is where I should ask this. 

But is it possible to use FireStore on this example? Instead of DataStore. 

Please correct me if my question does not make sense, I am entirely new to Google Cloud Platform. 

Thank you.

**Comment by jonparrott** [comment]
Which sample in particular are you referring to? (This repository contains a significant amount of samples).

In general, you can use both pretty much everywhere with one exception: the Firestore client library does not yet work on App Engine standard (but we're working on it). You can still interact with Firestore from App Engine standard via the REST API.

**Comment by essramos** [comment]
Sorry, I was talking about the Firenotes example, will I need to use App Engine for that example? Since the Authentication is on FireBase? and then save the notes on FireStore instead of DataStore. thanks.

**Comment by jonparrott** [comment]
i see, you could, but like I said right now it's not possible to use the Firestore client on standard, so, datastore and ndb is still the easiest route.

**Comment by BlonDev** [comment]
Is this still the case? Really want to use App Engine with FireStore instead of DataStore.
