### ISSUE TITLE
IOError: [Errno -9996] Invalid input device (no default output device)

### ISSUE THREAD

**Issue by titusece** [GoogleCloudPlatform/python-docs-samples#1201]
## In which file did you encounter the issue?

~python-docs-samples-master/speech/cloud-client/transcribe_streaming_mic.py

### Did you change the file? If so, how?

Nope, I didn't change anything.

## Describe the issue

Want to convert speech to text using the transcribe_streaming_mic.py python script. (I am able to run this script on one of my i.MX6 ARM board and able to convert to text successfully and used the same USB sound card)
Getting the following errors while running the MIC streaming issue.

```
source /env/bin/activate
export GOOGLE_APPLICATION_CREDENTIALS=/TESTxyz.json
python ~python-docs-samples-master/speech/cloud-client/transcribe_streaming_mic.py 
```

```
(env) root@apalis-imx6:/python-docs-samples/speech/cloud-client#
(env) root@apalis-imx6:/python-docs-samples/speech/cloud-client# python transcribe_streaming_mic.py
Traceback (most recent call last):
  File "transcribe_streaming_mic.py", line 193, in <module>
    main()
  File "transcribe_streaming_mic.py", line 181, in main
    with MicrophoneStream(RATE, CHUNK) as stream:
  File "transcribe_streaming_mic.py", line 67, in __enter__
    stream_callback=self._fill_buffer,
  File "/env/lib/python2.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/env/lib/python2.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9996] Invalid input device (no default output device)
(env) root@apalis-imx6:/python-docs-samples/speech/cloud-client# 
(env) root@apalis-imx6:/python-docs-samples/speech/cloud-client#
```

And able to run other examples.

```
(env) root@root:/python-docs-samples-master/speech/cloud-client#
(env) root@root:/python-docs-samples-master/speech/cloud-client# python transcribe_streaming.py resources/audio.raw
Finished: True
Stability: 0.0
Confidence: 0.987628996372
Transcript: how old is the Brooklyn Bridge
(env) root@root:/python-docs-samples-master/speech/cloud-client#
(env) root@root:/python-docs-samples-master/speech/cloud-client#
```

BTW, I have connected USB sound card into my host.

```
(env) root@root:/python-docs-samples-master/speech/cloud-client# arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: U0x46d0x81b [USB Device 0x46d:0x81b], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
(env) root@root:/python-docs-samples-master/speech/cloud-client#
(env) root@root:/python-docs-samples-master/speech/cloud-client#
```

Can you please help to solve this issue ?

**Comment by jonparrott** [comment]
@jerjou @gguuss can you take a look?

**Comment by jerjou** [comment]
Hm... I'm not sure I understand. You say you *did* get it to work on one system, but not on another? What exactly is the difference between the environment you did get it to work on, and the one you didn't?

Regardless, it sounds like perhaps pulseaudio isn't setup in the environment it didn't work in. Perhaps you could try getting a small pyaudio and/or pulseaudio program working first? I'd start with the short examples in the [pyaudio documentation](https://people.csail.mit.edu/hubert/pyaudio/) and try to get those to work, and see if you can't get some more informative error messages out of that, that might point to what needs changing.

**Comment by titusece** [comment]
Hi,
Thanks for the reply, the same error I got when I try to play wav file using pyaudio example.

```
(env) root@apalis-imx6:/# 
(env) root@apalis-imx6:/# python pyaudio_test_play.py christ_song.wav
Traceback (most recent call last):
  File "pyaudio_test_play.py", line 18, in <module>
    output=True)
  File "/env/lib/python2.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/env/lib/python2.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9996] Invalid output device (no default output device)
(env) root@apalis-imx6:/#
```

What could be the problem  ? Can you please help?

**Comment by titusece** [comment]
Any help ?

**Comment by gguuss** [comment]
This is not an issue in our sample code, you should try and figure out why audio doesn't work on your imx6 first, then we'll be able to help.

**Comment by titusece** [comment]
Thanks for your reply.
Actually it worked one time for me, once I reboot and then getting this issue.
What could be the problem ?

**Comment by gguuss** [comment]
The problem appears to the audio configuration on your device. At some point something changed and caused things to break. You should try and get audio playing back on your linux system before trying the sample. This could mean anything from hotplugging your USB soundcard while watching `dmesg` to determining whether you're loading a bad module with `lsmod` ... `insmod`. There are too many variables given the information we have to really be able to isolate the fault. 

* Are you using your imx6 with Linux or Android?
  * What version of Linux do you have installed?
* Are you using an external audio card?
  * Does your USB sound card have drivers? Do they work on the Linux Distro / ARM hardware of the IMX6?

**Comment by engelke** [comment]
Not an issue with the sample code in this repository.
