### ISSUE TITLE
Is there a way to measure streaming request performance?

### ISSUE THREAD

**Issue by akmalhakimi1991** [GoogleCloudPlatform/python-docs-samples#1204]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py

## Describe the issue

This is not really an issue. Just a question. Not sure where else can I ask this. So, I want to do a performance comparison between difference Speech To Text API and not sure how to do this. Basically, I want to measure how long would it take (in seconds) for Google Speech to return the final transcription result. In other words, I want to know the time taken from the time I finish talking to the time I get the final transcription. I believe there's no direct way to do this? 

Since I'm streaming from microphone, the only way I can think of is to take the time for each interim results as the start time, and take the time when is_final is True as the end time. However, I get 0.0 sec every time.

**Comment by jonparrott** [comment]
I would recommend just using the built-in python profiling tools.
