### ISSUE TITLE
Unable to import flask

### ISSUE THREAD

**Issue by zjn0505** [GoogleCloudPlatform/python-docs-samples#1212]
## In which file did you encounter the issue?

[/appengine/standard/flask/hello_world/main.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/flask/hello_world/main.py)

### Did you change the file? If so, how?

no

## Describe the issue

Like it is said in the [guide](https://cloud.google.com/appengine/docs/standard/python/getting-started/python-standard-env#setting_up_libraries_to_enable_development), "Flask is bundled into the runtime". I suppose as long as flask is added to libraries in app.yaml, I should be able to import it from main.py. That is what has been implemented after this [commit](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1206). But I still get ImportError: No module named flask.

I've tested on online console and local env that I can't import flask simply by adding it to app.yaml, and I tested PIL in the same way, which managed to be imported.

**Comment by michaelawyu** [comment]
Hi @zjn0505 ! If you do not mind me asking, are you running your application directly or with dev_appserver.py?

**Comment by zjn0505** [comment]
Hi @michaelawyu, I ran it with `dev_appserver.py app.yaml` in local terminal and from the cloud console, both failed with `ImportError: No module named flask`

**Comment by michaelawyu** [comment]
Hi @zjn0505 , what version of _gcloud_ are you currently using? You can check it by running `gcloud --version` in the terminal.

**Comment by zjn0505** [comment]
Local env is:

> Google Cloud SDK 179.0.0
> app-engine-go 
> app-engine-python 1.9.62
> bq 2.0.27
> core 2017.11.06
> gsutil 4.28

Cloud env is:

> Google Cloud SDK 179.0.0
> alpha 2017.09.15
> app-engine-go
> app-engine-java 1.9.59
> app-engine-php " "
> app-engine-python 1.9.62
> beta 2017.09.15
> bq 2.0.27
> cloud-datastore-emulator 1.3.0
> core 2017.11.06
> datalab 20171003
> docker-credential-gcr
> gcd-emulator v1beta3-1.0.0
> gsutil 4.28
> kubectl
> pubsub-emulator 2017.09.15

**Comment by michaelawyu** [comment]
Thanks, @zjn0505 !

Did you have _Extra Libraries component for Python_ installed? It can be installed with

`gcloud components install app-engine-python-extras`

After installing this extra library you should be able to use built-in flask library without a problem. For more information, refer to [this page](https://cloud.google.com/appengine/docs/standard/python/download) :)

**Comment by zjn0505** [comment]
This is it, thank you.
