### ISSUE TITLE
Error on installing cryptography on Raspberry pie with python 2.7.9

### ISSUE THREAD

**Issue by kunalvjti** [GoogleCloudPlatform/python-docs-samples#1213]
This is in reference to https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/iot/api-client/mqtt_example

(env) pi@kp-rpi:~/python-docs-samples/iot/api-client/mqtt_example $ sudo pip install -r requirements.txtDownloading/unpacking cryptography==2.1.3 (from -r requirements.txt (line 1))
  Downloading cryptography-2.1.3.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/tmp/pip-build-V8VXtv/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-V8VXtv/cryptography
Storing debug log for failure in /root/.pip/pip.log

**Comment by kunalvjti** [comment]
Looks like i had to upgrade python setuptools to address the above error. But now running into another issue while installing libffi-dev

sudo apt-get install libffi-dev libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libssl-doc
The following NEW packages will be installed:
  libffi-dev libssl-dev libssl-doc
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,263 kB/2,416 kB of archives.
After this operation, 6,764 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  libffi-dev libssl-dev libssl-doc
Install these packages without verification? [y/N] y
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libssl-dev armhf 1.0.1t-1+deb8u6
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libssl-doc all 1.0.1t-1+deb8u6
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl-dev_1.0.1t-1+deb8u6_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl-doc_1.0.1t-1+deb8u6_all.deb  404  Not Found [IP: 93.93.128.193 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by jonparrott** [comment]
Hey @kunalvjti, this seems to be an issue with raspian itself and not necessarily our samples / client library. This question is better suited for stackoverflow where more people who have expertise will be watching. I'm going to close for now, but if you run into issues after you get through this let us know.

**Comment by kunalvjti** [comment]
Thanks. I got this resolved. Was missing a 'apt-get update' step :)
