### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by dfoley84** [GoogleCloudPlatform/python-docs-samples#1214]
I am unable to get the VIsion API working. i have enable it on the console, 
david@LinuxMint ~ $ gcloud beta auth application-default login

The environment variable [GOOGLE_APPLICATION_CREDENTIALS] is set to:
  [/home/david/google-cloud-sdk/Tensor-48a38a21ecd1.json]
Credentials will still be generated to the default location:
  [/home/david/.config/gcloud/application_default_credentials.json]
To use these credentials, unset this environment variable before
running your application.

/usr/bin/python3.5 /home/david/PycharmProjects/untitled3/labels.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/gax/retry.py", line 121, in inner
    return to_call(*args)
  File "/usr/local/lib/python3.5/dist-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Cloud Video Intelligence API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/videointelligence.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/PycharmProjects/untitled3/labels.py", line 10, in <module>
    operation = video_client.annotate_video('gs://demomaker/cat.mp4', features)
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/videointelligence_v1beta2/gapic/video_intelligence_service_client.py", line 224, in annotate_video
    self._annotate_video(request, options), self.operations_client,
  File "/usr/local/lib/python3.5/dist-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/lib/python3.5/dist-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/usr/local/lib/python3.5/dist-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
google.gax.errors.RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Cloud Video Intelligence API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/videointelligence.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.)>)

Process finished with exit code 1

**Comment by ZoeZhangBUPT** [comment]
I use python in windows, and i have the same error when i run
“annotations = client.analyze_sentiment(document=document)”
RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Project strategic-ivy-184503 (#562870082271) has billing disabled. Please enable it.)>)


do you know how to solve it.thanks

**Comment by dfoley84** [comment]
Still trying to figure out how to solve it, I did open a case with Google, as i tried to use the Code inside Google Shell

**Comment by michaelawyu** [comment]
Hi @dfoley84 ! Cloud Video Intelligence API is still in Beta and currently does not recognize the credentials set by _gcloud_ utilities. You need to set up a service account for calling it. Check out the instructions [here](https://cloud.google.com/video-intelligence/docs/common/auth#set_up_a_service_account) (you might want to skip the API Key part).

**Comment by michaelawyu** [comment]
Hi @ZoeZhangBUPT ! As the error message implies, your project (strategic-ivy-184503) does not have an active billing account associated thus some of the products may not be available. [Enable billing](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project) in your project and the problem will be solved.

**Comment by dfoley84** [comment]
HI @michaelawyu, I didn't call the API key I followed that Link that you sent a few days ago, and it didn't seem to work, I was using my linux machine i might try a windows box and see will i get the same issue.

**Comment by michaelawyu** [comment]
Hi @dfoley84 , as said earlier you need to use the service account key (usually .json file where you need to set in your environment by running command `export GOOGLE_APPLICATION_CREDENTIALS=<path_to_service_account_file>`) instead of the API key. If you were using a correct service account key, would you mind double-checking it and confirming that the environment variable is set up correctly? Thanks.
