### ISSUE TITLE
Cloud Functions 

### ISSUE THREAD

**Issue by dfoley84** [GoogleCloudPlatform/python-docs-samples#1220]
I was trying out the Google Cloud Functions but getting errors of the following 

Deployment failure:
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/index.js:1
(function (exports, require, module, __filename, __dirname) { exports.subscribe function analyzeLabelsGCS(gc, callback) {
                                                                                ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getUserFunction (/var/tmp/worker/worker.js:373:24)

exports.subscribe function analyzeLabelsGCS(gc, callback) {
   projectId: process.env.cloudvision-185709
  // Imports the Google Cloud Video Intelligence library
 // const video = require('@google-cloud/video-intelligence');
    const video = require('gcloud')
  // Creates a client
    const client = new video.VideoIntelligenceServiceClient();
​
  /**
   * TODO(developer): Uncomment the following line before running the sample.
   */
  const gc = 'gs://<MY HOME BUCKET>/cat.mp4';
​
  const request = {
    inputUri: gc,
    features: ['LABEL_DETECTION'],
  };
​
  // Detects labels in a video
  client
    .annotateVideo(request)
    .then(results => {
      const operation = results[0];
      console.log('Waiting for operation to complete...');
      return operation.promise();
    })
    .then(results => {
      // Gets annotations for video
      const annotations = results[0].annotationResults[0];

**Comment by jonparrott** [comment]
Hi @dfoley84, this repository and issue tracker are for our Python samples. You might be better served to ask this question on Stackoverflow or over at https://github.com/GoogleCloudPlatform/nodejs-docs-samples.

**Comment by dfoley84** [comment]
Hi @jonparrott Thanks for the Reply, but i notice that your Cloud functions are also in beta, just wondering is it possible, to run Google functions within the 'Cloud Function' ? i know these type of calls are possible within AWS Lambda by calling BOTO3.

**Comment by jonparrott** [comment]
Not sure what you mean by running "Google functions" within Cloud Functions.
