### ISSUE TITLE
Accessing Gemini models using Vertex AI for WebAPP outside GCP

### ISSUE THREAD

**Issue by surendransuri** [GoogleCloudPlatform/python-docs-samples#12206]
I have developed a web app outside gcp in azure platform that includes a chat application. I want to integrate gemini models in that. I possess an enterprise license for the Gemini subscription and am using service account credentials for authentication. The issue I'm encountering is that the Google OAuth tokens, generated using the service account details, expire after a certain interval.
My goal is for the web app to be continuously running and ready to answer user questions instantly, interfacing with the Gemini model without delay. However, I can't use API Keys or endpoint authentication like the Google AI developers for the enterprise version.
Please help me resolve this issue. How can I ensure my web app remains operational and responsive with continuous authentication?

**Comment by iennae** [comment]
@surendransuri , 

Could you please create an issue in the [support console](https://cloud.google.com/support/)? We are not able to provide general assistance for Google Cloud platform usage. We leave issues open so that if folks find problems with the samples that exist in this repository that we can address them.

**Comment by gericdong** [comment]
@surendransuri: can you please check if the sample for a credential refresher is useful to you? https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/generative_ai/chat_completions/chat_completions_credentials_refresher.py

**Comment by iennae** [comment]
I'm going to go ahead and close this issue as @gericdong as provided a potential example to help. If you need general assistance, please create an issue in the [support console](https://cloud.google.com/support/). If you do find an issue with samples, feel free to open up issues on those samples. Thanks!
