### ISSUE TITLE
python transcribe_streaming_mic.py 9996(Invalid input device) error help me..

### ISSUE THREAD

**Issue by krKeydown** [GoogleCloudPlatform/python-docs-samples#1226]
python transcribe_streaming_mic.py << run 

but occur error!!

how fixed this error? teach me plz.

(env) pi@raspberrypi:~/GoogleCloudSDK/google-cloud-sdk/bin/python-docs-samples/speech/cloud-client $ python transcribe_streaming_mic.py
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Traceback (most recent call last):
  File "transcribe_streaming_mic.py", line 193, in <module>
    main()
  File "transcribe_streaming_mic.py", line 181, in main
    with MicrophoneStream(RATE, CHUNK) as stream:
  File "transcribe_streaming_mic.py", line 67, in __enter__
    stream_callback=self._fill_buffer,
  File "/home/pi/GoogleCloudSDK/google-cloud-sdk/bin/python-docs-samples/speech/cloud-client/env/local/lib/python2.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/pi/GoogleCloudSDK/google-cloud-sdk/bin/python-docs-samples/speech/cloud-client/env/local/lib/python2.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9996] Invalid input device (no default output device)

**Comment by jonparrott** [comment]
@jerjou @dizcology can ya'll take a look?

**Comment by jerjou** [comment]
It looks like pyaudio / portaudio isn't detecting the microphone on your raspberry pi. I don't have a raspberry pi handy to try this on, but a quick search for "pyaudio raspberry pi" and "portaudio raspberyy pi" turns up some pages that look promising:

https://www.raspberrypi.org/forums/viewtopic.php?t=25173
https://app.assembla.com/wiki/show/portaudio/Platforms_RaspberryPi

You might be able to get away with just running `sudo apt-get install python-pyaudio` (from the first link)

**Comment by krKeydown** [comment]
thanks reply

install pyaudio and try more your link
and occur error T.T

pi@raspberrypi:~/GoogleCloudSDK/google-cloud-sdk/bin/python-docs-samples/speech/cloud-client $ python transcribe_streaming_mic.py/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.9.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "transcribe_streaming_mic.py", line 34, in <module>
    from google.cloud import speech
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/speech/__init__.py", line 22, in <module>
    from google.cloud.speech.client import Client
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/speech/client.py", line 22, in <module>
    from google.cloud.client import Client as BaseClient
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/client.py", line 25, in <module>
    import google.auth.transport.requests
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 30, in <module>
    caught_exc,
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
ImportError: The requests library is not installed, please install the requests package to use the requests transport.

**Comment by jerjou** [comment]
Hello -

The ImportError message should give you a clue - it's looking for a library that hasn't been installed. Try going through the [setup instructions](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech/cloud-client#setup) in the `README.md` for this script, which should at least get you past this error.

**Comment by engelke** [comment]
If the issue persists after reviewing the setup instructions you can reopen this.
