### ISSUE TITLE
TransportError: ('Connection broken: IncompleteRead(208 bytes read)', IncompleteRead(208 bytes read))

### ISSUE THREAD

**Issue by cpraveen412** [GoogleCloudPlatform/python-docs-samples#1235]
Hi,
I'm trying to connect to My BigQuery using service_account.json file. But I'm facing issues in connection.
1) Initially I got "module Cloud not detected" Error. I solved it by uploading packages to GAE while pushing the app.
2) After That I got [TransportError: HTTPSConnectionPool](https://gist.github.com/cpraveen412/dcc6c70993c1fafb5d1ea64fd9f015f1#file-error1) Error. I resolved this by adding ssl package in [app.yml](https://gist.github.com/cpraveen412/dcc6c70993c1fafb5d1ea64fd9f015f1#file-app-yml) file and imported into [main.py](https://gist.github.com/cpraveen412/dcc6c70993c1fafb5d1ea64fd9f015f1#file-main-py) file.
3) Now I'm getting another Error saying [TransportError: ('Connection broken: IncompleteRead(208 bytes read)', IncompleteRead(208 bytes read))](https://gist.github.com/cpraveen412/dcc6c70993c1fafb5d1ea64fd9f015f1#file-error2).

The same application worked fine in DEV on my PC but it is not working in GAE.

Can anyone Please help me?

Thanks

**Comment by jonparrott** [comment]
Hi there, unfortunately the cloud client libraries are not yet supported on App Engine standard. We're working on it and you can follow progress at https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893.

In the meantime, you can use the google-api-python-client. There's a sample for doing so [here](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/bigquery).
