### ISSUE TITLE
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.RESOURCE_EXHAUSTED, Resource has been exhausted (e.g check quota).)>

### ISSUE THREAD

**Issue by krKeydown** [GoogleCloudPlatform/python-docs-samples#1238]
Did you exceed the api request limit?

**Comment by adrobnych** [comment]
I also see this error. I tested streaming with mic. Now it's second day when I see this error even with other examples like

python transcribe_async.py resources/audio.raw

I can't realize which quota I broken. My GoogleCloud Dashboard shows no-data for usage

**Comment by krKeydown** [comment]
I've seen this error, but the sample rate changes from 16000 to 48000 so it works fine. But again,
 I see this error.

**Comment by jonparrott** [comment]
@jerjou @gguuss can you take a look?

**Comment by krKeydown** [comment]
thanks reply, jonparrott 

attch screenshot

![2017-12-05-150030_1920x1080_scrot](https://user-images.githubusercontent.com/33707734/33592238-383a223a-d9cd-11e7-84a1-eaf152452eda.png)

**Comment by jerjou** [comment]
Hello-

Did you set up your auth? ie did you download a service account and set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to it? [More details here](https://cloud.google.com/speech/docs/auth#application_default_credentials)

**Comment by nnegrey** [comment]
This appears to have been resolved. Please feel free to reopen.
