### ISSUE TITLE
Bring appengine/angular up to standards

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/python-docs-samples#124]

**Comment by bkovacev** [comment]
@jerjou When do you think this will occur?

**Comment by jerjou** [comment]
Mostly this is a reminder bug to add integration tests and audit for pep8 style compliance. It's fairly low priority at the moment, but shouldn't stop you from using the sample if you'd like. ie there shouldn't be anything functionally incorrect about it or anything.

If you have reason for it to be of higher priority, do let us know, so we can take that into consideration!

**Comment by jmkrimm** [comment]
Can we get a sample for Angular 2+ on App Engine?

**Comment by engelke** [comment]
The sample is still working in App Engine Standard Environment for Python 2.7.

New features should be requested and followed on the issues tracker at [https://cloud.google.com/support/docs/issue-trackers](https://cloud.google.com/support/docs/issue-trackers) rather than for this repository.
