### ISSUE TITLE
Cloud IoT Core: mqtt: SERVER:The authorization token expired.

### ISSUE THREAD

**Issue by mkahn5** [GoogleCloudPlatform/python-docs-samples#1264]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/mqtt_example/cloudiot_mqtt_example.py

and my version on:
https://github.com/mkahn5/iot-projects/blob/master/RaspberryPi_Thermostat_Cloud_IoT/pubsub_thermostat_f10.py

### Did you change the file? If so, how?

Just changed the payload in my version, https://github.com/mkahn5/iot-projects/blob/master/RaspberryPi_Thermostat_Cloud_IoT/pubsub_thermostat_f10.py

## Describe the issue
After the script is running for awhile I will receive the error mqtt: SERVER:The authorization token expired. in Cloud IoT core. The script is only publishing every 120 seconds to PubSub. It will resolve itself over time, sometimes it does not. How long does the MQTT token last for? 

Here is the script failing then recovering:

Publishing payload {"temp": 68.0, "time": "12/10/2017 13:17:41 PST"}
Connection Result: 4: The client is not currently connected.
Disconnected: 5: The connection was refused.
Publishing payload {"temp": 68.0, "time": "12/10/2017 13:19:41 PST"}
Connection Result: 4: The client is not currently connected.
Disconnected: 5: The connection was refused.
Creating JWT using RS256 from private key file rsa_private.pem
Connection Result: 0: No error.
Publishing payload {"temp": 68.0, "time": "12/10/2017 13:21:42 PST"}
Subscribed:  (1,)
Received message '' on topic '/devices/temphome/config' with Qos 1
Published message acked, sleeping 120 sec
Publishing payload {"temp": 68.0, "time": "12/10/2017 13:23:42 PST"}
Published message acked, sleeping 120 sec
Publishing payload {"temp": 68.0, "time": "12/10/2017 13:25:43 PST"}
Published message acked, sleeping 120 sec
Publishing payload {"temp": 68.0, "time": "12/10/2017 13:27:43 PST"}
Published message acked, sleeping 120 sec
Publishing payload {"temp": 68.0, "time": "12/10/2017 13:29:43 PST"}

**Comment by mkahn5** [comment]
<img width="694" alt="screen shot 2017-12-05 at 11 05 25 pm" src="https://user-images.githubusercontent.com/5521191/33809732-558ec002-ddb0-11e7-84c8-3e066cdea6a2.png">

**Comment by mkahn5** [comment]
<img width="452" alt="screen shot 2017-12-10 at 1 44 49 pm" src="https://user-images.githubusercontent.com/5521191/33809735-5d88d1f8-ddb0-11e7-9576-74b21dfc7ffd.png">

**Comment by jonparrott** [comment]
@gguuss can you take a look?

**Comment by gguuss** [comment]
Yup, I was seeing strange things from the console last week as well.

**Comment by gguuss** [comment]
I'm guessing that you're not refreshing the JWT after 3600 seconds.    @mkahn5 do you have code similar to the following that is executing:

        if seconds_since_issue > 60 * jwt_exp_mins:
            print('Refreshing token after {}s').format(seconds_since_issue)
            client.loop_stop()
            jwt_iat = datetime.datetime.utcnow()
            client = get_client(
                args.project_id, args.cloud_region,
                args.registry_id, args.device_id, args.private_key_file,
                args.algorithm, args.ca_certs, args.mqtt_bridge_hostname,
                args.mqtt_bridge_port)

**Comment by mkahn5** [comment]
@gguuss Nope, I was unaware of the JWT expiration. I can try that snip see if it works. Maybe I missed the JWT refresh in the quickstart example.

**Comment by mkahn5** [comment]
@gguuss Couldnt find any documentation on refreshing JWT for cloud iot core. Can you make a pull request on my project? https://github.com/mkahn5/iot-projects/blob/master/raspberrypi_temp_monitor_cloud_iot/temp_monitor.py

**Comment by gguuss** [comment]
Done, let me know if the PR helps!

**Comment by mkahn5** [comment]
@gguuss hey Gus, I implemented the PR and JWT refresh and now getting another error..

mqtt: SERVER:The connection was closed because MQTT keep-alive check failed.

Thoughts?
![screen shot 2018-01-04 at 1 33 26 pm](https://user-images.githubusercontent.com/5521191/34585312-091eb404-f154-11e7-9630-c48b8c9997a4.png)

**Comment by gguuss** [comment]
@mkahn5 I'm not sure I've seen this error before - is this happening after a duration of time or are you seeing it at random?

**Comment by mkahn5** [comment]
@gguuss Deleted comment in thread, error was from another device. Will provide feedback on the PR and JWT refresh soon. Thanks :)
