### ISSUE TITLE
detect.py with document call gets UnicodeEncodeError: 'ascii' codec can't encode character...

### ISSUE THREAD

**Issue by rz93594** [GoogleCloudPlatform/python-docs-samples#1273]
## In which file did you encounter the issue?

python-docs-samples/vision/cloud-client/detect/detect.py

## Describe the issue

When processing a sample jpg of a document it would start to process the first part of the document and then dump out on an error shown below.

```./detect.py document letter.jpg```
Block Content: Bor953Sioux,lookout
Block Bounds:
 vertices {
  x: 1432
  y: 262
}
vertices {
  x: 2301
  y: 262
}
vertices {
  x: 2301
  y: 572
}
vertices {
  x: 1432
  y: 572
}

Traceback (most recent call last):
  File "./detect.py", line 699, in <module>
    run_local(args)
  File "./detect.py", line 578, in run_local
    detect_document(args.path)
  File "./detect.py", line 522, in detect_document
    print('Block Content: {}'.format(block_text)).decode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201d' in position 369: ordinal not in range(128)

I attempted to add encode/decode.('utf-8') to the print statements to resolve the problem but making the following addition to the beginning of detect.py resolved my issue in the end.   Probably not an ideal solution but it moved me forward.

### I made the following changes to resolve the issue

```
32,35d31
< import sys
< reload(sys)
< sys.setdefaultencoding('utf-8')
<
```

**Comment by jonparrott** [comment]
@dizcology can you take a look?

**Comment by namangt68** [comment]
Is this repo updated with above issue fixed?

**Comment by nnegrey** [comment]
This appears to have been resolved in sample updates, if this is not true, feel free to reopen the issue.
