### ISSUE TITLE
extract_table does not check that the job config is an ExtractJobConfig

### ISSUE THREAD

**Issue by quarrazzella** [GoogleCloudPlatform/python-docs-samples#1281]
Trying to use this one for my task - export_data_to_gcs.py. But what I get is ''google.api_core.exceptions.BadRequest: 400 Operation cannot be performed on a nested schema. Field: user"

**Question 1**

Is there still a way to export this kind of tables from GBQ to GCS using CSV format?

I tried to export the table using JSON, but failed as well. Here's the code

```
from google.cloud import bigquery

def export_data_to_gcs(dataset_id, table_id, destination):
    bigquery_client = bigquery.Client()
    dataset_ref = bigquery_client.dataset(dataset_id)
    table_ref = dataset_ref.table(table_id)

    job_config = bigquery.LoadJobConfig()
    job_config.source_format = 'NEWLINE_DELIMITED_JSON'

    job = bigquery_client.extract_table(table_ref, destination, job_config=job_config)

    job.result()  # Waits for job to complete

    print('Exported {}:{} to {}'.format(
        dataset_id, table_id, destination))
```

**Question 2**

How do I export the table with nested schema using JSON format?

**Question 3**

How do I export query result table to GSC?

**Comment by jonparrott** [comment]
@tswast can you take a look?

@quarrazzella thanks for reporting, but in the future these sort of broad questions are better suited for Stackoverflow.  :)

**Comment by tswast** [comment]
The code you provide appears correct. I'll give it a try.

**Comment by quarrazzella** [comment]
Any news? @tswast

**Comment by tswast** [comment]
I am able to reproduce the issue using the `test_table_nested` from the integration tests in this library. I can successfully export from the web UI, so it is something on this end.

**Comment by tswast** [comment]
I found the issue.

```python
job_config = bigquery.LoadJobConfig()
job_config.source_format = 'NEWLINE_DELIMITED_JSON'
```

should be changed to

```python
job_config = bigquery.ExtractJobConfig()
job_config.destination_format = 'NEWLINE_DELIMITED_JSON'
```

since this is an extract job.

**Comment by tswast** [comment]
I imagine the client library could probably help with this by checking that the provided `job_config` argument is of the right type, or at least produces an extract job configuration if we want to be duck-typed about it.

**Comment by tswast** [comment]
Hopefully this resolves your issue.

I've opened https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4622 on the library to do some better checking on the `job_config` arguments.
