### ISSUE TITLE
Django Load Static

### ISSUE THREAD

**Issue by NikosTzagkarakis** [GoogleCloudPlatform/python-docs-samples#1283]
I have a Django app on GCloud Flex and everything works fine except that I cannot find a way to load static files.

These are the steps that I have taken:
a) Handlers in app.yampl:

handlers:
- url: /static
  static_dir: static/

b) settings.py:
STATIC_ROOT = 'static'
STATIC_URL = '/static

c) index.html:

{% load static %}

Is there something I am missing? 
Thanks!

**Comment by michaelawyu** [comment]
Hi!

Are you using `gunicorn` to serve your Django application in App Engine Flexible Environment?

**Comment by NikosTzagkarakis** [comment]
Hello there!

Thanks for the fast answer.

Yes I am using gunicorn and I have configured it at the app.yaml file as
follows:

entrypoint: gunicorn -b :$PORT mysite.wsgi


Let me know if you need more information.

Best,
Nikos

**Comment by michaelawyu** [comment]
Hi!

If you are using `gunicorn`, static files in your web application will not be served as `gunicorn` will only host the app itself. It is recommended that you collect all the static files, upload them to Cloud Storage and update the `STATIC_ROOT` variable to serve static files from other sources. You may want to check out [Running Django in App Engine Flexible Environment](https://cloud.google.com/python/django/flexible-environment) for more information.

More specifically,
(Create a Cloud Storage bucket) `gsutil mb gs://<your-gcs-bucket>`
(Make the bucket publically readable) `gsutil defacl set public-read gs://<your-gcs-bucket>`
(Collect static files) `python manage.py collectstatic`
(Sync to Cloud Storage) `gsutil rsync -R static/ gs://<your-gcs-bucket>/static`
Update `STATIC_URL` to `https://storage.googleapis.com/<your-gcs-bucket>/static/`

Do not forget to update `<your-gcs-bucket>` to a name of your own :) `gsutil` is a utility for accessing Cloud Storage and it comes with [Cloud SDK](https://cloud.google.com/sdk/).

Technically speaking you do not have to use Cloud Storage. Any HTTP server (apache2, nginx, etc.) capable of serving static files will do.

**Comment by NikosTzagkarakis** [comment]
Hello again!.. Thank you so much for your response and your help! I will try it and come back to write about the results and It (hopefully) worked. I guess that I am not the only one that will face this issue.

Thanks again!

**Comment by NikosTzagkarakis** [comment]
It worked! I used a Google Cloud Storage Bucket and it works perfectly! Thank you so much! :)

**Comment by michaelawyu** [comment]
Great 👍
