### ISSUE TITLE
"Cannot load CSV data with a nested schema" with a JSON file in load_data_by_post

### ISSUE THREAD

**Issue by Falydoor** [GoogleCloudPlatform/python-docs-samples#129]
Hello

With the new load_data_by_post, I'm not able to upload a JSON file and I have this error "Cannot load CSV data with a nested schema".

Sounds like the job expect a CSV not a JSON file so do I need to do something special ?

And I tested on the web client with my data/schema and it works fine, here the [schema](https://gist.github.com/Falydoor/200477dee839c84afc2a) and the [data](https://gist.github.com/Falydoor/cc4fc2a28a91e86cefb5) in case you wanna test.

Regards

**Comment by jonparrott** [comment]
@jerjou do you mind checking this one out?

**Comment by jerjou** [comment]
Oops - overlooked json data uploads. Thanks for catching that! PR pending..

**Comment by jerjou** [comment]
Okay - should be fixed. Let us know if you run into any issues!
