### ISSUE TITLE
Admin Console not working in tutorial "Running Django in the App Engine Flexible Environment"

### ISSUE THREAD

**Issue by QuestionC** [GoogleCloudPlatform/python-docs-samples#1290]
## In which file did you encounter the issue?

/python-docs-samples/appengine/flexible/django_cloudsql/mysite/settings.py

### Did you change the file? If so, how?

I replaced the middleware settings in your settings.py with those from fresh `django-admin startproject`
```
-MIDDLEWARE_CLASSES = (
+MIDDLEWARE = [
+    'django.middleware.security.SecurityMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
-    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware',
-    'django.middleware.security.SecurityMiddleware',
-)
+]
```

## Describe the issue

I have been following the tutorial at 
https://cloud.google.com/python/django/flexible-environment

When connecting to the admin login, I got the error
> 'WSGIRequest' object has no attribute 'user'

This appears to be caused by the seetings.py using 'old-style' MIDDLEWARE configuration as described in https://stackoverflow.com/questions/37949198/wsgirequest-object-has-no-attribute-user-django-admin.

After making the change, the admin console works.

**Comment by imwillhang** [comment]
Not only that, but you also need to remove `django.contrib.auth.middleware.SessionAuthenticationMiddleware`, otherwise things will continue to break. This tutorial needs to be updated for Django 2.0. I spent a solid hour banging my head against this :(

**Comment by michaelawyu** [comment]
Temporarily revert to Django 1.11.7 now for Python 2.7 users
#1292
