### ISSUE TITLE
Is it normal for non-english language to have a long transcription time?

### ISSUE THREAD

**Issue by akmalhakimi1991** [GoogleCloudPlatform/python-docs-samples#1294]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py

## Describe the issue

Is it normal for non-english language to have longer transcription time? When I run the script with `en-US`, it will take only 1 sec max to get the final transcription. However when I changed it to `ms-MY` and `cmn-Hans-CN`, it took at least 5 seconds to get the final transcription. I can see the interim result is there but the final transcription didn't come immediately.

**Comment by jonparrott** [comment]
@dizcology can you take a look?

**Comment by akmalhakimi1991** [comment]
Hi. I just tested the same script on a faster network (100mbps) and I can see the transcription time for non-English are a lot faster and on par with English. FYI the first test was done on 8mbps network.

**Comment by jonparrott** [comment]
@akmalhakimi1991 are we good to close this, then?

**Comment by akmalhakimi1991** [comment]
Hi @jonparrott . My program will not run on a 100mbps network. I will be using it mostly on a 10mbps - 20mbps Wi-Fi network. What I don't understand is, why `en-US` transcription didn't take as long as `ms-MY` and `cmn-Hans-CN` on the slower network. Is it expected for the non-English to perform worse on a slower connection? And why the difference is so big?  
  
FYI, here's our test results :  
  
| Language  | Average Time Taken (10mbps) | Average Time Taken (100mbps) |
| ------------- | ------------- | ------------- |
| en-US  | 0.5 s  | 0.5 s |
| ms-MY  | 5.3 s  | 0.7 s|
| cmn-Hans-CN  | 6.1 s  | 0.6 s |  
  
Testing methodology:  
  

1. Each test is done using a set of sentences. Each set has 10 sentences.  
2. Measurement is taken from the timestamp of the last interim result to the time of final result (is_final:True)

**Comment by jonparrott** [comment]
@dizcology would be able to track that down.

**Comment by dizcology** [comment]
@nnegrey Please take a look.

**Comment by dizcology** [comment]
@akmalhakimi1991 Are you still experiencing the same issue?

**Comment by akmalhakimi1991** [comment]
I haven't use the library for quite some time (and I don't have the capacity to test it now), but the last time I used it, I still experience the problem (I think it was somewhere in December)
