### ISSUE TITLE
How to run unit tests?

### ISSUE THREAD

**Issue by degroote22** [GoogleCloudPlatform/python-docs-samples#1299]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/taskqueue/counter

### Did you change the file? If so, how?

The instructions for running locally and deploying are incredible useful but I can't figure out how to run the test that came within this sample folder.

## Describe the issue

I'm new to Python but I'm not new to programming in general, which means that I can do most stuff by I have zero knowledge of the Python ecosystem.
I tried following [other tutorials on google-app-engine](https://cloud.google.com/appengine/docs/standard/python/tools/localunittesting) but none of them would work because the test runner wouldn't find Google's libraries.
I guess that if you'd packed the SDK on pip then the test runner would find the file, as well as pylint. Isn't that an option?

Anyway, I'm here requesting that you also instruct us on the 'readme.md' how to run the test that comes in the sample :)

Thanks for your time :+1:

**Comment by michaelawyu** [comment]
Hi degroote22!

We have a guide for running tests and automated tools in the [authoring guide of this repository](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#running-tests-and-automated-tools).
