### ISSUE TITLE
Pub / Sub list_subscriptions_in_topic uses wrong method

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/python-docs-samples#1305]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/06453e45a644fae39ea2c22d4c761645b71aa42b/pubsub/cloud-client/subscriber.py#L30

## Describe the issue

`publisher.list_topic_subscriptions()` should be used rather than `subscriber.list_subscriptions()`

See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4426

**Comment by jonparrott** [comment]
@andrewsg can you take this on?

**Comment by andrewsg** [comment]
Problem was solved but bug wasn't closed. Closing now.
