### ISSUE TITLE
Streaming from mic sample code not working after update with error - "TypeError: __call__() got multiple values for keyword argument 'timeout'"

### ISSUE THREAD

**Issue by akmalhakimi1991** [GoogleCloudPlatform/python-docs-samples#1337]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py

## Describe the issue

The sample code straight up not working after the new `0.31.0` update. Full error message:  

>   File "transcribe_streaming_mic.py", line 234, in <module>
>     main()
>   File "transcribe_streaming_mic.py", line 225, in main
>     responses = client.streaming_recognize(streaming_config, requests)
>   File "/home/nao/.local/lib/python2.7/site-packages/google/cloud/speech_v1/helpers.py", line 69, in streaming_recognize
>     options,
>   File "/home/nao/.local/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
>     return wrapped_func(*args, **kwargs)
>   File "/home/nao/.local/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
> 
> on_error=on_error,
>   File "/home/nao/.local/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
>     return target()
>   File "/home/nao/.local/lib/python2.7/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
>     return func(*args, **kwargs)
>   File "/home/nao/.local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
>     result = callable_(*args, **kwargs)
>     TypeError: __call__() got multiple values for keyword argument 'timeout'

**Comment by jonparrott** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4820
