### ISSUE TITLE
Vision: error: 'dict' object has no attribute 'before_request'

### ISSUE THREAD

**Issue by lxmn** [GoogleCloudPlatform/python-docs-samples#1347]
error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: 'dict' object has no attribute 'before_request'

Can anyone tell me how to resolve this issue

**Comment by jonparrott** [comment]
Can you let us know which sample you're using and the output of `pip freeze`?

**Comment by carlsednaoui** [comment]
Hi @theacodes, I'm having a similar issue.

[Note: this is my first time trying to use a Google API.]

Here is my pip freeze: http://share.mailcharts.com/012f0Y080R01
Here is the image I am trying to use: https://dha4w82d62smt.cloudfront.net/items/2i1h33230w0C0U3Q1E44/demo-image.jpg?X-CloudApp-Visitor-Id=1951556&v=23a7e102

Here is a more complete example of what I have:

```
from google.cloud.vision_v1 import ImageAnnotatorClient

# Instantiates a client
client = ImageAnnotatorClient(credentials="/Users/carl/sites/google_creds.json")

image_url = "https://dha4w82d62smt.cloudfront.net/items/2i1h33230w0C0U3Q1E44/demo-image.jpg?X-CloudApp-Visitor-Id=1951556&v=23a7e102"

request = {'image':{'source':{'image_uri':image_url}}}

response = client.annotate_image(request)
```

Let me know if you need more info. I can also post this on StackOverflow if that'd be preferable.

**Comment by nnegrey** [comment]
Hi, do you have more info on the error you're seeing?

**Comment by nnegrey** [comment]
Going to close this issue due to how old it is, please feel free to reopen. :)
