### ISSUE TITLE
Sample code is out of sync

### ISSUE THREAD

**Issue by talonx** [GoogleCloudPlatform/python-docs-samples#1352]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/monitoring/api/v3/api-client/custom_metric.py#L176

### Did you change the file? If so, how?
No

## Describe the issue
The function get_client() does not exist in list_resources

**Comment by engelke** [comment]
PR #1396 addressed this issue.
