### ISSUE TITLE
"on_disconnect. 1. Out of memory"

### ISSUE THREAD

**Issue by junying1** [GoogleCloudPlatform/python-docs-samples#1357]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/mqtt_example/cloudiot_mqtt_example.py

### Did you change the file? If so, how?

No

## Describe the issue

I'm seeing a hard to track down error with Google Cloud IoT. I have 2 projects set up with IoT API enabled. I'm using the same "quickstart" instructions to test, by setting up "my-registry" and "my-device". Let's call them projects A and B. I then run both the python and node examples pulled straight from git. The node example runs fine for both projects A and B, validated by pulling using gcloud. However, the python example works for project A, but with project b gets a "on disconnect. 1. out of memory" error. There is never a "connection accepted" message for B, but yes for A. "Out of memory" seems to be a generic error, not really the issue. It could represent a variety of issues in connectivity. Nothing on the server side Anyone encountered this one before? I appreciate any help in resolving or at least trace the eror.

**Comment by junying1** [comment]
Turns out it's the python version. It was just about impossible to debug. I ended trying on many different devices/os to slowly isolate the issue. Looks like newly created projects rely on newer versions of google cloud sdk and python. Must have python 2.7.14.

**Comment by Goruti** [comment]
Hi, 

I see this an old issue that seems to be fixed using Python 2.7.14. (back in 2018)

Nowadays I am getting the same issue using Python 3.8.8. Has anyone faces this?

Thanks!
Diego

**Comment by harshilfromventurelabs** [comment]
Yes I too am facing this issue right now. any solution @Goruti ??
