### ISSUE TITLE
streaming_recognize blocking

### ISSUE THREAD

**Issue by tadly** [GoogleCloudPlatform/python-docs-samples#1364]
## In which file did you encounter the issue?

[transcribe_streaming_mic.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/d93f8e90c974b24c67f57669d388ae84f705b0ed/speech/cloud-client/transcribe_streaming_mic.py) I guess

### Did you change the file? If so, how?
Doesn't matter

## Describe the issue
Title probably gives it away already.
`streaming_recognize` is (or can be) blocking f.e when the mic is muted.
=> no audio stream and you're stuck.

Also, the [loop](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/d93f8e90c974b24c67f57669d388ae84f705b0ed/speech/cloud-client/transcribe_streaming_mic.py#L128) only loops if/when the server returns something right?

As I'm trying to implement a engine that behaves like any of the google assistant devices (that is to stop recording if nothing was spoken for _n_ seconds. being able to interrupt current ASR etc.) I'm interested in ways that don't block at all but give me the ability to immediately exit/cancel the process.  
I'm working with `asyncio` and am kind of stuck on this.

Is there another way I'm just unable to find in any of the docs (as many as there are) or am I just being to stupid?

Any help/examples would be much appreciated :)

**Edit:**
I since have learned that it is enough for google to not be able to recognize any speech and `streaming_recognize` will block.

**Edit 2:**
Right, not `streaming_recognize` is blocking but iter access to `grpc._channel._Rendezvous`.
Question now is how I'd be able to tell whether or not a result is available.

**Edit 3:**
`_Rendezvous.result` with a `timeout` inside a simple `while` loop is probably what I want :)
At least I've got a loop that doesn't block now.

Whether or not my `_Rendezvous.result(timeout=0.1)` will actually return something on speech I'll be able to test later today.

**Edit 4:**
`_Rendezvous.result` does not work.

**Comment by pedrorjbr** [comment]
Did u have any update here? I am stucked on responses iteraror...
```
        for response in responses:
            if not response.results:
                continue
            result = response.results[0]
            if not result.alternatives:
                continue
            transcript = result.alternatives[0].transcript
            if result.is_final:
                self.transcript = transcript
```
