### ISSUE TITLE
flac encoding vs. headers: google.api_core.exceptions.InvalidArgument: 400 Specify FLAC encoding to match file header.

### ISSUE THREAD

**Issue by bjohas** [GoogleCloudPlatform/python-docs-samples#1380]
## In which file did you encounter the issue?

 transcribe_async.py 

### Did you change the file? If so, how?

Unchanged

## Describe the issue

I've not managed to get flac encoded with ffmpeg to match the headers (encoding flac, 16000). Does anybody have a conversion command (ffmpeg ideally) that produces compatible flac?

For flac, why is it necessary to specify the header anyway?

**Comment by jonparrott** [comment]
@jerjou @dizcology can one of you take a look?

**Comment by bjohas** [comment]
Many thanks - happy to engage if further data is needed.

**Comment by nnegrey** [comment]
Hi, it looks like the encoding you specified in the request does not match the encoding of the file. If this is not the case, please feel free to reopen the issue. :)
