### ISSUE TITLE
how to run the entity sentiment for each line of a file saved in google cloud storage?

### ISSUE THREAD

**Issue by monajalal** [GoogleCloudPlatform/python-docs-samples#1381]
I need to write a script that runs a python script on each line of a text file as an input separately and then saves the result in json file named after the line it reads the file from. 

So text file input.txt looks like below:
Monday
Tuesday 
Wednesday
Thursday
Friday

and I want the output be like 1.json, 2.json, 3.json, 4.json, 5.json in output folder.

The way the script is ran is like below

   ```
 $ python entity_sentiment.py sentiment-entities-text "Thank you for saying you won't use vulger language anymore"
    Mentions: 
    Name: "vulger language"
      Begin Offset : 35
      Content : vulger language
      Magnitude : 0.699999988079071
      Sentiment : -0.699999988079071
      Type : 2
    Salience: 1.0
    Sentiment: magnitude: 0.699999988079071
    score: -0.699999988079071
```

In which for example, the input to script could be assumed the first line of the file.

Can you suggest what to do? When I selected the sentiment-entities-file it used the entire text in the file as input while I want each line of the file to be considered input.

Additionally, is it doing the task of entity-based sentiment analysis?

**Comment by jonparrott** [comment]
Hi @monajalal, this question might be better suited for Stackoverflow- generally this issue tracker is for bugs or issues with the samples as they are written.
