### ISSUE TITLE
video / labels doesn't report actual label segments

### ISSUE THREAD

**Issue by exjohn** [GoogleCloudPlatform/python-docs-samples#1391]
In `python-docs-samples/video/cloud-client/labels/labels.py`, line 53:

```
    segment_labels = result.annotation_results[0].segment_label_annotations
```
is not as helpful as
```
    segment_labels = result.annotation_results[0].shot_label_annotations
```

The former is the current state. It always returns the whole clip length for each label.

The latter returns the label segments as detected.

**Comment by nnegrey** [comment]
Hi, this appears to have been resolved on the backend potentially. 
Most up to date sample is here: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/video/cloud-client/analyze/analyze.py#L57-L94
