### ISSUE TITLE
MicroPyhon Support

### ISSUE THREAD

**Issue by yozmag** [GoogleCloudPlatform/python-docs-samples#1403]
Looking at iot/api-client/mqtt_example/cloudiot_mqtt_example.py the exemple is not support on devices running on https://micropython.org/. If somehow this lib could be ported to Micropython would allow a vast range of devices to connect to Google Clould IOT, that cant connect otherway, incluiding the MQTT service.

**Comment by gguuss** [comment]
Thanks for the request, we're working on a solution for MicroPython / CircuitPython.

**Comment by gguuss** [comment]
This just launched about 60 seconds ago!

[Google Cloud IoT Core MicroPython](https://github.com/googlecloudplatform/iot-core-micropython)
