### ISSUE TITLE
client.document_text_detection()  errors "Bad image data." but the file seems fine

### ISSUE THREAD

**Issue by grantdelozier** [GoogleCloudPlatform/python-docs-samples#1432]
## In which file did you encounter the issue?

You can download the file in question from s3 here: https://s3.amazonaws.com/oseberg-public/nlp-files/57c3bad43cc4b5d1ce9cecf2ff6b2fde55c0e797c366704ee264c4091cc43d4a_copy.png

## Describe the issue

Download the file and run the following:

```
from google.cloud import vision
client = vision.ImageAnnotatorClient()

downloaded_image = 'path_to_file'

with open(downloaded_image, 'rb') as f:
     content = f.read()

image = vision.types.Image(content=content)
response = client.document_text_detection(image)

error {
  code: 3
  message: "Bad image data."
}
```

I don't think there is anything wrong with the png file in question. I can open the png just fine using MacOSX Viewer application, and can convert it to other image types using imagemagick tool from the console.

Is there any way I can get more information on how the image is bad?

**Comment by nnegrey** [comment]
Hi, did you use `io.open`?
` with io.open(path, 'rb') as image_file:`

**Comment by nnegrey** [comment]
Going to close this issue due to how old it is, please feel free to reopen. :)
