### ISSUE TITLE
Is there a way to gracefully stop transcription process if it's not returning anything within a period of time?

### ISSUE THREAD

**Issue by akmalhakimi1991** [GoogleCloudPlatform/python-docs-samples#1443]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py

## Describe the issue

Is there any way to gracefully stop the `listen_print_loop()` if it's not returning anything within a period of time? I know I can add a timeout parameter in `streaming_recognize()` but seems like the minimum timeout is too high and not practical for me (3 * audio-duration + 5 seconds). Reason being is that the language that I used has a very slow final transcription time (3-8s) and sometimes the final transcription didn't come at all. So I want to have a hard timeout where if there's no final transcription given after few seconds user finishes speaking, the transcription waiting process is gracefully stopped and proceed to use the interim results.

**Comment by nnegrey** [comment]
Hi this is a bit old, but would the `single_utterance` field be using in `RecognitionConfig`?
https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#streamingrecognitionconfig

Please feel free to reopen this issue if that doesn't help.
