### ISSUE TITLE
Can we load data into cloud storage through pubsub

### ISSUE THREAD

**Issue by srivasp2006** [GoogleCloudPlatform/python-docs-samples#1450]
Hi ,

Our requirement is to load data into cloud storage through pubsub , as part of testing we have executed scripts which are given in below path 
python-docs-samples/pubsub/cloud-client
quickstart.py
iam.py
subscriber.py
publisher.py
requirements.txt
Can you please suggest where we have to give cloud storage bucket path in this scripts or console level.

and my source files are at desktop and other paths .

Where we can mention source paths in below sample scripts ?

After execution of the above scripts I can see some messages ids delivering from topic to subscriber but I want to load a files through pubsub to cloudstorage.

Please suggest the reference docs.

Even in push-subscriber unable to give bucketpath

Regards,
Sri

**Comment by anguillanneuf** [comment]
@srivasp2006 How large are these files? Cloud Pub/Sub has a [size limit](https://cloud.google.com/pubsub/quotas#resource_limits) for messages. I'm quoting the most up-to-date information below:

Message size (the data field): 10MB (the maximum request size)
Attributes per message: 100
Attribute key size: 256 bytes
Attribute value size: 1024 bytes

If you have the right data for Cloud Pub/Sub, you should be able to read the data from the source files,  by pointing to them using something like [this](https://stackoverflow.com/questions/4028904/how-to-get-the-home-directory-in-python). The publish call takes `bytestrings` only, so please keep that in mind.
