### ISSUE TITLE
Django 2.0 doesn't support Python 2.7 mismatch with official Cloud Platform tutorial

### ISSUE THREAD

**Issue by vggl** [GoogleCloudPlatform/python-docs-samples#1451]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/flexible/django_cloudsql/requirements.txt

### Did you change the file? If so, how?
No.

## Describe the issue
In the following [official GCP tutorial], it states "This tutorial requires Python 2.7 or 3.4." and then it makes you use [this GitHub repo]. In the "requirements.txt" file, Django version is: "Django==2.0.3" . However [Django 2.0 doesn't support Python 2.7] ("Django 1.11.x series is the last to support Python 2.7")

[official GCP tutorial]: https://cloud.google.com/python/django/flexible-environment 
[this GitHub repo]: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/flexible/django_cloudsql
[Django 2.0 doesn't support Python 2.7]: https://docs.djangoproject.com/en/2.0/releases/2.0/#python-compatibility

**Comment by tswast** [comment]
I've sent CL 207788129 to remove Python 2.7 from the list of versions in the tutorial.

**Comment by tswast** [comment]
The [tutorial](https://cloud.google.com/python/django/flexible-environment) has been updated. Thanks for the report!
