### ISSUE TITLE
RecognitionConfig has no "enable_automatic_punctuation" field

### ISSUE THREAD

**Issue by dalmam11** [GoogleCloudPlatform/python-docs-samples#1456]
i want to enable punctuation  on the result of the google cloud speech api .I added  enable_automatic_punctuation=True on the config But i have an error : ValueError: Protocol message RecognitionConfig has no "enable_automatic_punctuation" field.

**Comment by tuanlemau** [comment]
I have the same problem

> <ipython-input-17-bef5239f5764> in transcribe_file_with_auto_punctuation(path)
     12         language_code='en-US',
     13         # Enable automatic punctuation
---> 14         enable_automatic_punctuation=True)
     15 
     16     response = client.recognize(config, audio)

ValueError: Protocol message RecognitionConfig has no "enable_automatic_punctuation" field.

**Comment by ATajadod94** [comment]
I am also having the same problem  in 

config = types.RecognitionConfig(
    encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
    sample_rate_hertz=24000,
    language_code='en-US',	
    enable_word_time_offsets=True,
    enable_automatic_punctuation= True)



I am using long_running_recognize

**Comment by ATajadod94** [comment]
I was able to resolve this by importing speech_v1p1beta1

Here is my [code]('https://github.com/ATajadod94/AudioTranscriber_Gui') 

the main thing is from google.cloud import speech_v1p1beta1 though

**Comment by tuanlemau** [comment]
@ATajadod94 I've checked out your code. Worked awesomely (though the quality of the punctuation transcription could have been better).

**Comment by ATajadod94** [comment]
@tuanlemau I am getting a lot of the same feedback. Does not seem like google's punctuation is worth the hassle just yet

**Comment by nnegrey** [comment]
Hi, as noted above this feature is currently in beta with the following import:
`from google.cloud import speech_v1p1beta1 as speech`

The docs page can be found [here](https://cloud.google.com/speech-to-text/docs/automatic-punctuation).
The beta samples can be found [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/beta_snippets.py#L111-L137)

Hope that clarifies things. :)
