### ISSUE TITLE
Example connecting to PostgreSQL CloudSQL from App Engine standard?

### ISSUE THREAD

**Issue by ericgj** [GoogleCloudPlatform/python-docs-samples#1463]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/cloudsql

## Describe the issue

I noticed the [docs](https://cloud.google.com/appengine/docs/standard/java/cloud-sql/using-cloud-sql-postgres) only have an example for Java standard GAE environment, is there a way to connect to PostgreSQL yet in Python standard environment?

**Comment by kurtisvg** [comment]
Currently, Python GAE Standard runtimes do not support connection to CloudSQL Postrgres instances. You can however use the flexible environment.
