### ISSUE TITLE
Customise Sentiment Analysis

### ISSUE THREAD

**Issue by zhukaisjtu** [GoogleCloudPlatform/python-docs-samples#1467]
Hi,

I am trying to use gcp natural language API to do sentiment analysis. In my project, "The project status is red" is very negative, while "The project status is green" is very positive. Thus, I'd like to update words like "red" and "green" (may be more words) in the sentiment analysis model. Is it possible to do this?

Thanks!

**Comment by nnegrey** [comment]
Hi yea, if you look at this page: https://cloud.google.com/natural-language/docs/basics#interpreting_sentiment_analysis_values

You can take the sentiment analysis results and use those to update your text. 

Hope this helps! Please feel free to reopen this issue if you need further assistance. Thanks! :)
