### ISSUE TITLE
[Monitoring] Update docs to handle google-cloud-monitoring 0.29.0

### ISSUE THREAD

**Issue by syedashrafulla** [GoogleCloudPlatform/python-docs-samples#1470]
## In which file did you encounter the issue?

monitoring/api/v3/cloud-client/snippets.py

### Did you change the file? If so, how?

No.

## Describe the issue

0.29.0 of the client library is incompatible with 0.28.1, and as a result all of the docs for this client should change. I don't know if that means telling users that the docs are for 0.28.1 or updating the docs to handle 0.29.0.

**Comment by engelke** [comment]
PR #1495 addressed this issue.
