### ISSUE TITLE
Translate words which is taken from excel using python through google translate.

### ISSUE THREAD

**Issue by ManjunathanRajan** [GoogleCloudPlatform/python-docs-samples#1476]
Hi 

I am developing a code in python similar to the above where the above python code takes the single word and it converts the language specified in the program.
But please help me how to take data from an excel sheet which contains 100 words all of the words should be converted to the language which i choose.

Please refer the below attached excel file where we have to convert the word hello to different languages in the excel.
To which language should be converted mentioned in the excel of column B and output should be displayed in column D.

[Languages.xlsx](https://github.com/GoogleCloudPlatform/python-docs-samples/files/1993244/Languages.xlsx)

**Comment by nnegrey** [comment]
Hi, 

You won't be able to pass the file as is to the translate api rather you'll have to first parse the files contents then pass them to the api.
