### ISSUE TITLE
module' object has no attribute 'LanguageServiceClient

### ISSUE THREAD

**Issue by prasadnuk145** [GoogleCloudPlatform/python-docs-samples#1484]
getting this issue in the get_text_classify and ClassifyTextRequest method 
@google-admin 
I'm trying to get the text classification based on the text document . I'm extracting text content from one of the API and i'm passing the content data into google nlp api method get_text_classify  from this .
i'm getting the error 

module' object has no attribute 'LanguageServiceClient . 
Can you help me how to resolve this issue

**Comment by nnegrey** [comment]
Hi, are you importing `from google.cloud import language`
On this file: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/language/cloud-client/v1/snippets.py

If this doesn't solve your issue, please feel free to re-open. Thanks! :)
