### ISSUE TITLE
GoogleCloudPlatform/python-docs-samples/transcribe_streaming_test.py

### ISSUE THREAD

**Issue by GaddamKishore** [GoogleCloudPlatform/python-docs-samples#1499]
GoogleCloudPlatform/python-docs-samples/speech/cloud-client/transcribe_streaming_mic_test.py

Error saying no module found named mock

**Comment by nnegrey** [comment]
Hi, 

Try: `pip install mock`

If this doesn't solve your issue, please feel free to reopen. Thanks! :)
