### ISSUE TITLE
module 'google.cloud.firestore_v1beta1.proto.firestore_pb2' has no attribute 'FirestoreStub'

### ISSUE THREAD

**Issue by AlabhyaVaibhav** [GoogleCloudPlatform/python-docs-samples#1502]
Was following the https://firebase.google.com/docs/firestore/quickstart 
At the following step : 
```
doc_ref = db.collection(u'users').document(u'alovelace')
doc_ref.set({
    u'first': u'Ada',
    u'last': u'Lovelace',
    u'born': 1815
})
```

Getting

> AttributeError: module 'google.cloud.firestore_v1beta1.proto.firestore_pb2' has no attribute 'FirestoreStub'

I updated the libraries still the same error persists. How do we resolve this ?

**Comment by engelke** [comment]
The example code works now, provided the Firestore API has been enabled and a Firestore database has been created. This was probably an issue with the beta library that has been resolved now.
