### ISSUE TITLE
GoogleCloudPlatform/python-docs-samples/speech/cloud-client/transcribe_streaming_mic.py

### ISSUE THREAD

**Issue by GaddamKishore** [GoogleCloudPlatform/python-docs-samples#1505]
## In which file did you encounter the issue?

GoogleCloudPlatform/python-docs-samples/speech/cloud-client/transcribe_streaming_mic.py

### Did you change the file? If so, how?
No.

## Describe the issue
It is giving The import error if I try to run above python file.

ImportError                               Traceback (most recent call last)
<ipython-input-1-22919fe1a463> in <module>()
     14 import sys
     15 
---> 16 from google.cloud import speech
     17 from google.cloud.speech import enums
     18 from google.cloud.speech import types

ImportError: cannot import name 'speech'

**Comment by nnegrey** [comment]
Hi, can you run `pip install --force-reinstall google-cloud-speech`

Hope this helps, if that doesn't solve the issue, please feel free to reopen this issue. :)
