### ISSUE TITLE
Add Cloud Bigtable quickstart

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/python-docs-samples#1514]
https://github.com/jabubake/nodejs-bigtable/blob/master/samples/README.md#quickstart
Please see expected quickstart for Bigtable here :
https://github.com/jabubake/nodejs-bigtable/blob/master/samples/quickstart.js
(Read a row from an existing table)

@sduskis FYI

**Comment by billyjacobson** [comment]
Fixed by #1616
