### ISSUE TITLE
Remove Channel Example

### ISSUE THREAD

**Issue by patelnav** [GoogleCloudPlatform/python-docs-samples#1515]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/channel/chatactoe.py

### Did you change the file? If so, how?

No changes required

## Describe the issue

[Channel API has been deprecated](https://cloud.google.com/appengine/docs/deprecations/). This example uses channel API, so it doesn't work on local dev-server or on GAE

**Comment by engelke** [comment]
This sample is obsolete because the channel API was eliminated in October 2017. PR #1896 removes it from this code repository.
