### ISSUE TITLE
Can we use crop-hints on each object detected using vision-cloud api itself.

### ISSUE THREAD

**Issue by aakashshah94** [GoogleCloudPlatform/python-docs-samples#1516]
I am trying to use cloud vision api to detect objects in my image. The crop hints provides the bounds for the objects it considers as the main object in the image. Is it possible to use it to detect bounds for each object in the image.

**Comment by nnegrey** [comment]
Hi, the object-localization feature currently in beta may be what you are looking for.
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/vision/cloud-client/detect/beta_snippets.py#L37-L58

**Comment by aakashshah94** [comment]
@nnegrey  thank you so much for the suggestion. I will definitely try it out for sure.

**Comment by nnegrey** [comment]
If that doesn't work, feel free to reopen the issue.
:)
