### ISSUE TITLE
Error when I try to run example code: from grpc._cython import cygrpc as _cygrpc  ImportError: cannot import name 'cygrpc'

### ISSUE THREAD

**Issue by antoineChammas** [GoogleCloudPlatform/python-docs-samples#1540]
## In which file did you encounter the issue?

I used the code in the tutorial on my local machine

https://codelabs.developers.google.com/codelabs/cloud-vision-api-python/index.html?index=..%2F..%2Findex#5

### Did you change the file? If so, how?

No

## Describe the issue

When running the example code locally, I get the error mentioned in the title:
from grpc._cython import cygrpc as _cygrpc  ImportError: cannot import name 'cygrpc'

**Comment by antoineChammas** [comment]
the problem was with the grcp library not with google cloud, in case anyone stumbles on the same mistake, run python -m pip install grcpio --ignore-installed

**Comment by xueluofeng** [comment]
"python -m pip install grcpio --ignore-installed" , is grpcio not grcpio;
But to me is invalid

**Comment by zhaodi-Wen** [comment]
you can use  "python -m pip install grcpio --ignore-installed"

**Comment by xiaoyangnihao** [comment]
is this "python -m pip install grpcio --ignore-installed" useful ? I met the same error, and don't know how to solve it.

**Comment by Hamiltonsjtu** [comment]
`conda install grpcio` works for me

**Comment by iugov** [comment]
Specifying version as `grpcio==1.27.2` resolved my issue

**Comment by Paprika-a11y** [comment]
> is this "python -m pip install grpcio --ignore-installed" useful ? It seems invalid to me, I met the same error, and don't know how to solve it.

Did you find a way to solve this?

**Comment by absognety** [comment]
> Specifying version as `grpcio==1.27.2` resolved my issue

this doesn't work for python 3.9 due to incompatibility issue: 
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - grpcio==1.27.2 -> python[version='>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by sadmankiba** [comment]
`python3.8 -m pip install -U grpcio` worked for me.

**Comment by roshanlabh** [comment]
`cannot import name 'cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)`

If you are still facing the same issue with AWS Lambda layer and using mac for building the package locally.
Then the solution is to just use linux (ubuntu) to build your `google-cloud-*` package. It will solve the issue.

**Comment by fnsfroskos** [comment]
@roshanlabh  Can you provide a link with some detail on how to use linux (ubuntu) to build your google-cloud-* package? Thanks!

> `cannot import name 'cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)`
> 
> If you are still facing the same issue with AWS Lambda layer and using mac for building the package locally. Then the solution is to just use linux (ubuntu) to build your `google-cloud-*` package. It will solve the issue.
