### ISSUE TITLE
Create compute instances with a container

### ISSUE THREAD

**Issue by francescoperera** [GoogleCloudPlatform/python-docs-samples#1547]
Hi,
I am trying to understand if I can use the REST API  to create an instance with a container.
The console and gcloud ( beta) support it.
```bash
gcloud beta compute instances create-with-container [INSTANCE_NAME] \
     --container-image [DOCKER_IMAGE]
```
Does the rest api support this same functionality. I was looking at the `instances.insert` method but did not see an attribute for the container-image.
Is this not supported yet on the api or am I looking at the wrong method ?

**Comment by engelke** [comment]
This repository isn't the place for general questions; it's for issues with the contents of the repository. However, you might be able to find what you need at https://cloud.google.com/compute/docs/containers/deploying-containers and https://cloud.google.com/compute/docs/reference/rest/v1/ (look for instances and instance-templates).

StackOverflow is a good place for questions like this. You might want to check the google-compute-engine tag there: https://stackoverflow.com/questions/tagged/google-compute-engine.
