### ISSUE TITLE
Unresolved conflict in pubsub/cloud-client/requirements.txt file

### ISSUE THREAD

**Issue by carusology** [GoogleCloudPlatform/python-docs-samples#1550]
## In which file did you encounter the issue?

[pubsub/cloud-client/requirements.txt](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/pubsub/cloud-client/requirements.txt)

### Did you change the file? If so, how?

I did not. I tried to load it using `pip install -r requirements.txt`

Here's a link to the commit that appears to have broken it.
https://github.com/GoogleCloudPlatform/python-docs-samples/commit/0f26000946455cba56ee0b9e07ed88a2d2858116

## Describe the issue

I am attempting to follow the instructions on [this page](https://cloud.google.com/pubsub/docs/emulator#using_the_emulator) to use this SDK to test the Pubsub emulator, but the `requirements.txt` file it references looks to have an unresolved conflict in here. The commit touching this file claims to have resolved a host of conflicts, but it looks like this file got missed.

**Comment by techieshark** [comment]
Here's the [exact spot](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/0f26000946455cba56ee0b9e07ed88a2d2858116/pubsub/cloud-client/requirements.txt#L1) that's broken.

Easy to reproduce:
```
git clone git@github.com:GoogleCloudPlatform/python-docs-samples.git
cd python-docs-samples/pubsub/cloud-client/
pip install -r requirements.txt
```
results in a glaring problem from `pip`:
```
Invalid requirement: '<<<<<<< HEAD'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 252, in from_line
    req = Requirement(req)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "u'<<<<<<< '"
```
("'<<<<<<< HEAD") is the dead giveaway. Must have accidentally been missed during a merge (thanks, git!).

**Comment by nnegrey** [comment]
This issue appears to have been fixed. Please feel free to reopen if that is not the case. :)
