### ISSUE TITLE
Fix Bigtable sample test failures

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/python-docs-samples#1555]
@sangramql FYI

Please fix the errors here:
https://travis-ci.org/GoogleCloudPlatform/python-docs-samples/builds/401814769?utm_source=email&utm_medium=notification

**Comment by jabubake** [comment]
@sduskis FYI

**Comment by sduskis** [comment]
@sangramql, please fix this.

**Comment by nnegrey** [comment]
This appears to have been fixed.
