### ISSUE TITLE
command "python publisher.py project-name publish topic-name messages" doesn't work

### ISSUE THREAD

**Issue by kuonumber** [GoogleCloudPlatform/python-docs-samples#1611]
## In which file did you encounter the issue?
maybe a bug of publisher.py
path : python-docs-samples/pubsub/cloud-client/publisher.py

## Describe the issue

when I run :
''' python publisher.py project-name publish topic-name 123 '''
It shows  this error message "publisher.py: error: unrecognized arguments: 123"

To be short, I can not find a way to publish message via  "publisher.py" .

**Comment by melom13** [comment]
I'm also using this file in an SPL lab. Will this issue be fixed anytime soon?

**Comment by anguillanneuf** [comment]
If you look closely at `publisher.py`, you will [notice](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/fb2c633eadba31a4a9f2c28a093131dc54132041/pubsub/cloud-client/publisher.py#L272) it takes just one argument, your topic name. 

If you remove `123` from your command, it will work. 

Closing.
