### ISSUE TITLE
running tests in publisher_test.py

### ISSUE THREAD

**Issue by haifabenaouicha** [GoogleCloudPlatform/python-docs-samples#1625]
I am trying to run tests in the script  publisher_test.py , But I am getting errors saying that no tests are run , I lanched pytest publisher_test.py, pytest -v , python publisher_test.py. But I am getting the same no tests ran . 
Any help with this please. 
Thanks a lot

**Comment by engelke** [comment]
`pytest publisher_test.py` works here, and should now work for you. There are some steps you need to do first to set it up:

```
cd pubsub/cloud-client
virtualenv env
source env/bin/activate
pip install -r requirements.txt
pip install -r ../../testing/requirements.txt
```

Under Linux or Mac, add: `export GCLOUD_PROJECT=[yourprojectid]`

Under Windows, add: `set GCLOUD_PROJECT=[yourprojectid]`

You will also need to have gcloud configured, pointing to your project. The `gcloud init` command does that.

Then pytest publisher_test.py should work. This was just tested on Linux using both Python 2.7 and Python 3.5.

If you still have a problem after doing the above, you can reopen this issue for further work. Thanks.
