### ISSUE TITLE
"transcribe_streaming_mic.py" Error on Raspberry Pi

### ISSUE THREAD

**Issue by hanugogi** [GoogleCloudPlatform/python-docs-samples#1649]
## In which file did you encounter the issue?
              ~/python-docs-samples/speech/cloud-client/transcribe_streaming_mic.py
(/home/pi)

### Did you change the file? If so, how?
No I use original source file.

## Describe the issue
![image](https://user-images.githubusercontent.com/26743019/44443607-96d60d00-a613-11e8-9f06-8c614b37b52c.png)

I try this source on Raspberry Pi. And I think it can't find microphone.
Microphone is USB PnP mic. Test 'rec' command, it done well.

How can I fix this error?

**Comment by nnegrey** [comment]
Going to close this issue due to how old it is, please feel free to reopen. :)
