### ISSUE TITLE
./transcribe_model_selection.py --> TypeError: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by ashrutv** [GoogleCloudPlatform/python-docs-samples#1654]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_model_selection.py

### Did you change the file? If so, how?

No

## Describe the issue
same script has worked in the past without any changes. My other personal script has started failing on importing beta speech api with the same error.

  File "./transcribe_model_selection.py", line 100, in <module>
    transcribe_model_selection_gcs(args.path, args.model)
  File "./transcribe_model_selection.py", line 62, in transcribe_model_selection_gcs
    from google.cloud import speech_v1p1beta1 as speech
  File "/Library/Python/2.7/site-packages/google/cloud/speech_v1p1beta1/__init__.py", line 17, in <module>
    from google.cloud.speech_v1p1beta1 import types
  File "/Library/Python/2.7/site-packages/google/cloud/speech_v1p1beta1/types.py", line 21, in <module>
    from google.cloud.speech_v1p1beta1.proto import cloud_speech_pb2
  File "/Library/Python/2.7/site-packages/google/cloud/speech_v1p1beta1/proto/cloud_speech_pb2.py", line 286, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

**Comment by nnegrey** [comment]
Hi,

Which version of the library are you currently using?

`pip show google-cloud-speech`

**Comment by ashrutv** [comment]
upgraded to 0.36 and still same issue.

Name: google-cloud-speech
Version: 0.36.0
Summary: Google Cloud Speech API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Library/Python/2.7/site-packages
Requires: google-api-core
Required-by:

**Comment by nnegrey** [comment]
Huh, interesting. 

Have you tried using a virtual environment to reinstall?

I'm guessing you used `pip install --upgrade google-cloud-speech`

Is your Python version the one that comes installed on Mac? (Trying to repeat the steps)

**Comment by nnegrey** [comment]
Updated that sample with the new library: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1702

How about using the v1 library. `from google.cloud import speech`

**Comment by ashrutv** [comment]
upgraded protobuf and now I am seeing an solvable error. Thanks for the help

**Comment by nnegrey** [comment]
👍
