### ISSUE TITLE
The "file a bug link" in iot core tour codelab is pointing to the wrong repo

### ISSUE THREAD

**Issue by banpiao** [GoogleCloudPlatform/python-docs-samples#1676]
## In which file did you encounter the issue?
Not any file here, but in codelab.developers.google.com

### Did you change the file? If so, how?
N/A
## Describe the issue
The "file a bug link" in iot core tour codelab is pointing to the wrong repo, it should be pointing to this issues page instead. 
https://codelabs.developers.google.com/codelabs/cloud-iot-core-overview/index.html?index=..%2F..%2Findex#2

**Comment by hongalex** [comment]
Done, and thanks for your feedback!
