### ISSUE TITLE
  PDF/TIFF Document Text Detection 

### ISSUE THREAD

**Issue by Justice-lords** [GoogleCloudPlatform/python-docs-samples#1697]
In **python-docs-samples/vision/cloud-client/detect/detect.py** line 645 **async_detect_document(gcs_source_uri, gcs_destination_uri)** the source and destination URI should can only be GCS.Is there any workaround to use other cloud storage URI for this API?If not how to solve this problem without manually downloading and uploading the pdf.

**Comment by nnegrey** [comment]
Hi thanks for commenting.

Right now, the API only supports files on GCS. 

Are you looking for a way to use a client library to help automate the process of uploading a PDF to GCS and then downloading the stored results?
