### ISSUE TITLE
Fail to copy an airflow environment using the copy_environment.py script

### ISSUE THREAD

**Issue by mastoj** [GoogleCloudPlatform/python-docs-samples#1712]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/composer/tools/copy_environment.py

### Did you change the file? If so, how?

No

## Describe the issue

I ran the copy script trying to copy one of our environments. It didn't work as expected. A composer environment was created, but it seems like the airflow database wasn't populated.

**Comment by mastoj** [comment]
Or maybe I'm not supposed to run be able to run the script, am I? 

The message I get is:

> HttpError 403 when requesting https://iam.googleapis.com/v1/projects/uc-prox-core-dev/serviceAccounts/501207560282-compute@developer.gserviceaccount.com/keys?alt=json returned "Identity and Access Management (IAM) API has not been used in project 563584335869 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=563584335869 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Clicking the link and I got to a place where I didn't have access.

**Comment by mastoj** [comment]
I still struggle even though I should be authenticated with as the service account. Output from what I've run and output:

```
➜  gcloud auth activate-service-account --key-file=/Users/tomasjansson/credentials/uc-prox-core-dev-df5bb956033d.json
```

Output: 

```
Activated service account credentials for: [501207560282-compute@developer.gserviceaccount.com]
```

```
➜  python copy_environment.py uc-prox-core-dev us-central1 visitpipeline tomaspipeline2
```

Output: 

```
Starting Composer Environment Create Operation. This takes 20 - 60 mins.
Composer operation successful.
Starting Composer Update PyPI Packages Operation. This takes 20 - 30 mins
Composer operation successful.
Starting database transfer.
Obtaining service account `501207560282-compute@developer.gserviceaccount.com` credentials to access SQL database.
Traceback (most recent call last):
  File "copy_environment.py", line 617, in <module>
    "diskSizeGb": args.override_disk_size_gb,
  File "copy_environment.py", line 596, in clone_environment
    copy_database(project, existing_env, new_env, running_as_service_account)
  File "copy_environment.py", line 488, in copy_database
    iam_client, project, gke_service_account_name
  File "copy_environment.py", line 288, in create_service_account_key
    body={},
  File "/Users/tomasjansson/git/unacast/GoogleCloudPlatform/python-docs-samples/composer/tools/.direnv/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/tomasjansson/git/unacast/GoogleCloudPlatform/python-docs-samples/composer/tools/.direnv/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://iam.googleapis.com/v1/projects/uc-prox-core-dev/serviceAccounts/501207560282-compute@developer.gserviceaccount.com/keys?alt=json returned "Identity and Access Management (IAM) API has not been used in project 563584335869 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=563584335869 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.">
```

Am I doing something wrong here?

**Comment by alan-ma-umg** [comment]
I had the same issue when running copy_environment.py. got 403 error and coudl not figure out what's causing it.

**Comment by engelke** [comment]
It seems you have not managed to enable the API. Sometimes the direct links don't result in the correct project being selected. Try going to the console home page at https://console.cloud.google.com/, selecting your project, then select APIs & Services/Dashboard from the left sidebar. Once there, search for IAM, and you should Identity and Access Management (IAM) API as a choice. Click that, then click Enable and try again.

Let us know whether that fixes it. If so, we'll see if we can change the instructions to avoid the problem. If not, we will keep looking for the problem. Thanks.
