### ISSUE TITLE
Copy_environment should check prerequisites before running

### ISSUE THREAD

**Issue by mastoj** [GoogleCloudPlatform/python-docs-samples#1718]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/composer/tools/copy_environment.py

## Describe the issue

Working my way through the file trial by trial to get it to run. I know it is not official, but this is the script that is available to copy a composer environment. A more clear example of how to run it should be provided, and when the script runs it should check for prerequisites. In my last run I failed after 30 minutes because I was missing `gcsfuse`, that should be checked first thing for faster feedback.

**Comment by engelke** [comment]
There are a number of commands invoked by this script. The documentation at [https://cloud.google.com/composer/docs/how-to/managing/migrating](https://cloud.google.com/composer/docs/how-to/managing/migrating) has you run the command in the Cloud Shell, which has those commands already installed.

If you'd like to make suggestions on that (or any other) web page please use the Send Feedback link at the bottom of the page.
