### ISSUE TITLE
fusermount doesn't work on OSX

### ISSUE THREAD

**Issue by mastoj** [GoogleCloudPlatform/python-docs-samples#1719]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/composer/tools/copy_environment.py

### Did you change the file? If so, how?

Yes, https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/composer/tools/copy_environment.py#L435 changed to:

    subprocess.call(["umount", fuse_dir])

## Describe the issue

fusermount seems to be linux specific command. Changing to `umount` on OSX did the trick.

**Comment by irvifa** [comment]
@mastoj can you give me the details? I also have a similar problems

**Comment by mastoj** [comment]
@irvifa the easiest approach is probably to this through the cloud console, but here is how I solved it on OSX:

1. Install gcsfuse
2. Install/make sure cloud_sql_proxy is in your path
3. If you are using OSX you need to change script to use umount instead of fusermount
4. Run the script with something like: GOOGLE_APPLICATION_CREDENTIALS=<service account file> python copy_environment.py <project> <location> <current env> <new env> --running_as_service_account

**Comment by irvifa** [comment]
@mastoj what's the relationship between cloudsql and the osxfuse by the way?

**Comment by mastoj** [comment]
@irvifa. There’s no direct relation more than in this script. The script mount gcs to be able to make the cloud sql backup and store the result on gcs, if I’m not mistaking. So I guess you need it mounted for the script to work.

**Comment by irvifa** [comment]
@mastoj I see, it's working exactly after I applied what you're suggesting before 🙂

**Comment by engelke** [comment]
PR #1915 should deal with this environmental variation.
