### ISSUE TITLE
URL Pattern in app.yaml App Engine Development Server Requests from Firefox Browser Automatically Failing When Working in Chrome, Edge, Opera, etc.

### ISSUE THREAD

**Issue by amrosado** [GoogleCloudPlatform/python-docs-samples#1721]
## In which file did you encounter the issue?

app.yaml

### Did you change the file? If so, how?

Changed the url path from:
.*
to:
/.*

## Describe the issue
The app.yaml as provided in this repository when I run using the development server for a python app engine standard environment has a weird issue whereby **requests made from a firefox or nightly browser would automatically fail compared to other browsers**.  **Changing the url pattern seemed to fix the issue with a firefox request compared to all other browsers (opera, chrome, ie, etc.).**

I am using python 2.7 and webapp2.  This issue also impacts requests even when using django instead of webapp2.

**Comment by engelke** [comment]
Either pattern in app.yaml should work, since the path name sent to the web server should always start with a /. I just tested each pattern with the dev_appserver.py driver, with the latest Chrome and Firefox (both on Linux). Please check this again with the latest released browsers, and reopen this issue if the problem recurs for you. Thanks.

**Comment by amrosado** [comment]
I'm using the development environment in Windows.  Since it works either way in production, I would assume that linux would work with either path.

**Comment by engelke** [comment]
Okay, thanks. I'll get a Windows environment and try it out. I'm reopening this for now.

**Comment by engelke** [comment]
I still can't replicate the problem. Either pattern works with both Chrome and Firefox on Windows 10 for me. Please run gcloud --version, and Python -V, and post the results. Also, please make sure you aren't running any security software that installs a proxy server.

**Comment by engelke** [comment]
Please reopen with more info if the problem persists. Thanks.
