### ISSUE TITLE
Issue in document_text_detection with large images

### ISSUE THREAD

**Issue by retd-jerome** [GoogleCloudPlatform/python-docs-samples#1726]
## In which file did you encounter the issue?

python-docs-samples/vision/cloud-client/document_text/doctext.py

### Did you change the file? If so, how?

No

## Describe the issue

When detecting text on large images, there is an increasing offset between the real position of the text and the bounding box coordinates. 

In this example, the higher is the Y coordinates, the higher is the offset (60 pixels at the end of the image).

You can find a sample attached and the result when applying python-docs-samples/vision/cloud-client/document_text/doctext.py on it.

![alododofrjpg](https://user-images.githubusercontent.com/40624675/46299227-2bcc0e80-c5a1-11e8-8b34-057b413891d8.jpg)
![alododofrjpg_result](https://user-images.githubusercontent.com/40624675/46299241-325a8600-c5a1-11e8-956b-1704bd026336.jpg)

Thanks.

**Comment by dizcology** [comment]
@retd-jerome This appears to be an old issue and should have been fixed - my apologies for the much delayed response.  Are you still having the issue?

**Comment by leahecole** [comment]
@dizcology can you verify if this is obsolete and please close if so?

**Comment by andrewferlitsch** [comment]
It has been 60 days without a response from the submitter. Closing the (old) issue.
