### ISSUE TITLE
Update to new Nox

### ISSUE THREAD

**Issue by theacodes** [GoogleCloudPlatform/python-docs-samples#1736]
Nox recently made a [big change](https://github.com/theacodes/nox/blob/master/CHANGELOG.md#2018823) from declarative to imperative and broke the Noxfile API.

We need to update our Noxfiles to work with the new API and update our test scripts to install `nox` (instead of `nox-automation`) and invoke `python3 -m nox {args}`.

Most projects just need to do a few steps:

1. Remove usage of `session_{name}` sessions and use `@nox.session` instead.
2. Don't use `session.interpreter`, use `@nox.session(py='...')`
3. Don't use `nox.parametrize` for multiple Pythons, use `@nox.session(py=['..', '..'])`.

**Comment by engelke** [comment]
Handled in PR #1770.
