### ISSUE TITLE
The main function has to be written in reuse-able way. 

### ISSUE THREAD

**Issue by vishwanathkavya** [GoogleCloudPlatform/python-docs-samples#1741]

**Comment by vishwanathkavya** [comment]
Remove the agr for the microphone !!

**Comment by nnegrey** [comment]
Hi, 

Which sample are you referring to?

Thanks! :)

**Comment by vishwanathkavya** [comment]
I'm referring to python samples for async transcription. The code which was written will not work for every one who wants to use the API's.

**Comment by vishwanathkavya** [comment]
The samples will be in speech folder !! transcribe_mic.py

**Comment by nnegrey** [comment]
To help pin down the issue a little more.

Is the issue related to how we call the microphone in the sample or how the api itself it called? 

Thanks
