### ISSUE TITLE
Video Intelligence API: SpeechTranscription

### ISSUE THREAD

**Issue by jermainkaminski** [GoogleCloudPlatform/python-docs-samples#1769]
## Documentation and Snippet Update

[https://cloud.google.com/video-intelligence/docs/transcription](https://cloud.google.com/video-intelligence/docs/transcription)

(https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/video/cloud-client/analyze/beta_snippets.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/video/cloud-client/analyze/beta_snippets.py)

### Issues

1. Documentation:

`google-cloud-videointelligence==1.2.0
`
**Update (correct?):** `google-cloud-videointelligence==1.5.0
`

2. Snippet:
```
config = videointelligence.types.SpeechTranscriptionConfig(
        language_code='en-US',
        enable_automatic_punctuation=True)
```

Returns: `RecognitionConfig has no "enable_automatic_punctuation" field`. It appears, there is a temporary issue with the automatic punctuation. See [https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1456](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1456).

**Comment by nnegrey** [comment]
Hi, is this issue for using the same sample video file or for a different video file? 

Trying to reproduce. :)

**Comment by jermainkaminski** [comment]
Hi @nnegrey it was a >240sec video stored on GCS.

**Comment by jermainkaminski** [comment]
The issue with automatic_punctuation might have been temporary. By Oct 21, it seems to work again.
