### ISSUE TITLE
microphone audio stream from browser using python

### ISSUE THREAD

**Issue by rrrepos** [GoogleCloudPlatform/python-docs-samples#1774]
I have not found how to handle this use-case in the documentation; hence raising it here.

I need to stream audio from microphone from a browser to a Flask based app on the backend server which needs to send the stream to the Google Cloud API to convert into text. I have the project working in NodeJS but am unable to do so with Python.

Step 1: On browser enable microphone access using getUserMedia.

Step 2: On start of user talking, a websocket connection is made to send audio streams to the server (that works). The ws continuously is passing the audio stream to the websocket server which makes call to the three speech module functions in python (see below)

Step 3: The speech module has a startSpeech, endSpeech and updateStream functions. (again, this is similar to what I have done in NodeJS).

The speech module is as below:
```
from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types

# create client
client = speech.SpeechClient()

#variables
config = types.RecognitionConfig(
        encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=16000,
        language_code='en-US',
        profanity_filter=False,
        enable_word_time_offsets=False)
streaming_config = types.StreamingRecognitionConfig(config=config, interim_results=False)
responses = None

def startRecognitionStream(data):
    requests = types.StreamingRecognizeRequest(audio_content=data)
    # not sure how to add the data to the request
    responses = client.streaming_recognize(streaming_config, requests)
    for response in responses:
        for result in response.results:
            if result.is_final:
                #socket.emit('speechData', result)
                print(result)
                stopRecognitionStream()

def stopRecognitionStream():
  if responses:
    # I need to clear the responses
  responses = None

def writeStreamData(data):
  if responses:
    # I need to update the responses with data
```

In the above code data is the steam that the socket is sending when calling the startRecognitionStream and writeStreamData functions. I could not find out how to set that stream to the requests variable. The error that appears is:

```
message handler error
Traceback (most recent call last):
  File "/Users/rr/Documents/GitHub/eda/edaenv/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 526, in init
    setattr(self, field_name, field_value)
  File "/Users/rr/Documents/GitHub/eda/edaenv/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 674, in setter
    field_setter(self, new_value)
  File "/Users/rr/Documents/GitHub/eda/edaenv/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/Users/rr/Documents/GitHub/eda/edaenv/lib/python3.7/site-packages/google/protobuf/internal/type_checkers.py", line 109, in CheckValue
    raise TypeError(message)
TypeError: '' has type <class 'str'>, but expected one of: ((<class 'bytes'>,),)
```

Appreciate any help or direction to look into. Thanks

**Comment by nnegrey** [comment]
Hey,

Have you seen these samples which tackle streaming?
- [transcribe_streaming.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming.py)
- [transcribe_streaming_mic.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py)

In your code above, which part is causing that error?

**Comment by nnegrey** [comment]
From your use case, it sounds like you'll want to take pieces of that code and put it into your three different `emit` methods that you have rather than calling the main method outright.

**Comment by rrrepos** [comment]
Yes you are right @nnegrey . I just picked the code provided in the google documentation as a module and called the main function in part (a) start of streaming and it at least did not throw an error. Unlike the NodeJS module, it looks like the (b) while streaming is going on is not required. Now I am confident of getting it working. Thanks for the inputs

**Comment by nnegrey** [comment]
Awesome! 

Feel free to open another issue or re-open if you run into more trouble. :)
