### ISSUE TITLE
Transcribe async misses sentences 

### ISSUE THREAD

**Issue by junqi95** [GoogleCloudPlatform/python-docs-samples#1775]
Hi! I'm using the Transcribe async function to transcribe a one-hour long audio file. However, I noticed that some sentences are missing here and there. Is this normal? If not, how to solve this problem?

**Comment by nnegrey** [comment]
Hey, not exactly sure. 

Do you know what kind of confidence score is returned with your transcriptions?

**Comment by junqi95** [comment]
They are all like 0.9 something--very close to 1. However, for the missed ones, since there was no transcript, there was no confidence score as well.

**Comment by nnegrey** [comment]
Ah cool! 
[Link to submitted issue](https://b.corp.google.com/issues/118090788)
