### ISSUE TITLE
[FIrestore Samples] Update tests to be self-contained and verified for correctness.

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/python-docs-samples#1788]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets_test.py

## Describe the issue

Tests aren't self contained and also not being verified for correctness. At the moment, tests only run the samples and verify that they execute without failure. Although, tests do provide some level of support using this method, they aren't verifying state correctness of Firestore post after testing a given sample.

**Comment by gguuss** [comment]
This may be fixed in [the updated tests](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets_test.py) from @BenWhitehead.

**Comment by BenWhitehead** [comment]
There are a few older tests that need to have assertions added to them.

**Comment by crwilcox** [comment]
@BenWhitehead do we have the individual tests we should fix?

**Comment by BenWhitehead** [comment]
@crwilcox I think with your updated bootstrapping for the tests that should hopefully transparently take care of this.

@frankyn Do you have specific tests that we should double check to make sure the fix from @crwilcox addresses things?

**Comment by andrewferlitsch** [comment]
@crwilcox PTAL

**Comment by frankyn** [comment]
Apologies, I missed this in email.

The tests are not validating correctness and only making sure samples execute without failures.

Here's an example of a test being verified: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets_test.py#L74-L80

Here's an example of test not being verified: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets_test.py#L70-L71

**Comment by leahecole** [comment]
I've been in touch with @BenWhitehead recently, and it is still in the pipeline.

**Comment by meredithslota** [comment]
A partial fix was implemented in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2667 but work remains (see last comment from @frankyn).
