### ISSUE TITLE
bigtable: metricscaler should fail gracefully for development instances

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/python-docs-samples#1790]
## In which file did you encounter the issue?

`https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigtable/metricscaler/metricscaler.py`

### Did you change the file? If so, how?

No

## Describe the issue

When I ran the metric scaler, I accidentally specified a Cloud Bigtable development instance, which can't be scaled. As a result, I got the following stack trace:

```
Traceback (most recent call last):
  File "metricscaler.py", line 172, in <module>
    int(args.long_sleep))
  File "metricscaler.py", line 129, in main
    scale_bigtable(bigtable_instance, bigtable_cluster, False)
  File "metricscaler.py", line 83, in scale_bigtable
    cluster.reload()
  File "/Users/[REDACTED]/python-docs-samples/bigtable/metricscaler/env/lib/python3.7/site-packages/google/cloud/bigtable/cluster.py", line 184, in reload
    self._update_from_pb(cluster_pb)
  File "/Users/[REDACTED]/python-docs-samples/bigtable/metricscaler/env/lib/python3.7/site-packages/google/cloud/bigtable/cluster.py", line 92, in _update_from_pb
    raise ValueError('Cluster protobuf does not contain serve_nodes')
ValueError: Cluster protobuf does not contain serve_nodes
```

If the user specifies a development instance, we should fail gracefully and display an appropriate error message.

(It also seems odd that the client library is raising an error when we call `cluster.reload()` on a development instance, so perhaps this is a client-library bug as well. I'm not familiar enough with the Python client library to know for sure.)

**Comment by andrewferlitsch** [comment]
@billyjacobson What is the status of this issue?

**Comment by billyjacobson** [comment]
@andrewferlitsch I haven't really looked into it. Been working on higher priority items

**Comment by andrewferlitsch** [comment]
@billyjacobson PTAL
