### ISSUE TITLE
The insert example code updates an entity even if it exists

### ISSUE THREAD

**Issue by lidalei** [GoogleCloudPlatform/python-docs-samples#1796]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/b99e12db0ab8d763ab9bb6810be7279e2ee673f6/datastore/cloud-client/snippets.py#L150

**Comment by engelke** [comment]
It may appear that way because all the non-key fields have the same values. However, the insert operation creates a new entity each time it is called.
