### ISSUE TITLE
mysqlclient dependency but project uses PostgreSQL

### ISSUE THREAD

**Issue by jbrucker** [GoogleCloudPlatform/python-docs-samples#1813]
In `requirements.txt` of the code for python-docs-samples/container_engine/django_tutorial
there is a dependency on mysqlclient: 

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/ae838c1a5154a978fef877db252cae746430b818/container_engine/django_tutorial/requirements.txt#L2

but the instructions for deploying this on Kubernetes Engine specify to use PostreSQL:
https://cloud.google.com/python/django/kubernetes-engine

Is the `mysqlclient` dependency correct?

**Comment by engelke** [comment]
The mysite/settings.py file has a comment for using mysql instead of postgresql. Should a user decide to make the change mentioned in the comment mysqlclient would need to be available.
