### ISSUE TITLE
App Engine Flask: pip complains about werkzeug

### ISSUE THREAD

**Issue by YaguraStation** [GoogleCloudPlatform/python-docs-samples#1817]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/flask/tutorial/requirements.txt

### Did you change the file? If so, how?

No. 

## Describe the issue

When running `pip install -t lib -r requirements.txt`, I receive the following warning: 
> flask 1.0.2 has requirement Werkzeug>=0.14, but you'll have werkzeug 0.12.2 which is incompatible.

**Comment by engelke** [comment]
The latest versions of Flask and werkzeug have issues under dev_appserver. PR #1888 rolled the versions back to address this.
