### ISSUE TITLE
Bigtable autoscaler: Add Dockerfile

### ISSUE THREAD

**Issue by mattayes** [GoogleCloudPlatform/python-docs-samples#1835]
## In which file did you encounter the issue?

N/A

### Did you change the file? If so, how?

N/A

## Describe the issue

A Dockerfile for the Bigtable autoscaling would be nice. Happy to submit the PR!

**Comment by andrewferlitsch** [comment]
@crwilcox Is there a plan for this enhancement?

**Comment by mattayes** [comment]
@andrewferlitsch Waiting on the 👍, happy to do the work once folks think it's a good idea.

**Comment by andrewferlitsch** [comment]
@mattayes PTAL

**Comment by billyjacobson** [comment]
That sounds good 👍

**Comment by mattayes** [comment]
Closed via #3103.
