### ISSUE TITLE
Transfer service does not support logging of failed objects

### ISSUE THREAD

**Issue by timbuktuu** [GoogleCloudPlatform/python-docs-samples#1839]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/transfer_service/aws_request.py

## Describe the issue

Transfer service is especially powerful to move data from s3 to GCS.   However currently, there seems to be no mechanism in the API, CLI, or UI to log exceptions.   

Example use case: transferring 100TB from S3 to GCS.   
If 0.001% of the objects have an incorrect ACL and cannot be transferred, how would I identify those objects which failed?   Setting the ACL's for all objects is quite slow.  I am displayed currently that 5 of the 10,000 failed objects but there does not seem to be a way to log all failed objects.

**Comment by engelke** [comment]
This repository has sample code showing how to use the API. To ask for a new feature in the API itself you should use the issue tracker page at [https://cloud.google.com/support/docs/issue-trackers](https://cloud.google.com/support/docs/issue-trackers).
