### ISSUE TITLE
Automatic Spoken Language Detection HANGING

### ISSUE THREAD

**Issue by NeoLuk** [GoogleCloudPlatform/python-docs-samples#1854]
## In which file did you encounter the issue?

python-docs-samples/speech/cloud-client/transcribe_streaming_mic.py

### Did you change the file? If so, how?

Changes to the following lines were made:

```python
language_code=language_code,
```
to
```python
language_code=language_code,
lternative_language_codes=['yue-Hant-HK', 'cmn-Hans-CN'],
````

## Describe the issue

Recognition works normally when the spoken text is above certain length. When the input is short, responses from 

`client.streaming_recognize(audio_content=content) for content in audio_generator) `

hangs without spitting any results (both final and interim). Oddly enough, if I were to say any random word, or even to just make some noise, the hanging goes away, and I get ALL interim and final recognized text all in one lump. 

The code used to work fine. The problem was first spotted since Friday Nov 16th, and has persisted since then. Any help will be greatly appreciated. Thanks.

**Comment by nnegrey** [comment]
Hi, yea it does seem to hang for this sample on the initial request. 

I'll pass this along. Please note that automatic language detection is still in beta.

**Comment by nnegrey** [comment]
Hi, I tried it again today and beside a slight delay on the first detection (likely to identify the spoken language) this seems to be working now. 

Feel free to reopen the issue if that is not the case. :)
