### ISSUE TITLE
transcribe_streaming_mic.py  not giving proper result

### ISSUE THREAD

**Issue by noufanpmc** [GoogleCloudPlatform/python-docs-samples#1873]
## In which file did you encounter the issue?

 python-docs-samples/speech/cloud-client/transcribe_streaming_mic.py

### Did you change the file? If so, how?

Nop, I did not change anything I just added my google cloud speech API credentials

## Describe the issue

I am able to run this python code without any errors, but the result is not how I wanted, if I say something its getting converted to text, but the problem is if I say hello one time the text which
I got has multiple hellos.
I'll show you my output when I say hello only two times:
'hellohellohellohello hello' 
This is the problem which I am facing.

Please help me to solve this issue, I tried everything I can to avoid this, but nothing worked. 
So if possible give me a solution to this problem as soon as possible

Thankyou.

**Comment by nnegrey** [comment]
Hi the transcribe mic sample tries to provide intermittent results while waiting the final result. 

Is this the final result or a intermittent result?

**Comment by noufanpmc** [comment]
Hi, Thanks for the reply.
Actually I'm not getting the final result, while executing it gives the
intermediate result on whatever I speak and then program crashes after
60 seconds without any final result. It's shows some limit exceeded kind of
error and crashes.
Please let me know if there's any way to solve this.
Thanks & Regards

**Comment by nnegrey** [comment]
If you have multiple phrases does this problem persist? 

Yea, the API has a ~60 seconds limit on streaming and I don't think that sample tries to cut off before the time limit.

**Comment by noufanpmc** [comment]
Yes, It does. Even if I say a single word or a full sentence it's showing
multiple times

Yeah I know about the limitation but why it's getting crashed  after 60
seconds rather than giving the result.

**Comment by nnegrey** [comment]
What is the terminal program that you are using? The sample tries to overwrite the intermittent results, but maybe that is causing this problem. 

The sample doesn't handle the error message returned by the server.

**Comment by nnegrey** [comment]
Hi, going to close this issue, please feel free to reopen if you're still having a problem. Thanks!
