### ISSUE TITLE
AttributeError: 'ResumableMicrophoneStream' object has no attribute '_num_channels'

### ISSUE THREAD

**Issue by SarahTeoh** [GoogleCloudPlatform/python-docs-samples#1877]
## In which file did you encounter the issue?  

python-docs-samples/speech/cloud-client/transcribe_streaming_indefinite.py
    
### Did you change the file? If so, how?  

No, I didnt change the file at all.

## Describe the issue
I got this error when I try to run it.

`Traceback (most recent call last):
  File "transcribe_streaming_indefinite.py", line 192, in <module>
    main(args.rate, args.audio_src)
  File "transcribe_streaming_indefinite.py", line 162, in main
    sample_rate, int(sample_rate / 10))
  File "transcribe_streaming_indefinite.py", line 30, in __init__
    self._bytes_per_sample = 2 * self._num_channels
AttributeError: 'ResumableMicrophoneStream' object has no attribute '_num_channels'`

and I also tried to comment out `self._bytes_per_sample = 2 * self._num_channels`, this error came out.

`File "transcribe_streaming_indefinite.py", line 31, in __init__
    self._bytes_per_chunk = (self._chunk_size * self._bytes_per_sample)
AttributeError: 'ResumableMicrophoneStream' object has no attribute '_chunk_size'
`

**Comment by nnegrey** [comment]
Hi, 

Do you have `sox` installed?

**Comment by nnegrey** [comment]
Ah it looks like the sample also relies on this file: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/speech-continuous/speech/cloud-client/transcribe_streaming_mic.py
Do you have that file as well?

Note: This sample is in a branch that was never published to master
