### ISSUE TITLE
Salience not correctly ordered

### ISSUE THREAD

**Issue by LucioGrimaldi** [GoogleCloudPlatform/python-docs-samples#1914]
# [SOLVED] 
## In which file did you encounter the issue?
python-docs-samples/language/cloud-client/v1/snippets.py

### Did you change the file? If so, how?

no didn't change

## Describe the issue

I'm using the function provided in then file at row 85 to analyse a block of comment coming from social network written in Italian.

With small block of comments seem to work normally. But then I tried with another txt built in the same way the output is ordered by salience as before just for a portion of it. At a certain point the salience value is very high (9.99) and starting to decrease again
#### UPDATE SOLVED

**Comment by andrewferlitsch** [comment]
This is labeled as [SOLVED], so I will close it.
