### ISSUE TITLE
How to use DLP on PostgreSQL tables and where can i save my postgreSQL data on GoogleCloudPlatofrm?

### ISSUE THREAD

**Issue by ku294714** [GoogleCloudPlatform/python-docs-samples#1932]
Hello,

I have a set of PostgreSQL tables and I want those tables to be hosted on GoogleCloudPlatform first and then use DLP on those tables.

Which kind of data store or any other storage can I use which will be compatible with DLP API?

**Comment by kurtisvg** [comment]
Hi @ku294714,

Sorry for the delayed response. 

The DLP API supports job triggers for GCS, Big Query, and Datastore. You can find more information here: https://cloud.google.com/dlp/docs/quickstart-create-job-trigger
