### ISSUE TITLE
ImportError: cannot import name texttospeech

### ISSUE THREAD

**Issue by ngoalongtb** [GoogleCloudPlatform/python-docs-samples#1935]
I try with python2.7. I installed google-cloud-texttospeech==0.2.0.

And I try with python3.7. AttributeError: module 'google.cloud.texttospeech' has no attribute 'TextToSpeechClient'. Pls help me.
This is my script

```python
# -*- coding: utf-8 -*-
"""Synthesizes speech from the input string of text or ssml.

Note: ssml must be well-formed according to:
    https://www.w3.org/TR/speech-synthesis/
"""
from google.cloud import texttospeech

# Instantiates a client
client = texttospeech.TextToSpeechClient()

# Set the text input to be synthesized
synthesis_input = texttospeech.types.SynthesisInput(text="Xin chào tôi là tạ minh luận")

# Build the voice request, select the language code ("en-US") and the ssml
# voice gender ("neutral")
voice = texttospeech.types.VoiceSelectionParams(
    language_code='vi-VN',
    ssml_gender=texttospeech.enums.SsmlVoiceGender.NEUTRAL)

# Select the type of audio file you want returned
audio_config = texttospeech.types.AudioConfig(
    audio_encoding=texttospeech.enums.AudioEncoding.MP3)

# Perform the text-to-speech request on the text input with the selected
# voice parameters and audio file type
response = client.synthesize_speech(synthesis_input, voice, audio_config)


# The response's audio_content is binary.
with open('output.mp3', 'wb') as out:
    # Write the response to the output file.
    out.write(response.audio_content)
    print('Audio content written to file "output.mp3"')
```

**Comment by ngoalongtb** [comment]
`# -*- coding: utf-8 -*-
"""Synthesizes speech from the input string of text or ssml.

Note: ssml must be well-formed according to:
    https://www.w3.org/TR/speech-synthesis/
"""
from google.cloud import texttospeech

# Instantiates a client
client = texttospeech.TextToSpeechClient()

# Set the text input to be synthesized
synthesis_input = texttospeech.types.SynthesisInput(text="Xin chào tôi là tạ minh luận")

# Build the voice request, select the language code ("en-US") and the ssml
# voice gender ("neutral")
voice = texttospeech.types.VoiceSelectionParams(
    language_code='vi-VN',
    ssml_gender=texttospeech.enums.SsmlVoiceGender.NEUTRAL)

# Select the type of audio file you want returned
audio_config = texttospeech.types.AudioConfig(
    audio_encoding=texttospeech.enums.AudioEncoding.MP3)

# Perform the text-to-speech request on the text input with the selected
# voice parameters and audio file type
response = client.synthesize_speech(synthesis_input, voice, audio_config)


# The response's audio_content is binary.
with open('output.mp3', 'wb') as out:
    # Write the response to the output file.
    out.write(response.audio_content)
    print('Audio content written to file "output.mp3"')`

**Comment by nnegrey** [comment]
Hi, in either python 2.7 or 3.7, 

What's the result of `pip  show google-cloud-texttospeech`?

**Comment by nnegrey** [comment]
Hi, any updates?

**Comment by mayouf** [comment]
hi any updates ?
I keep having `AttributeError: module 'google.cloud.texttospeech' has no attribute 'SynthesisInput'
`

**Comment by cmicek1** [comment]
Same :/ I'm trying to run the demo Python script in the cloud shell.

**Comment by TopCode111** [comment]
As stated in the comment above, you need to first install the library on your machine before calling the function within your app.
`pip install google-cloud-texttospeech`
