### ISSUE TITLE
Datastore API tutorial: args.func(client, args) errors out on Python 3.7.1

### ISSUE THREAD

**Issue by fredrikaverpil** [GoogleCloudPlatform/python-docs-samples#1939]
OS: MacOS X Mojave 10.14.2
Python: 3.7.1 homebrew, venv
google-cloud-datastore: 1.7.1

#### Steps to reproduce

  1. Follow tutorial at https://cloud.google.com/datastore/docs/datastore-api-tutorial
  1. Using service account and `export GOOGLE_APPLICATION_CREDENTIALS=/path/to/.json` 
  1. Run `python tasks.py --project-id <project-id>` as per the tutorial
  1. The very [last line](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/datastore/cloud-client/tasks.py#L139) of this script will cause an error.

@theacodes hey, I am taking the liberty to mention you here, as I saw you were the original author! :wink:
I don't quite understand what the intent is with this last line... The arguments returned by argparse returns a `Namespace` object. This does not have have a `func` method/function...?

#### Stack trace

```
Traceback (most recent call last):
  File "tasks.py", line 139, in <module>
    args.func(client, args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by fredrikaverpil** [comment]
Hm. I see now that argparse does indeed have this...
https://docs.python.org/2/library/argparse.html
https://docs.python.org/3/library/argparse.html

**Comment by aneeshp1994** [comment]
@fredrikaverpil Did you manage to find a solution? I am also getting this error.

**Comment by aneeshp1994** [comment]
@fredrikaverpil You have to provide extra arguments for the tasks.py to work. Like:
```
python tasks.py --project-id <your-project-id> new "Buy milk"
python tasks.py --project-id <your-project-id> done "Buy milk"
```

**Comment by fredrikaverpil** [comment]
Ah, ok thanks.
