### ISSUE TITLE
Google Cloud Pub/Sub : subscribe() takes atleast 3 arguments (2 given)

### ISSUE THREAD

**Issue by ku294714** [GoogleCloudPlatform/python-docs-samples#1942]
## I tried using inspect.py file of DLP to inspect the cloud storage bucket file.

Used the below file from python samples under DLP
--> inspect_content.py under DLP 

### I included my project details including the ids of the topic and subscription.

-- when I execute this file like:
python inspect_content.py  gcs --project <project_id> <bucket_id> <file_name> <topic_id> <subscription_id>
it throws me the below error: 

Traceback (most recent call last):
  File "inspect_content.py", line 944, in <module>
    timeout=args.timeout)
  File "inspect_content.py", line 312, in inspect_gcs_file
    subscription = subscriber.subscribe(subscription_path)
TypeError: subscribe() takes at least 3 arguments (2 given)

**Comment by anguillanneuf** [comment]
@ku294714 When you use `subscribe()`, you need to supply a callback function, which acts on individual received messages. You can see an example of it [here](https://googleapis.github.io/google-cloud-python/latest/pubsub/#subscribing). Unacknowledged messages will be sent again by the Pub/Sub server. 

Closing. But feel free to open if you are still stuck.
