### ISSUE TITLE
Disconnected: 1: Out of memory.

### ISSUE THREAD

**Issue by RamPrasadPrabu** [GoogleCloudPlatform/python-docs-samples#1943]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/mqtt_example/cloudiot_mqtt_example.py

### Did you change the file? If so, how?

No
## Describe the issue

ram_prasad_prabu@cloudshell:~/python-docs-samples/iot/api-client/end_to_end_example$ python cloudiot_pubsub_example_mqtt_device.py   --registry_id tour-registry   --device_id test-dev   --project_id "${DEVSHELL_PROJECT_ID:-Cloud Shell}"   --private_key_file rsa_private.pem   --algorithm RS256   --ca_certs roots.pem   --cloud_region us-central1
Creating JWT using RS256 from private key file rsa_private.pem
Disconnected: 1: Out of memory.
Disconnected: 1: Out of memory.
Disconnected: 1: Out of memory.
Traceback (most recent call last):
  File "cloudiot_pubsub_example_mqtt_device.py", line 259, in <module>
    main()
  File "cloudiot_pubsub_example_mqtt_device.py", line 234, in main
    device.wait_for_connection(5)
  File "cloudiot_pubsub_example_mqtt_device.py", line 100, in wait_for_connection
    raise RuntimeError('Could not connect to MQTT bridge.')
RuntimeError: Could not connect to MQTT bridge.

I checked the python version as mentioned in the similar ticket[https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1357]. Still I'm facing same issue.

**Comment by gguuss** [comment]
This error occurs whenever your connection settings are incorrect. I'm going to close this as it's been a while - feel free to reopen if you'd like to diagnose.
