### ISSUE TITLE
When using detect.py get error

### ISSUE THREAD

**Issue by z490938304** [GoogleCloudPlatform/python-docs-samples#1945]
when using   python detect.py web ./resources/landmark.jpg  in CMD:
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application.

Or using in Cloud Shell:
google.api_core.exceptions.PermissionDenied: 403 Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the visi
on.googleapis.com. We recommend that most server applications use service accounts instead. For more information about service accounts and how to use them in your application, see https://cloud
.google.com/docs/authentication/.

under the path
python-docs-samples/vision/cloud-client/detect/

no change of the file

**Comment by nnegrey** [comment]
Hi, did you follow the Setup steps on the README?
- README: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/vision/cloud-client/detect#setup

Or
- Cloud docs quickstart: https://cloud.google.com/vision/docs/quickstart-client-libraries#client-libraries-install-python

Hope this helps, if not, please feel free to reopen the issue.
