### ISSUE TITLE
Open reports error on cloudfunction log

### ISSUE THREAD

**Issue by markabUK** [GoogleCloudPlatform/python-docs-samples#1961]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/8e36ed73e6a047413929b53cd00d2f07422b56a5/dlp/inspect_content.py#L645

I am calling the DLP service through the a python cloud function, and when it gets down to the code 
subscriber = google.cloud.pubsub.SubscriberClient()
    subscription_path = subscriber.subscription_path(
        project, subscription_id)
#    subscription = subscriber.subscribe(subscription_path, callback)
    subscription = subscriber.subscribe(subscription_path)

    # Set up a callback to acknowledge a message. This closes around an event
    # so that it can signal that it is done and the main thread can continue.
    job_done = threading.Event()

    def callback(message):
        try:
            if (message.attributes['DlpJobName'] == operation.name):
                # This is the message we're looking for, so acknowledge it.
                message.ack()

                # Now that the job is done, fetch the results and print them.
                job = dlp.get_dlp_job(operation.name)
                if job.inspect_details.result.info_type_stats:
                    for finding in job.inspect_details.result.info_type_stats:
                        print('Info type: {}; Count: {}'.format(
                            finding.info_type.name, finding.count))
                else:
                    print('No findings.')

                # Signal to the main thread that we can exit.
                job_done.set()
            else:
                # This is not the message we're looking for.
                message.drop()
        except Exception as e:
            # Because this is executing in a thread, an exception won't be
            # noted unless we print it manually.
            print(e)
            raise

    # Register the callback and wait on the event.
    subscription.open(callback)

 the clound function when running reports the error TypeError: subscribe() missing 1 required positional argument: 'callback'

When I have added the callback into the subscribe method then it will timeout and nothing is posted to the topic.

I am wondering whether there is an issue with this, or whether I am missing something.

Thanks

**Comment by michaelawyu** [comment]
The issue seems to be obsolete; the code has been updated.
