### ISSUE TITLE
broken request.data.decode('utf-8') call

### ISSUE THREAD

**Issue by cerebraljam** [GoogleCloudPlatform/python-docs-samples#1965]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/da0d097e9e6e2ac1db53491553f7c985c2f7cbf2/appengine/standard/pubsub/main.py#L71

As written currently, the code returns the following error message, since request.data is empty.
`raise ValueError("No JSON object could be decoded")`

It works if written as
`envelope = json.loads(request.get_data().decode('utf-8'))`

**Comment by andrewferlitsch** [comment]
@michaelawyu - any update on fixing the sample?

**Comment by leahecole** [comment]
Hey @michaelawyu any updates?

**Comment by leahecole** [comment]
It looks like a fix for this was pushed so I'll close this for now, but feel free to reopen if needed!
