### ISSUE TITLE
Cloud API into Google Doc

### ISSUE THREAD

**Issue by levycarneiro** [GoogleCloudPlatform/python-docs-samples#1971]
This is a question:

Is there a way to perform a live transcription from an audio stream (mic) and send the text into a Google doc?

Thanks.

**Comment by nnegrey** [comment]
I'm not familiar with the Google Drive API, but would something like this work?
https://developers.google.com/drive/api/v3/manage-uploads

**Comment by nnegrey** [comment]
Going to close this, please feel free to reopen.
