### ISSUE TITLE
Cloud storage file is not available to speech API

### ISSUE THREAD

**Issue by codeAshu** [GoogleCloudPlatform/python-docs-samples#1972]
I frequently encounter error from speech API that google storage file is not available, whereas I upload 
the file just before calling the speech API. 

Mostly I encounter:
`No such object: <cloud storage file path>`

This is the actual error: 
`cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND: No such object: `

I get error when I poll the speech API for results, in long_running_job `~/env/local/lib/python2.7/site-packages/google/api_core/future/polling.py line 120, in result
   raise self._exception`

What do you suggest to make sure file is available in the network?

**Comment by nnegrey** [comment]
Hi, which sample are you referring to?

**Comment by nnegrey** [comment]
Going to close this, please feel free to reopen.
