### ISSUE TITLE
How to save result of TEXT_DETECTION without annotations

### ISSUE THREAD

**Issue by OndoyManing** [GoogleCloudPlatform/python-docs-samples#1974]
I'm having a bit of a trouble with Google Cloud Vision's TEXT_DETECTION. Let's say I have an image of a license plate and I just want to save the contents of the license plates without their corresponding coordinates/annotations. How do I do that in Python?

**Comment by nnegrey** [comment]
From this sample: https://cloud.google.com/vision/docs/detecting-text
You can just use the `response.text_annotations.description`

If that isn't what you are looking for, feel free to reopen the issue. :)
