### ISSUE TITLE
how to annotate the image with trained images set?

### ISSUE THREAD

**Issue by ganeshsingamaneni** [GoogleCloudPlatform/python-docs-samples#1981]
## In which file did you encounter the issue?
i trained the models with data set of images and successfully evaluated and get prediction and classification score.
My major doubt is what to do with that classification score?
and what i need is,
i trained the models with a images with a same stamp on it,and while prediction i'am send a 
image with a stamp like i trained and two other different stamps.
Now i need to get the only stamp which i trained from the 3 stamps as a another image or base 64.
is it possible with auto ml with python?

**Comment by nnegrey** [comment]
Your classification score is how confident the model is that it classified the image correctly.

Sounds like you are looking for object localization inside an image, as of right now, automl only support classification. 

Hope this helps, feel free to reopen the issue. :)
