### ISSUE TITLE
Need to decode data coming from MQTT bridge on Python3

### ISSUE THREAD

**Issue by CarlosMendonca** [GoogleCloudPlatform/python-docs-samples#1985]
## In which file did you encounter the issue?
python-docs-samples/iot/api-client/end_to_end_example/cloudiot_pubsub_example_mqtt_device.py
python-docs-samples/iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py

### Did you change the file? If so, how?
[Diff](https://gist.githubusercontent.com/CarlosMendonca/92dd7a901c87c1df37da6901b415bbd4/raw/21f67c448b5ee04c3339cf7f15d779f3eb37bb0e/gistfile1.txt)

## Describe the issue

Data from MQTT bridge must be decoded in Python3 to become a string that can be parsed to JSON by this code. Adding explicit decode calls solves the issue.

**Comment by gguuss** [comment]
Self-assigning - I'll try and investigate here

**Comment by gguuss** [comment]
Should be resolved when [this PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2383) merges.

**Comment by gguuss** [comment]
Should be resolved now.
