### ISSUE TITLE
about using google.oauth2

### ISSUE THREAD

**Issue by emilefokkema** [GoogleCloudPlatform/python-docs-samples#1986]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python37/building-an-app/building-an-app-3/main.py#L21
### Did you change the file? If so, how?
no
## Describe the issue
Will this implementation, or one that uses `google.oauth2.id_token`, still work once Google+ is shut down? I'm asking because I got an email saying
> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown, with API calls starting to intermittently fail as early as January 28, 2019, and OAuth requests for Google+ scopes starting to intermittently fail as early as February 15, 2019.

**Comment by andrewsg** [comment]
Apologies for the significant wait. This example code does not use any of the deprecated scopes so it will continue to work. For details on the scopes turned off and their replacements, please refer to this page: https://developers.google.com/+/scopes-shutdown
