### ISSUE TITLE
Gateways: make the --device_id parameter required only for commands that need it

### ISSUE THREAD

**Issue by stevebriskin** [GoogleCloudPlatform/python-docs-samples#1996]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/beta-features/gateway/gateway.py#L597 requires the `--device_id` for all invocations but some calls ( list_devices_for_gateway and list_gateways) do not need it.

**Comment by gguuss** [comment]
We could probably benefit from refactoring the commands all at once as there are more than just the device ID that should be optional.

**Comment by gguuss** [comment]
Should be resolved once we've merged [this PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2320).
