### ISSUE TITLE
Gateways: Confusing output for list_devices_for_gateway

### ISSUE THREAD

**Issue by stevebriskin** [GoogleCloudPlatform/python-docs-samples#1997]
The list_devices_for_gateway function in gateway/gateway.py has a [loop](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/3b84c35aaf6f585222e54e77696ecab639b14692/iot/api-client/beta-features/gateway/gateway.py#L318-L327) that isn't exercised which results in confusing output. There is no 'deviceNumIds' key in the devices dict .

In this example 'my-node-device' is bound to gateway 'testgateway'
```
$ python gateway.py --service_account_json XYZ.json --registry_id=my-registry --device_id=null --gateway_id=testgateway --project_id=myproject list_devices_for_gateway
Device: 2587394384972593 : my-node-device
No devices bound to gateway testgateway
```
The dict at [devices dict](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/3b84c35aaf6f585222e54e77696ecab639b14692/iot/api-client/beta-features/gateway/gateway.py#L307) is missing 'deviceNumIds'
```
{u'devices': [{u'numId': u'2587394384972593', u'id': u'my-node-device'}]}
```

**Comment by gguuss** [comment]
Thanks for the heads up, what version of Python are you using? I just tested the sample and I'm seeing the following output for a gateway with no bound devices:?

```
No devices bound to gateway jah
```

A gateway with one bound device renders as:

```
Device: 2658882084459077 : alpha
```

A gateway with two bound devices renders as:
```
Device: 2658882084459077 : alpha
Device: 2765886308686097 : bleep
```

**Comment by gguuss** [comment]
I see what you're saying though, I'm not sure what conditions the sample is trying to resolve with the second loop or why/when the deviceNumIds dict would be populated. I'll take another look later on.

**Comment by gguuss** [comment]
Resolved in [this PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2319). As you pointed out, the initial check for `deviceNumIds` would never be reached.
