### ISSUE TITLE
Airflow jobs failing with bq_copy_across_locations.py

### ISSUE THREAD

**Issue by benpowis** [GoogleCloudPlatform/python-docs-samples#2006]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/composer/workflows/bq_copy_across_locations.py

I am using the AirFlow workflow (unedited) for moving BigQuery data between different GCP regions. I ran a test workflow with 7 files in the .csv config file, which completed in around one minute, However, when I scale this up to all the tables I want to more (300+), the first stage of the workflow errors for _almost_ every file. The logs for the failed jobs are empty.

I am fairly new to AirFlow - I tried increasing my nodes from 3 to 6, but it's made no noticeable difference. Are there limits I should be aware of? What would be the best approach to move a large number of tables with this workflow?

Thanks,
Ben

**Comment by leahecole** [comment]
Hi @benpowis, I'm sorry you ran into this problem, and I'd like to get to the bottom of it if it's still a problem for you. To help my debugging, could you provide me with some more info:

- What version of Cloud Composer are you using? To figure this out, you can run this command in your Cloud Shell, replacing <environment-name> with your environment name and <location> with the region your Composer env is located in, or you can look on the Environment Details page. 
```gcloud composer environments describe <environment-name> \ --location <location> \ --format "value(config.softwareConfig.imageVersion)"```
- What location is your Composer environment in?
- What BQ locations are you trying to use? 
- Do you have a rough idea of the size of the tables in the 300 you're working with? 

Thank you

**Comment by leahecole** [comment]
I'm going to close this due to inactivity, but feel free to reopen!
