### ISSUE TITLE
Speaker tag is not accurate 

### ISSUE THREAD

**Issue by balavenkatesh3322** [GoogleCloudPlatform/python-docs-samples#2016]
Please refer the issue details.
https://github.com/google/uis-rnn/issues/34

**Comment by nnegrey** [comment]
Hi, as this feature is currently in beta, from the docs: https://cloud.google.com/speech-to-text/docs/multiple-voices
Note: Cloud Speech-to-Text supports speaker diarization for the en-US, en-IN, and es-ES languages. Cloud Speech-to-Text only supports speaker diarization for transcribing phone calls.

Does your audio file match these requirements?

**Comment by nnegrey** [comment]
Hi, going to close this now, but feel free to reopen.
