### ISSUE TITLE
extend Auto ML Vision api with export functionality

### ISSUE THREAD

**Issue by pentium10** [GoogleCloudPlatform/python-docs-samples#2017]
In the AutoML Vision examples
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/vision/automl

it's missing the real business value, like how do you export the model?

you build and train, but no additional steps to do that, locked in the phase of build an train

we need export as well added, so we can take the model and implement for example on a mobile app

**Comment by nnegrey** [comment]
Hi, Thanks for the feedback! 

Going to close this issue as it isn't directly a problem with the samples, but a Feature Request. 

Feel free to reopen, thanks!

**Comment by nnegrey** [comment]
Check out here to file Feature Requests: https://cloud.google.com/support/docs/issue-trackers
