### ISSUE TITLE
Full audio clip is not getting transcribed

### ISSUE THREAD

**Issue by tapas4java** [GoogleCloudPlatform/python-docs-samples#2023]
## In which file did you encounter the issue?
`speech/cloud-client/transcribe_async.py`

### Did you change the file? If so, how?
I have just commented out following lines:

```
encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
sample_rate_hertz=16000,
```

## Describe the issue
Hi, I am trying to transcribe a 5min wav file using async option. I can see only couple of words getting transcribed instead of full audio clip. Could you please help me to understand how to transcribe full length clip?

```
Waiting for operation to complete...
Transcript: good morning
Confidence: 0.9359552264213562
Transcript:  quantitative 317
Confidence: 0.802681028842926

Process finished with exit code 0
```

**Comment by nnegrey** [comment]
You'll need to set `encoding` and `sample_rate_hertz` to match your audio file.

**Comment by nnegrey** [comment]
Please feel free to reopen the issue if that doesn't fix the issue. :)
