### ISSUE TITLE
Firebase authentication with e-mail provider is not redirecting

### ISSUE THREAD

**Issue by dagamargit** [GoogleCloudPlatform/python-docs-samples#2031]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python37/building-an-app/building-an-app-3/templates/index.html

### Did you change the file? If so, how?

Updated firebaseui version to a newer version:

<script src="https://cdn.firebase.com/libs/firebaseui/3.5.2/firebaseui.js"></script>
<link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/3.5.2/firebaseui.css" />  

## Describe the issue

The example as described here:
https://cloud.google.com/appengine/docs/standard/python3/building-app/adding-firebase?hl=es-419
is using version 2.6.2 of the libraries. 

When using an e-mail for the authentication with firebase, redirection is not working properly when a new user is registered. If the use click the "Save" button nothing happens.

Newer versions of the library (e.g. 3.5.2) are working properly.

Kind regards,
Daniel.

**Comment by andrewferlitsch** [comment]
@andrewsg Any update on the issue?

**Comment by andrewsg** [comment]
Thanks for the reminder. I tried this out and it turns out the workflow doesn't work at all now, because Firebase split auth into a separate library and doesn't include it in the copy/paste snippet by default. I'm investigating.
