### ISSUE TITLE
Google Cloud Functions - Test/Mock with Authentication for HTTP triggered functions?

### ISSUE THREAD

**Issue by mxlei01** [GoogleCloudPlatform/python-docs-samples#2037]
I have an API built using GCP Cloud Functions, I know it's built upon Flask, however the app itself is not exposed to the user.

From the [Testing Documentation][1] for GCP Cloud Functions it uses the `Mock` object from `unittest` built in from Python.

However, I have an authentication decorator that I can throw around and it detects if there is an appropriate password in the `x-api-key` on the header.

   ```
 """Authentication for Cloud Functions."""
     
from functools import partial, wraps
from flask import request, abort
     
import config
     
     
def auth(func=None):
    if func is None:
        return partial(auth)

    @wraps(func)
    def wrap(*args, **kwargs):
        if request.headers.get('x-api-key') and request.headers.get('x-api-key') == config.API_KEY:
            return func(*args, **kwargs)
        else:
            abort(401)
    return wrap
```

Then I can apply it onto a Google Cloud Functions:

```
@auth
def frontend_query(request):
    request_json = request.get_json(silent=True)
    # Do Something Else
```

You can use `mock` to create a `request_json`, but how do I also get fake header data into `request.headers`?

  [1]: https://cloud.google.com/functions/docs/bestpractices/testing

**Comment by michaelawyu** [comment]
Hi mxlei01!

To mock a property, consider using the [`unittest.mock.PropertyMock` class](https://docs.python.org/3/library/unittest.mock.html#mock.PropertyMock). You also create your own request object for tests.

Example: Using the PropertyMock class

```
from unittest.mock import MagicMock, PropertyMock

request = MagicMock()
headers = PropertyMock(return_value="YOUR-API-KEY")
type(request).headers = headers
assert(request.headers == "YOUR-API-KEY")
```
