### ISSUE TITLE
Not able to predict on multiple rows of test file?

### ISSUE THREAD

**Issue by sagar625** [GoogleCloudPlatform/python-docs-samples#2073]

**Comment by nnegrey** [comment]
Hi, which sample is this referring to?

**Comment by sagar625** [comment]
I am using the same tarining examples just for test run,before I put the test datapoints. I am using a txt file.

eg file look like this


SocialHistoryObservedValue
N
1 cigarette daily,
no 
1 pack a day for 10yrs,
Are you a: Never smoker,
1 PPD for years but at some point smoked more.

**Comment by nnegrey** [comment]
Is there a specific python file this is related to?

Also, what error messages are you getting?

**Comment by nnegrey** [comment]
Gonna close this for now, feel free to re-open. :)
