### ISSUE TITLE
using shared objects with google cloud functions

### ISSUE THREAD

**Issue by karanrk** [GoogleCloudPlatform/python-docs-samples#2075]
## Describe the issue

I have a go-lang script that is compiled and has header file and .so file which is referenced by my python cloud function. Deployment is successful but the invocation gives me connection error. 

This was something that worked on Lambda and i am assuming it should work with google cloud too. Please let me know if am missing on any configuration.

**Comment by ace-n** [comment]
@karanrk can you post a copy of your Go and Python code, as well as the error message?

In any case - this is likely a better use case for [Cloud Run](https://cloud.google.com/run), which operates on containers. Cloud Functions (at least the Python version) is designed _primarily_ to run _Python_ code, and it's possible there's a missing dependency somewhere causing the failure.

**Comment by karanrk** [comment]
@ace-n  Since i didn't hear back sooner, we re-wrote the code in python. But i am curios to know can't we invoke a function implemented in other(except python) language within python runtime? Is there a cross language runtime restriction ?

**Comment by andrewferlitsch** [comment]
@karanrk It sounds like you found a workaround. I will close this issue.
