### ISSUE TITLE
Dual language streaming

### ISSUE THREAD

**Issue by DrBelk** [GoogleCloudPlatform/python-docs-samples#2099]
Hi!
I am trying to use this example to implement streaming recognition for 2 language in 1 phrase, like there: https://cloud.google.com/speech-to-text/docs/multiple-languages
How can I do it for stream? I had some experiments, but it looks like it is not supported at the moment. Could you please give an advance here?

**Comment by nnegrey** [comment]
Hi, according to: https://cloud.google.com/speech-to-text/docs/multiple-languages#enabling_language_recognition_in_audio_transcription_requests

multiple language should be supported by streaming, what kind of error are you getting?

**Comment by nnegrey** [comment]
Gonna close this for now, please feel free to re-open. :)
