### ISSUE TITLE
django_tutorial

### ISSUE THREAD

**Issue by hanzvanaardt** [GoogleCloudPlatform/python-docs-samples#2118]

**Comment by hanzvanaardt** [comment]
> ## In which file did you encounter the issue?

When doing the Django_Tutorial as described here https://cloud.google.com/python/django/kubernetes-engine the installation step gives an error due to an error in the requirements.txt file (mysqlclient==1.4.1 is the source of the error).

> ## Describe the issue
This entry gives an error when running pip install -r requirements.txt in cases where MySQL does not exist on the current machine.  The error is: "mysql_config not found" and the rest of the requirements fails.  Simply hashing out the line like so: #mysqlclient==1.4.1 will resolve this issue.
This ticket keeps on being opened and is then closed - see tickets:
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1813

I understand that MySQL might be used by someone ,however, the project references a tutorial which fails if a user does not have MySQL installed.  The full output of the error is:

Collecting mysqlclient==1.4.1 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/de/d7/919042fb7ed78a89e21c4e43d5daed90d5df18ec183bae3de493a7d9e3ed/mysqlclient-1.4.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5c/wggspwss6ln_qpqszpqzjhmh0000gn/T/pip-install-r8pix6du/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/5c/wggspwss6ln_qpqszpqzjhmh0000gn/T/pip-install-r8pix6du/mysqlclient/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/5c/wggspwss6ln_qpqszpqzjhmh0000gn/T/pip-install-r8pix6du/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5c/wggspwss6ln_qpqszpqzjhmh0000gn/T/pip-install-r8pix6du/mysqlclient/

**Comment by engelke** [comment]
Thank you for the report. This is fixed in PR 2202 by commenting out the mysqlclient requirement with an explanation that it should be uncommented if you are using the MySQL option, and have already installed MySQL.
