### ISSUE TITLE
Run task HTTP from Cloud Task to Cloud Run Endpoint

### ISSUE THREAD

**Issue by gregorymendes** [GoogleCloudPlatform/python-docs-samples#2140]
## In which file did you encounter the issue?

`python-docs-samples/tasks/create_http_task.py`

### Did you change the file? If so, how?

Modifications for auth with service account:
```python
    credentials = service_account.Credentials.from_service_account_file(
        '<PATH>/credentials.json',
        scopes=['https://www.googleapis.com/auth/cloud-tasks']
    )
    # Create a client.
    client = tasks_v2beta3.CloudTasksClient(credentials=credentials)
```
## Describe the issue
I run this command:
```bash
$ python create_http_task.py --project=$PROJECT_ID --queue=$QUEUE_ID --location=$LOCATION_ID --url=$URL --payload=hello
```

And the output is :
```bash
google.api_core.exceptions.InvalidArgument: 400 Task.payload_type is not set.
```

I've try lot of thing but it never work ? 
Can someone help me ?

**Comment by averikitsch** [comment]
Hi @gregorymendes 
That error usually comes from not correctly creating the task object or an older version of the library. What version of google-cloud-tasks are you using (you can see this by `pip freeze`)? Have you modified the task object from:
```
task = {
            'http_request': {  # Specify the type of request.
                'http_method': 'POST',
                'url': url  # The full url path that the task will be sent to.
            }
    }
```

**Comment by averikitsch** [comment]
Feel free to reopen this issue, if you continue to experience this error.
