### ISSUE TITLE
There are no samples for Data Catalog clients in the repository

### ISSUE THREAD

**Issue by ricardosm-cit** [GoogleCloudPlatform/python-docs-samples#2141]
## Describe the issue

Data Catalog is a new product in GCP's Big Data family. There is an initial version for its cloud client library publicly available (https://googleapis.github.io/google-cloud-python/latest/datacatalog/gapic/v1beta1/api.html), but not samples for it in this repository.

As an early adopter of this product, I would like to contribute by creating the `datacatalog/cloud-client` folder in repo's root and adding samples there.

**Comment by tswast** [comment]
Thanks for volunteering to add samples, Ricardo. I agree that `datacatalog/cloud-client` is the best location for the suggested samples.
