### ISSUE TITLE
Dialogflow upload knowledge document using local csv

### ISSUE THREAD

**Issue by chen-bowen** [GoogleCloudPlatform/python-docs-samples#2147]
## In which file did you encounter the issue?
python-docs-samples/dialogflow/cloud-client/document_management.py

### Did you change the file? If so, how?
No.

## Describe the issue
The function``` create_document(project_id, knowledge_base_id, display_name, mime_type,
 knowledge_type, content_uri) ``` does not allow me to use a local csv. It is forcing me to use either a public url or a google cloud storage csv. Here is my code

```        
client = dialogflow.DocumentsClient()
knowledge_base_path = client.knowledge_base_path(project_id,
                                                         knowledge_base_id)

document = dialogflow.types.Document(display_name=display_name, 
                                            mime_type='text/csv',
                                            content_uri='../Data/faq.csv')

document.knowledge_types.append(
            dialogflow.types.Document.KnowledgeType.Value('FAQ'))

response = client.create_document(knowledge_base_path, document)
document = response.result(timeout=90)

```

and it's returning the error of 
```
google.api_core.exceptions.InvalidArgument:
400 The Public Url Type and FAQ Knowledge Type do not support the text/csv MIME Type.
```
Could you help me figure out how I should use my local csv file? It is crucial to our team in building out this knowledge base management system.

**Comment by nnegrey** [comment]
The `content_uri` field is expecting a uri not the path to a file. 

However, if you want to use a local file, you'll need to use the `raw_content` field. 

Example:
```
fileBytes = read_your_csv_file('../Data/faq.csv')

document = dialogflow.types.Document(display_name=display_name, 
                                            mime_type='text/csv',
                                            raw_content=fileBytes)
```

For more info, you can check out the reference pages for the Document: https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2beta1#google.cloud.dialogflow.v2beta1.Document
