### ISSUE TITLE
Trigger deployment with cli-gcloud not triggering, found the issue

### ISSUE THREAD

**Issue by ricardochen** [GoogleCloudPlatform/python-docs-samples#2188]
## In which file did you encounter the issue?

main.py

### Did you change the file? If so, how?

Did not change

## Describe the issue

Function is not triggered when deploying with the command showed in the documentation: 
https://cloud.google.com/functions/docs/calling/cloud-firestore#functions_firebase_firestore-python

gcloud functions deploy FUNCTION_NAME \
  --runtime RUNTIME
  --trigger-event providers/cloud.firestore/eventTypes/document.write \
  --trigger-resource projects/YOUR_PROJECT_ID/databases/default/documents/messages/{pushId}

The fix is to change default with (default) like so:
`projects/YOUR_PROJECT_ID/databases/\(default\)/documents/messages/{pushId}`

**Comment by elartey** [comment]
@ricardochen I just spent the better part of my day trying to figure out why this was not working for me. You're a life-saver.

**Comment by elartey** [comment]
is `default` a reserved or special word of some kind that needs to be escaped/formatted?

**Comment by ricardochen** [comment]
Its a bug already reported to Google and acknowledged, meanwhile the workaround is to put the () , and the escaping is for the url to accept ()

**Comment by pdcoded** [comment]
Spent 2 hours to figure out this is outcome of bad documentation - Need to use backslash for default

**Comment by ace-n** [comment]
Thanks for reporting this! It looks like this has been fixed in the current published doc, so I'm marking this as closed. 🙂
