### ISSUE TITLE
I am a newbee at gcp and google translate.I want to use v3 beta 1 translate for a project(because its pricing is cheap and I have to translate a lot of characters). But the method translate_text() returns a list of dictionaries and it seems that each dictionary contains individual translated char. I have tried concatenating these characters but result doesn't make sense

### ISSUE THREAD

**Issue by vinayaksharmagh** [GoogleCloudPlatform/python-docs-samples#2193]
## Describe the issue

I want to use v3 beta 1 translate for a project(because its pricing is cheap and I have to translate a lot of characters). But the method translate_text() returns a list of dictionaries and it seems that each dictionary contains individual translated char. I have tried concatenating these characters but result doesn't make sense. How am I supposed to make sense of object returned by translate_text()

**Comment by nnegrey** [comment]
Have you seen this sample?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/translate/cloud-client/beta_snippets.py#L18-L38
