### ISSUE TITLE
The given sample raises an InterfaceError

### ISSUE THREAD

**Issue by pranaynanda** [GoogleCloudPlatform/python-docs-samples#2197]
## In which file did you encounter the issue?

cloud-sql/postgres/sqlalchemy/main.py 

### Did you change the file? If so, how?

![Screenshot 2019-06-06 at 7 20 24 PM](https://user-images.githubusercontent.com/8961079/59038141-27729680-8890-11e9-939b-0fa7c28ab1ed.png)

I changed the connection driver and the associated library in requirements.txt

## Describe the issue

Running the project as is on the local development environment raises InterfaceError 

`raise InterfaceError("communication error", e) sqlalchemy.exc.InterfaceError: (pg8000.core.InterfaceError) ('communication error', ConnectionRefusedError(111, 'Connection refused')) (Background on this error at: sqlalche.me/e/rvf5)`

**Comment by kurtisvg** [comment]
Hi @pranaynanda, Your issues here is that you've changed host to `cloud_sql_connection_name`, which is not the same as `unix_socket='/cloudsql/<INSTANCE_CONNECTION_NAME>'`. Once you adjust the directory to point to the correct socket it should work.
