### ISSUE TITLE
cloud functions logging example possible typo

### ISSUE THREAD

**Issue by manikantanr** [GoogleCloudPlatform/python-docs-samples#2204]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/functions/log/main.py#L44

### Did you change the file? If so, how?
NO

## Describe the issue

I was looking at Stack Driver logging with python example. One line did not make sense to me.

`log_name` has no interpolation ({}). But its using `format` method. Not sure the use of it or whats missing there.

**Comment by engelke** [comment]
Please clarify why a particular name would be used for a log. Note that the example does not actually add the GCP_PROJECT to the log name.

**Comment by ace-n** [comment]
@manikantanr thanks for spotting this.

@engelke It appears that `log_name` is used to determine which product's log entries to fetch. I tested the code, and confirmed that GCP_PROJECT isn't necessary.

(Submitted [a PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2223) to remove it.)

**Comment by engelke** [comment]
Thanks.
