### ISSUE TITLE
AutoML Vision Object Detection: import_data sample variable unclear

### ISSUE THREAD

**Issue by hongalex** [GoogleCloudPlatform/python-docs-samples#2213]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/9c01c4d1dbe049286761bc726b1950e0a6096def/vision/automl/automl_vision_od_dataset.py#L141

`vision/automl/automl_vision_od_dataset.py`

### Did you change the file? If so, how?

No

## Describe the issue

It is unclear from the sample that `paths` should be an array. It is properly mentioned in the [documentation](https://cloud.google.com/vision/automl/docs/reference/rpc/google.cloud.automl.v1beta1#gcssource), but from the other commented fields (which also use brackets), it is unclear whether `paths` should be a string or an array of strings. Originally encountered by @andrewferlitsch, where passing a GCS URL leads to a `DEADLINE_EXCEEDED` error.

**Comment by engelke** [comment]
File updated at https://github.com/GoogleCloudPlatform/python-docs-samples/blob/automl_object_detection_april_2019/vision/automl/automl_vision_od_dataset.py. Will merge along with PR when overall PR is approved.
