### ISSUE TITLE
Object takes no parameters? Error

### ISSUE THREAD

**Issue by ParkerShamblin** [GoogleCloudPlatform/python-docs-samples#2228]
I'm currently working through the "Analyzing entities" examples here: https://cloud.google.com/natural-language/docs/analyzing-entities

And after copy and pasting the example into google colab, I get the follow error
![analyzing_entities_error](https://user-images.githubusercontent.com/48718776/59558468-cef27600-8fc0-11e9-8cf9-caf0080d2914.PNG)

**Comment by nnegrey** [comment]
Hi, what version of the library do you have?

`pip freeze | grep google-cloud-language`
