### ISSUE TITLE
ERROR from  grpc._cython import cygrpc as _cygrpc ImportError: cannot import name cygrpc

### ISSUE THREAD

**Issue by xiaoyangnihao** [GoogleCloudPlatform/python-docs-samples#2237]
from  grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name cygrpc
 This problem happens when I run the build tests

**Comment by xiaoyangnihao** [comment]
Does anyone can help me solve this problem ? thanks a lot

**Comment by nnegrey** [comment]
Which sample are you trying to run?

**Comment by xiaoyangnihao** [comment]
> Which sample are you trying to run?

I try to compile the tenserflow serving with bazel, the "bazel build -c opt tensorflow_serving/..." run succussfully, but when I run the "bazel test -c opt tensorflow_serving/...", 'tensorflow_model_server_beta_grpc_test.py' and 'tensorflow_model_server_test.py' tests failed. the test log shows that   from grpc._cython import cygrpc as _cygrpc ImportError: cannot import name cygrpc. 
I try to unistall the grpcio and install again, but still failed

**Comment by nnegrey** [comment]
Are you referring to the samples in this repo? https://github.com/tensorflow/serving

**Comment by iugov** [comment]
Specifying version as `grpcio==1.27.2` resolved my issue
