### ISSUE TITLE
Query.get' is deprecated:  please use 'Query.stream' instead

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/python-docs-samples#2256]
[docs = db.collection(u'cities').where(u'capital', u'==', True).get()](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/b8298b3739a2a9e9f010bb89b64a429ccc7cede2/firestore/cloud-client/snippets.py#L243)
throws a warning of **Query.get' is deprecated:  please use 'Query.stream' instead**

I believe the fix can be simply replacing _.get_ with _.stream_

**Comment by petervandenabeele** [comment]
yes, but not a blind search/replace (on an individual document, `get(key_name)` is still valid.
Only on `Collection`, `Query`, etc. if I see correctly.

**Comment by petervandenabeele** [comment]
This issue may be solved in the Merge Request that just got merged:

https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2240

**Comment by andrewferlitsch** [comment]
@hilliao did the issue get solved?

**Comment by hilliao** [comment]
@andrewferlitsch , I lost access to the code since I changed my employer. By reviewing the initial comment, It was a warning so I'm closing the issue here.
