### ISSUE TITLE
Wrong get_check_exists sample. No exception now

### ISSUE THREAD

**Issue by limexp** [GoogleCloudPlatform/python-docs-samples#2261]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/b32f7df710973170efc5fdfbcf0e5182d13ced7c/firestore/cloud-client/snippets.py#L219-L225

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets.py

### Did you change the file? If so, how?

https://github.com/GoogleCloudPlatform/python-docs-samples/compare/master...limexp:patch-1

## Describe the issue

There are no more exceptions when no document found in DocumentReference.get() call. 

> If the document does not exist at the time of the snapshot is taken, the snapshot’s reference, data, update_time, and create_time attributes will all be None and its exists attribute will be False.
From https://googleapis.github.io/google-cloud-python/latest/firestore/document.html#google.cloud.firestore_v1.document.DocumentReference.get

Now issues https://github.com/googleapis/google-cloud-python/issues/4530 and https://github.com/googleapis/google-cloud-python/pull/4531 are resolved

**Comment by crwilcox** [comment]
Would you mind opening a pull request with your branch?

**Comment by BenWhitehead** [comment]
Fixed by: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2429
