### ISSUE TITLE
incorrect send mail address in python example file

### ISSUE THREAD

**Issue by JosephJeffs** [GoogleCloudPlatform/python-docs-samples#2267]
## In which file did you encounter the issue?

python-docs-samples/appengine/standard/mail/send_mail.py

## before correction
class SendMailHandler(webapp2.RequestHandler):
    def get(self):
        send_approved_mail('{}@appspot.gserviceaccount.com'.format(
            app_identity.get_application_id()))

## after correction
class SendMailHandler(webapp2.RequestHandler):
    def get(self):
        emailid = ('anything@{}.appspotmail.com'.format(
            app_identity.get_application_id()))
        send_approved_mail(emailid)

## Describe the issue
As per https://cloud.google.com/appengine/docs/standard/python/mail/#who_can_send_mail the sender address in the example python file is incorrect.    The example code returns the error "Unauthorized sender"  my example code shows how to format with a valid sender.

**Comment by andrewferlitsch** [comment]
@beccasaurus Don't know who would cover appengine. Can you triage and reassign.

**Comment by ace-n** [comment]
@michaelawyu can you take a look?

**Comment by leahecole** [comment]
Note for future Leah and everyone - I did ping @michaelawyu today : )

**Comment by leahecole** [comment]
Looks like a fix for this was pushed, so I'll close this for now, but reopen if needed!
