### ISSUE TITLE
Batch prediction for AutoML Vision

### ISSUE THREAD

**Issue by minhnguyenvan95** [GoogleCloudPlatform/python-docs-samples#2271]
Can I use batch prediction for AutoML vision ?

**Comment by nnegrey** [comment]
It doesn't look like that is currently supported for AutoML Vision. 

Based on the docs pages: https://cloud.google.com/vision/automl/docs/reference/rpc/google.cloud.automl.v1beta1

I'd suggest opening a Feature Request on this page: https://cloud.google.com/support/docs/issue-trackers

Link to the AutoML Vision Issues creation: https://issuetracker.google.com/issues/new?component=187174&template=0

Going to close, but let me know if there's anything else I can do.
