### ISSUE TITLE
beta_snippets.py speech transcribe not working?

### ISSUE THREAD

**Issue by ningwudm00** [GoogleCloudPlatform/python-docs-samples#2277]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/beta_snippets.py
### Did you change the file? If so, how?
no

## Describe the issue
I tried to run this python file to transcribe a simple .wav file but it's just stuck and not finishing or reporting any error message.  does this code still work with google cloud service?

**Comment by nnegrey** [comment]
Hi, which method inside that file are you calling?

**Comment by ningwudm00** [comment]
thanks a lot for the reply!  i figured out it was a network issue.
