### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Joooshua** [GoogleCloudPlatform/python-docs-samples#2305]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/vision/cloud-client/detect/detect.py

### Did you change the file? If so, how?

I only use the defined function 'label_detection' in this py file to realize label detection for several images in my folder

## Describe the issue
It shows:

PermissionError: [Errno 13] Permission denied: <DIRECTORY>

I think this issue may be related to authorization of Google API?

I have already authorized the credential

`from google.cloud import vision
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="MyFirstProject-af21618a29c3.json"`

But I still how to solve this problem. First time using google vision API :(

**Comment by nnegrey** [comment]
Do you call `export GOOGLE_APPLICATION_CREDENTIALS=".....:"` on the command line?
