### ISSUE TITLE
Talent solution documentation examples missing required packages

### ISSUE THREAD

**Issue by RandomAnomaly** [GoogleCloudPlatform/python-docs-samples#2307]
## In which file did you encounter the issue?

https://cloud.google.com/talent-solution/job-search/docs/libraries

### Did you change the file? If so, how?

N/A

## Describe the issue

I found the instructions on the above page a little unclear. They mention that pip package `google-api-python-client` is required, but running the examples throws a `not found` error on the `google.cloud` line. Suggest noting that pip package `google-talent-solution` is required.

**Comment by nnegrey** [comment]
Seems like this got fixed. 
I see `pip install --upgrade google-cloud-talent` on that page now.
