### ISSUE TITLE
Is the Google documentation on the Signed URLs page contradictory?

### ISSUE THREAD

**Issue by TanGolf** [GoogleCloudPlatform/python-docs-samples#2308]
On the Signed URLs page (https://cloud.google.com/storage/docs/access-control/signed-urls) it states that the Python Storage Client library does not support V4 signed URLs, however there is a link on the page to a Python example which does use generate_signed_url with version v4 (https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers#storage-signed-url-get-object-python).

Then on another page the example given is given to sign URL's manually. This is a tad confusing. Is there a contradiction in the documentation?

**Comment by leahecole** [comment]
Closing this - the docs have been updated to include v4 signing, which appears to be in Beta right now : )
