### ISSUE TITLE
explicit credentials not detected for storage client?

### ISSUE THREAD

**Issue by jspeis** [GoogleCloudPlatform/python-docs-samples#2314]
## In which file did you encounter the issue?

* google/cloud/storage/client.py
* google/auth/_default.py

## Describe the issue

I am trying to avoid using the `GOOGLE_APPLICATION_CREDENTIALS` to interact with the GCS client because in my application I need to use multiple credentials. So I tried the following as an example:

```python
from google.cloud import storage
from google.oauth2 import service_account
fp = '/path/to/credentials.json'
credentials = service_account.Credentials.from_service_account_file(fp)
client = storage.Client(credentials=credentials)
```

Running this code hits an exception on line 317 in `google/auth/_default.py`

```
DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

(If I set `GOOGLE_APPLICATION_CREDENTIALS` to `/path/to/credentials.json` , the client works as expected so the credential file seems OK, but again would like to utilize multiple credentials within same app)

How can I create the storage client without using the environment variable?

**Comment by jspeis** [comment]
Fixed by using `storage.Client.from_service_account_json(self.credentials_path)`

**Comment by nozimica** [comment]
I've got the same problem.

In order to  use the `credentials` object when using `storage.Client` constructor, what worked for me was setting explicitly the project name:

```
from google.cloud import storage
from google.oauth2 import service_account
fp = '/path/to/credentials.json'
credentials = service_account.Credentials.from_service_account_file(fp)
client = storage.Client(credentials=credentials, project=credentials.project_id)
```
