### ISSUE TITLE
pubsub: incorrect region tag in async sample

### ISSUE THREAD

**Issue by hongalex** [GoogleCloudPlatform/python-docs-samples#2330]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/18f766ab2e84ea106c2fbedec2382f2061204934/pubsub/cloud-client/subscriber.py#L198-L200

This sample uses a region tag that says `pubsub_subscriber_sync_pull_custom_attributes`, but in reality, the messages are being received asynchronously using [`subscriber.subscribe`](https://googleapis.github.io/google-cloud-python/latest/pubsub/subscriber/index.html#pulling-a-subscription-asynchronously). We need to update the region tag and referencing docs.

There's a similar issues with the [Ruby samples](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/ae4a6765fd481515e1dea24b642afe1d7ee40f72/pubsub/subscriptions.rb#L137-L159)

**Comment by anguillanneuf** [comment]
@hongalex Shall we standardize the region tag for all languages as `pubsub_subscriber_async_pull_custom_attributes`?

**Comment by hongalex** [comment]
Sounds good to me. Can you update the tracker? Thanks!

**Comment by anguillanneuf** [comment]
Sure! Just need to make sure we don't delete these tags until changes are published.
