### ISSUE TITLE
Security flaw: Cloud Endpoint - API Key authentication works even with incorrect API keys

### ISSUE THREAD

**Issue by rafiqhasan** [GoogleCloudPlatform/python-docs-samples#2342]
Example referred: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/endpoints/getting-started

Did you change the file? If so, how? - No changes were done

While referring to the Cloud Endpoint tutorial at https://cloud.google.com/endpoints/docs/openapi/get-started-app-engine , the API was successfully enabled to accept API key in the URL but works even with incorrect API key. 

Please see below **different runs** for the API after enabling Cloud Endpoint:

1. https://example-project-12345.appspot.com/echo  --> **Gives missing key error as expected**
2. https://example-project-12345.appspot.com/echo?key=< correct key > **Gives echo response as expected**
3. https://example-project-12345.appspot.com/echo?key=1 **Gives echo response - Unexpected**

After doing complete analysis I found that the issue was because two services were not enabled in the GCP project:

servicecontrol.googleapis.com | Service Control API
endpoints.googleapis.com | Google Cloud Endpoints

However then in this case the API should not be functional at all rather than working partially with even incorrect API keys. 

Also none of the calls to the API were being logged in the Cloud Endpoint until the 2 required APIs were enabled, **this is a security flaw in the Cloud endpoint system**.

**Comment by gguuss** [comment]
@jeffmendoza @DanSanche /FYI

**Comment by DanSanche** [comment]
It seems like this is product feedback, not related to the code samples. I'll open an internal bug to make sure this is seen by the Endpoints team. Thanks for the report!

**Comment by qiwzhang** [comment]
It was fixed by https://github.com/cloudendpoints/esp/pull/779
