### ISSUE TITLE
How to set the language

### ISSUE THREAD

**Issue by jbrepogmailcom** [GoogleCloudPlatform/python-docs-samples#2348]
## In which file did you encounter the issue?

transcribe_streaming_indefinite.py

### Did you change the file? If so, how?

No

## Describe the issue

The script transcribes in other language. How do I set up the language in which the script understands?

**Comment by nnegrey** [comment]
You'll have to modify this line with your preferred language: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_indefinite.py#L197

Available Language Codes: https://cloud.google.com/speech-to-text/docs/languages

**Comment by jbrepogmailcom** [comment]
Thank you. I also had crashes with displaying non-ASCII characters but I fixed that by export PYTHONIOENCODING=utf8
