### ISSUE TITLE
Mistake in firestore numeric increment example for python

### ISSUE THREAD

**Issue by fronbasal** [GoogleCloudPlatform/python-docs-samples#2374]
## In which file did you encounter the issue?

´python-docs-samples/firestore/cloud-client/snippets.py

### Did you change the file? If so, how?

[Line 884](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/0ce1495b41b25fb7f8c02511aca3c7cb392da4f5/firestore/cloud-client/snippets.py#L884):
```diff
-washington_ref.update("population", firestore.Increment(50))
+washington_ref.update({"population": firestore.Increment(50)})
```
(the update parameters need to be passed as a dict)

## Describe the issue

The original command raises an exception.

**Comment by BenWhitehead** [comment]
Thanks for the heads up on this sample, I've posted a PR with the fix.

**Comment by fronbasal** [comment]
Awesome. Thank you!

**Comment by fronbasal** [comment]
I think we can close this issue now. Thanks to @BenWhitehead for writing the PR.
