### ISSUE TITLE
Monitoring v3 custom_metrics timeout

### ISSUE THREAD

**Issue by sharbison3** [GoogleCloudPlatform/python-docs-samples#238]
The first call to write a data point in a new metric takes some time. When I ran the sample on my personal account, the read-time-series call timed out with an error ("no metric with that name" I think). The work-around is to run the sample program again, but better would be for the program to automatically retry the read-time-series method a few times if it fails.

**Comment by waprin** [comment]
Ok, the tradeoff is the code gets a little less readable but you're right, I'll do this.

**Comment by jonparrott** [comment]
@waprin Is this still an issue?

**Comment by waprin** [comment]
Think given we are switching to new client libraries anyway it's not worth fixing, especially since adding retry logic to samples is already debatable.
