### ISSUE TITLE
Missing CI/CD and tests for contributed code in AutoML/census_income_prediction

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/python-docs-samples#2380]
It looks like someone is circumventing our style checks and avoiding contributing tests by putting code in Jupyter notebooks.

[See this PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2338) for additional details regarding the missing tests for AutoML/census_income_prediction.  For all functions within the code, there should be an accompanying test and the contributed Python should meet the style standards for our repo.  

There are definitely errors in the code that would be caught by lint, for example, most of the code uses 2 spaces where there should be 4 for indentations. Another example, on lines 288-289, it looks like the import order is wrong. There are probably a lot more but it's difficult to tell with the code obfuscated within Jupyter markdown.

**Comment by andrewferlitsch** [comment]
@sirtorry Can you take a look at this issue.

**Comment by sirtorry** [comment]
Working on it this week.

**Comment by andrewferlitsch** [comment]
@sirtorry Any update on the issue?

**Comment by czahedi** [comment]
Hi Torry, gentle reminder ping about this issue. Thanks!

**Comment by sirtorry** [comment]
This quarter, we'll be introducing a notebook creation process that will address testing. At which point, we'll resolve this issue.
