### ISSUE TITLE
Missing CI/CD and tests for contributed code in AutoML/notebooks/retail_product_stockout_prediction

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/python-docs-samples#2381]
It appears that someone is circumventing lint and avoiding contributing tests by contributing code in Jupyter notebooks.

See [this PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2340/files) for examples where the code probably would not pass lint. For example, on lines 278+ the indention is 2 spaces when it should be 4. Import order on lines 345+ looks incorrect as well.

That said, it's difficult to evaluate because the code is obfuscated within the Jupyter notebook markdown.

**Comment by andrewferlitsch** [comment]
@sirtorry Any update

**Comment by sirtorry** [comment]
Working on it this week.

**Comment by andrewferlitsch** [comment]
@sirtorry Any update on this issue?

**Comment by czahedi** [comment]
Hi Torry, gentle reminder ping about this issue. Thanks!

**Comment by sirtorry** [comment]
This quarter, we'll be introducing a notebook creation process that will address testing. At which point, we'll resolve this issue.
