### ISSUE TITLE
quickstart.py is missing imports in Cloud Shell

### ISSUE THREAD

**Issue by chrisvensand** [GoogleCloudPlatform/python-docs-samples#2382]
## In which file did you encounter the issue?

/pubsub/cloud-client/quickstart.py

### Did you change the file? If so, how?

N/A

## Describe the issue

When running ($python quickstart.py) in cloud shell I receive this error.

Traceback (most recent call last):
  File "quickstart.py", line 108, in <module>
    args.num_msgs)
  File "quickstart.py", line 25, in end_to_end
    from google.cloud import pubsub_v1
ImportError: cannot import name pubsub_v1

Should this script should run correctly in Cloud Shell without any additional changes?

**Comment by nnegrey** [comment]
Did you install the client library?
```
pip3 install google-cloud-pubsub
```
