### ISSUE TITLE
how to access streaming recognize using while loop

### ISSUE THREAD

**Issue by ningwudm00** [GoogleCloudPlatform/python-docs-samples#2405]
## In which file did you encounter the issue?
used google example on how to transcribe streaming audio

## Describe the issue
Need help on how to access stream recognize results in while loop.  the code below works fine:

responses = client.streaming_recognize(streaming_config, requests)
for response in responses:
result = response.results[0]

but when i try to access the same data using while loop, it shows "'_StreamingResponseIterator' object is not subscriptable".  can someone help me how to resolve this issue?  I need to use while loop to show GUI update.  Thanks a lot!

rr=0
while True: 
response=responses[rr] 
result = response.results[0]
rr+=1

**Comment by nnegrey** [comment]
Have you seen these samples?

1. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_indefinite.py

2. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_infinite.py

**Comment by ningwudm00** [comment]
Thanks!  The issue is resolved.
