### ISSUE TITLE
pyaudio import crashes when running in cloud shell

### ISSUE THREAD

**Issue by dymxcontender** [GoogleCloudPlatform/python-docs-samples#2406]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_mic.py

## Describe the issue
    src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory

Getting the above error when running the command
**pip install pyaudio**

should run
**sudo apt install portaudio19-dev**
https://techoverflow.net/2019/08/05/how-to-fix-pyaudio-fatal-error-portaudio-h-no-such-file-or-directory/

**Comment by nnegrey** [comment]
Streaming from a microphone on cloud shell won't work as cloud shell doesn't have access to your local microphone.
