### ISSUE TITLE
Can we identify the font size or font type while detecting text from images? 

### ISSUE THREAD

**Issue by Sagartheocean** [GoogleCloudPlatform/python-docs-samples#2409]
Hi,

I am not sure this issue would be addressed here or not, pardon me if it is not the right place. I am posting it here because I didn't get any other way to reach out to google cloud vision api people.

Case:
We want to extract the text out of images. These images contains details about product like product name, tagline, features, benefits, price etc. We need to extract those details and then tag with the correct type. For example: Need to identify out of all text what is the product name, what is the tagline etc.

I am able to extract the text using vision api ocr. However, I am not able to get what should I do in order to tag it with the correct type.

Does anyone have any idea how should I approach this problem?

I was thinking if I get the font size, it would be of great help at least to start with. Because product name always would be with highest font size in the image.

Thank you for your help in advance.

**Comment by gguuss** [comment]
I'm not sure the [TextAnnotation / Paragraph](https://cloud.google.com/vision/docs/reference/rest/v1/AnnotateImageResponse#Paragraph) includes font information; however, there is a bounding box around text bodies such as words, paragraphs, and so forth that you could potentially use to find the larger relative text in annotations. I'll mark this as a feature request.

**Comment by gguuss** [comment]
@Sagartheocean if you have example images (without any personal data) it could be helpful in explaining the feature request. I'll close this issue for now as the product team is aware of the request and there's no further action we can take here on GH.
