### ISSUE TITLE
Cloud SQL Missing tests

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/python-docs-samples#2416]
The following samples do not have accompanying tests:

- [Cloud SQL MySQL](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/cloud-sql/mysql/sqlalchemy)
- [Cloud SQL Postgres](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/cloud-sql/postgres/sqlalchemy)

**Comment by andrewferlitsch** [comment]
@kurtisvg PTAL

**Comment by shubha-rajan** [comment]
I'm currently working on plan for end to end testing for Cloud SQL samples across language repos.  These samples will probably be the first ones where that's implemented.

**Comment by kurtisvg** [comment]
Fixed in #4977
