### ISSUE TITLE
Speech infinite vs indefinite streaming - doc request

### ISSUE THREAD

**Issue by bbookman** [GoogleCloudPlatform/python-docs-samples#2435]
It would be crazy helpful to know the purpose of each of these two.  What, exactly, is the difference between **indefinite** and **infinite**.  I'm asking for simple English such that the user does not have to dig through the code to understand

python-docs-samples/speech/microphone/

- transcribe_streaming_indefinite.py	
- transcribe_streaming_infinite.py

**Comment by bbookman** [comment]
I did notice this **comment**.  I'm not sure exactly how this is better or worse or the use case.  

> adding infinite streaming sample to samples folder, unlike indefinite streaming, this sample uses result_end_time to calculate unfinalized audio, and to resend it to maintain context across into the next streaming request

Also, I think this rises above the need for a comment.  There is a clear need for readme.md update or other method of more formal documentation and clarification

**Comment by bbookman** [comment]
I'm now wondering about transcribe_streaming_mic.py as well.  I'd like to see documentation on the use case for each of these.

**Comment by nnegrey** [comment]
Docs links:

`transcribe_streaming_infinite.py`: https://cloud.google.com/speech-to-text/docs/endless-streaming-tutorial

`transcribe_streaming_mic.py`: https://cloud.google.com/speech-to-text/docs/streaming-recognize#speech-streaming-mic-recognize-python

Will delete transcribe_streaming_indefinite.py as that is not hosted on our docs site.

**Comment by nnegrey** [comment]
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2628
