### ISSUE TITLE
Functions/cloudsql tests failing

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/python-docs-samples#2441]
The tests in `functions/sql` are failing. I took a brief look at them but I'm not seeing a quick resolution.  Anecdotally, the tests succeed when I run them locally with Postgres / MySQL configured using the parameters in `/testing`.

To try getting the tests working locally for later on looking at the configuration in cloud, run:

```bash
pip install nox-automation
nox -s "py36(sample='./functions/sql')"
```

**Comment by leahecole** [comment]
I'm going to close this because the tests have been running green in fusion for the past week after being red for a long time. @gguuss or @ace-n if you're still seeing this issue, please feel free to reopen!
