### ISSUE TITLE
Firestore test, test_listen_document, freezes and crashes CI

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/python-docs-samples#2442]
Running [the code on our automation is failing](https://travis-ci.org/GoogleCloudPlatform/python-docs-samples/builds/593780642), maybe the test is forking a process that never terminates?

This issue is to track and resolve this stuck test.

**Comment by gguuss** [comment]
It actually looks like the `test_listen_*` tests may be failing?

**Comment by BenWhitehead** [comment]
This is caused by googleapis/google-cloud-python#9008 which has a merged fix in googleapis/google-cloud-python#9337. We're just waiting on a new release of google-cloud-core with the fix.

**Comment by BenWhitehead** [comment]
Related PR blocked by this same issue: #2427

**Comment by BenWhitehead** [comment]
My PR #2427 is now passing CI. @gguuss I've triggered a new build for the link you provided. If it's green, I'll close this issue.

**Comment by BenWhitehead** [comment]
When I tried to re-run the build it failed because the PR had already been merged.

@gguuss Is it okay to close this now that the listen tests are working again?

**Comment by gguuss** [comment]
Yes, go ahead and close, I have verified this is passing now.
