### ISSUE TITLE
Prefer client library over using shell commands

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/python-docs-samples#2444]
[This sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dataflow/run_template/main_test.py) has been having issues in CI/CD because it is shelling out to a subprocess that may or may not be properly configured.

I have patched the test for now to configure the shell but this is just a short-term solution.

Please replace the `sp` calls with client library calls to avoid regressions in the future.

**Comment by davidcavazos** [comment]
Addressed in #2450
