### ISSUE TITLE
The problem of Adding Firebase to GCP project

### ISSUE THREAD

**Issue by JiyangZhang** [GoogleCloudPlatform/python-docs-samples#2447]
## In which file did you encounter the issue?

[/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python37/building-an-app/building-an-app-3/templates/index.html](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python37/building-an-app/building-an-app-3/templates/index.html)
### Did you change the file? If so, how?

This solution will work:
1. Paste the initialization snippet in the <head> part of html page before the alert.
2. Change the version of firebase ui to 4.2.0: 
`<script src="https://cdn.firebase.com/libs/firebaseui/4.2.0/firebaseui.js"></script>`
 `<link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/4.2.0/firebaseui.css">`
3. add this line at the <head>: 
  `<script src="https://www.gstatic.com/firebasejs/6.2.4/firebase-auth.js"></script>`
AND PROBLEM SOLVED.
The problem is the version in the example code is too old.

## Describe the issue

When I wanna to add firebase to my web app, the webpage cannot have the index page showing the icon according to the tutorial: [Adding Firebase to your GCP project](https://cloud.google.com/appengine/docs/standard/python3/building-app/adding-firebase)

**Comment by leahecole** [comment]
Hi @JiyangZhang - thanks for opening up this issue! Feel free to submit a PR for this - I'll make sure to add it to the backlog anyways, but PRs are always welcome :)

**Comment by andrewferlitsch** [comment]
@leahecole can this issue be closed?

**Comment by tbpg** [comment]
Thank you for the report! Looks like this was fixed in #2796.
