### ISSUE TITLE
many identical redundant lines 

### ISSUE THREAD

**Issue by abdvlz** [GoogleCloudPlatform/python-docs-samples#2458]
<img width="569" alt="Screen Shot 2019-10-09 at 12 34 10 AM" src="https://user-images.githubusercontent.com/48181597/66435168-e3a1c080-ea2c-11e9-97b7-f5c07c681315.png">

how can i fix that?

**Comment by nnegrey** [comment]
Can you provide more info on what sample this is?

**Comment by abdvlz** [comment]
#this code implementation was provided by google cloud speech-to-text:
#https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_infinite.py

import time
import re
import sys
# uses result_end_time currently only avaialble in v1p1beta, will be in v1 soon
from google.cloud import speech_v1p1beta1 as speech
import pyaudio
from six.moves import queue

# Audio recording parameters


STREAMING_LIMIT = 10000
SAMPLE_RATE = 16000
CHUNK_SIZE = int(SAMPLE_RATE / 10)  # 100ms


class Transcriber(object):
    """Opens a recording stream as a generator yielding the audio chunks."""

    def __init__(self, rate, chunk_size):
        self._rate = rate
        self.chunk_size = chunk_size
        self._num_channels = 1
        self._buff = queue.Queue()
        self.closed = True
        self.restart_counter = 0
        self.audio_input = []
        self.last_audio_input = []
        self.result_end_time = 0
        self.is_final_end_time = 0
        self.final_request_end_time = 0
        self.bridging_offset = 0
        self.last_transcript_was_final = False
        self.new_stream = True
        self._audio_interface = pyaudio.PyAudio()
        self._audio_stream = self._audio_interface.open(
            format=pyaudio.paInt16,
            channels=self._num_channels,
            rate=self._rate,
            input=True,
            frames_per_buffer=self.chunk_size,
            # Run the audio stream asynchronously to fill the buffer object.
            # This is necessary so that the input device's buffer doesn't
            # overflow while the calling thread makes network requests, etc.
            stream_callback=self._fill_buffer,
        )

    def __enter__(self):

        self.closed = False
        return self

    def __exit__(self, type, value, traceback):

        self._audio_stream.stop_stream()
        self._audio_stream.close()
        self.closed = True
        # Signal the generator to terminate so that the client's
        # streaming_recognize method will not block the process termination.
        self._buff.put(None)
        self._audio_interface.terminate()

    def _fill_buffer(self, in_data, *args, **kwargs):

        self._buff.put(in_data)
        return None, pyaudio.paContinue

    def generator(self):

        while not self.closed:
            data = []

            if self.new_stream and self.last_audio_input:

                chunk_time = STREAMING_LIMIT / len(self.last_audio_input)

                if chunk_time != 0:

                    if self.bridging_offset < 0:
                        self.bridging_offset = 0

                    if self.bridging_offset > self.final_request_end_time:
                        self.bridging_offset = self.final_request_end_time

                    chunks_from_ms = round((self.final_request_end_time -
                                            self.bridging_offset) / chunk_time)

                    self.bridging_offset = (round((
                        len(self.last_audio_input) - chunks_from_ms)
                                                  * chunk_time))

                    for i in range(chunks_from_ms, len(self.last_audio_input)):
                        data.append(self.last_audio_input[i])

                self.new_stream = False

            # Use a blocking get() to ensure there's at least one chunk of
            # data, and stop iteration if the chunk is None, indicating the
            # end of the audio stream.
            chunk = self._buff.get()
            self.audio_input.append(chunk)

            if chunk is None:
                return
            data.append(chunk)
            # Now consume whatever other data's still buffered.
            while True:
                try:
                    chunk = self._buff.get(block=False)

                    if chunk is None:
                        return
                    data.append(chunk)
                    self.audio_input.append(chunk)

                except queue.Empty:
                    break

            yield b''.join(data)

    @staticmethod
    def listen_print_loop(responses, stream):

        num_chars_printed = 0
        for response in responses:
            if not response.results:
                continue

            # The `results` list is consecutive. For streaming, we only care about
            # the first result being considered, since once it's `is_final`, it
            # moves on to considering the next utterance.
            result = response.results[0]
            if not result.alternatives:
                continue

            # Display the transcription of the top alternative.
            transcript = result.alternatives[-1].transcript

            # Display interim results, but with a carriage return at the end of the
            # line, so subsequent lines will overwrite them.
            #
            # If the previous result was longer than this one, we need to print
            # some extra spaces to overwrite the previous result
            overwrite_chars = ' ' * (num_chars_printed - len(transcript))

            if not result.is_final:
                sys.stdout.write(transcript + overwrite_chars + '\r')
                sys.stdout.flush()

                num_chars_printed = len(transcript)

            else:
                print(transcript + overwrite_chars)

                # Exit recognition if any of the transcribed phrases could be
                # one of our keywords.
                if re.search(r'\b(exit|quit)\b', transcript, re.I):
                    print('Exiting..')
                    break

                num_chars_printed = 0

    @staticmethod
    def transcribe():

        client = speech.SpeechClient.from_service_account_json('/Users/abdulrahman/Desktop/gradproj/service_account.json')
        config = speech.types.RecognitionConfig(
            encoding=speech.enums.RecognitionConfig.AudioEncoding.LINEAR16,
            sample_rate_hertz=SAMPLE_RATE,
            language_code='ar-SA',
            max_alternatives=1)
        streaming_config = speech.types.StreamingRecognitionConfig(
            config=config,
            interim_results=False)

        mic_manager = Transcriber(SAMPLE_RATE, CHUNK_SIZE)

        with mic_manager as stream:

            while not stream.closed:

                stream.audio_input = []
                audio_generator = stream.generator()

                requests = (speech.types.StreamingRecognizeRequest(
                    audio_content=content)for content in audio_generator)

                responses = client.streaming_recognize(streaming_config,
                                                       requests)

                # Now, put the transcription responses to use.
                Transcriber.listen_print_loop(responses, stream)

                if stream.result_end_time > 0:
                    stream.final_request_end_time = stream.is_final_end_time
                stream.result_end_time = 0
                stream.last_audio_input = []
                stream.last_audio_input = stream.audio_input
                stream.audio_input = []
                stream.restart_counter = stream.restart_counter + 1

                if not stream.last_transcript_was_final:
                    sys.stdout.write('\n')
                stream.new_stream = True


if __name__ == '__main__':
    Transcriber.transcribe()

**Comment by nnegrey** [comment]
It looks like you've taken pieces of two different samples that don't work together and combined them.


1. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_indefinite.py
- Has your `listen_print_loop` method

2. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_infinite.py
- Has your `transcribe`, `generator`, and other methods


You've also changed `interim_results` to `False`. 
Try switching that back to `True`
and updating your `listen_print_loop` to the one in the `transcribe_streaming_infinite.py` file

**Comment by abdvlz** [comment]
<img width="568" alt="Screen Shot 2019-10-09 at 1 11 45 AM" src="https://user-images.githubusercontent.com/48181597/66437205-de934000-ea31-11e9-9fce-243d599e31bf.png">


i did your notes but still .. i dont know why it print many identical lines .. btw it only happens when i talk quickly

**Comment by nnegrey** [comment]
Try just directly running this https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_infinite.py sample.

You can export your credentials via:
`export GOOGLE_APPLICATION_CREDENTIALS=/Users/abdulrahman/Desktop/gradproj/service_account.json`

It still looks like you've made some changes from the expected output in the sample.

**Comment by abdvlz** [comment]
<img width="617" alt="Screen Shot 2019-10-09 at 1 22 45 AM" src="https://user-images.githubusercontent.com/48181597/66437902-c02e4400-ea33-11e9-9fee-a6dd9802ca7a.png">


there you go, here is the output of the original code without any modifications except adding my credentials ..

the problem seems to be in the implementation itself.... help.

**Comment by nnegrey** [comment]
Do you have all these libraries?
```
google-cloud-speech==0.36.3
pyaudio==0.2.11
six==1.12.0
```

**Comment by abdvlz** [comment]
yes they're all up to date .

**Comment by abdvlz** [comment]
Yes you're right, i already figured that i can change the interim to false, but it becomes noninteractive, in other words it prints the transcripts line by line rather than word but word, which looks kinda slow to the user. 

Anyway thanks a lot for cooperating.

**Comment by nnegrey** [comment]
Yep and mostly the sample is just meant as a small demo of what you can do, so that you can port it over to your own use case. 
:)
