### ISSUE TITLE
Speech api streaming sample doesn't support python 3

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/python-docs-samples#246]
This is a consequence of the underlying grpc lib not supporting it yet:

https://github.com/grpc/grpc/issues/282

Once grpc supports it, we should un-skip the test in [speech_streaming_test](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/api/speech_streaming_test.py#L56)

**Comment by jonparrott** [comment]
@jerjou grpc should ostensibly support Python 3 now. Can we look into removing our hacks for this?

**Comment by jerjou** [comment]
I believe this was addressed in #462
