### ISSUE TITLE
CI/CD for notebooks missing?

### ISSUE THREAD

**Issue by sirtorry** [GoogleCloudPlatform/python-docs-samples#2461]
Do tutorials in [/notebooks/tutorials](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/notebooks) have tests?

**Comment by sirtorry** [comment]
relevant to #2380 and #2381

**Comment by leahecole** [comment]
Looks like @alixhami wrote some of these initial ones - what's the scoop Alix? Help us solve the mystery!

**Comment by alixhami** [comment]
The notebooks do not have tests right now. I was writing a notebook tester tool that could work as a nox test suite, but there were multiple teams writing such tools so I stopped. I could probably dig it up and try to add it though.

**Comment by sirtorry** [comment]
before you work on it again, such a tool already exist. we'll just have to use it to test the notebooks.

**Comment by andrewferlitsch** [comment]
@sirtorry Any updates?

**Comment by sirtorry** [comment]
This quarter, we'll be introducing a notebook creation process that will address testing. At which point, we'll resolve this issue.

**Comment by busunkim96** [comment]
@sirtorry Friendly ping, are there any plans for this?
