### ISSUE TITLE
Decryption failed: the ciphertext is invalid.

### ISSUE THREAD

**Issue by lobsangTsering** [GoogleCloudPlatform/python-docs-samples#2465]
## In which file did you encounter the issue?
 python-docs-samples/dlp/deid.py deidentify_with_fpe() method.
### Did you change the file? If so, how?
NO change in file only parameters are passed 

I ran above method all parameters are correct but method is is giving back an error log as follow 
## Describe the issue

status = StatusCode.INVALID_ARGUMENT
details = "Received the following error message from Cloud KMS when unwrapping KmsWrappedCryptoKey [keypath] :  Decryption failed: the ciphertext is invalid."

**Comment by amitwats** [comment]
I see the issue closed, whats the resolution?
