### ISSUE TITLE
Callback function not invoked

### ISSUE THREAD

**Issue by Diptiranjan1** [GoogleCloudPlatform/python-docs-samples#2487]
## subscriber.py

python-docs-samples/pubsub/cloud-client/subscriber.py

### Did you change the file? If so, how?

I am trying to pull data from a pubsub topic using the code provided in docs using python.

subscriber.subscribe(subscription_path, callback=callback)

## Describe the issue

The only thing I am providing is projectId and subscription name. Have google authentication done and the code used to work before August 16th,2019. Has there been a depreciation in code? Also I tried printing message when callback is invoked in the above piece of code. But seems like its not printing. No error code is running fine. 

Is there any other way to invoke callback() ?

**Comment by andrewferlitsch** [comment]
@hongalex Any update?

**Comment by hongalex** [comment]
This seems related to #2561. Asking @anguillanneuf to look into this.

**Comment by anguillanneuf** [comment]
👋 @Diptiranjan1 Thanks for your question. I'm using`google-cloud-pubsub==1.0.2`, and the subscriber callback is working for me. A quick test to test if you use the same credentials: can you do a list subscriptions operation to see if your credentials are working?

We are in the progress of revamping our subscriber samples to not use the infinite while loop. This way of resolving the streaming pull future will help catch any exceptions: 

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/980c64ee57c5d5f3f585a2d0b19361dadb7e1df3/pubsub/cloud-client/quickstart/sub.py#L42-L51

**Comment by anguillanneuf** [comment]
@hongalex I don't think the two issues are related.

**Comment by pradn** [comment]
@Diptiranjan1 can you please share a minimal script that replicates the issue you're seeing?

We haven't completely broken the callback mechanism for subscriber according to my testing. Perhaps some of the surrounding logic has an issue or there is an edge-case in the subscriber code.

**Comment by anguillanneuf** [comment]
@Diptiranjan1 Please let us know if you are still experiencing this issue and we can reopen the ticket.
