### ISSUE TITLE
Storage signed URL generator script should allow virtual hosted-style URLs to be constructed

### ISSUE THREAD

**Issue by houglum** [GoogleCloudPlatform/python-docs-samples#2493]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/signed_urls/generate_signed_urls.py

### Did you change the file? If so, how?

See this commit, with a working fix (and also the ability to specify a subresource):
https://github.com/houglum/python-docs-samples/commit/501c64f56d01712df2d0d4293dc513b67b827f65

## Describe the issue

This script only constructs signed URLs in path-style, where the bucket is included in the path of the URL, e.g. storage.googleapis.com/bucket/object.  We should allow users to also construct URLs in virtual hosted-style -- bucket in the host of the URL, e.g. bucket.storage.googleapis.com/object -- as it is slightly more secure (avoids the potential for obscure XSS attacks, etc.).

I wrote up a fix to allow users to supply which style they want to use -- prototype commit is linked above.  I'm not sure if it's in the style we'd like, given that it introduced an enum class, which might appear to be confusing in an individual snippet of code that we use for documentation (see the comments in that file that specify snippets in square brackets).  If anyone has the bandwidth to send a pull request and iterate on my commit above, please do so.

**Comment by frankyn** [comment]
This was resolved a while ago. Closing issue.
