### ISSUE TITLE
problems to do batch predictions follow the docs

### ISSUE THREAD

**Issue by alefhsousa** [GoogleCloudPlatform/python-docs-samples#2500]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/tables/automl/automl_tables_predict.py

### Did you change the file? If so, how?

I fixed the problems using the named paremeters. This PR #2501  close the problem

## Describe the issue

Today when we try to use the function `batch_predict` follow the docs we receive and error saying: `the paramaters should be a pandas.Dataframe` it’s happens because the first parameter of the function `batch_predict` is a pandas.Dataframe. To solve this problem we need to use de named parameters of python.

![image](https://user-images.githubusercontent.com/9020828/67685147-4e328600-f973-11e9-8236-3f01c2a255ad.png)

**Comment by leahecole** [comment]
hi @sirtorry - PTAL - reassign this issue AND the linked PR to a teammate if needed.

**Comment by leahecole** [comment]
Merged #2501 which fixes this
