### ISSUE TITLE
Stop StreamingResponseIterator

### ISSUE THREAD

**Issue by MauroPfister** [GoogleCloudPlatform/python-docs-samples#2509]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/bc1183e2c958a6e00fc3ad05bb74c3d2685cb264/speech/microphone/transcribe_streaming_mic.py#L110-L162

### Did you change the file? If so, how?

No changes

## Describe the issue

It's not really an issue but rather a question of understanding. I was wondering if breaking the loop is the only way to exit the function? If I understand correctly `responses` is a `StreamingResponseIterator`. Does it not raise a `StopIteration` when no next element is available?

Thanks for the help =)

**Comment by nnegrey** [comment]
Yep, it will block until the timeout or the user says `exit`

```
The responses passed is a generator that will block until a response
    is provided by the server.
```
