### ISSUE TITLE
Non ascii problem when listening speech

### ISSUE THREAD

**Issue by jbrepogmailcom** [GoogleCloudPlatform/python-docs-samples#2512]
## In which file did you encounter the issue?

transcribe_streaming_mic.py

### Did you change the file? If so, how?

No

## Describe the issue

When using non-English language the file crashes:

  File "transcribe_streaming_mic.py", line 191, in <module>
    main()
  File "transcribe_streaming_mic.py", line 187, in main
    listen_print_loop(responses)
  File "transcribe_streaming_mic.py", line 148, in listen_print_loop
    sys.stdout.write(transcript + overwrite_chars + '\r')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

**Comment by nnegrey** [comment]
We probably just need to modify the encoding of `sys.stdout`
`sys.stdout.encoding`
As I'm guessing its default is limited.
