### ISSUE TITLE
synthesize_speech timeout error

### ISSUE THREAD

**Issue by davenlin19** [GoogleCloudPlatform/python-docs-samples#2514]
## In which file did you encounter the issue? utils.py

    from google.cloud import texttospeech
    import os
    from api import settings

    def text_to_speech(text, fileName):
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '{0}/my_file.json'.format(settings.BASE_DIR)

        # Instantiates a client
        client = texttospeech.TextToSpeechClient()

        # Set the text input to be synthesized
        synthesis_input = texttospeech.types.SynthesisInput(text=text)

        # Build the voice request, select the language code ("en-US") and the ssml
        # voice gender ("neutral")
        voice = texttospeech.types.VoiceSelectionParams(
        language_code='en-US',
        ssml_gender=texttospeech.enums.SsmlVoiceGender.NEUTRAL)

        # Select the type of audio file you want returned
        audio_config = texttospeech.types.AudioConfig(
            audio_encoding=texttospeech.enums.AudioEncoding.MP3)

        # Perform the text-to-speech request on the text input with the selected
        # voice parameters and audio file type
        response = client.synthesize_speech(synthesis_input, voice, audio_config)

        # The response's audio_content is binary.
        with open('./media/audio/{0}'.format(fileName), 'wb') as out:
            # Write the response to the output file.
            out.write(response.audio_content)
            print('Audio content written to file {0}'.format(fileName))

### Did you change the file? If so, how?

No

## Describe the issue
I have a view in Django to call this function. In localhost everything works as expected.
But in prod, when I used postman to call the Django's view, there's always a timeout error.
After inspected the problem, I see that the function **client.synthesize_speech** didn't return any response.

But if I try: **./manage.py shell**. Then import the text_to_speech function, call it with the same parameter, it works.

Do you have any idea?
Thank you!

**Comment by nnegrey** [comment]
In prod, is your server able to make any other external calls?
