### ISSUE TITLE
Getting partial result in Cloud speech api?

### ISSUE THREAD

**Issue by helloworldkr** [GoogleCloudPlatform/python-docs-samples#2519]
Cloud Speech API takes a lot of time for processing the file, though it gives back the progress percentage, Is there any way to get the partially processed speech that the system has processing before getting the final result ?

**Comment by nnegrey** [comment]
What kind of request are you making?
- Asynchronous
or
- Synchronous
or
- Streaming

Streaming lets you get `interim` results via: https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#streamingrecognitionconfig

**Comment by helloworldkr** [comment]
thanks @nnegrey , was curious if this could be possible with Asynchronous long speech recog

**Comment by nnegrey** [comment]
Ah no, Asynchronous does not support it, only streaming can do that. There are a couple different python samples that have different takes on doing infinite streaming in case you want to look at those and see if they might work for your longer audio files, if you need the interim results.
