### ISSUE TITLE
firestore: `listen_multiple` test is flakey

### ISSUE THREAD

**Issue by BenWhitehead** [GoogleCloudPlatform/python-docs-samples#2529]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets.py#L679

### Did you change the file? If so, how?
no changes

## Describe the issue

The `listen_multiple` firestore sample is flakey, likely due to not waiting appropriately for all of the async events to happen before the assertions.
To fix this flakeyness, someone with good python multithreading knowledge will be needed to add the correct await conditions.

**Comment by andrewferlitsch** [comment]
@BenWhitehead If the test is failing (flaky) in Fusion, shouldn't a bug be opened in buganizer and not here in issues?

**Comment by BenWhitehead** [comment]
@andrewferlitsch The flakiness of this test is due to the current implementation of some async threads and timeouts waiting for various events to happen over the course of the test run. These failures are independent of Fusion and can happen in any environment. A similar issue was present in the java tests that I fixed [here](https://github.com/googleapis/google-cloud-java/pull/5902), however I do not possess the requisite python threading knowledge to be able to fix this on my own and will need help from someone that does.

**Comment by andrewferlitsch** [comment]
@GoogleCloudPlatform/python-samples-owners Is there someone whom can help Ben with how to do this fix in Python?
