### ISSUE TITLE
Google StackDriver correlating logs with parent request python 3

### ISSUE THREAD

**Issue by PCS-Ismail** [GoogleCloudPlatform/python-docs-samples#2531]
## In which file did you encounter the issue?

GoogleCloudPlatform/python-docs-samples/blob/master/run/logging-manual/main.py

### Did you change the file? If so, how?

Nope.

## Describe the issue

In python 2.7, the app engine sdk was doing the work in the background to nest all logs with the parent request to have a correlation in Google StackDriver.

As of the transition to python 3, it is through the usage of google cloud logging or structured logging, and from all the different references I could found, it's important to have the same trace id in the 'sub' logs for stack driver to make a match with the 'request' log.

And still as you can see below, it still appear as different logs.

Got the same result, even when following the example in the documentation: https://cloud.google.com/run/docs/logging#writing_structured_logs

![image](https://user-images.githubusercontent.com/24900319/68902991-bfaa5c80-0707-11ea-988c-1242b47e96cc.png)

SO link: https://stackoverflow.com/questions/58846168/google-stackdriver-correlating-logs-with-parent-request-python-3

**Comment by dinagraves** [comment]
Answer addressed here: https://stackoverflow.com/questions/58846168/google-stackdriver-correlating-logs-with-parent-request-python-3/58868535#58868535

Thank you!
