### ISSUE TITLE
IoT Kokoro tests are failing

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#2544]
Hi Gus, I've been seeing errors for IoT in fusion on and off since 11/12. PTAL to see if we can resolve them, and let me know if there's anything I can do to help!

**Comment by gguuss** [comment]
I'm traveling and have limited access to resources at present.

It'd be helpful if you linked the test fusion logs for the failing tests.

The tests are passing locally for me and there is a single test that can be flaky if the backend infra is cold.

**Comment by gguuss** [comment]
A small investigation into the sponge logs (internal) shows that tests are sometimes passing but other times are flaky.

For example, invocation 39063a87-ca14-4c56-82e9-937705b67f04 is all green.

The test that I'm seeing failing is:


```
assert 'Out of memory' not in 'Created reg...d registry\n'   'Out of memory' is contained here:     Created registry     Created Gateway id: "test-device-RS256"     name: ""     num_id: 2568013289545473     credentials {       public_key {...      ...Full output truncated (71 lines hidden), use '-vv' to show
Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py", line 326, in test_gateway_send_data_for_device
    assert 'Out of memory' not in out  # Indicates could not connect
AssertionError: assert 'Out of memory' not in 'Created reg...d registry\n'
  'Out of memory' is contained here:
    Created registry
    Created Gateway id: "test-device-RS256"
    name: ""
    num_id: 2568013289545473
    credentials {
      public_key {...
  
  ...Full output truncated (71 lines hidden), use '-vv' to show
```

I'm unsure as to why this could happen (wee, it's new) but my first guess is that there's a new race condition in Gateway binding / the backend infra is cold.

**Comment by leahecole** [comment]
Right on. They're passing right now, but if it goes red again, I'll see if I can take a look, or I'll pass the torch to another lucky Googler til you're back :)

**Comment by leahecole** [comment]
I'm going to close the issue for housekeeping because things are alright for now, but with the understanding that I'll reopen if things fail again.
