### ISSUE TITLE
monitoring fusion tests are broken

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#2546]
Can you verify if their failure is related to the failure you talked about at our meeting today?

**Comment by shollyman** [comment]
Have a link to a test?

**Comment by shollyman** [comment]
https://sponge.corp.google.com/target?id=76bf5e01-d3b9-46a9-879d-2fc23c24fc7c&target=cloud-devrel/python-docs-samples/system_tests_monitoring&searchFor=&show=FAILED&sortBy=STATUS would indicate that the tests failed due to transient internal error, not a library issue.

**Comment by leahecole** [comment]
That's the one. Dang. Well, the mystery continues. Thanks for looking at it

**Comment by leahecole** [comment]
they seem to have fixed themselves. 🤞 that it stays!
