### ISSUE TITLE
appgengine fusion tests failing

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#2556]
Hey! It seems like this PR #2428 broke the appengine fusion tests awhile ago - it's having trouble finding that version of pytest for the python 2 tests. Given the sunset of Python 2, do you have opinions on how best to resolve this? Feel free to set up time with me if you want to look at this together.

**Comment by crwilcox** [comment]
Good catch. Digging into this we may need to pin pytest to < 5.0.0dev as at 5.0 they started requiring >= 3.5.
