### ISSUE TITLE
pubsub tests failing in fusion

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#2561]
Hi Alex, it's looking like pubsub tests are failing for the repo in fusion (I'll send you a link) - could you please take a look and see if changes need to be made?

**Comment by andrewferlitsch** [comment]
@hongalex , @leahecole  - if this is a test failing in fusion, then shouldn't the failing be added as bug in buganizer and not here in issues?

**Comment by hongalex** [comment]
This is passing again as of 11/28. Closing.
