### ISSUE TITLE
Run tests on new library versions

### ISSUE THREAD

**Issue by nnegrey** [GoogleCloudPlatform/python-docs-samples#2562]
Although our library versions are pinned in the samples, each time there is a new library version, it'd be good to run the sample tests again to catch breaking changes that cause our samples to be out of date. 
- Potentially first limiting to any minor versions, where a major version change would have an expected breaking change.

**Comment by leahecole** [comment]
@nnegrey just to clarify, this should happen upon release of the new version of the client library, as opposed to happening when we choose to increase the version used in this repo? (otherwise, wouldn't kokoro hypothetically catch this?)

**Comment by nnegrey** [comment]
Yea, so like when a new version gets pushed to PyPi, not when we push a PR to bump the library version.

**Comment by leahecole** [comment]
Right on. @busunkim96 do any other repos you know of do this well/do you know if we have any magic tooling to make this happen? I'm wholly in support of this as a way to make sure our samples are kept up to date.

**Comment by nnegrey** [comment]
I would imagine repos that have samples tied to libraries do, but where python does not, this might be more difficult

**Comment by busunkim96** [comment]
I think this will be handled by renovate bot (pending in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2550)

e.g. if `requirements.txt` has `google-cloud-storage==1.23.0` and renovate bot notices a newer version in PyPI, it will open a PR bumping the version. CI will run against the PR, so we'll notice if there's incompatibilities between the sample and the library.

**Comment by busunkim96** [comment]
Here's an example PR from the client library repo: https://github.com/googleapis/google-cloud-python/pull/9870

**Comment by leahecole** [comment]
@busunkim96 now that renovate bot is in place, can we close this issue?
