### ISSUE TITLE
Run all tests not just a subset

### ISSUE THREAD

**Issue by nnegrey** [GoogleCloudPlatform/python-docs-samples#2563]
I noticed on a few of my PRs, it was only running a subset of the tests and not all of them. 
While I've run them all locally there could be something I have set correctly here but not for everyone else that would be good to catch.

**Comment by leahecole** [comment]
Is this in direct conflict with #2559 ?

**Comment by nnegrey** [comment]
Yes and no, like I want all the test files I change to run. 
Like say it found 47 tests, it runs like 19 of them.

**Comment by leahecole** [comment]
Is "it" in this case travis?

**Comment by nnegrey** [comment]
Yea, so moving to Kokoro might solve this anyway.

**Comment by busunkim96** [comment]
The logic to determine if something's "changed" might be borked then. :thinking: Good to know.

**Comment by nnegrey** [comment]
Maybe?
Like here is the output: `collected 45 items / 26 deselected / 19 selected   `

**Comment by kurtisvg** [comment]
New tests should run py.test in each folder, so this should be covered.
