### ISSUE TITLE
Add a run test flag, to re-run samples.

### ISSUE THREAD

**Issue by nnegrey** [GoogleCloudPlatform/python-docs-samples#2564]
Sometimes there is a problem with the resources used rather than the code itself, rather than making up a change to get tests to run again, adding a run flag would be nice.

**Comment by leahecole** [comment]
I think there is a kokoro force run flag, but I'm not sure if it works as expected yet. @kurtisvg do you know?

**Comment by kurtisvg** [comment]
So for Kokoro tests, you can use `kokoro: run` or `kokoro: force-run` labels. This doesn't apply to Travis though.

**Comment by busunkim96** [comment]
I've seen Ben push empty commits to retrigger CI for Node repositories.
```
git commit --allow-empty -m "trigger ci"
git push
```

I believe if you have write permissions you can also re-run Travis builds using the UI.

**Comment by kurtisvg** [comment]
+1 to using the UI - that's how I typically trigger rebuilds with travis.

**Comment by kurtisvg** [comment]
Marking as fixed - the required tests are now on Kokoro.
