### ISSUE TITLE
Create sample format guidelines for Python-docs-samples

### ISSUE THREAD

**Issue by nnegrey** [GoogleCloudPlatform/python-docs-samples#2565]
The python reviewer group required to approve PRs has only 4 people, be nice to expand that quickly. 
Also probably having a canonical sample in Python that is agreed upon would be nice too! (To protobuf or to dictionary that is the question, I vote protobuf objects)

**Comment by leahecole** [comment]
Agreed re the group. It won't just be the 4 of us forever, but might be through Thanksgiving at least. 

For canonical sample, also agreed! In fact, we actually have had a PR open for awhile regarding this, and it's something that is in the backlog. https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1756

**Comment by nnegrey** [comment]
Yea, wasn't sure if Alix's sample was still the most up to date.

**Comment by andrewferlitsch** [comment]
@nnegrey. This seems to be about internal process (not issue). Can we close this?

**Comment by nnegrey** [comment]
No, I'd prefer this is left open until resolved.

**Comment by kurtisvg** [comment]
Reassigning this to Doug, since he volunteered to write a sample format guide similar to Java's. 

If anyone else is interested in becoming a python-samples-owner, let me know and I'll loop you in on the meeting.

**Comment by andrewferlitsch** [comment]
@dmahugh PTAL

**Comment by leahecole** [comment]
This is still ongoing and being talked about behind the scenes. #2728 is in progress
