### ISSUE TITLE
issue when using global variable in app engine

### ISSUE THREAD

**Issue by researchar** [GoogleCloudPlatform/python-docs-samples#2568]
how to share global variables in multiple instances  in app engine

**Comment by andrewferlitsch** [comment]
@leahecole Does this need to be assigned to someone?

**Comment by kurtisvg** [comment]
@researchar The only way to preserver global state is to use an external datasource. Some good examples with App Engine are [Firestore](https://cloud.google.com/firestore/), [Cloud Memorystore](https://cloud.google.com/memorystore/), or [Cloud SQL](https://cloud.google.com/sql/docs/).
