### ISSUE TITLE
Domain verified but permission denied

### ISSUE THREAD

**Issue by Emixam23** [GoogleCloudPlatform/python-docs-samples#2570]
I have issues regarding Kubernetes deployment. It asks for Configuring Cloud Endpoints and so for this, I need to verify ownership of the domain in order to use a custom domain. (see https://cloud.google.com/endpoints/docs/grpc/configure-endpoints?authuser=1 link I am currently following)

However, now that my domain has been verified (site.com), I am trying to push my security.pb and my app_config.yaml but it says that permission is denied...

*security-service.proto*
```
syntax = "proto3";

package security.service.site.com;

// ...
```

*app_config.yaml*
```
# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: security.service.site.com

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Security gRPC API
apis:
  - name: security.service.site.com.SecurityService
```

> MBP-de-Emixam23:security-service-interface emixam23$ gcloud endpoints services deploy security-service.pb api_config.yaml
>
> ERROR: (gcloud.endpoints.services.deploy) PERMISSION_DENIED: Ownership for domain name ‘security.service.site.com’ on project ‘PROJECT_ID’ cannot be verified.`

**Comment by andrewferlitsch** [comment]
@DanSanche Any update on this issue?

**Comment by DanSanche** [comment]
Based on the error message, it seems like there was an issue with the verification. A couple things to check:
- Are you sure the verification went through?
- Are you sure you're using the same project verified with?
- Have you tried using the OpenAPI option to see if you get the same error that way?

**Comment by andrewferlitsch** [comment]
no response from submitter -- so I will close the bug
