### ISSUE TITLE
appengine django examples don't have ci/cd tests

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#2574]
I was looking at available nox sessions to see how I could verify that an issue related to the appengine django sample, but it seems like there's no nox session because there aren't tests. Is there a reason why we don't have tests that verify at minimum that nothing is broken? If not, pretty please add them.

**Comment by andrewferlitsch** [comment]
@andrewsg PTAL

**Comment by tmatsuo** [comment]
There are two django apps:

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard_python37/django

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/django
