### ISSUE TITLE
Title issue for api_config deployment

### ISSUE THREAD

**Issue by Emixam23** [GoogleCloudPlatform/python-docs-samples#2576]
Hi,

I found a weird issue using your file. When I do

`gcloud endpoints services deploy my-service.pb api_config.yaml`

I have the url `my-service.endpoints.eyesapp.cloud.goog` but `(no-title)` beside, any idea?

**Comment by busunkim96** [comment]
@Emixam23 would you be able to provide a link to the sample/documentation?

**Comment by Emixam23** [comment]
Hey!

It's been already a couple of days so I dropped it, but as far as I remember, it was this one:
https://github.com/GoogleCloudPlatform/golang-samples/tree/master/endpoints/getting-started-grpc

Then I moved into this one (which seems to be really similar)
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/endpoints/getting-started-grpc

Thanks!

**Comment by busunkim96** [comment]
It seems like whatever issue there was has been resolved.

I went through the tutorial up to the `gcloud endpoints services deploy...` and my deployed API was correctly named "Hello gRPC API".

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/getting-started-grpc/api_config.yaml#L34

For details on how to edit `api_config.yaml` see https://cloud.google.com/endpoints/docs/grpc/configure-endpoints
