### ISSUE TITLE
Speech API not detecting punctuation in romanian

### ISSUE THREAD

**Issue by anamariamocanu** [GoogleCloudPlatform/python-docs-samples#2589]
Hello,

I am using the sample_long_running_recognize to get transcripts from mp3 files in Romanian.

Works pretty well, but even though I set "enable_automatic_punctuation": True it still doesn't work?

Any thoughts why?

Thanks!
Ana

**Comment by busunkim96** [comment]
@anamariamocanu Thank you for filing an issue. This issue tracker is primarily focused on keeping sample code up-to-date. It sounds like you may have discovered an issue with the backend API.

Please look through the [Speech-to-Text Public Issue Tracker](https://issuetracker.google.com/savedsearches/559758) and open a new issue if you don't see any pre-existing issues.

Thanks!
