### ISSUE TITLE
Python 2.7 Kokoro run fails for a directory with no Python 2 tests

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/python-docs-samples#2596]
Seen in PR #2554.

[Full log](https://source.cloud.google.com/results/invocations/51486277-77fe-4840-a7f6-0019ab316680/targets)
```
------------------------------------------------------------
- testing run/system-package
------------------------------------------------------------

 Using noxfile from project root. 

Error while collecting sessions.
Sessions not found: py2-2.7

 Testing failed: Nox returned a non-zero exit code. 

cleanup

```

**Comment by leahecole** [comment]
We're going to have similar problems for #2618 now that I've added it to the noxfile config as well

**Comment by busunkim96** [comment]
I made a small tweak to the kokoro config to run `py2` rather than `py2-2.7`, which I think will fix it. [python2.7/common.cfg](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/32403ebc0ed0de07636f73b00134b94c9699cdd5/.kokoro/python2.7/common.cfg#L42)

Closing for now, but please re-open if you see this happening.

**Comment by leahecole** [comment]
This is happening for the things I added in #2618 (run/hellobroken) as well as run/imageprocessing

**Comment by andrewferlitsch** [comment]
@busunkim96 PTAL
