### ISSUE TITLE
AutoML Tables `display_evaluation` function doesn't work properly in regression case

### ISSUE THREAD

**Issue by amygdala** [GoogleCloudPlatform/python-docs-samples#2598]
the automl tables `display_evaluation` function here: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/tables/automl/automl_tables_model.py#L244
does not work properly in at least the regression case, where it's grabbing the first eval in the list, when it should be using the second element.

**Comment by sirtorry** [comment]
@busunkim96 can you transfer this to https://github.com/googleapis/python-automl

**Comment by busunkim96** [comment]
Hmm, I don't think I can move it because it's cross-org. Would you mind re-opening it on python-automl?

**Comment by amygdala** [comment]
Hmm, I thought this was a 'user code' issue — Torry, are you thinking the API should be changed?

**Comment by sirtorry** [comment]
i'm thinking the tables SDK should figure out which eval to return and return that

**Comment by busunkim96** [comment]
Tracked in https://github.com/googleapis/python-automl/issues/15.
