### ISSUE TITLE
IoT: connection drop after around 24 hours

### ISSUE THREAD

**Issue by kilabyte** [GoogleCloudPlatform/python-docs-samples#2603]
Our raspi connection to google iot via mqtt fails to persist past the 24hour mark. I have the JWT refreshing about every 20 mins or so.

Running on a raspi 3 with mqtt and code is identical from the examples posted here just changed my device id and project id and other vars to match my instance.

**Comment by gguuss** [comment]
Thanks for reporting this issue, I'll see if I can figure out what's going on.

**Comment by kilabyte** [comment]
If i use the pubsub client library as also on your documentation this works flawlessly but then i get no information within the IoT console for things like last seen, heartbeat, config sent etc

**Comment by gguuss** [comment]
There are a lot of potential causes for a disconnect. If you go to the console and look up your device are you seeing any error details?

**Comment by kilabyte** [comment]
I get either "The connection was closed or broken by the client" or i get "The authorization token expired" Which either doesnt make sense. The raspi is also hardwired to my router and im refreshing the token every 20 minutes.

**Comment by kilabyte** [comment]
Or if i use the client library instead is there anyway to specify the device id so i can maintain status of each iot device?

**Comment by gguuss** [comment]
I'm trying to reproduce the issue now. There's a chance the device is not correctly refreshing the JWT, but it [looks like to me like it should work](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/mqtt_example/cloudiot_mqtt_example.py#L241-L248) as [the JWT is refreshed in the call to `get_client`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/mqtt_example/cloudiot_mqtt_example.py#L125-L154).

There's a chance on the reconnect we need to call:

```
client.loop_stop()
client.disconnect()
```

But I believe I have tested this before and it worked. If you're doing a lot of calculations between the calls to `mqtt.loop()` the client loses its connection and behavior after that could get inconsistent.

**Comment by kilabyte** [comment]
ok i can update and try that. what is the difference between client.loop(), client.stop_loop() and client.loop_start() ?

**Comment by gguuss** [comment]
`client.loop` is synchronous, `client.loop_stop` / `client.loop_start` are asynchronous helpers that create a background thread. The asynchronous methods run smoother in practice but can be difficult to test.

**Comment by gguuss** [comment]
Of note, adding the disconnect seems to be the right thing to do, I'm working on a PR to set it up.

**Comment by kilabyte** [comment]
ok i'll give that a shot a report back

**Comment by kilabyte** [comment]
Also can evey ioT device use the same public key? Or should each device have a unique one?

**Comment by kilabyte** [comment]
> To cleanly disconnect after this line to avoid the error. 

Ok so i added the disconnect here and i get this just repeating:
`on_disconnect 1: Out of memory.
Connection:  Connection Accepted.
on_disconnect 1: Out of memory.
Connection:  Connection Accepted.`

Im using client.loop_start() every time the loop is entered as i get better performance with the async call. Should i be calling client.loop_stop() somewhere?

**Comment by kilabyte** [comment]
OK i think i figured it out. I kept with the async loop calls. I put a `client.loop_start()` within my `getClient` method right before the return. Then when the JWT refresh is called i call `client.loop_stop`. Once the connection is recreated it starts the loop again since i have it abstracted into a connect method. Im going to run this for a bit and see what i get

**Comment by gguuss** [comment]
Sounds good, @kilabyte - I have created [a new branch where we cleanly disconnect the MQTT sample](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2622).  Feel free to reopen the issue if you're still seeing the client disconnecting or crashing.

**Comment by kilabyte** [comment]
@gguuss can you just explain why you used .loop() and .loop_stop() in the same file?

**Comment by gguuss** [comment]
@kilabyte Which file are you referring to? This should be a bug if it's going on.  In my anecdotal tests, there is no harm in calling loop in the mix with loop_start() and loop_stop() but if you call loop_start without ever calling loop_stop later on, the program will hang. 

If you're referring to the removed lines from `manager_test.py` those were a correction of the issue I'm referring to. In the `cloud_iot_mqtt.py` example I'm using the synchronous / explicit methods because they are easier to debug. To replace them with the loop_start / loop_stop methods would be the first thing I would do in real-world code.

**Comment by kilabyte** [comment]
Gotcha! Thanks for the explanation :) much appreciated. For handling like network offline and disconnects that is where the backoff comes in right? And then any offline message that was "published" is stored locally until the network is back in which case the messages will all dump out? (sorry i know this is off topic to the issue)

**Comment by gguuss** [comment]
@kilabyte Yes, you got it. The back off is to ensure devices behave well under a number of circumstances.  The sample/demo/example code itself does not buffer messages or do anything intelligent in terms of online / offline. There are other solutions built on top of Cloud IoT Core that are more robust.

**Comment by kilabyte** [comment]
do you have links to said examples?

**Comment by gguuss** [comment]
A few come to mind:

- [Mongoose OS](https://mongoose-os.com/)
- [FogLamp](https://dianomic.com/platform/foglamp/)

There's also [the device SDK](https://cloud.google.com/blog/products/iot-devices/introducing-cloud-iot-device-sdk-a-new-way-for-embedded-iot-devices-to-connect-to-google-cloud-iot-core) written in C.

**Comment by kilabyte** [comment]
thank you!
