### ISSUE TITLE
synthesize_text.py --ssml  doesn't interpret ssml 

### ISSUE THREAD

**Issue by xenophod** [GoogleCloudPlatform/python-docs-samples#2630]
## In which file did you encounter the issue?

GoogleCloudPlatform/python-docs-samples/tree/master/texttospeech/cloud-client/synthesize_text.py

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/texttospeech/cloud-client/synthesize_text.py

### Did you change the file? If so, how?

no

## Describe the issue
Example usage:
`    python synthesize_text.py --text "hello"`
`    python synthesize_text.py --ssml "<speak>Hello there.</speak>"`

When using the --ssml flag, it should be interpreting the ssml tags, but when I pass something like 
`"<speak>Hello <break time="5s" /> there.</speak>"`
or
`"<speak>You are <say-as interpret-as=\"ordinal\">10</say-as> in line.</speak>"`

The tags are ignored. The 5 second break doesn't render. When it should say "Tenth" it says "ten",
Is there a better python example for taking ssml inputs and having them appear in the outputs?

I'm getting example ssml tags from here:
https://cloud.google.com/text-to-speech/docs/ssml

**Comment by nnegrey** [comment]
Looks like your ssml strings are invalid. 

For 
`"<speak>Hello <break time="5s" /> there.</speak>"`
You'll need to add a back slash for the quotes around 5s
`"<speak>Hello <break time=\"5s\" /> there.</speak>"`

The 2nd ones is working as expected for me, what library version are you on?

**Comment by xenophod** [comment]
I just tested both (corrected the unescaped quotes for the time break example) and they work correctly now.

C:\BAK>python3 synthesize_text.py --ssml "<speak>Hello <break time=\"5s\" /> there.</speak>"
Audio content written to file "output.mp3"

C:\BAK>python3 synthesize_text.py --ssml "<speak>You are <say-as interpret-as=\"ordinal\">10</say-as> in line.</speak>"
Audio content written to file "output.mp3"


I'm not sure how to see which library version I'm using, but I think everything works now.  I haven't updated or changed anything other than escaping the quotes on this first command.

**Comment by nnegrey** [comment]
Great!

You can check library version via: `pip3 freeze | grep google-cloud-speech`
