### ISSUE TITLE
DB connection URI example for postgres

### ISSUE THREAD

**Issue by ttran** [GoogleCloudPlatform/python-docs-samples#2635]
## In which file did you encounter the issue?

`https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/cloud-sql/mysql/sqlalchemy/main.py#L39`

### Did you change the file? If so, how?

New line:
`postgresqll://<db_user>:<db_pass>@/<db_name>?host=/cloudsql/<cloud_sql_instance_name>`

## Describe the issue

Not sure if it's intentional but wasn't able to connect using unix_socket param; it's just for postgresql (doesn't support unix_socket) but I was able to connect using a different param name instead. Feel free to close this issue if this is intended.

Solution reference:
`https://stackoverflow.com/questions/27037990/connecting-to-postgres-via-database-url-and-unix-socket-in-rails/28125660`

**Comment by kurtisvg** [comment]
Hi @ttran - thanks for opening an issue. The link you've provided to StackOverflow is showing examples using Ruby. 

For Python, there is not a standard way to pass in the unix socket path. It varies on the driver - in our postgres example, we are using `pg8000` which uses `unix_sock`. You can view this example [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/cloud-sql/postgres/sqlalchemy/main.py#L39).
