### ISSUE TITLE
standard python3 building-an-app-3 tutorial missing firebase-auth script

### ISSUE THREAD

**Issue by flynneva** [GoogleCloudPlatform/python-docs-samples#2647]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python37/building-an-app/building-an-app-3/templates/index.html

### Did you change the file? If so, how?
Yes, it was missing this line at line number 21
```html
<script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-auth.js"></script>
```
## Describe the issue

GCloud Auth was non-functional without this fix. Would throw a "firebase.auth undefined" or firebase.auth not a function" error.

**Comment by r0f1** [comment]
I had the same issue. Thank you!

**Comment by andrewsg** [comment]
Fixed in an internal PR, will be published shortly. Thank you!
