### ISSUE TITLE
Remove oauth2client usage

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/python-docs-samples#2648]
oauth2client is deprecated. Samples using oauth2client should be updated to use google-auth instead.

**Comment by andrewferlitsch** [comment]
@busunkim96 PTAL

**Comment by busunkim96** [comment]
This is still relevant, but I haven't been able to prioritize it.

**Comment by grant** [comment]
I believe the usages are all in folder `appengine/standard`, which is likely de-prioritized.

**Comment by busunkim96** [comment]
It looks like there is one remaining usage of this.

[appengine/standard/firebase/firetactoe](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/79ef9242d8dedc5fadbd3b33391294c16a445cd1/appengine/standard/firebase/firetactoe)

Will open a PR shortly to clean this up.
