### ISSUE TITLE
How to set GOOGLE_APPLICATION_CREDENTIALS creations to cloud functions?

### ISSUE THREAD

**Issue by radianceltd** [GoogleCloudPlatform/python-docs-samples#2663]
I have now uploaded the project to cloud functions through gcloud command, but I don't know how to configure GOOGLE_APPLICATION_CREDENTIALS it in cloud functions.

**Comment by leahecole** [comment]
Hi @radianceltd - check out the [Getting Started with Authentication](https://cloud.google.com/docs/authentication/getting-started) for more info on setting the `GOOGLE_APPLICATION_CREDENTIALS` variable and authentication.
