### ISSUE TITLE
Update airflow to 1.10.7 when it's available in composer

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#2666]

**Comment by sschaetz** [comment]
Any idea when it will be available in composer?

**Comment by andrewferlitsch** [comment]
@leahecole PTAL

**Comment by leahecole** [comment]
Going to close this for now, as renovate-bot is paying attention to the Airflow version. Composer offers 1.10.6, and I believe 1.10.7 is on its way (https://groups.google.com/g/cloud-composer-discuss/c/65tvt1OVIIY/m/74djtr1PFAAJ)
