### ISSUE TITLE
Add Cloud Trace demo app to this repo

### ISSUE THREAD

**Issue by ZiweiZhao** [GoogleCloudPlatform/python-docs-samples#2675]
## In which file did you encounter the issue?

GoogleCloudPlatform/python-docs-samples

### Did you change the file? If so, how?

Adding a new directory.

## Describe the issue

Cloud Trace is creating a new demo app as part of the tutorial. We would like to add the code under this repo.

**Comment by gguuss** [comment]
Re-assigning to Leah as I'm less familiar with setting this up.

**Comment by leahecole** [comment]
added w/ #2716
