### ISSUE TITLE
errors in codelabs documentation

### ISSUE THREAD

**Issue by shanexxu** [GoogleCloudPlatform/python-docs-samples#2684]
## In which file did you encounter the issue?

https://codelabs.developers.google.com/codelabs/cloud-functions-python-http/index.html?index=..%2F..index#5

### Did you change the file? If so, how?

right now the document says in step 3
3. The function calls the send_file function with a filename to send (python_powered.jpg) and a mimetype.

However it is calling the flask.send_from_directory function and not the send_file function

**Comment by andrewferlitsch** [comment]
@crwilcox pls tirage

**Comment by ace-n** [comment]
This issue is obsolete - step 3 now uses `send_from_directory`.
