### ISSUE TITLE
Mac setup

### ISSUE THREAD

**Issue by texasmichelle** [GoogleCloudPlatform/python-docs-samples#2693]
## In which file did you encounter the issue?

MAC_SETUP.md

### Did you change the file? If so, how?

No

## Describe the issue

These instructions don't work on Catalina (10.15.2). If someone knows of a workaround, it would be great to add it here. Otherwise, we should add an acknowledgement so that users don't waste their time.

When I try to install pyenv, I get this message:
```
$ brew install pyenv
Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
```

**Comment by kurtisvg** [comment]
@texasmichelle - Looks like might be related to the version of brew that you are using (https://github.com/Homebrew/brew/issues/6557).

Can you try updating brew itself (`brew update`) and trying again?

**Comment by texasmichelle** [comment]
Helpfully, that command is in this file, so I ran it first. I'm using the latest version of homebrew: 2.1.11.

**Comment by kurtisvg** [comment]
Hmm, it looks like the [latest version of brew](https://github.com/Homebrew/brew/releases) is 2.2.2, and 2.1.11 is from August 2019. Support for Catalina was added in 2.1.13. 

My local version says 2.2.2, but I'm not on Catalina yet. I can update and see if I can reproduce.

**Comment by texasmichelle** [comment]
Interesting - this is what I see on Mac v10.15.2:

```
$ brew --version
Homebrew 2.1.11
Homebrew/homebrew-core (git revision dd2f; last commit 2020-01-08)
Homebrew/homebrew-cask (git revision ea81c; last commit 2020-01-08)
```

**Comment by texasmichelle** [comment]
I'll try uninstalling homebrew to see if I can get to v2.2.2.

**Comment by texasmichelle** [comment]
That worked, so now I'm on homebrew 2.2.2. Not sure why `brew update` didn't get me there, but if I can follow the rest of the instructions without issues, I'll add a note in the readme about uninstalling and reinstalling homebrew.

**Comment by texasmichelle** [comment]
This time, I didn't get any warnings about Catalina being unsupported when installing pyenv, but I still can't install any versions of python.

```
$ brew --version
Homebrew 2.2.2
Homebrew/homebrew-core (git revision dd2f; last commit 2020-01-08)
$ pyenv install 2.7.17
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-2.7.17.tar.xz...
-> https://www.python.org/ftp/python/2.7.17/Python-2.7.17.tar.xz
Installing Python-2.7.17...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 10.15.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/sh/dlw4l1p57d11l51pc4674z0r00h79z/T/python-build.20200108113039.43913
Results logged to /var/folders/sh/dlw4l1p57d11l51pc4674z0r00h79z/T/python-build.20200108113039.43913.log

Last 10 log lines:
checking size of long long... 0
checking for long double support... yes
checking size of long double... 0
checking for _Bool support... yes
checking size of _Bool... 0
checking for uintptr_t... yes
checking size of uintptr_t... configure: error: in `/var/folders/sh/dlw4l1p57d11l51pc4674z0r00h79z/T/python-build.20200108113039.43913/Python-2.7.17':
configure: error: cannot compute sizeof (uintptr_t)
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
$
$ pyenv install 3.7.6
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.6.tar.xz...
-> https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tar.xz
Installing Python-3.7.6...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 10.15.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/sh/dlw4l1p57d11l51pc4674z0r00h79z/T/python-build.20200108113546.47662
Results logged to /var/folders/sh/dlw4l1p57d11l51pc4674z0r00h79z/T/python-build.20200108113546.47662.log

Last 10 log lines:
Parser/tokenizer.c:214:22: warning: this function declaration is not a prototype [-Wstrict-prototypes]
            buf[i] = tolower(c);
                     ^
./Include/pyport.h:591:29: note: expanded from macro 'tolower'
#define tolower(c) towlower(btowc(c))
                            ^
make: *** [Parser/acceler.o] Error 1
make: *** [Parser/listnode.o] Error 1
221 warnings and 11 errors generated.
make: *** [Parser/tokenizer.o] Error 1
$
```

**Comment by kurtisvg** [comment]
I had to fiddle with my Xcode version, but now I'm able to install successfully: 
```
$ pyenv install 2.7.17
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-2.7.17.tar.xz...
-> https://www.python.org/ftp/python/2.7.17/Python-2.7.17.tar.xz
Installing Python-2.7.17...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-2.7.17 to /Users/kvg/.pyenv/versions/2.7.17
```

**Comment by kurtisvg** [comment]
Under pyenv's [Common Build Problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems), there is a section for MacOS that suggests the following:
```
brew install readline xz
```
and another section that suggests the following:
```
xcode-select --install
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```
Maybe one of those will help?

**Comment by texasmichelle** [comment]
OK, I figured out the issue. I had an experimental Swift toolchain in my path, which was interfering with Xcode command-line tools. Pyenv installation is now working 🎉 

Thanks for pointing me in the right direction! I'll create a PR about removing and reinstalling Homebrew for versions <  2.1.13.
