### ISSUE TITLE
Issue in vision api document text detection example

### ISSUE THREAD

**Issue by mfarberbrodsky** [GoogleCloudPlatform/python-docs-samples#2702]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/vision/cloud-client/document_text/doctext.py

### Did you change the file? If so, how?
No.

## Describe the issue
Here are lines 88, 89 of this file:
```python
        if (feature == FeatureType.PAGE):
            bounds.append(block.bounding_box)
```
Here, in case the feature requested is the page - the block's bounding box is added, instead of the page's. This needs to be changed to page.bounding_box.

**Comment by nnegrey** [comment]
@busunkim96, has a fix in this PR https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2705. 

Page doesn't actually have a `bounding_box` field, so we'll remove that from the tutorial. 
https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.Page
