### ISSUE TITLE
confused with py following this tutorial triggering-with-gcf

### ISSUE THREAD

**Issue by Arconapalus** [GoogleCloudPlatform/python-docs-samples#2712]
## In which file did you encounter the issue?
encountering authentication client ID and granting blob permission to Cloud Function 

https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf

### Did you change the file? If so, how?
I'm a bit confused as to where I should put the findclientid.py 

Would be help to know where to put this, either in the Cloud function of main.py or in cloud storage 

## Describe the issue
I'm following this tutorial https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf 
to trigger a dag to composer, I have not been able to get pass the permission side of Cloud Function to invoke the trigger of dag to airflow 

RefreshError: ('invalid_scope: Invalid oauth scope or ID token audience provided.', '{"error":"invalid_scope","error_description":"Invalid oauth scope or ID token audience provided."}')

 TransportError: Error calling the IAM signBytes API: b'{\n "error": {\n "code": 403,\n "message": "Permission iam.serviceAccounts.signBlob is required to perform this operation on service account projects

**Comment by Arconapalus** [comment]
Upon further investigation, this was a python script to be executed in gcloud sdk and/or cloud shell to pull the data. Could someone add this (execute as script) in the doc or is it trivial?

**Comment by leahecole** [comment]
Hi! I am submitting that change now. I am sorry for that confusion - you're right - there isn't language there to indicate that's what you're supposed to do with the script, and I can see how that would be confusing! I'm glad you were able to figure it out, and I'm glad that with this issue, we'll be able to improve the experience for future users. Thank you for opening the issue in the first place and for commenting with the update! I will formally close this when the change is published the website - sometime in the next few days.
