### ISSUE TITLE
Should we pin googleapis-common-protos in requirements.txt?

### ISSUE THREAD

**Issue by nnegrey** [GoogleCloudPlatform/python-docs-samples#2727]
@GoogleCloudPlatform/python-samples-owners 
googleapis-common-protos had a broken release that broke a lot of samples, tests, and PRs. 

Should samples start pinning all dependencies so that customers can also easily see what they should pin all their versions too so as to not catch these errors on accident?

For dialogflow:
```
dialogflow==0.7.2
googleapis-common-protos==1.6.0
```

I'd assume there are many more sub-dependencies that we also need to pin, but as an example.

**Comment by andrewferlitsch** [comment]
@leahecole PTAL

**Comment by gguuss** [comment]
I've long been a fan of pinning dependencies instead of leaving them to take "this release or newer" style dependencies.

**Comment by leahecole** [comment]
I'm in favor of pinning dependencies, but am not going to pin this transitive dependency here. However, I have made note of exploring it when samples are migrated alongside client libraries.
