### ISSUE TITLE
Bigtable CI/CD tests are broken

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#2729]
Hey! It looks like #2692 broke our CI/CD - @billyjacobson can we either make the test create the bigtable instance and tear it down, or if that's unrealistic in terms of how much time it'll take, can you ping me and we can work together to make sure kokoro has the right environment varaiables?

**Comment by billyjacobson** [comment]
Seems to be an environment variable issue as discussed over chat

**Comment by leahecole** [comment]
#2740
