### ISSUE TITLE
Add methods to publish a message with user provided content and attributes

### ISSUE THREAD

**Issue by danielfmsouza** [GoogleCloudPlatform/python-docs-samples#2741]
## In which file did you encounter the issue?
pubsub/cloud-client/publisher.py

### Did you change the file? If so, how?
I would like to add two methods to the referred file, like this:
1. publish_message_with_custom_body(project_id, topic_name, message_body_or_uri)
2. publish_message_with_custom_body_and_attributes(project_id, topic_name, message_body_or_uri, message_attributes_body_or_uri)

They would both support a single message to be sent per call.
## Describe the issue
I couldn't find a way to publish messages passing the content and attributes using this sample.

**Comment by anguillanneuf** [comment]
👋 @danielfmsouza! Thanks for checking out our samples. 

Would this be what you are looking for? 

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/ead06978013cceea3c6784637a8949ae07665956/pubsub/cloud-client/publisher.py#L122-L124

**Comment by danielfmsouza** [comment]
@anguillanneuf  I would like to expose that to the command line, so users can define the message content and attributes, using the methods I suggested earlier. Here's an example of the new commands:

1. **publish-with-custom-body**:
`python publisher.py project_id publish-with-custom-body topic_name file://textFileWithUserDefinedBody.txt`

2. **publish-with-custom-body-and-attributes**:
`python publisher.py project_id publish-with-custom-body-and-attributes topic_name file://textFileWithUserDefinedBody.txt file://textFileWithUserDefinedMessageAttributes.txt`

I don't think we can do that with the existing commands, or am I missing something?
In the snippet you provided both data and attributes are hard coded, so there is no way for the user to pass them as parameters.

**Comment by anguillanneuf** [comment]
@danielfmsouza Ah I see what you mean. The main purpose of the samples in this repo is to demo what our client libraries can do, for instance, users can use it to publish messages with custom attributes or they can publish messages with batch settings. 

What you suggest is a valid use of the library. But we would like to leave specific use cases (there can be many different ones) to the user and keep the current sample as it is. 

No you did not miss anything. All your comments are valid :)

**Comment by danielfmsouza** [comment]
I see, @anguillanneuf .

Thank you!
