### ISSUE TITLE
storage samples merged w/o passing all presubmits

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#2742]
Hey Jonathan - it looks like #2730 was merged in without passing all of its presubmits - I realize it passed the required ones - you actually helped us find an oversight, that we need to be requiring more than just 3.6. Could you and/or @frankyn take a look at the failures and address them pretty please?

**Comment by jkwlui** [comment]
The PR previously passed all tests across the board when they were re-ran individually. I had since rebased the PR since master was pushed and the tests are showing as failed again because of concurrent runs (issue #2732 - CI split causing Storage tests to fail).

**Comment by kurtisvg** [comment]
Duplicate of #2732
