### ISSUE TITLE
Docs should have FlaskMiddleware for request-based tracing

### ISSUE THREAD

**Issue by eddie-scio** [GoogleCloudPlatform/python-docs-samples#2760]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/trace/main.py

from [the GCP docs](https://cloud.google.com/trace/docs/setup/python).

### Did you change the file? If so, how?

No 

## Describe the issue

If you log the produced spans, you'll see the same trace ID across requests, because the same `Tracer` object is used.  I first noticed this in the StackDriver Trace UI, where I noticed multiple requests being grouped as the same trace (note 1m gap between spans)

<img width="864" alt="Screen Shot 2020-02-01 at 4 22 44 PM" src="https://user-images.githubusercontent.com/52253266/73601058-1f4a2400-450f-11ea-9726-82c3d374d721.png">

To do this correctly, you need to use the [Flask middleware](https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-flask).  Then, you'll also need to get `Tracer` from the execution context instead of sharing one.  Here's a little decorator I wrote that works:
```
from opencensus.trace import execution_context
from opencensus.trace.tracers.noop_tracer import NoopTracer


def trace(func):
    def wrap_with_trace(*args, **kwargs):
        tracer = execution_context.get_opencensus_tracer()
        if isinstance(tracer, NoopTracer):
            return func(*args, **kwargs)
        else:
            with tracer.span(func.__name__):
                return func(*args, **kwargs)
    return wrap_with_trace
```
That decorator can be used on any functions called from a Flask URL route, as long as the middleware is configured as the `opencensus-python`.

I spent a bunch of time on this, so I hope even if the docs aren't updated, this issue helps someone else Googling around!

**Comment by JustinBeckwith** [comment]
@leahecole  for bugs, the robots are asking for a priority :)

**Comment by eddie-scio** [comment]
Sorry if I filed the wrong type of issue, by the way!

**Comment by JustinBeckwith** [comment]
Oh not at all!  This is super helpful @eddie-scio - thanks for giving us a heads up!

**Comment by andrewferlitsch** [comment]
@dmahugh PTAL

**Comment by leahecole** [comment]
@dukeng @ZiweiZhao could you take a look at this?

I tried to replicate but couldn't, partly because when I went through the linked tutorial, I kept running into links to the Neo demo and the quickstart that is the same as the Neo demo. Perhaps this sample actually needs to be removed given the one you wrote?

**Comment by ZiweiZhao** [comment]
I think this app could potentially be replaced by the new demo app, which uses flask middleware. I would bring this up to our technical writer and see if we could replace the sample code with the new demo app. I'll keep you updated in this thread.

**Comment by leahecole** [comment]
Fixed and closed in buganizer
