### ISSUE TITLE
Question regarding to Google Analytics documentation

### ISSUE THREAD

**Issue by y226xie** [GoogleCloudPlatform/python-docs-samples#2765]
In file: python-docs-samples/appengine/flexible/analytics/main.py

In this example, start from line 30 - 50. 
```python
def track_event(category, action, label=None, value=0):
    data = {
        'v': '1',  # API Version.
        'tid': GA_TRACKING_ID,  # Tracking ID / Property ID.
        # Anonymous Client Identifier. Ideally, this should be a UUID that
        # is associated with particular user, device, or browser instance.
        'cid': '555',
        't': 'event',  # Event hit type.
        'ec': category,  # Event category.
        'ea': action,  # Event action.
        'el': label,  # Event label.
        'ev': value,  # Event value, must be an integer
    }

    response = requests.post(
        'https://www.google-analytics.com/collect', data=data)

    # If the request fails, this will raise a RequestException. Depending
    # on your application's needs, this may be a non-error and can be caught
    # by the caller.
    response.raise_for_status()
```
In the above function, it indicates the params that required for Google Analytics. I follow step by step through the Google analytics' documentations, and I received ZERO ERROR message and ZERO WARNING message. However, at the Google Analytics platform, I kept receiving no active user data and no hits. 

After 2 days debugging and searching online, I finally find out I should also include a parameter call `ua` (User Agent Override) for the `data` payload. 

some background info: Our project is written in Python with Flask, and it's integrated with Google Assistance and Amazon Alexa. We want to use Google Analytics to track users' data

I really think I am not the only one encounter this issue, and a clearer documentation or example would be a lot helpful.

**Comment by gguuss** [comment]
Ack, do you have an example of the data body with a `ua` parameter set in the data field?

**Comment by y226xie** [comment]
```json
data = {
        'v': '1',  # API Version.
        'tid': GA_TRACKING_ID,  # Tracking ID / Property ID.
        # Anonymous Client Identifier. Ideally, this should be a UUID that
        # is associated with particular user, device, or browser instance.
        'cid': '555',
        't': 'event',  # Event hit type.
        'ec': category,  # Event category.
        'ea': action,  # Event action.
        'el': label,  # Event label.
        'ev': value,  # Event value, must be an integer
        'ua': Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14
    }
```
I used the example value that I found from the Google Analytics measurement protocol documentation.

**Comment by gguuss** [comment]
Thank you, I'll update the snippet.

**Comment by gguuss** [comment]
This should be [fixed in this PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2997).
