### ISSUE TITLE
DeadlineExceeded google.api.core.exception in transcribe_streaming_infinite.py 

### ISSUE THREAD

**Issue by Luke1962** [GoogleCloudPlatform/python-docs-samples#2786]
Running **speech_transcribe_infinite_streaming.py**, - which in my understanding should allow STT without  timeout issues - I get the following  exception message , which seems quite in contradiction with the purpose of thi program.
What I'm missing ?
I would be happy if I could submit utterance only after snowboy hot-word detection, but I don't know how.
p.s pyaudio and mic seem working properly 

```
pi@rockpi:~/ros/src/myrobotmaster/src/dialogflow_ros/src/dialogflow_ros$ **python3 ``speech_transcribe_infinite_streaming.py**
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM dmix:3
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM dmix
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM dmix
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
1600

Listening, say "Quit" or "Exit" to stop.

End (ms)       Transcript Results/Status
=====================================================

0: NEW REQUEST
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 79, in next
    return six.next(self._wrapped)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 703, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1581025046.085924444","description":"Error received from peer ipv4:216.58.206.42:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "speech_transcribe_infinite_streaming.py", line 298, in <module>
    main()
  File "speech_transcribe_infinite_streaming.py", line 281, in main
    listen_print_loop(responses, stream)
  File "speech_transcribe_infinite_streaming.py", line 186, in listen_print_loop
    for response in responses:
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
pi@rockpi:~/ros/src/myrobotmaster/src/dialogflow_ros/src/dialogflow_ros$ 
```

**Comment by nnegrey** [comment]
I'll try to reproduce this today, are you using the speech api or the dialogflow api with that sample?
Just saw some of the output above says dialogflow.

**Comment by nnegrey** [comment]
Hi, we don't have a file called `speech_transcribe_infinite_streaming.py`, did you take an existing sample and modify it or just rename one?

**Comment by nnegrey** [comment]
@Luke1962, which library version are you using? If v1p1beta1, I suggest switching to just speech
Change `from google.cloud import speech_v1p1beta1 as speech` to:
`from google.cloud import speech`

@busunkim96, I think this has to do with the timeouts from the library, but I can't figure out what is wrong from the v1 to the beta ones. https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1p1beta1/speech_gapic.yaml

I am on the latest version where I thought we made the fixes. `1.3.2`. Any ideas from those config files or should I be looking at some other files?
I tried looking around, but most seem correct from what I can tell.

**Comment by busunkim96** [comment]
@nnegrey Were you able to reproduce this? Or does it only happen in one version and not the other?
* [v1/speech_client_config.py](https://github.com/googleapis/python-speech/blob/master/google/cloud/speech_v1/gapic/speech_client_config.py)
* [v1p1beta1/speech_client_config.py](https://github.com/googleapis/python-speech/blob/master/google/cloud/speech_v1p1beta1/gapic/speech_client_config.py)

`1.3.2` definitely has the commit to bump the timeouts. https://github.com/googleapis/python-speech/commits/master

**Comment by nnegrey** [comment]
@busunkim96, 

I can reproduce in v1p1beta1, but not v1. 
Not sure why.

**Comment by busunkim96** [comment]
The only difference in the two configs is that `Recognize` is `idempotent` in [v1](https://github.com/googleapis/python-speech/blob/master/google/cloud/speech_v1/gapic/speech_client_config.py#L22) and `nonidempotent` in [v1p1beta1](https://github.com/googleapis/python-speech/blob/master/google/cloud/speech_v1p1beta1/gapic/speech_client_config.py#L22). But I don't think that would matter since the sample is using `StreamingRecognize`? 🤔 

Have you seen similar issues in other language repos?

**Comment by Luke1962** [comment]
I'm desolated for wrong name the correct one is **transcribe_streaming_infinite.py** 
I renamed the file, changing only language_code='it-IT', at line 245.
Since I'm making many trials to integrate the file in ROS, I relaunched few minutes ago the file to be shure.
This is the output
```
 luca@ENVY:~/ros/src/myrobot/dialogflow_ros/scripts$ python3 transcribe_streaming_infinite.py 
1600

Listening, say "Quit" or "Exit" to stop.

End (ms)       Transcript Results/Status
=====================================================

0: NEW REQUEST
7710: Ciao Donato

10000: NEW REQUEST
10770: Ciao Donato
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 79, in next
    return six.next(self._wrapped)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 703, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1581370298.481936247","description":"Error received from peer ipv4:172.217.21.74:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "transcribe_streaming_infinite.py", line 292, in <module>
    main()
  File "transcribe_streaming_infinite.py", line 275, in main
    listen_print_loop(responses, stream)
  File "transcribe_streaming_infinite.py", line 180, in listen_print_loop
    for response in responses:
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 2, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
luca@ENVY:~/ros/src/myrobot/dialogflow_ros/scripts$ 
```
Similar behaviour applying the suggested change: 
```
#from google.cloud import speech_v1p1beta1 as speech
from google.cloud import speech
```


`luca@ENVY:~/ros/src/myrobot/dialogflow_ros/scripts$ python3 transcribe_streaming_infinite.py 
1600

Listening, say "Quit" or "Exit" to stop.

End (ms)       Transcript Results/Status
=====================================================

0: NEW REQUEST
6560: Ciao Robot
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 79, in next
    return six.next(self._wrapped)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 703, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1581370559.939453509","description":"Error received from peer ipv4:216.58.206.42:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "transcribe_streaming_infinite.py", line 293, in <module>
    main()
  File "transcribe_streaming_infinite.py", line 276, in main
    listen_print_loop(responses, stream)
  File "transcribe_streaming_infinite.py", line 181, in listen_print_loop
    for response in responses:
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 2, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Connection reset by peer
luca@ENVY:~/ros/src/myrobot/dialogflow_ros/scripts$ 
`

**Comment by busunkim96** [comment]
@Luke1962 Could you confirm that you are using the latest version (1.3.2) of the library? You can check by doing `pip show google-cloud-speech`. 

```
$ pip show google-cloud-speech
Name: google-cloud-speech
Version: 1.3.2
Summary: Google Cloud Speech API client library
Home-page: https://github.com/googleapis/python-speech
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/google/home/busunkim/.pyenv/versions/3.6.9/lib/python3.6/site-packages
Requires: google-api-core
Required-by:
```

**Comment by nnegrey** [comment]
On 1.3.2, I get the following:
```
Listening, say "Quit" or "Exit" to stop.

End (ms)       Transcript Results/Status
=====================================================

0: NEW REQUEST

240000: NEW REQUEST

480000: NEW REQUEST

720000: NEW REQUEST
773110: check one
776170:  check check
789460:  exit
Exiting...
```

**Comment by Luke1962** [comment]
```
luca@ENVY:~/ros/src/myrobot/dialogflow_ros/scripts$ pip show google-cloud-speech
Name: google-cloud-speech
Version: 1.3.1
Summary: Google Cloud Speech API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: google-api-core
Required-by: 
luca@ENVY:~/ros/src/myrobot/dialogflow_ros/scripts$ pip3 show google-cloud-speech
Name: google-cloud-speech
Version: 1.3.1
Summary: Google Cloud Speech API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: google-api-core
Required-by: 
luca@ENVY:~/ros/src/myrobot/dialogflow_ros/scripts$ 
```
I'll try updating to  1.3.2 and I'll report the results.Thank you

**Comment by Luke1962** [comment]
Working after upgrading to 1.3.2! 
Thank you  for the support

**Comment by Luke1962** [comment]
Just final question 
Are long silence periods considered by billing algorithms?

**Comment by busunkim96** [comment]
Hey @Luke1962, you can read more about billing for this API at https://cloud.google.com/speech-to-text/pricing
