### ISSUE TITLE
Text to Speech: more languages/accents?

### ISSUE THREAD

**Issue by jchwenger** [GoogleCloudPlatform/python-docs-samples#2798]
Hi,

First of all, thanks for providing such easy access to the text to speech resources ([api page here](https://cloud.google.com/text-to-speech/docs/quickstart-client-libraries#client-libraries-install-python), [python code here](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/texttospeech/cloud-client)), I've looked into it for a project I had been mulling for a while, and the current ecosystem provides a nice first step.

It might not be the best place to ask the question, but I am not sure where would be the place to do so, so I thought I'd give it a shot here, and would be grateful for any help in pointing me to the right place. I found the [list of supported voices](https://cloud.google.com/text-to-speech/docs/voices), and was wondering if :

1. there was more coming (the big gap so far is African languages), and:

2. if there was also a plan to develop more detailed/specific variations within languages (e.g. US English from Texas or other regions, Scottish/Irish/etc., various French or German accents, and so forth)? That would be very interesting.

P.S: the scripts I used, both python and bash, worked fine out of the box, so no issues there. Thanks in advance!

**Comment by czahedi** [comment]
Hi! Great question :). I'm reaching out to the product team to get this kind of roadmap information. Stay tuned!

**Comment by czahedi** [comment]
Hi,

I spoke with the product team, and  unfortunately there isn't a near-term plan for African languages, or different accents of US English yet. The next launches will focus mainly on latin languages. 

However, please let us know what particular African languages you're interested in! Even better if you have any traffic estimates or interest in helping find some :). I can bring this information to the product team and this might help them prioritize new language decisions.

**Comment by czahedi** [comment]
I'm going to close this issue for now but please feel free to continue the discussion or send me a private message about your desired features. Thanks :)

**Comment by jchwenger** [comment]
My apologies for the late reply! I got completely submerged into other things, and the notification slipped me by. Thanks for all this! I didn't have any specific African language in mind, and I'll see if I can find anything. I'll be on the lookout for the Latin languages you mention, and will write again with any news, cheers! :)
