### ISSUE TITLE
gcp-python-repo-tools installation fails.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/python-docs-samples#283]
Following the instructions here:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/TESTING.md

rennie@rennie:~/gitrepos/python-docs-samples$ sudo pip install --upgrade nox-automation pip gcp-python-repo-tools
[sudo] password for rennie: 
Downloading/unpacking nox-automation
  Downloading nox-automation-0.2.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/nox-automation/setup.py) egg_info for package nox-automation
    
Downloading/unpacking pip from https://pypi.python.org/packages/31/6a/0f19a7edef6c8e5065f4346137cc2a08e22e141942d66af2e1e72d851462/pip-8.1.1-py2.py3-none-any.whl#md5=22db7b6a517a09c29d54a76650f170eb
  Downloading pip-8.1.1-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Downloading/unpacking gcp-python-repo-tools
  Could not find any downloads that satisfy the requirement gcp-python-repo-tools
Cleaning up...
No distributions at all found for gcp-python-repo-tools
Storing debug log for failure in /root/.pip/pip.log
rennie@rennie:~/gitrepos/python-docs-samples$

**Comment by jonparrott** [comment]
Fixed by c697937967be24

You just need nox.
