### ISSUE TITLE
cloud-sql/postgres/sqlalchemy + Python: error connection

### ISSUE THREAD

**Issue by bp91** [GoogleCloudPlatform/python-docs-samples#2845]
Hi, I tried to connect to a PostgreSQL hosted using Cloud SQL. I've followed the file **python-docs-samples/cloud-sql/postgres/sqlalchemy/main.py**.

I have the following piece of code:

```
# HERE I'm setting the service account to be used with the role Cloud SQL Admin
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = os.path.join(appconfig.configs[appconfig.ENV]["ROOT_DIR"], "config", "google", appconfig.configs[appconfig.ENV]["SERVICE_ACCOUNT_CLOUD_SQL"])

_engine = create_engine(
                    'postgres+pg8000://{}:{}@/{}?unix_sock=/cloudsql/{}/.s.PGSQL.{}'.format(self.username, self.password, self.db_name, self.instance_name, self.port),
                    pool_size=5,
                    max_overflow=2,
                    pool_timeout=30,
                    pool_recycle=1800
                )

_connection = _engine.connect()
```
the DB url is like "postgres+pg8000://admin:password@/dbname?unix_sock=/cloudsql/my_gcp_project:europe-west3:dbname/.s.PGSQL.5432".

The python modules are the same defined into the requirements.txt file.

I receive the following error:

```
File "C:\Users\b.pistone\development\reply\et-api-layer\venv\lib\site-packages\pg8000\core.py", line 1157, in __init__
    "attempt to connect to unix socket on unsupported "
sqlalchemy.exc.InterfaceError: (pg8000.core.InterfaceError) attempt to connect to unix socket on unsupported platform
(Background on this error at: http://sqlalche.me/e/rvf5)
```
Can I receive support? Thank you for your help.

**Comment by kurtisvg** [comment]
Hi bp91@,

1. This sample is designed to connect to Cloud SQL either running in a serverless environment (App Engine / Cloud Run) or using the Cloud SQL proxy. It connects using a unix socket path that the Cloud SQL proxy provides. 
2. It looks like you are running on Windows. Unfortunately, the Cloud SQL proxy doesn't support unix sockets on Windows at this time. This means you'll have to connect using a TCP port.

Please take a look at this page in our documentation regarding connecting to Cloud SQL: https://cloud.google.com/sql/docs/mysql/connect-external-app

**Comment by dmahugh** [comment]
@bp91, in case it's helpful - here's the connection string syntax I'm using in some Windows code that connects to a Cloud SQL for Postgres instance via TCP:

```python
connection_string = f"{driver}://postgres:{password}@127.0.0.1:5432/{database}"
```

**Comment by bp91** [comment]
Hi @kurtisvg. The problem was related also to a proxy configured for the network where I'm working for. 
I've used the cloud_sql_proxy.exe with instance name and service account path as parameters.
@dmahugh thanks for your response. I've already configured the DB_URL for a TCP connection and now is working well.

Thanks for your support
