### ISSUE TITLE
Library where you input the Google annotation object and it draws the bounding boxes

### ISSUE THREAD

**Issue by mofa** [GoogleCloudPlatform/python-docs-samples#2922]
Is there a library that simplifies the process of overlaying the bounding boxes on the original video given the annotation object as input?

**Comment by kurtisvg** [comment]
@nnegrey Do you have any recommendations?

**Comment by nnegrey** [comment]
Um not really, but some quick searches suggest one of the 3 below can overlay rectangles on images, you probably have to process the video frame by frame though and for each frame overlay the rectangle, then save or display it based on your need. 

https://stackoverflow.com/questions/23720875/how-to-draw-a-rectangle-around-a-region-of-interest-in-python?noredirect=1&lq=1
 
https://stackoverflow.com/questions/33311153/python-extracting-and-saving-video-frames


matplotlib: https://pypi.org/project/matplotlib/
pillow: https://pypi.org/project/Pillow/
openCV: https://pypi.org/project/opencv-python/

Images to videos: https://stackoverflow.com/questions/44947505/how-to-make-a-movie-out-of-images-in-python
