### ISSUE TITLE
Remove this text ASAP from transcribe_streaming_infinite.py

### ISSUE THREAD

**Issue by bbookman** [GoogleCloudPlatform/python-docs-samples#2958]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_infinite.py

The file contains the following line which should be immediately removed.
>uses result_end_time currently only avaialble in v1p1beta, will be in v1 soon

Google absolutely should not be promising specific feature releases IN CODE

**Comment by nnegrey** [comment]
That feature has been v1 for awhile now. 
But there is a PR to update that sample to v1 out already: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2628
