### ISSUE TITLE
KubernetesPodOperator parameterize the image tag ID

### ISSUE THREAD

**Issue by atejano** [GoogleCloudPlatform/python-docs-samples#3019]
## In which file did you encounter the issue?
airflow/contrib/operators/kubernetes_pod_operator.py

### Did you change the file? If so, how?
No

## Describe the issue
Given the task definition below using KubernetesPodOperator, I need to be able to provide the image tag (16.04) as an configurable value in the ConfigMap object.
```
k = KubernetesPodOperator(namespace='default',
                          image="ubuntu:16.04",
                          cmds=["bash", "-cx"],
                          arguments=["echo", "10"],
                          labels={"foo": "bar"},
                          secrets=[secret_file, secret_env, secret_all_keys],
                          ports=[port]
                          volumes=[volume],
                          volume_mounts=[volume_mount]
                          name="test",
                          task_id="task",
                          affinity=affinity,
                          is_delete_operator_pod=True,
                          hostnetwork=False,
                          tolerations=tolerations,
                          configmaps=configmaps
                          )
```

**Comment by leahecole** [comment]
Hi @atejano - the file that you're referring to is actually part of the upstream Airflow project - [here's the most recent source code](https://github.com/apache/airflow/blob/master/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py) - if you're needing to parameterize the image tag ID, I'd recommend checking out using [Jinja Templating](https://airflow.apache.org/docs/stable/tutorial.html#templating-with-jinja) with Airflow. 

Also, if you're not already involved with the broader [Airflow community](https://airflow.apache.org/community/), I highly recommend subscribing to the devlist and joining the slack. More info is in that linked community page.
