### ISSUE TITLE
Update create custom metric example to include resource labels

### ISSUE THREAD

**Issue by tinylox** [GoogleCloudPlatform/python-docs-samples#3020]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/monitoring/api/v3/cloud-client/snippets.py#L27
### Did you change the file? If so, how?
I've updated the example to include adding a label descriptor in line with the Java examples
## Describe the issue
The create_metric_descriptor example currently doesn't add any label descriptors to the custom metric it creates.
It should match the Java example and provide sample code that creates a custom metric with a LabelDescriptor. This is a common use case and should be surfaced in the sample code.

**Comment by dandhlee** [comment]
The snippets have moved, but it seems like it is now supported with `LabelDescriptor`!
