### ISSUE TITLE
managed_vms/endpoints: fix lint errors

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/python-docs-samples#305]
https://travis-ci.org/GoogleCloudPlatform/python-docs-samples/builds/126491131

**Comment by broady** [comment]
`./managed_vms/endpoints/clients/google-id-token-client.py:24:1: I100 Import statements are in the wrong order. from oauth2client.file should be before from oauth2client.tools`

**Comment by jerjou** [comment]
Fixed in #304
