### ISSUE TITLE
cloudiot_mqtt_example.py  create_jwt wrong token expiry time

### ISSUE THREAD

**Issue by somervda** [GoogleCloudPlatform/python-docs-samples#3133]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/mqtt_example/cloudiot_mqtt_example.py 

In the create_jwt function 

The actual expiry token time of 60 minutes does not align with the comments for the code that say it is set to 20 minutes. Also does not align with the  send_data_from_bound_device function in the same file that indicates jwt expiry should be using the jwt_expires_minutes parameter. 

Suggested fix is to pass the jwt_expires_minutes parameter to create_jwt function to remove the inconsistencies.

**Comment by gguuss** [comment]
Fixed in #3139

**Comment by JustinBeckwith** [comment]
Looks to be fixed :)
