### ISSUE TITLE
google.api_core.exceptions.InvalidArgument: 400 Could not de-identify all content due to transformation errors. 

### ISSUE THREAD

**Issue by nandini1696** [GoogleCloudPlatform/python-docs-samples#3245]
## In which file did you encounter the issue?
deid.py

### Did you change the file? If so, how?
Nope

## Describe the issue
I'm trying to use deidentify with fpe to deidentify SSN and credit card numbers.
I'm facing this error - google.api_core.exceptions.InvalidArgument: 400 Could not de-identify all content due to transformation errors. See the error details for an overview of all the transformation errors encountered.

**Comment by nandini1696** [comment]
How do you solve "google.api_core.exceptions.InvalidArgument: 400 Could not de-identify all content due to transformation errors. See the error details for an overview of all the transformation errors encountered."

**Comment by crwilcox** [comment]
Could you provide a code sample that will demonstrate this error?

**Comment by crwilcox** [comment]
Closing as I can't reproduce with the information provided.
