### ISSUE TITLE
Google Cloud SDK pub/sub sample memory leak

### ISSUE THREAD

**Issue by gaurgs** [GoogleCloudPlatform/python-docs-samples#3259]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/flexible/pubsub/main.py

### Did you change the file? If so, how?
It's always best practice to declare the client only once in an application. 
Change: Going to move line 49 outside the function at the global level.

## Describe the issue
For every request, the client is getting instantiated therefore leaking the memory. 

```
@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'GET':
        return render_template('index.html', messages=MESSAGES)

    data = request.form.get('payload', 'Example payload').encode('utf-8')

    # Consider initialzing the publisher client outside this function
    # for low latency publish.
    publisher = pubsub_v1.PublisherClient()
```

**Comment by anguillanneuf** [comment]
👋@gaurgs, thanks for suggesting the change. 

You are right that client init should be at the global level. We left the comment "Consider initializing the publisher client outside this function for low latency publish" right above the client init code out of a similar concern. 

But note that this entire code block wrapped around by the [region tag](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/eb6a7a29b0e187d8451a778cc4901771012176c6/appengine/flexible/pubsub/main.py#L39) `gae_flex_pubsub_index` is getting quoted [here](https://cloud.google.com/appengine/docs/flexible/python/writing-and-responding-to-pub-sub-messages#code_review). If we move this line out of the handler block, it may be unclear to people where the publisher client comes from. 

How does #3280 look?
