### ISSUE TITLE
testing: only run tests which has code changes in continuous builds

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3314]
In presubmit builds, we only run tests which has code changes. I think we should do the similar thing in continuous builds too.

This will significantly reduce the build time, and avoid consuming cloud resources.
For example, this will significantly mitigate issues like: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3291

**Comment by tmatsuo** [comment]
@JustinBeckwith Had a thought about this.

**Comment by JustinBeckwith** [comment]
👋 I did!  Thinking out loud - we use this model for presubmit tests, and rely on continuous and nightly to run the whole suite.  If we only run changed code on continuous, it effectively means we're testing the exact same thing as the presubmit tests, right?

**Comment by kurtisvg** [comment]
It's mostly the same if we assume that every branch is up to date when the presubmit checks are run (which we are currently enforcing via a branch check).
