### ISSUE TITLE
Switch functions tests to Python 3.6+

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/python-docs-samples#3341]
Currently functions is using a check in the bashfile - instead, we should use the noxfile-templates to control this:

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.kokoro/tests/run_tests.sh#L79-87

**Comment by tmatsuo** [comment]
Here is the permalink: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/07bc5fc7e11983377a40de95e4e1cd3eefd75db3/.kokoro/tests/run_tests.sh#L89-L97

@kurtisvg 
I'm not sure it's still relevant. The bash script is excluding python 2.x and python 3.5? We don't have python 3.5 any more iirc.

**Comment by tmatsuo** [comment]
Maybe I'll try to remove that block and run the periodic build to see how it goes.

**Comment by kurtisvg** [comment]
SGTM
