### ISSUE TITLE
ImportError: Missing optional dependency 'gcsfs'

### ISSUE THREAD

**Issue by Embo1** [GoogleCloudPlatform/python-docs-samples#3409]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/tables/automl/notebooks/purchase_prediction/purchase_prediction.ipynb

### Did you change the file? If so, how?
I ran the notebook in Colab, and made the relevant changes to support my project Id and Google drive end points

## Describe the issue

I have logged an issue in StackOverflow, but no responses yet:
https://stackoverflow.com/questions/61210060/automl-colab-notebook-importerror-missing-optional-dependency-gcsfs

**Comment by sirtorry** [comment]
thank you for bringing this to light. it looks like the notebook wasn't written for colab. i'll investigate whether we can make this notebook runnable from colab.

**Comment by telpirion** [comment]
With the focus on uCAIP and changes to notebook pipelines, let's close this issue. Please re-open if the issue persists.
