### ISSUE TITLE
Split testing container from testing-infra-docker

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/python-docs-samples#3442]
Currently we use the currently use this [Dockerfile](https://github.com/googleapis/testing-infra-docker/tree/master/python/googleapis/python-multi) for testing. However we really should have our own Dockerfile with our own dependencies here in python-docs-samples. 

Here are the steps that need to be taken to do this:
1. Create a dockerfile based on python:3.6 here in the repo with the dependencies necessary for our tests (maybe in root or `.kokoro`?)
2. Create a Kokoro continuous job that checks if the Dockerfile has changed, and if so pushes a new version of the container
3. Update our tests to use this image instead of the current `python-multi`.

**Comment by tanjinP** [comment]
@kurtisvg I can take this on - looks pretty straightforward.

**Comment by tmatsuo** [comment]
Can we close this now?
