### ISSUE TITLE
[kms] flake: 429 Quota exceeded

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3482]
[Build](https://source.cloud.google.com/results/invocations/9ada194b-05b3-4cd5-a229-ac97bae0ad42/targets/github%2Fpython-docs-samples%2Fkms%2Fapi-client/tests)

Log:
google.api_core.exceptions.ResourceExhausted: 429 Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute' of service 'cloudkms.googleapis.com' for consumer 'project_number:1012616486416'.

**Comment by leahecole** [comment]
I looked into this, and this quota, which we have set to 60 requests per minute, has been exceeded just once in the past 30 days, with this build. Our average hovers well below the 60 requests per minute quota - usually around 25-30 - so I'm not inclined to increase it and am going to mark it as a fluke for now. If it continues to fail though, plz reopen and we can explore increasing the quota.

**Comment by rgelb** [comment]
@leahecole Unrelated, however, where did you find documentation for the "60 requests per minute" number?  I am having same issue with the Google Photos API.
