### ISSUE TITLE
[automl] no information about `AUTOML_PROJECT_ID` and `OBJECT_DETECTION_MODEL_ID`

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3491]
I tried to run `automl/cloud-client/vision_object_detection_predict_test.py` against my project then it errored out because I don't set `AUTOML_PROJECT_ID` and `OBJECT_DETECTION_MODEL_ID`.

It's great if we have those environment variables in [`testing/test-env.tmpl.sh`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/testing/test-env.tmpl.sh) with some explanations for why you need a different cloud project and how to prepare the model.

**Comment by munkhuushmgl** [comment]
feel free to assign it to me, I can provide some context on this.
