### ISSUE TITLE
Transfer service: http to gs bucket

### ISSUE THREAD

**Issue by bmyerz** [GoogleCloudPlatform/python-docs-samples#359]
How do I set up a transfer from an HTTP URL to a bucket? There are only samples for amazon-google and google-google.

https://cloud.google.com/storage/transfer/create-manage-transfer-program

**Comment by jonparrott** [comment]
It seems like it's just using `httpDataSource` in place of `gcsDataSource`.

```
        'transferSpec': {
            'httpDataSource': {
                'listUrl': 'https://...'
            },
            ...
```

We can put this on our list of new samples to add, but if you want to make a sample and contribute it I'll be happy to review.
