### ISSUE TITLE
How to read GeoPoint in python script?

### ISSUE THREAD

**Issue by pratik-dropshop** [GoogleCloudPlatform/python-docs-samples#3701]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets.py#L103

## Describe the issue
If there location of city (as Firestore.GeoPoint) existed, how can we read it in the python script?

**Comment by tmatsuo** [comment]
This is a question about firestore. @BenWhitehead Are you a right person for the question?

**Comment by BenWhitehead** [comment]
Take a look at the [GeoPoint](https://github.com/googleapis/python-firestore/blob/c67d252f42a3dfbca4a3e498fc83123eec6e16e7/google/cloud/firestore_v1/_helpers.py#L56) class in the Firestore package.

**Comment by pratik-dropshop** [comment]
Thank you.
