### ISSUE TITLE
Re-enable model test

### ISSUE THREAD

**Issue by Strykrol** [GoogleCloudPlatform/python-docs-samples#3706]
`python-docs-samples/vision/automl/model_test.py`

## Describe the issue

After  [Pull Request 3693](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3693), there is only one test in this file: `test_model_create_status_delete`, and it is currently skipped. 

This should be re-enabled.

**Comment by tmatsuo** [comment]
Let's close this. This directory will be removed soon (see #3766). @busunkim96 WDYT?
