### ISSUE TITLE
PubSub python - add another example for custom attributes and another comment

### ISSUE THREAD

**Issue by StanfordLin** [GoogleCloudPlatform/python-docs-samples#3715]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/pubsub/cloud-client/publisher.py

receive_messages_with_custom_attributes

### Did you change the file? If so, how?

Not yet, I can add an example when permitted

## Describe the issue

Note: Maybe I'm just new to pubsub and python and don't understand the syntax, but I feel like others can benefit as well on the time saved because I was learning to use during a hackathon and time was of the essence.

receive_messages_with_custom_attributes

When I was starting to use python pubsub, I grew increasingly frustrated when it took me a long time (6+ hours) to pass 2 or more custom attributes from a publisher to subscriber because  there was a comment "Note that the callback is defined *before* the subscription is opened." which was not clearly stated on the example, but stated in another reference. 

https://googleapis.dev/python/pubsub/latest/subscriber/index.html#subscription-callbacks

current  receive_messages_with_custom_attributes

```
def callback(message):
        print("Received message: {}".format(message.data))
        if message.attributes:
            print("Attributes:")
            for key in message.attributes:
                value = message.attributes.get(key)
                print("{}: {}".format(key, value))
        message.ack()
```

The proposed example (something similar): 
```

global destinationOrigin
global destinationUsername

 def callback(message):
        print("Received message: {}".format(message.data))
        if message.attributes:
            print(f"Attributes: {message.attributes}")
           destinationOrigin = message.attributes['origin']
           destinationUsername = message.attributes['username']
   
         message.ack()
```

**Comment by busunkim96** [comment]
@hongalex Would you mind triaging this?

**Comment by hongalex** [comment]
Hi, thanks for opening this issue. I think the issue of accessing message attributes is unrelated to the note about defining the callback prior to subscription open. The latter simply means we have to define a callback function before calling `subscriber.subscribe`.

In addition, we try to make the samples as generic as possible (not passing in specific variables). It seems like the only difference between the existing sample and the proposed change is the difference in accessing map elements (using `get` versus square brackets). I think for most users of Python, this is clear either way. Closing for now, but feel free to comment if you'd like to discuss this further.
