### ISSUE TITLE
missing Python namespace example

### ISSUE THREAD

**Issue by niravmerchant** [GoogleCloudPlatform/python-docs-samples#372]
This page: 

https://cloud.google.com/appengine/docs/python/multitenancy/#Python_Building_a_multitenant_application_with_the_Namespaces_API

refers to a Python Namespacing example with this link:

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/multitenancy

Python App Engine: appengine-multitenancy – A namespace-aware sample guestbook application.

and that link 404's...

**Comment by jonparrott** [comment]
@waprin likely something you missed when you moved /appengine to /appengine/standard ?

**Comment by waprin** [comment]
Yep ty I'll fix it.

**Comment by waprin** [comment]
Ty again for report, fix is submitted, will be live next time our docs are published.
