### ISSUE TITLE
Debug detect_test.py::test_async_detect_document failure

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3753]
In https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3751 we disabled `detect_test.py::test_async_detect_document` in `vision/cloud-client/detect` directory.

It constantly timing out with LRO.

Debug it and re-enable it if possible.

**Comment by tmatsuo** [comment]
The test is using a PDF file:
gs://cloud-samples-data/vision/document/custom_0773375000.pdf

The file size is 4.8MB. I'm experimenting with a smaller file.

**Comment by tmatsuo** [comment]
It also times out with a smaller file. I also explicitly added ObjectCreator role on the bucket, but no success.

I'm asking vision API devs for help.

**Comment by tmatsuo** [comment]
For the record, it even fails with 3600 seconds timeout.

**Comment by detinho** [comment]
It seems to be a backend issue. I have been using this same operation in production via the Java SDK for a long time and today a customer complained. I noted a 100% error rate on this operation for the past 48 hours.
I opened a case on GCP console and for all the tests we (the support guy and me) did (even via the REST API directly) the operation never finishes.
Our files are all 1 page PDFs and small files, ranging from 15kb to 250kb avg.

**Comment by tmatsuo** [comment]
@detinho Thanks for your input and sorry for the trouble. We're working on the fix.
