### ISSUE TITLE
[datalabeling] debug failing tests

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3759]
We will disable `label_text_test.py::test_label_text` and `manage_dataset_test.py::test_list_dataset` in `datalabeling` directory.

[Failed build ](https://source.cloud.google.com/results/invocations/cf30940a-c7ec-43be-a9f6-6f413b5fb22b/targets/github%2Fpython-docs-samples%2Fdatalabeling/tests)

It seems like
- the dataset is considered empty for `label_text_test.py::test_label_text`.
- the test backend is throwing DeadlineExceeded for `manage_dataset_test.py::test_list_dataset`.

This bug is to debug them and re-enable them if possible.

**Comment by tmatsuo** [comment]
History of the test_label_text:
https://github.com/GoogleCloudPlatform/python-docs-samples/commits/master/datalabeling/label_text_test.py

After this commit, we had several successful builds, so the last commit is not the direct culprit.

**Comment by tmatsuo** [comment]
Well I tried to repro, but `manage_dataset_test.py::test_list_dataset` is now constantly passing.

**Comment by tmatsuo** [comment]
For `label_text_test.py::test_label_text`, it might be a permission issue with the datalabeling agent:
service-1012616486416@gcp-sa-test-datalabeling.iam.gserviceaccount.com

**Comment by tmatsuo** [comment]
I tracked down the issue to this point.

For that particular test, we create a dataset and import a CSV file to it. The import job succeeds, but for some reason, the import job doesn't import anything (both `total_count` and `import_count` in the result are 0).

The same code for importing just works on the production endpoint.

Here is the code for repro. You can put it in `datalabeling` and run it with the required env vars.

`import.py`
```python
import os

import backoff
from google.api_core.exceptions import DeadlineExceeded
import pytest

import label_text
import testing_lib

PROJECT_ID = os.getenv('GCLOUD_PROJECT')
INPUT_GCS_URI = 'gs://cloud-samples-data/datalabeling/text/input.csv'
INSTRUCTION_GCS_URI = ('gs://cloud-samples-data/datalabeling'
                       '/instruction/test.pdf')


# create a temporary dataset
dataset = testing_lib.create_dataset(PROJECT_ID)

result = testing_lib.import_data(dataset.name, 'TEXT', INPUT_GCS_URI)

print("Total count: {}".format(result.total_count))
print("Import count: {}".format(result.import_count))
``` 

If you run it against the production, it successfully import the data, but on the testing server, no data is imported.

**Comment by tmatsuo** [comment]
@busunkim96 Can you transfer this issue to `googleapis/python-datalabeling`?

**Comment by busunkim96** [comment]
It's unfortunately not possible to transfer issues between orgs. I opened a new issue on that repo.

**Comment by munkhuushmgl** [comment]
@busunkim96 Can u close this?
