### ISSUE TITLE
Media Translation Cloud-Client "Copy to Cloudshell"

### ISSUE THREAD

**Issue by Orkogithub** [GoogleCloudPlatform/python-docs-samples#3769]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/media-translation/cloud-client/README.rst
## Describe the issue
This file is showing "copy to cloudshell" boilerplate. This should be removed.

**Comment by tmatsuo** [comment]
@Orkogithub Thanks for reporting. I don't see "copy to cloudshell", but I assume you are talking about "OPEN IN GOOGLE CLOUD SHELL" button for the sample that uses mic (since you don't access to mic in the cloud shell environment).

**Comment by Orkogithub** [comment]
That is correct! Thanks.
