### ISSUE TITLE
`raise RuntimeError` not showing in Logging or Stackdriver Errors

### ISSUE THREAD

**Issue by dror-g** [GoogleCloudPlatform/python-docs-samples#3777]
## In which file did you encounter the issue?

functions/helloworld/main.py

### Did you change the file? If so, how?

No, just tried this one line `raise RuntimeError('I failed you')` in a fresh function

## Describe the issue

According to the doc & this example:
```
    # This WILL be reported to Stackdriver Error Reporting,
    # and WILL terminate the function
    raise RuntimeError('I failed you')
```

However, this `raise` on its own does **not** show in Logging, and is **not** shown in Stackdriver Error Reporting.

**Comment by tmatsuo** [comment]
@dror-g Thanks for your report. I deployed `hello_error_1`, accessed with a web browser and saw the error got popped up in ErrorReporting UI.

I think it works correctly for me.

I'm closing this, but feel free to reopen it with repro step.

Thanks!

**Comment by yamadatomonori** [comment]
@dror-g Have you enabled Error Reporting API?

**Comment by dror-g** [comment]
Yup. 

If I use `client.report_exception()` I can see errors both in StackDriver Error Reporting and in Logging,
But using just `raise RuntimeError('something')` on its own terminates the function, but nothing appears in Logging or Error Reporting.

@tmatsuo this is in a background function triggered by pubsub. Also, where's `hello_error_1` you're referring to?
