### ISSUE TITLE
Segmentation Fault inside (probably) make_channel

### ISSUE THREAD

**Issue by dariocazzani** [GoogleCloudPlatform/python-docs-samples#379]
I am testing the performances of this STT engine and others in my app.
I am using Ubuntu 14.04
After 4 requests of transcription (streaming mode), I always get Segmentation Fault.

**Comment by waprin** [comment]
Sorry, what's STT?

**Comment by dariocazzani** [comment]
Google Speech API. In other words, this repo

**Comment by jerjou** [comment]
Ah - "speech to text".
This repo contains samples for the whole of the Google Cloud Platform (ie not just the speech api), so it's hard to decipher acronyms without context.

Are you hitting the [one-minute mark](https://cloud.google.com/speech/docs/best-practices#usage_limits) in your testing? If not, it'd be helpful to get some details on what platform you're using, and a [paste](https://gist.github.com/) of your invocation and output.

**Comment by jerjou** [comment]
Closing for now. Feel free to reopen with more details!
