### ISSUE TITLE
Export data to CSV sample

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/python-docs-samples#38]
Needed for docs.

**Comment by jonparrott** [comment]
@elibixby this hasn't been updated since june. Is this issue still valid?

**Comment by elibixby** [comment]
It is, just low priority. Thanks for bumping.

**Comment by jonparrott** [comment]
Alright, will leave open (trying to clean up this repo)

**Comment by jonparrott** [comment]
The sample for exporting to cloud storage exports in CSV format. Is that not sufficient? If not, what exactly does this bug want?

**Comment by jonparrott** [comment]
Closing this. Feel free to re-open.
