### ISSUE TITLE
Move samples to client library repositories

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/python-docs-samples#3891]
This is a list of all the samples projects that should likely be moved to client library repositories:

- [x] [asset](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/asset/cloud-client)
- [x] [automl](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/automl)
- [x] [bigquery](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigquery)
- [x] [bigquery_datatransfer](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigquery/transfer)
- [x] [bigquery_storage](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigquery_storage/to_dataframe)
- [x] [bigtable](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigtable)
    - https://github.com/googleapis/python-bigtable/pull/38
- [ ] [cloud-sql](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/cloud-sql)
- [ ] [compute](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/compute)
- [x] [container_registry](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/container_registry/container_analysise)
- [x] [datacatalog](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/datacatalog/cloud-client)
- [x] [datalabeling](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/datalabeling)
- [x] [dataproc](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dataproc)
- [ ] [datastore](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/datastore)
- [x] [dialogflow](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dialogflow/cloud-client)
- [x] [dlp](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dlp)
- [ ] [dns](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dns/api)
- [x] [document](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/document/cloud-client)
- [x] [error_reporting](error_reporting)
- [ ] [firestore](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/firestore/cloud-client)
- [ ] [iot](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/iot/api-client)
- [ ] [jobs](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/jobs)
- [x] [kms](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/kms)
    - https://github.com/googleapis/python-kms/pull/14
- [x] [language](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/language)
- [x] [logging](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/logging/cloud-client)
- [x] [media-translation](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/media-translation/cloud-client)
- [ ] [memorystore](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/memorystore/redis)
- [ ] [monitoring](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/monitoring/api/v3)
- [x] [pubsub](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/pubsub)
- [x] [scheduler](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/scheduler)
- [x] [secretmanager](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/secretmanager/api-client)
- [x] [spanner](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/spanner/cloud-client)
- [x] [speech](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech)
- [ ] [storage](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/storage)
- [x] [tables](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/tables/automl) (technically automl, unclear if these should be merged)
- [x] [tasks](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/tasks)
- [x] [texttospeech](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/texttospeech/cloud-client)
    - #3845 
- [ ] [trace](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/trace)
- [x] [translate](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/translate)
- [x] [video](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/video/cloud-client)
- [x] [vision](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/vision)

**Comment by meredithslota** [comment]
Is this list current?

**Comment by dandhlee** [comment]
Current as of today.

**Comment by anguillanneuf** [comment]
Missing `pubsublite` in the list. The samples in `pubsub` and `pubsublite` are x-product samples and don't belong with libraries.

**Comment by dandhlee** [comment]
@anguillanneuf would you like to migrate them back to this repo then?

**Comment by anguillanneuf** [comment]
@dandhlee everything here looks good. I was just pointing out the fact that the samples in this repo are x-product. Nothing needs to be changed.

**Comment by dandhlee** [comment]
Ah, misread that. So we should take out `Pubsub` from this list then right?

**Comment by anguillanneuf** [comment]
I think you should check it off. We moved single-product Pub/Sub samples out of there a long time ago. AFAIK, the work is done :)

**Comment by anguillanneuf** [comment]
I checked it off just now.

**Comment by dandhlee** [comment]
Thank you!

**Comment by leahecole** [comment]
I think this is obsolete now 😁
