### ISSUE TITLE
Can we have percent matching for a job search ?

### ISSUE THREAD

**Issue by izuku-franck1555** [GoogleCloudPlatform/python-docs-samples#3901]
Hello everyone. Please, I would like to know if it is possible to get the matching percentage of a job when searching with the API. I've looked through the docs and samples but I couldn't find anything.
Thank you in advance !

**Comment by busunkim96** [comment]
Hi @izuku-franck1555,

Could you let us know which API you are working with?

**Comment by izuku-franck1555** [comment]
Hello @busunkim96 . Thank you for you reply. I use google cloud talent solution api. The v4beta1 version.

**Comment by busunkim96** [comment]
Does Job Search provide the percent match somewhere? (in the UI for example?) I don't see anything obvious in the [docs](https://cloud.google.com/talent-solution/job-search/docs/reference/rpc/google.cloud.talent.v4beta1#google.cloud.talent.v4beta1.SearchJobsResponse).

**Comment by izuku-franck1555** [comment]
Yes @busunkim96. I just thought that if API has the option to match a job application to a job offer, maybe they also have the ability to provide us with a percentage or a rating so that we can see who has the best profile.

**Comment by busunkim96** [comment]
I see. Since this is a feature request for the Talent Solutions API, please file an issue [here](https://issuetracker.google.com/savedsearches/559664) and someone on the team will get back to you.

Thanks!
