### ISSUE TITLE
Feat: Add Sample: Events for Cloud Run – Pub/Sub

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/python-docs-samples#3928]
Add a minimal sample for Events for Cloud Run for Pub/Sub triggers. See the design doc below for more details as to the actual sample:

- Sample `run_events_pubsub`
- Directory: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/run
- Dockerfile would look something like this: https://cloud.google.com/run/docs/quickstarts/build-and-deploy#python

## Resources

- Similar PR: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1809
- Design doc: go/events-for-cloud-run-devrel-code

**Comment by grant** [comment]
Curtis, assign yourself after registering on go/github

**Comment by grant** [comment]
How does this sound @cumason123?

**Comment by cumason123** [comment]
Working on it!

**Comment by tmatsuo** [comment]
@cumason123 FYI, the markdown-preview directory is a nice example for end 2 end testing:
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/run/markdown-preview

Feel free to ask anything.

**Comment by grant** [comment]
Fixed with https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4011.
