### ISSUE TITLE
endpoints: add /auth/info/firebase endpoint

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/python-docs-samples#396]
This one needs CORS headers.

See sample implementation here:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/app.go

and copy the new swagger file:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/swagger.yaml

**Comment by jonparrott** [comment]
MMMkay.

**Comment by broady** [comment]
thank ye!
