### ISSUE TITLE
Dataflow flex template failed to launch.

### ISSUE THREAD

**Issue by rororo** [GoogleCloudPlatform/python-docs-samples#4003]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dataflow/flex-templates/streaming_beam/README.md

### Did you change the file? If so, how?
I tried to launch a python batch job using Flex template, here's my requirements.txt.

```
apache-beam[gcp]==2.21.0
Jinja2==2.11.2
pymongo[srv]==3.10.1
```

## Describe the issue

I find the launcher instance always failed and shut down when executing the `pip download` command.

```
INFO:apache_beam.runners.portability.stager:Executing command: ['/usr/local/bin/python', '-m', 'pip', 'download', '--dest', '/tmp/dataflow-requirements-cache', '-r', '/dataflow/template/requirements.txt', '--exists-action', 'i', '--no-binary', ':all:']
```

I think this is a resource issue because the launcher always uses n1-standard-1,
and I could not found a way to change it.

**Comment by davidcavazos** [comment]
Hi @rororo, I haven't run into that issue before. Can you give us more information to try to see what's going on?

* What version of Python are you using?
* What command are you using to run the pipeline?
* Could you copy-paste the section of the logs where it fails?
* If you remove the `Jinja` and `pymongo[srv]` requirements (and maybe run in a clean virtual environment), does it still fail?

I suspect there might be an incompatible version of some library introduced by the additional requirements.

If removing the `Jinja` and `pymongo[srv]` makes it work, then you could make a new virtual environment with just `apache-beam[gcp]` and do a `pip freeze`, then install the other dependencies and do another `pip freeze`. Maybe you can spot a version mismatch. If that's the case, then pinning to those specific versions in your `requirements.txt` file might fix it.

**Comment by richardo-ps** [comment]
@rororo Running into the same issue here. Did you find a fix?

**Comment by leahecole** [comment]
@richardo-ps - sorry to hear you're having this issue too! It might help if you give some of the info @davidcavazos was looking for from @rororo - we can never have too much info to help debug! 😄

**Comment by meredithslota** [comment]
I'm going to close this out - please reopen if you are still seeing this and have info that might help us get a repro. Thanks!
