### ISSUE TITLE
Google Cloud Function"finished with status: 'crash'"

### ISSUE THREAD

**Issue by GuanacoDevs** [GoogleCloudPlatform/python-docs-samples#4005]
## In which file did you encounter the issue?

Google Cloud Functions for python
### Did you change the file? If so, how?

No

## Describe the issue

I have been deploying a few functions, and some of them crashes without any message of the crash I have been able to debug the issue adding manually a `try/except` but in some instances it does not show not even the `stacktrace` only `Function execution took 1002 ms, finished with status: 'crash'`

The very first time that this happened to me i asked a [Question in StackOverflow](https://stackoverflow.com/questions/61647500/how-to-deploy-python-google-cloud-function-with-local-dependencies?noredirect=1#comment109072836_61647500), now I'm trying to move a file from one bucket to another using: 
```
        try:
            # gif_blob = storage_client.get_bucket(MAIN_BUCKET).get_blob(file_name)
            # gif_blob = storage_client.get_bucket(MAIN_BUCKET).blob(file_name)
            gif_blob = storage_client.bucket(MAIN_BUCKET).blob(file_name)
            gif_blob.upload_from_filename(temp_filename_in)
        except:
            [logging.error(line) for stack in traceback.format_exception(*sys.exc_info()) for line in stack.splitlines()]

```
But the issue is that not even the try/catch tells me where my error is, therefore I can not debug my functions properly.

**Comment by di** [comment]
This is a known issue that is in the process of being fixed: https://issuetracker.google.com/issues/155215191
