### ISSUE TITLE
testing: consider how to preserve logs for btlr workers even if the CI job timed out

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#4104]
[Example build](https://source.cloud.google.com/results/invocations/30295de3-f92a-44a5-9d5d-d5aff4ad2bda)

This build timed out. We lost majority of the invocation logs.
Questions:

Is it worth spending our time to preserve logs even the CI job times out.
(Actually all the xml test result files are uploaded, so maybe we can live with the current situation)
If yes, how to achieve this?

I think Kokoro uploads all the `build.log` in the artifact dir, but I'm not sure.

**Comment by kurtisvg** [comment]
Does it send a kill command to the process? We can probably update it to output results even when interrupted.

**Comment by tmatsuo** [comment]
@kurtisvg dunno. Maybe you can ask Kokoro team.
