### ISSUE TITLE
Docker image rebuilt for dependency update PR

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/python-docs-samples#4113]
PR: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4109

Log: https://source.cloud.google.com/results/invocations/62276164-4adf-42d7-ae21-c96d43abe161/targets

The PR is only updating `requirements.txt`, but the docker re-build was triggered.

**Comment by busunkim96** [comment]
It appears to have happened again in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4122

**Comment by tmatsuo** [comment]
Fixed by #4123
