### ISSUE TITLE
Unable to Launch Flexy Python Intstance

### ISSUE THREAD

**Issue by pkonkodi** [GoogleCloudPlatform/python-docs-samples#4133]
## Dataflow Error
When I launch instance, I get below mentioned issue,
  Failed to start the VM, launcher-202006191438199204637963205780746, used for launching because of status code: INVALID_ARGUMENT, reason: Error: Message: Invalid value for field 'resource.networkInterfaces[0]': '{ "network": "global/networks/default", "accessConfig": [{ "type": "ONE_TO_ONE_NAT", "name":...'. Subnetwork should be specified for custom subnetmode network HTTP Code: 400.

## Supporting files
[supporting files.zip](https://github.com/GoogleCloudPlatform/python-docs-samples/files/4806788/supporting.files.zip)

## Steps to reproduce:

I have executed the following commands to standard up Flexy instance
1. Performed Docker build 
     docker build -t dataflow_flexy .
2. Tagged the image to repository 
     docker tag dataflow_flexy gcr.io/ProjectId/samples/dataflow/streaming-beam:latest
3. Pushed the image to repo
    docker push gcr.io/ProjectId/samples/dataflow/streaming-beam:latest
4. Performed the build
    gcloud beta dataflow flex-template build \
  gs://bucket-name/templates/template_df \
  --image "gcr.io/ProjectId/samples/dataflow/streaming-beam:latest" \
  --sdk-language "PYTHON" \
  --metadata-file "metadata.json"
5. Executed Dataflow Flexy
   gcloud beta dataflow flex-template run "<job-id>" \
  --template-file-gcs-location "gs://bucket-name/templates/template_df"  

I have also tried with  --parameters experiments="disable_flex_template_entrypoint_overrride", no luck

It looks like dataflow expecting subnetwork parameter. Unfortunately, I don't see that option in gcloud

**Comment by davidcavazos** [comment]
There were some instructions that weren't adapted from the Java version. We will be merging those changes shortly. There were also some validation issues in the Python example, fixed on #4244 

I hope that fixes the INVALID_ARGUMENT error.

**Comment by davidcavazos** [comment]
The new version of the docs with the fixed Python instructions was published on July 10, 2020.

**Comment by pkonkodi** [comment]
I am still getting error for subnet

gcloud beta dataflow flex-template run "custom-df1" --template-file-gcs-location "gs://projectId/templates/custom_df" --region "us-central1"  --subnetwork "regions/us-central1/subnetworks/default"
ERROR: (gcloud.beta.dataflow.flex-template.run) unrecognized arguments:
  --subnetwork
  regions/us-central1/subnetworks/default
  To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS

**Comment by davidcavazos** [comment]
@manavgarg do you know what's going on here? Are subnetworks supported?

**Comment by manavgarg** [comment]
We do support specifying subnetwork parameter. You need to specify it using the --parameters flag as listed here:https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dataflow/flex-templates/streaming_beam#running-a-dataflow-flex-template-pipeline

**Comment by meredithslota** [comment]
I'm guessing that this issue has been resolved so going to go ahead and close it but feel free to reopen, @pkonkodi, if you are still having trouble.
