### ISSUE TITLE
speech_streaming.py ERROR - something related to GPRC I suppose

### ISSUE THREAD

**Issue by mark4in** [GoogleCloudPlatform/python-docs-samples#414]
> python speech_streaming.py 

D0712 23:18:44.320062112    2197 ev_posix.c:101]             Using polling engine: poll
Traceback (most recent call last):
  File "speech_streaming.py", line 147, in <module>
    main()
  File "speech_streaming.py", line 139, in main
    service.Recognize(request_stream(stop_audio), DEADLINE_SECS))
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 539, in __getattr__
    raise AttributeError('_DynamicStub object has no attribute "%s"!' % attr)
AttributeError: _DynamicStub object has no attribute "Recognize"!

---
The REST based speech sample scripts are running fine.

> pip list - shows all the required tools and dependencies installed.

**Comment by jonparrott** [comment]
This should now be resolved, can you update your copy and try again?

/cc @xinjiez
