### ISSUE TITLE
run_tests_local.sh isn't working on MacOS

### ISSUE THREAD

**Issue by evil-shrike** [GoogleCloudPlatform/python-docs-samples#4166]
as there's no `realpath` tool on MacOS
```
/../../scripts/run_tests_local.sh: line 49: realpath: command not found 
```
it can be used from `coreutils` package:
```
brew install coreutils 
```
if it's OK (it seems so), please update the README.

**Comment by tmatsuo** [comment]
@evil-shrike Thanks! #4167 will fix this
