### ISSUE TITLE
help in create vm instance API details  

### ISSUE THREAD

**Issue by ravikumar1907** [GoogleCloudPlatform/python-docs-samples#4205]
Could some one help me how to pass public ssh-key while creating vm instance using client library : https://cloud.google.com/compute/docs/tutorials/python-guide
I failed to find a example to pass ssh public while creating vm instance.in https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/compute/api/create_instance.py

**Comment by kurtisvg** [comment]
Hi @ravikumar1907,

In the future, you'll have better luck directing your request to [StackOverflow](https://stackoverflow.com/questions/tagged/google-compute-engine) - this forum is for tracking issues with our samples provided in our documentation, and not for general support. 

I believe you can do what you are trying to accomplish by [editing the metadata for the instance](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/7a4a7e02f84ad10626d9be4a526002fa90a8a4aa/compute/api/create_instance.py#L92). For more information, check out the [Managing SSH keys in metadata](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys#api) page.
