### ISSUE TITLE
ERROR: (gcloud.alpha.events.triggers.create) Unknown event type: com.google.cloud.auditlog.event

### ISSUE THREAD

**Issue by nanukn** [GoogleCloudPlatform/python-docs-samples#4228]
## In which file did you encounter the issue?

Create Cloud Storage trigger section of README at https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/run/events-storage

### Did you change the file? If so, how?

No

## Describe the issue

When running the command shown on the README:
`gcloud alpha events triggers create $MY_GCS_TRIGGER \
 --target-service "$MY_RUN_SERVICE" \
 --type com.google.cloud.auditlog.event \
 --parameters methodName=storage.buckets.update \
 --parameters serviceName=storage.googleapis.com \
 --parameters resourceName=projects/_/buckets/"$MY_GCS_BUCKET"`

I receive this error:
> ERROR: (gcloud.alpha.events.triggers.create) Unknown event type: com.google.cloud.auditlog.event. If you're trying to use a custom event type, add the "--custom-type" flag

**Comment by busunkim96** [comment]
Hi @nanukn,

It looks like that feature is fairly new. Could you try [updating your gcloud version](https://cloud.google.com/sdk/gcloud/reference/components/update) and re-running the command? `gcloud components update`

**Comment by nanukn** [comment]
Read the conversation at #4232 and it appears only whitelisted projects can use events. Going to close this ticket because I pivoted to using GKE with istio and knative installed instead of managed Cloud Run.

**Comment by grant** [comment]
@nanukn Alpha command require whitelisted projects.
https://forms.gle/ZhQoHYXo7ZFLWTRV6
