### ISSUE TITLE
[tests] Tests in tables/automl/dataset_test.py expect to have  access to gs://python-docs-samples-tests-automl-tables-test

### ISSUE THREAD

**Issue by evil-shrike** [GoogleCloudPlatform/python-docs-samples#4233]
## In which file did you encounter the issue?

tables/automl/dataset_test.py

## Describe the issue
All tests are failing with error:
AccessDeniedException: 403 xxx@xxx.com does not have storage.objects.list access to the Google Cloud Storage bucket.

It's not clear what account should I use for tests. All that said in AUTHORING_GUIDE.MD is that I need to setup my own project. But this GCS absolute bucket path is hard-coded inside tests file. How should I get access to this bucket?

**Comment by sirtorry** [comment]
pr merged.
