### ISSUE TITLE
~/training-data-analyst/courses/developingapps/python/datastore/start/run_server.py is broken - throws Flask error in GCP lab testing

### ISSUE THREAD

**Issue by Rubix982** [GoogleCloudPlatform/python-docs-samples#4234]
## In which file did you encounter the issue?

The file path is `/training-data-analyst/courses/developingapps/python/datastore/start/run_server.py`, specifically, `training-data-analyst/courses/developingapps/python/datastore/start/quiz/webapp/routes.py`, and `training-data-analyst/courses/developingapps/python/datastore/start/quiz/webapp/questions.py`

### Did you change the file? If so, how?

I have not touched those files.

## Describe the issue

Issue was encountered when working with [this lab - App Dev: Storing Application Data in Cloud Datastore - Python](https://www.qwiklabs.com/focuses/1076?parent=catalog) on Qwiklabs. 

Under `Run the application and create a Cloud Datastore entity`, following the steps, and only modifying,
```
~/training-data-analyst/courses/developingapps/python/datastore/start/quiz/gcp/datastore.py
```

The issue is encountered or recreated when you run `python run_server.py`, head over to the new server generated by GCP, then heading into the create quiz, entering the values provided by the lab, and then on clicking `create`, doing so gives back the follllwoing output,

![image](https://user-images.githubusercontent.com/41635766/86409360-2a79c980-bcd2-11ea-8beb-faa323976396.png)

I have double checked that,
1. I exported the GCLOUD_PROJECT variable in my GCP console session, the syntax used was `export GCLOUD_PROECT=$DEVSHELL_PROJECT_ID
2. That I wrote my code as it is, no syntactical issues

I'm confused about the key issue. It definitely is exported, and my code seems to be as it is. Pictures of my code are,

1. ![image](https://user-images.githubusercontent.com/41635766/86409643-bab80e80-bcd2-11ea-863b-3ba42243e4c3.png)
2. ![image](https://user-images.githubusercontent.com/41635766/86409684-cdcade80-bcd2-11ea-86d3-90c7a5c1ea39.png)

That's pretty much it. Thanks!

**Comment by tmatsuo** [comment]
@Rubix982 Thanks for the report, but which file should I look at in this repo? I don't see `run_server.py` in this repo.

**Comment by Rubix982** [comment]
Looking back at this question, I must have been extremely sleep. :I 
Meant to post this at https://github.com/GoogleCloudPlatform/training-data-analyst instead of here.
I'm really sorry. Let me close this.
