### ISSUE TITLE
How to add progress bar when downloading large files.

### ISSUE THREAD

**Issue by shahanaz873** [GoogleCloudPlatform/python-docs-samples#4269]
I am downloading a large file (5GB) from the bucket.  How to show progress bar when  blob.download_to_filename(destination_file_name) starts and ends

**Comment by busunkim96** [comment]
Hi, it looks like this isn't currently a feature of the library. See https://github.com/googleapis/python-storage/issues/27.

Someone did post a workaround which may work for you.

**Comment by shahanaz873** [comment]
@busunkim96 I followed the above workaround but how to read the source file from the bucket to download. 

`
def download_file(bucket, dest_file_name):
    blob_name = config_data['name']
    blob = bucket.get_blob(blob_name)
    size = blob.size
    content_type = blob.content_type
    try:
        with open(blob, "wb") as in_file:
            total_bytes = os.fstat(in_file.fileno()).st_size
        with tqdm.wrapattr(blob, "read", total=size, miniters=1,
                           desc="Downloading") as destination_file_name:
            blob.download_to_filename(destination_file_name, content_type=content_type, size=size)
            return blob
    except Exception as e:
        print(e)
`
