### ISSUE TITLE
Secured Read Failed - FD Shutdown error on Async GRPC request

### ISSUE THREAD

**Issue by mitbeaver** [GoogleCloudPlatform/python-docs-samples#427]
I'm having issues with the async grpc reqest.  I have uploaded the audio raw file to GS under the project with the service account I'm using for authentication.

I'm able to access the file fine via gsutil and verified that the ACL seems to have the service account:

johndoe@xyz.com:~/google/python-docs-samples/speech/api$ gsutil cp gs://#####/audio.raw .
Copying gs://#####/audio.raw...
Downloading file://./audio.raw:                                  56.6 KiB/56.6 KiB 

johndoe@xyz.com:~/google/python-docs-samples/speech/api$ gsutil acl get gs://#####/audio.raw
[
  {
    "email": "#####@call-qa.iam.gserviceaccount.com",
    "entity": "user-#####@call-qa.iam.gserviceaccount.com",
    "role": "OWNER"
  }
]

But, keep getting the following transport errors

johndoe@xyz.com:~/google/python-docs-samples/speech/api$ python speech_async_grpc.py gs://#####/audio.raw
D0721 10:58:13.542879368   20691 ev_posix.c:101]             Using polling engine: poll
name: "851082764888594635"

Waiting for server processing...
Waiting for server processing...
Waiting for server processing...
Waiting for server processing...

E0721 10:58:19.494730797   20691 chttp2_transport.c:1810]    close_transport: {"created":"@1469087899.491311775","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.c","file_line":157,"referenced_errors":[{"created":"@1469087899.491294226","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}

Which looks like it just can't reach Google Storage to read the file?  Just not sure what else to do or how to verify I have things setup properly.  I'm hoping this is just a permission issue and I'm being stupid :)

**Comment by jerjou** [comment]
It's probably not you being stupid :)
How are you [exposing](https://developers.google.com/identity/protocols/application-default-credentials#howtheywork) the service account to the script? Are you using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable? If not, can you try using that?

**Comment by puneith** [comment]
@mitbeaver Were you able to try @jerjou suggestion and make things work?

**Comment by jerjou** [comment]
Closing this for now. Please re-open if you're still having this issue, and we can dig deeper.
