### ISSUE TITLE
Question regarding PubSubToGCS.py

### ISSUE THREAD

**Issue by bryangaikwad** [GoogleCloudPlatform/python-docs-samples#4292]
Hello,

I have a question regarding:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/pubsub/streaming-analytics/PubSubToGCS.py

How does the "Add Dummy Key" step work at the moment? Looking at the pipeline code it looks like None has been added as the key
`
| "Add Dummy Key" >> beam.Map(lambda elem: (None, elem))
`

If I want to add a window key and another attribute to the GroubyBy, whats the best way of doing that? Thank you!

**Comment by bryangaikwad** [comment]
Solved the above problem. 

The only question I have now is:
1. In the above solution its mentioned make use of: `beam.util.BatchElements` if the window elements don't fit the instance memory. Do you have an example of how I can use the BatchElements in the above example? Thanks!

**Comment by anguillanneuf** [comment]
👋  @bryangaikwad Glad to hear you were able to solve the problem! 

```python
def expand(self, pcoll):
        return (
            pcoll
            | 'BatchElements' >> beam.util.BatchElements(**kwargs)
       )
```

Should do batching for you ([documentation](https://beam.apache.org/releases/pydoc/2.22.0/apache_beam.transforms.util.html#apache_beam.transforms.util.BatchElements)).
