### ISSUE TITLE
Add 3LO Auth examples for python clients

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/python-docs-samples#43]

**Comment by jerjou** [comment]
Note: integration tests can be tricky, since 3LO requires user intervention to authorize tokens.

**Comment by elibixby** [comment]
Is there an easy way to mock 3LO Flow? @jonparrott maybe has an idea?

**Comment by jonparrott** [comment]
The oauth2 decorators in oauth2client are well tested by that library specifically. No need to re-tread that ground, just test that the following:

1. No credentials -> redirect to auth screen
2. Has credentials -> gets through to page

**Comment by jerjou** [comment]
Yeah - how do you set up the has-credentials scenario? Do we just generate a refresh token for one of our accounts and put that in the repo? That sounds all kinds of sketch :)

**Comment by jonparrott** [comment]
Fake one, and never *actually* use it.

**Comment by jerjou** [comment]
Trouble is, if we want the test to be an integration test, we'll want the api call to actually be authenticated, so we can verify we're getting the expected (successful) response.
For unit tests, of course, we can mock to our heart's content.

**Comment by jonparrott** [comment]
:/ well, hmm, we should either see if we can obtain a test account specifically for this, or only do the int test for 2lo.

**Comment by elibixby** [comment]
Internally we have a way to get dummy accounts that don't last. Which I have been using to test my 3LO stuff. But this is a larger problem with Travis being on the other side of SSO.

**Comment by jonparrott** [comment]
We'll have a good 3lo sample once the [Flask 3LO Helper](https://github.com/google/oauth2client/pull/226) is merged.

**Comment by jonparrott** [comment]
Closing this as obsolete.
