### ISSUE TITLE
[Speech] Error - CancellationError(code=StatusCode.CANCELLED, details="")

### ISSUE THREAD

**Issue by heroddaji** [GoogleCloudPlatform/python-docs-samples#430]
I got this error after everything setup:
I just run the example code of speech_streaming

`
I0727 05:42:15.039469042    6765 socket_utils_common_posix.c:196] Disabling AF_INET6 sockets because socket() failed.
I0727 05:42:15.209272924    6764 http_client_filter.c:97]    Unexpected content-type 'text/html; charset=UTF-8'
ERROR CancellationError(code=StatusCode.CANCELLED, details="")
E0727 05:42:15.243894095    6766 chttp2_transport.c:1810]    close_transport: {"created":"@1469598135.235867967","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.c","file_line":157,"referenced_errors":[{"created":"@1469598135.235829686","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}
`

**Comment by jerjou** [comment]
Can you include a little more detail about your environment? Are you on a mac or raspberry pi or linux on some other platform? I assume you're using python2? Are you in a virtualenv? Are you behind any sort of network proxy? Do you know at around what line you're encountering this error (you can try using `pdb` to step through, or just scatter `print` statements to narrow down where the error is thrown)? It looks like it's getting an html page when it tries to make an http request, which seems to be causing the error, so just trying to figure out why you might be getting an html page, and from what call.
