### ISSUE TITLE
Setting up Http functions - GCP Image Download - Invoke Http Request

### ISSUE THREAD

**Issue by siva2k16** [GoogleCloudPlatform/python-docs-samples#4339]
I am trying to implement http function for
 - Download image from bucket
 - Run another request to pass the image to process

The setup is similar to
├── main.py
├── requirements.txt
└── mylocalpackage/
    ├── __init__.py
    ├── credentials.json
    └── myscript.py

1. Able to deploy it as http request
gcloud functions deploy main --runtime python37 --trigger-http --allow-unauthenticated

2. Error returned is 'Error: could not handle the request'

3. Logs mention - textPayload: "Function execution took 19 ms, finished with status: 'crash'" 

Can I get any inputs from google team / subject matter experts.

**Comment by tmatsuo** [comment]
Sorry, it's more of a general question. Please use Stackoverflow for this purpose.
