### ISSUE TITLE
JWT auth error in jwt_token_gen.py and bookstore_client.py under python3

### ISSUE THREAD

**Issue by wwuck** [GoogleCloudPlatform/python-docs-samples#4340]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/bookstore-grpc/jwt_token_gen.py

### Did you change the file? If so, how?

Yes, updated to run `.decode('utf-8')` on the `signed_jwt` before it is printed to `stdout`.

## Describe the issue

Running the sample from https://cloud.google.com/endpoints/docs/grpc/service-account-authentication, and also reading the documentation at https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/bookstore-grpc/README.md#generating-a-jwt-token-from-a-service-account-file.  They state that the output from `jwt_token_gen.py`
 can be used directly as input into `bookstore_client.py --auth_token`.

This works fine for python2 but is broken in python3 as the output of `jwt_token_gen.py` now wraps the token with `b'<token>'` under python3.

There was a similar bug report for another sample client file at https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1958.

**Comment by ace-n** [comment]
@tmatsuo I'm not sure who the right person for this is, but I don't work on endpoints anymore.

Maybe @simonz130 knows?
