### ISSUE TITLE
Re-organize speech api samples

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/python-docs-samples#437]
Currently apiary and grpc samples are in the sample folder. The structure should be updated to:

* /speech
  * /api-client
    * /requirements.txt
    * /main.py (or snippets.py)
  * /grpc
    * /requirements.txt
    * /main.py (or snippets.py)

**Comment by jonparrott** [comment]
@jerjou @puneith bump?

**Comment by jerjou** [comment]
On it
