### ISSUE TITLE
Cloud IoT End-to-End server example is not pulling telemetry data from subscription

### ISSUE THREAD

**Issue by adwinang** [GoogleCloudPlatform/python-docs-samples#4371]
## In which file did you encounter the issue?
python-docs-samples/iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py

### Did you change the file? If so, how?
I set the default cloud region to be asia-east1 in the example mqtt device

## Describe the issue
I pushed data to my topic
`python cloudiot_pubsub_example_mqtt_device.py \
--project_id=letterbot-staging \
--registry_id=test \
--device_id=adwin-macbook2 \
--private_key_file=rsa_private.pem \
--algorithm=RS256
Creating JWT using RS256 from private key file rsa_private.pem
Connection Result: 0: No error.
Publishing payload {"temperature": 1}
Subscribed:  (1,)
Received message '' on topic '/devices/adwin-macbook2/config' with Qos 1
Published message acked.
Publishing payload {"temperature": 2}`

But the server does not detect addition to the subscription
`python cloudiot_pubsub_example_server.py  \
--project_id=letterbot-staging \
--pubsub_subscription=test
Listening for messages on projects/letterbot-staging/subscriptions/test`

I have checked on the gcloud cli to make sure that the data is properly pushed to the topic and I am able to pull data from the subscription

`gcloud pubsub subscriptions pull --auto-ack projects/letterbot-staging/subscriptions/test --limit=1000
┌──────────────────────┬──────────────────┬───────────────────────────────────┬──────────────────┐
│         DATA         │    MESSAGE_ID    │             ATTRIBUTES            │ DELIVERY_ATTEMPT │
├──────────────────────┼──────────────────┼───────────────────────────────────┼──────────────────┤
│ {"temperature": 2}   │ 1408746150116512 │ deviceId=adwin-macbook2           │                  │
│                      │                  │ deviceNumId=3264992015176080      │                  │
│                      │                  │ deviceRegistryId=test             │                  │
│                      │                  │ deviceRegistryLocation=asia-east1 │                  │
│                      │                  │ projectId=letterbot-staging       │                  │
│                      │                  │ subFolder=                        │                  │
│ {"temperature": 3}   │ 1408746684520232 │ deviceId=adwin-macbook2           │                  │
│                      │                  │ deviceNumId=3264992015176080      │                  │
│                      │                  │ deviceRegistryId=test             │                  │
│                      │                  │ deviceRegistryLocation=asia-east1 │                  │
│                      │                  │ projectId=letterbot-staging       │                  │
│                      │                  │ subFolder=                        │`

**Comment by tranthanhtung04101995** [comment]
Looks like you're missing: --cloud_region = us-central1 and --mqtt_bridge_port = 8883

**Comment by adwinang** [comment]
@tranthanhtung04101995 the two arguments I presume are meant for the device example which is working by checking via the 
`gcloud pubsub subscriptions pull --auto-ack projects/letterbot-staging/subscriptions/test --limit=1000`
In the description.

The original server example code does not require those two arguments

**Comment by adwinang** [comment]
Ok somehow it got fixed, so I'm going to close this
