### ISSUE TITLE
CODEOWNERS file needs updates

### ISSUE THREAD

**Issue by tequilarista** [GoogleCloudPlatform/python-docs-samples#4381]
## In which file did you encounter the issue?

.github/CODEOWNERS

### Did you change the file? If so, how?

PR opened

## Describe the issue

A number of component areas are missing reviewers or the reviewers are out of date.

**Comment by busunkim96** [comment]
Hi @tequilarista. If there incorrectly assigned owners please send a PR and we'll happily merge it. :)

**Comment by engelke** [comment]
I will reach out individually to each person in the file to make sure they are still appropriate.
