### ISSUE TITLE
Python firebase_admin SDK randomly returning 503 error 

### ISSUE THREAD

**Issue by codal-mharkhani** [GoogleCloudPlatform/python-docs-samples#4396]
I have one python script, which is executing at every 4 minutes from the AWS lambda function. it will do GET and UPDATE query on firestore. this script is worked 15 days without any issue. and suddenly started raising 503 errors randomly, like 30% it is returning 503 errors. please help me ASAP how can I resolve it

```
Deadline of 600.0s exceeded while calling functools.partial(<function _wrap_stream_errors.<locals>.error_remapped_callable at 0x7fe5a9c26840>, parent: "projects/contap-dev/databases/(default)/documents/dev_virtual_speed/3121"
structured_query {
  from {
    collection_id: "speedMembers"
  }
}
, metadata=[('google-cloud-resource-prefix', 'projects/contap-dev/databases/(default)'), ('x-goog-request-params', 'parent=projects/contap-dev/databases/%28default%29/documents/dev_virtual_speed/3121'), ('x-goog-api-client', 'gl-python/3.6.10 grpc/1.30.0 gax/1.21.0 gapic/1.8.1 gccl/1.8.1')]), last exception: 503 failed to connect to all addresses: RetryError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 255, in lambda_handler
    available_users = get_available_users(event_id, db)
  File "/var/task/lambda_function.py", line 49, in get_available_users
    available_users = [i.id for i in event_member]
  File "/var/task/lambda_function.py", line 49, in <listcomp>
    available_users = [i.id for i in event_member]
  File "/var/task/google/cloud/firestore_v1/query.py", line 859, in stream
    metadata=self._client._rpc_metadata,
  File "/var/task/google/cloud/firestore_v1/gapic/firestore_client.py", line 1311, in run_query
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/var/task/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/var/task/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/var/task/google/api_core/retry.py", line 206, in retry_target
    last_exc,
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling functools.partial(<function _wrap_stream_errors.<locals>.error_remapped_callable at 0x7fe5a9c26840>, parent: "projects/contap-dev/databases/(default)/documents/dev_virtual_speed/3121"
structured_query {
  from {
    collection_id: "speedMembers"
  }
}
, metadata=[('google-cloud-resource-prefix', 'projects/contap-dev/databases/(default)'), ('x-goog-request-params', 'parent=projects/contap-dev/databases/%28default%29/documents/dev_virtual_speed/3121'), ('x-goog-api-client', 'gl-python/3.6.10 grpc/1.30.0 gax/1.21.0 gapic/1.8.1 gccl/1.8.1')]), last exception: 503 failed to connect to all addresses
```

**Comment by leahecole** [comment]
Hi, I'm sorry you're having this issue. To help us debug, could you please fill out the rest of the template, including in which sample file you encountered the issue and what changes you made? 

If your problem isn't with one of the samples in this repo, but instead with something you created, you may want to open an issue with the [firebase admin SDK](https://github.com/firebase/firebase-admin-python) directly 

## In which file did you encounter the issue?



### Did you change the file? If so, how?



## Describe the issue

**Comment by codal-mharkhani** [comment]
@leahecole 

`  if not firebase_admin._apps:
        cred = credentials.Certificate(
            'authorization.json')
        firebase_admin.initialize_app(cred)
    
    db = firestore.client()`

when try to fetch user it is returning above error
`def get_available_users(event_id, db):
    """
    get a list of available user
    """
    # need to optimize where get a list of the user within one query

    event_member = db.collection(
        '{0}_virtual_speed/{1}/speedMembers'.format(
            SENDBIRD_ENV, event_id)).get()
    available_users = [i.id for i in event_member]
    return available_users`

**Comment by leahecole** [comment]
Hi @codal-mharkhani, from what I can tell, this issue is not related to any examples found in this repo so I'm closing it. If it is though, please link to the related sample in this repo (python-docs-samples) and feel free to reopen! Otherwise, please open an issue in the [firebase admin repo](https://github.com/firebase/firebase-admin-python/issues) where you will be able to get some help with folks familiar with this tooling 🙂
