### ISSUE TITLE
Add notebook testing

### ISSUE THREAD

**Issue by vuppalli** [GoogleCloudPlatform/python-docs-samples#4408]
## In which file did you encounter the issue?

This issue is related to new notebook code that will be added to this repository.
PR: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4389

## Describe the issue

Add testing for notebooks to this repository after @sirtorry finishes his work on notebook testing with [ai-platform-samples](https://github.com/GoogleCloudPlatform/ai-platform-samples).

The notebook also includes testing setup code (first cell) and teardown code (last cell) that uploads resources to GCS and BigQuery. However, if the code fails, the teardown cell will not execute. There needs to be a resource cleanup script for this as well.

**Comment by meredithslota** [comment]
(Accidental un-assign, meant to just add @ivanmkc.)

**Comment by ivanmkc** [comment]
@bradmiro can you let me know if this repo needs a notebook testing CI?

**Comment by bradmiro** [comment]
@ivanmkc does that repo have automated notebook testing? Maybe we can move the notebooks there. 

@leahecole wdyt?

**Comment by leahecole** [comment]
Oooo that would be convenient. I know we have our data-science-onramp notebook but I also know these old samples are still kickin around https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/notebooks

If they seem like good candidates to move, let's do it, or if there's a process for onboarding a repo to notebook CI the @GoogleCloudPlatform/python-samples-owners and I would love to know it!

**Comment by leahecole** [comment]
Adding Lo to this old issue because they're making it happen!

**Comment by leahecole** [comment]
Closed this because @ivanmkc marked this as verified internally. For future reference @ivanmkc when you mark things as fixed on buganizer you need to also need to close them here otherwise the mirror will keep opening it :)
