### ISSUE TITLE
Add region tags to Data Science Onramp code

### ISSUE THREAD

**Issue by vuppalli** [GoogleCloudPlatform/python-docs-samples#4409]
## In which file did you encounter the issue?

The code in python-docs-samples/data-science-onramp needs to have region tags added to it.

## Describe the issue

The code in this folder needs region tags added to it so since it is going to be a tutorial living in cloud.google.com. Specifically, the feature engineering code ([PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4389)) needs these tags so that the testing setup and teardown cells will get hidden from the end user.

**Comment by leahecole** [comment]
Also we'll need to update the readme to point to the datacleaning code
