### ISSUE TITLE
speech stop listening after few seconds

### ISSUE THREAD

**Issue by heroddaji** [GoogleCloudPlatform/python-docs-samples#442]
So I manage to make speech works on my rpi3 using the sample code speech_streaming.py.
But I want my program always listen for a long period of time (days).

But the sample code seem to be able to listen for brief moment after it start-ups. I speak a few sentences, then I silent for a few secs, then in the transcript response, I will see the accuracy value. After that, the program stop listening, but the app does not quit, it just stay there

So is their a way to make the script listen forever?
and if there is no way to do it, can I constantly reset the request every few seconds, then there is alway listening thread? 

Also my concern is when I reset the listening thread and there is no sound to recognize, will it count as 1 speech_api request?

**Comment by jerjou** [comment]
Out of curiosity - what did you end up having to tweak to get things running on the rpi?

Take a look at the [usage limits](https://cloud.google.com/speech/limits). Basically, it'll only recognize for a minute at a time. What you could do is to [detect silences](http://stackoverflow.com/questions/2668442/detect-and-record-a-sound-with-python), and only start streaming audio to the api when there's someone speaking, and close the connection once you detect silence again (after some pause, presumably, to allow for folks taking a breath or whatnot).

**Comment by heroddaji** [comment]
thank you for your answer.
So when you say it'll only recognize for a minute, you mean at one time or many time?
- so can I speak many times during one minute and get recognized, or just one time, but with maximum speak duration of 1 minute?
