### ISSUE TITLE
`cdn.firebase.com` support dropped in favor of `gstatic`

### ISSUE THREAD

**Issue by bojeil-google** [GoogleCloudPlatform/python-docs-samples#4421]
Hey folks, Firebase is no longer releasing new binaries via `cdn.firebase.com`.
This specifically applies to FirebaseUI usage in the [samples](https://github.com/GoogleCloudPlatform/python-docs-samples/search?q=cdn.firebase.com&unscoped_q=cdn.firebase.com).

Basically you just need to replace:
```
<script src="https://cdn.firebase.com/libs/firebaseui/4.5.0/firebaseui.js"></script>
<link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/4.5.0/firebaseui.css">
```

with:
```
<script src="https://www.gstatic.com/firebasejs/ui/4.5.0/firebase-ui-auth.js"></script>
<link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/4.5.0/firebase-ui-auth.css" />
```

All older versions are also available in gstatic.

Issue was brought in this thread: https://github.com/firebase/firebaseui-web/issues/651#issuecomment-667615303

**Comment by engelke** [comment]
Fixed in PR #4456
