### ISSUE TITLE
Test failure in memorystore/redis

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#4481]
[Build](https://source.cloud.google.com/results/invocations/97357480-466d-4978-bb58-f36f4a87843b/targets)

```
ERROR: (gcloud.redis.instances.create) {
  "code": 8,
  "message": "Unable to create instance. System limit for internal resources has been reached. Please request higher limit here: https://forms.gle/zY66qAosE75F6SNi7"
}
```

**Comment by tmatsuo** [comment]
@ericschmidtatwork

I guess we can just request the quota bump. WDYT?

**Comment by tmatsuo** [comment]
I noticed there is one instance in our test project, so I manually deleted it. I also requested a quota bump.

**Comment by ericschmidtatwork** [comment]
Thanks - did it look like an instance that was left over from the test? Might it not be cleaning up properly?
