### ISSUE TITLE
billing: clean up sample added in #4494

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/python-docs-samples#4505]
The following items need to be cleaned up in the `billing` directory once #4494 is merged:

1) Update the code to use GAPIC libraries.
2) Add tests similar to [the ones the Node.js sample uses](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/functions/billing/test).

**Comment by meredithslota** [comment]
I'm reclassifying this as a `bug` to address the lack of tests.

**Comment by busunkim96** [comment]
I've rewritten this to use the `google-cloud-billing` library in #7432, but the tests still need work.

@ace-n The Node.js samples look like they use a live project, is that correct? There were some warnings about removing billing accounts in the docs, but if the Node CI project is okay the python ones will probably be okay as well.

**Comment by ace-n** [comment]
@busunkim96 you're correct; that project ID is `cdpe-functions-billing-test`.

**Comment by NimishC** [comment]
Thank you, @busunkim96 !

**Comment by busunkim96** [comment]
Closed by #7432.
