### ISSUE TITLE
typo in cd path in qwiklabs course 

### ISSUE THREAD

**Issue by ilam-natarajan** [GoogleCloudPlatform/python-docs-samples#4541]
## In which file did you encounter the issue?

https://googlecourses.qwiklabs.com/focuses/11362?parent=catalog

## Describe the issue

Above url says

Navigate to the source directory
cd python-docs-samples/appengine/standard_python37/hello_world

but the actual path is 
cd python-docs-samples/appengine/standard_python3/hello_world

<img width="780" alt="Screenshot 2020-08-21 at 16 20 52" src="https://user-images.githubusercontent.com/28389350/90907422-dd110300-e3ca-11ea-910f-729ccfc28b1a.png">

sorry if I should not be reporting this issue here. the qwiklabs support team is very slow.

**Comment by leahecole** [comment]
Hey @engelke I think you did this move - if you're not the right person though could you assign it to whoever is pretty please? Thank you!

**Comment by engelke** [comment]
We don't control QuikLabs content, which is what needs to be updated to reflect the change we made in the path. I have reported the need to fix this to the QuikLabs team.
