### ISSUE TITLE
bq://product-stockout.product_stockout.stockout project not found error

### ISSUE THREAD

**Issue by tfayyaz** [GoogleCloudPlatform/python-docs-samples#4553]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/tables/automl/notebooks/retail_product_stockout_prediction/retail_product_stockout_prediction.ipynb

### Did you change the file? If so, how?

No changes

## Describe the issue

It appears that the project for the BQ dataset is missing - bq://product-stockout.product_stockout.stockout 

The following error came up:

```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "The BigQuery dataset bq://product-stockout.product_stockout doesn't exist."
```

**Comment by leahecole** [comment]
adding Seth in case he also knows anything

**Comment by shollyman** [comment]
I never seen this notebook, project, or dataset in my life.  From the history of the notebook it looks like sirtorry has more context.

Is this a case where we should be keeping the BQ resources in something cloud-samples-data?  Or is the sample reliant on another team producing the data?

**Comment by sirtorry** [comment]
My initial assessment is the original dataset is missing. Let me investigate this and yes we should move it to cloud-samples-data when all is said and done.

**Comment by sirtorry** [comment]
I've contacted original authors to resurface dataset.

**Comment by ivanmkc** [comment]
Update, the dataset is indeed missing. However, after internal discussion, we are looking to deprecate this notebook in favour of a more relevant sample for AutoML with regards to time-series data.
