### ISSUE TITLE
testing(run): timeout in run/logging-manual

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#4609]
I saw weird timeout in our py-3.8 builds.

[Build](https://source.cloud.google.com/results/invocations/4253288f-9bca-4cfc-b8cc-a31b2a4bb8de/targets)

```
nox > Running session py-3.8
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/py-3-8
nox > pip install -r requirements.txt
nox > pip install -r requirements-test.txt
nox > pytest --junitxml=sponge_log.xml
============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /workspace/run/logging-manual/.nox/py-3-8/bin/python
cachedir: .pytest_cache
rootdir: /workspace, configfile: pytest.ini
collecting ... collected 3 items

e2e_test.py::test_end_to_end PASSED                                      [ 33%]
main_test.py::test_no_trace_in_headers PASSED                            [ 66%]
main_test.py::test_with_cloud_headers PASSED                             [100%]

------- generated xml file: /workspace/run/logging-manual/sponge_log.xml -------
======================== 3 passed in 2103.89s (0:35:03) ========================
nox > Session py-3.8 was successful.


err: signal: killed
```

It seems like the test finishes rather quick, but btlr sent the signal.

**Comment by kurtisvg** [comment]
@tmatsuo It looks like the runtime was 2103.89s - 35 minutes. Is it possible that the job was hung on a different part - after nox was run?

**Comment by tmatsuo** [comment]
Oh you're right, so this is expected because now we limit each job to 30m:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/5df67f0af433fadd28ad29fc7fb10c37b26fc236/.kokoro/tests/run_tests.sh#L149

Let's close this for now and if the timeout continues, I'll do something about it.

**Comment by tmatsuo** [comment]
I actually ran the test, and the e2e test is taking a long time, way longer than expected. I think we should debug this further.

**Comment by tmatsuo** [comment]
@grant I think the test might be hanging indefinitely. Probably we should set timeout on log retrieval.

The test in question is in:
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/run/logging-manual

**Comment by tmatsuo** [comment]
I was wrong. When I ran the test locally, the e2e_test.py took like 30 minutes, but it succeeded.

I still think the e2e test shouldn't take that long. This causes the timeout in our test infrastructure.

**Comment by tmatsuo** [comment]
My current guess:

The following loop doesn't actually find the log in question somehow.

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/19f35d6b43456f45f512bd4c7e291ecca1cf0071/run/logging-manual/e2e_test.py#L128-L132

Also failing to report failure.

I may be wrong though.

**Comment by tmatsuo** [comment]
Or actually the service is taking a long time to return the first portion of the request.
Because we're not filtering with time, the server may need to scan huge amount of logs to process.

If this is the case, we can add time based filter and it will reduce the time significantly.

**Comment by tmatsuo** [comment]
I checked the test logs before the latest python-logging:
https://source.cloud.google.com/results/invocations/fa65013d-c660-4039-abbf-9be9bcbeeb19/targets

The build is on Aug 4th.
```
------------------------------------------------------------
- testing /workspace/run/logging-manual
------------------------------------------------------------

 Using noxfile-template from parent folder (/workspace).

Running session py-3.8
Creating virtual environment (virtualenv) using python3.8 in .nox/py-3-8
pip install -r requirements.txt
pip install -r requirements-test.txt
pytest --junitxml=sponge_log.xml
============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /workspace/run/logging-manual/.nox/py-3-8/bin/python
cachedir: .pytest_cache
rootdir: /workspace, configfile: pytest.ini
collecting ... collected 3 items

e2e_test.py::test_end_to_end PASSED                                      [ 33%]
main_test.py::test_no_trace_in_headers PASSED                            [ 66%]
main_test.py::test_with_cloud_headers PASSED                             [100%]

------- generated xml file: /workspace/run/logging-manual/sponge_log.xml -------
======================== 3 passed in 231.19s (0:03:51) =========================
```

**Comment by tmatsuo** [comment]
python-logging is updated with #4458 on Aug 7th.

In [the build logs on the build on Aug 10th](https://source.cloud.google.com/results/invocations/e6e0ea36-a7c9-4d74-891d-6c0f24c0397d/targets):

```
------------------------------------------------------------
- testing /workspace/run/logging-manual
------------------------------------------------------------

 Using noxfile-template from parent folder (/workspace).

Running session py-3.8
Creating virtual environment (virtualenv) using python3.8 in .nox/py-3-8
pip install -r requirements.txt
pip install -r requirements-test.txt
pytest --junitxml=sponge_log.xml
============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /workspace/run/logging-manual/.nox/py-3-8/bin/python
cachedir: .pytest_cache
rootdir: /workspace, configfile: pytest.ini
collecting ... collected 3 items

e2e_test.py::test_end_to_end PASSED                                      [ 33%]
main_test.py::test_no_trace_in_headers PASSED                            [ 66%]
main_test.py::test_with_cloud_headers PASSED                             [100%]

------- generated xml file: /workspace/run/logging-manual/sponge_log.xml -------
======================== 3 passed in 209.02s (0:03:29) =========================
```

**Comment by tmatsuo** [comment]
I think we can rule out the possibility of a defect in the latest python-logging.

**Comment by kurtisvg** [comment]
Maybe add a time component to the filter? could potentially be a lot of logs to iterate through

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/19f35d6b43456f45f512bd4c7e291ecca1cf0071/run/logging-manual/e2e_test.py#L120-L125

**Comment by tmatsuo** [comment]
@kurtisvg Good call.

https://cloud.google.com/logging/docs/view/advanced-queries#finding-quickly
States that `resource.type` is indexed. Adding timestamp might make the query faster.
