### ISSUE TITLE
dependency failure in language/cloud-client/v1

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#4610]
We have a dependency failure in language/cloud-client/v1.
[build](https://source.cloud.google.com/results/invocations/4253288f-9bca-4cfc-b8cc-a31b2a4bb8de/targets)

I'm assigning @busunkim96 because you have many experiences on similar issues. I'll appreciate it if you can take a look.

Log:
```
nox > Running session py-3.8
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/py-3-8
No user noxfile_config found: detail: No module named 'noxfile_config'
nox > pip install -r requirements.txt
nox > Command pip install -r requirements.txt failed with exit code 1:
Collecting google-cloud-language==1.3.0
  Using cached google_cloud_language-1.3.0-py2.py3-none-any.whl (83 kB)
Collecting google-api-core[grpc]<2.0.0dev,>=1.14.0
  Using cached google_api_core-1.22.1-py2.py3-none-any.whl (91 kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Using cached googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
Requirement already satisfied: setuptools>=34.0.0 in ./.nox/py-3-8/lib/python3.8/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-language==1.3.0->-r requirements.txt (line 1)) (49.6.0)
Collecting pytz
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting google-auth<2.0dev,>=1.19.1
  Using cached google_auth-1.21.0-py2.py3-none-any.whl (92 kB)
ERROR: Could not find a version that satisfies the requirement six>=1.10.0 (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-language==1.3.0->-r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for six>=1.10.0 (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-language==1.3.0->-r requirements.txt (line 1))
nox > Session py-3.8 failed.
PWD: /workspace/language/cloud-client/v1
[Buildcop] Sending logs to Build Cop Bot...
[Buildcop] See https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop.
[Buildcop] Done!
```

**Comment by busunkim96** [comment]
Oddly this only showed up in the 3.8 run.

I'm also not able to repro this locally. I've tried both `pip install -r requirements.txt` directly and doing `nox -s py-3.8`. 

My initial guess was that it had something to do with the new pip dependency resolver, but it looks like that is hidden away behind a [flag](https://pip.pypa.io/en/stable/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020) until October.  To check for conflicts in the tree I tried with the new flag `pip install --use-feature=2020-resolver -r requirements.txt` and that also succeeds.

Maybe there's something off with the pip version we have installed in the docker image?

**Comment by tmatsuo** [comment]
@busunkim96 Thanks! That's helpful. I'll take this from now on.

**Comment by tmatsuo** [comment]
I also tried to reproduce this with the Docker image by:

```
$ scripts/run_tests_local.sh language/cloud-client/v1 py-3.8
```

The test passed. Possibly our build fetched a bad pip version? Let's close this bug for now. I'll dig deeper if we see the same failure tomorrow.
