### ISSUE TITLE
AttributeError: 'TranslationServiceClient' object has no attribute 'location_path'

### ISSUE THREAD

**Issue by AhmedSamyMerah** [GoogleCloudPlatform/python-docs-samples#4616]
## Issue in following path

python-docs-samples/translate/cloud-client/translate_v3_translate_text.py 

I keep getting the following issue when trying to call the Translation API to make a simple translation, I tried changing to locationPath as mentioned in documentation but to no avail.

Any help would be appreciated.

<img width="735" alt="Screen Shot 2020-09-01 at 10 41 29 PM" src="https://user-images.githubusercontent.com/34383929/91926015-484cb600-eca4-11ea-976f-2b7e1e5a4c8b.png">

<img width="708" alt="Screen Shot 2020-09-01 at 10 39 12 PM" src="https://user-images.githubusercontent.com/34383929/91925892-f86def00-eca3-11ea-89ad-cb652f366474.png">

**Comment by busunkim96** [comment]
Hi @AhmedSamyMerah,

We're in the process of re-organizing the samples. An up-to-date version of this sample is in the python-translate repository. See https://github.com/googleapis/python-translate/blob/master/samples/snippets/translate_v3_translate_text.py

The v3 release of the google-cloud-translate library has some changes from the previous release. One of those is the removal of `location_path`.

CC @danoscarmike

**Comment by engelke** [comment]
The issue has been addressed above. Please re-open it if you still feel there is a problem. Thanks!

**Comment by Hemanthkumar2112** [comment]
I used this

`parent = client.common_location_path(project_id, location) `
