### ISSUE TITLE
AttributeError: 'str' object has no attribute 'detect_intent'

### ISSUE THREAD

**Issue by DeWolfRobin** [GoogleCloudPlatform/python-docs-samples#4618]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/824d2dd547f73780fda9a49d217fe8361c3217f6/dialogflow/cloud-client/detect_intent_texts.py#L51

### Did you change the file? If so, how?
Did not change the file

## Describe the issue

When I run the script I get this issue:

```
Traceback (most recent call last):
  File "google.py", line 78, in <module>
    args.project_id, args.session_id, args.texts, args.language_code)
  File "google.py", line 40, in detect_intent_texts
    session=session, query_input=query_input)
  File "G:\anaconda\lib\site-packages\dialogflow_v2\gapic\sessions_client.py", line 318, in detect_intent
    self.transport.detect_intent,
AttributeError: 'str' object has no attribute 'detect_intent'
```

When I do dir(dialogflow.SessionsClient) I can see the detect_intent in there

**Comment by munkhuushmgl** [comment]
@DeWolfRobin Which python version and which dialogflow api version are you using it for output this error?

**Comment by munkhuushmgl** [comment]
![image](https://user-images.githubusercontent.com/45373284/93933481-974f9f00-fcd6-11ea-8931-8f5696a23a04.png)
Current version seems to be stable when I ran tests

**Comment by telpirion** [comment]
Please check the library version that you are using. Reopen this issue if you continue to experience problems. Thank you!
