### ISSUE TITLE
Outdated example doesn't work

### ISSUE THREAD

**Issue by szeitlin** [GoogleCloudPlatform/python-docs-samples#4631]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/9b13a6f2701ab3b6b45eb28796ee29693631418a/firestore/cloud-client/snippets.py#L23-L26

### Did you change the file? If so, how?

No, I'm just trying to follow the example. 

## Describe the issue
![Screen Shot 2020-09-03 at 1 13 39 PM](https://user-images.githubusercontent.com/5185401/92162633-53f4c580-ede7-11ea-8a0c-9ebf2b9905c9.png)

I think the client now gets imported from `firebase_admin`, but I'm not sure. It's very confusing when there seems to be so much out of date code and documentation floating around.

**Comment by engelke** [comment]
The line should be db = firestore.Client(), not db = firestore.client(). The samples in the repo have the correct capitalization and they work. The case of "Client" in the non-working code must have been changed somehow when the code was copied.

The samples in this repository are tested at least daily, so they are not likely to be outdated.
