### ISSUE TITLE
I import image in gcp dicom store, but on my pubsub topic assigned dicom store is not publishing message

### ISSUE THREAD

**Issue by ankitdata** [GoogleCloudPlatform/python-docs-samples#4638]
**steps**

### I create

- dicom dataset
- inside dataset dicom store
- pubsub topic for dicom store

**Issue**
I am trying to import dcm image to dicom store from storage bucket operation is showing Success in dicom-store operations but message is not publishing on assigned topic.

_Healthcare and Pubsub API are Enable and granted permissions._

**Comment by busunkim96** [comment]
@noerog Could you take a look?

**Comment by noerog** [comment]
@ankitdata Have you configured the Pub/Sub topic in notificationConfig inside the DICOM store? See https://cloud.google.com/healthcare/docs/how-tos/pubsub#dicom_instances
