### ISSUE TITLE
PubSub future result is an indicator of publish success

### ISSUE THREAD

**Issue by mbrancato** [GoogleCloudPlatform/python-docs-samples#4671]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/04a7a7f7ecdc2cfe343486e54ea15b9fcf7a9f89/functions/pubsub/main.py#L50-L57

## Describe the issue

It is my understanding that the `result()` method of the future will return the message ID on success. The `publisher.publish()` method may raise an exception, but only in certain ways (too large, or publisher was stopped). In this code block, by merely calling `result()` then returning a successful message, Cloud Functions will ack the message even if `result()` is `None` or `False`.

On a related note, I do something like this and I indeed have seen messages fail to publish.

```py
        if future.result():
            message.ack()
        else
            message.nack()
```

**Comment by anguillanneuf** [comment]
👋  @mbrancato, can I clarify with you what is meant by "Cloud Functions will ack the message even if `result()` is `None` or `False`"?

If your Cloud Function is triggered by a Pub/Sub message, the message is ack'ed at function invocation. See [docs](https://cloud.google.com/functions/docs/calling/pubsub).

In general, ack'ing applies to subscriber clients sending an ack to the service to indicate that it has received a message. Ack'ing isn't really associated with publishing messages.

**Comment by mbrancato** [comment]
Hi @anguillanneuf - to clarify here is exactly what the documentation says:

```
Cloud Functions acks the message internally upon successful function invocation.
```

In GCF, the input to the function is the data in, but the output is the HTTP response status indicating success or failure. By reading the above description, it indicates that acks only happen when a 20x response is returned. If this is incorrect, I'd suggest updating the documentation to say that GCF acks a message "as soon as a function is invoked, regardless if the function returns a successful response". Also, that sounds like a pretty dangerous approach if the GCF + PubSub integration acks before a successful result.

Also, to clarify, acking is designed not to acknowledge receiving a message (although much of the non-technical docs seem to indicate that, I think for simplicity) when received, but actually when the message has been successfully processed. To quote the Google documentation for the PubSub library for Python (which I'm using):
```
In Pub/Sub, the term ack stands for “acknowledge”. You should ack a message when your 
processing of that message has completed. When you ack a message, you are telling 
Pub/Sub that you do not need to see it again.
```

The issue here is `publish_future.result()` can return a `False` or `None` value (it sometimes does in practice), ostensibly indicating that a publish failed. The sample code seems to expect this to always raise an exception in order to return a 500 error, indicating the message was not successfully published. Here, if `publish_future.result()` returns `False` or `None`, the function in this sample code will still return a successful HTTP response.

**Comment by anguillanneuf** [comment]
👍  How about we change the docs to say: 

> Cloud Functions acks the message internally upon successful function invocation (not successful function execution). 

I think the confusion comes from pulled messages vs. push messages. For pulled messages, we distinguish receiving messages from processing messages, and we recommend ack'ing after processing. For push messages, once the endpoint sends a successful code, i.e. once the delivery is successful, the message is ack'ed.

**Comment by anguillanneuf** [comment]
I have updated the official docs with this note: https://cloud.google.com/functions/docs/calling/pubsub#sample_code
