### ISSUE TITLE
Add documentation on customizing test environment

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/python-docs-samples#4764]
* How to fetch and upload secrets locally using the scripts.

Using `noxfile_config`:
  * using alternate projects
  * passing environment variables

**Comment by tmatsuo** [comment]
Do we recommend contributors use secret manager for local run?
For local run, shouldn't we recommend that contributors copy `test-env.tmpl.sh` to `test-env.sh` and edit it?

**Comment by tmatsuo** [comment]
When you need to add a secret, you'll have to use the secret manager, so anyways we should have that kind of document.
