### ISSUE TITLE
A Better README

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/python-docs-samples#4837]
## In which file did you encounter the issue?

`README.md`

### Did you change the file? If so, how?

No

## Describe the issue

It would be cool if this repo had a slightly better main README experience. I think [Node](https://github.com/GoogleCloudPlatform/nodejs-docs-samples#google-cloud-platform-nodejs-samples-) has an ideal experience, [ruby](https://github.com/GoogleCloudPlatform/ruby-docs-samples#ruby-docs-samples) is also slightly better. This would include:

- H1 for repo title
- Organization of badges (under repo title)
- Smaller Cloud Shell button
- Generic setup instructions ([like Node](https://github.com/GoogleCloudPlatform/nodejs-docs-samples#setup))
  - (Or like the [`functions/` directory](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/functions#install-dependencies))
  - Prereqs
    - List prereqs
    - Clone the repo
    - Obtain auth creds
  - How to run a sample
    - Change to a directory in one of the sample folders
    - Create a virtualenv
    - Install the dependencies needed to run the samples
    - Run the sample

This could also reduce the duplicated instructions we have in specific folders.

In addition to these additive instructions, we could remove links to standard GitHub repo files

- Contributing changes is in `CONTRIBUTING.md`
- Licensing is in `LICENSE`

GitHub and modern git tools automatically detect these files. It's not necessary for projects to add links to them in the README.

---

# CURRENT

## Google Cloud Platform Python Samples

[![Open in Cloud Shell][shell_img]][shell_link]

[shell_img]: http://gstatic.com/cloudssh/images/open-btn.png
[shell_link]: https://console.cloud.google.com/cloudshell/open?git_repo=https://github.com/GoogleCloudPlatform/python-docs-samples&page=editor&open_in_editor=./README.md

This repository holds the samples used in the python documentation on [cloud.google.com](https://cloud.google.com).

[![Build Status][py-2.7-shield]][py-2.7-link]
[![Build Status][py-3.6-shield]][py-3.6-link]
[![Build Status][py-3.7-shield]][py-3.7-link]
[![Build Status][py-3.8-shield]][py-3.8-link]

[py-2.7-shield]: https://storage.googleapis.com/cloud-devrel-public/python-docs-samples/badges/py-2.7.svg
[py-2.7-link]: https://storage.googleapis.com/cloud-devrel-public/python-docs-samples/badges/py-2.7.html
[py-3.6-shield]: https://storage.googleapis.com/cloud-devrel-public/python-docs-samples/badges/py-3.6.svg
[py-3.6-link]: https://storage.googleapis.com/cloud-devrel-public/python-docs-samples/badges/py-3.6.html
[py-3.7-shield]: https://storage.googleapis.com/cloud-devrel-public/python-docs-samples/badges/py-3.7.svg
[py-3.7-link]: https://storage.googleapis.com/cloud-devrel-public/python-docs-samples/badges/py-3.7.html
[py-3.8-shield]: https://storage.googleapis.com/cloud-devrel-public/python-docs-samples/badges/py-3.8.svg
[py-3.8-link]: https://storage.googleapis.com/cloud-devrel-public/python-docs-samples/badges/py-3.8.html

For a more detailed introduction to a product, check the README.md in the
corresponding folder.

## Contributing changes

* See [CONTRIBUTING.md](CONTRIBUTING.md)

## Licensing

* See [LICENSE](LICENSE)

---

# SUGGESTED

# Google Cloud Platform Python Samples

Python samples for [Google Cloud Platform products][cloud].

[slack_badge]: https://img.shields.io/badge/slack-Google%20Cloud%20Platform-E01563.svg	
[slack_link]: https://googlecloud-community.slack.com/
[cloud]: https://cloud.google.com/
[cloud_python_setup]: https://cloud.google.com/python/setup
[auth_command]: https://cloud.google.com/sdk/gcloud/reference/beta/auth/application-default/login
[gcp_auth]: https://cloud.google.com/docs/authentication#projects_and_resources

## Setup

1. Install [`pip` and `virtualenv`][cloud_python_setup] if you do not already have them.

1. Clone this repository:

    ```
     git clone https://github.com/GoogleCloudPlatform/python-docs-samples.git
    ```

1. Obtain authentication credentials.

    Create local credentials by running the following command and following the
    oauth2 flow (read more about the command [here][auth_command]):

        gcloud auth application-default login

    Read more about [Google Cloud Platform Authentication][gcp_auth].

### How to run a sample

1. Change directory to one of the sample folders, e.g. `language`:

        cd language/

1. Create a virtualenv. Samples are compatible with Python 2.7 and 3.4+.

    ```
    virtualenv env
    source env/bin/activate
    ```

1. Install the dependencies needed to run the samples.

    ```
    pip install -r requirements.txt
    ```

1. Run the sample:

    ```
    python snippets
    ```

**Comment by engelke** [comment]
This seems like a good idea. Could you make a PR to implement it?

**Comment by grant** [comment]
I created a PR. :)
