### ISSUE TITLE
Don't Use Both rst and md for Documentation

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/python-docs-samples#4843]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/functions/README.rst

### Did you change the file? If so, how?

No

## Describe the issue

I'm trying to copy and paste README contents, but some files use `rst` and some use `md`.

For example:

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/functions/README.rst

Can we just stick to one format such that we don't need to manually modify contents between file formats?

**Comment by tmatsuo** [comment]
tl;dr; Feel free to change it to markdown IMO.


There is a script for rendering the `README.rst` from `README.rst.in`. The script is extracting help text from the command line style python files and the help text into the final `README.rst`.

If your python files don't have command line interface, there's no reasons to use the `scripts/readme-gen.py` or `readmegen` nox session.

@kurtisvg @busunkim96 @leahecole Please chime in if I'm wrong.

**Comment by kurtisvg** [comment]
+1 to preferring markdown.

**Comment by busunkim96** [comment]
I don't think we have to bandwidth to actively change all the existing RSTs to MDs, but it sounds fine to use MDs going forward.

**Comment by grant** [comment]
> I don't think we have to bandwidth to actively change all the existing RSTs to MDs, but it sounds fine to use MDs going forward.

I wasn't really looking for bandwidth from anybody in particular, was mostly asking why we have both markdown and rst files. I can't copy between them.

It seems like folks are neutral about this.

Here's an initial PR that would require some polishing: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4867

**Comment by kurtisvg** [comment]
The reason was that "readmegen" uses to automatically generate READMEs for some samples, and it generates them in an RST format. 

I don't know if anyone is still actively using readmegen or not.

**Comment by grant** [comment]
> The reason was that "readmegen" uses to automatically generate READMEs for some samples, and it generates them in an RST format.
> 
> I don't know if anyone is still actively using readmegen or not.

Hmm, thanks for the background.

LMK if this change makes sense or who we should contact.

**Comment by grant** [comment]
Talking to Bu Sun, it's not feasible to do this repo-wide, so I'll look at per product changes.
