### ISSUE TITLE
ESP in GKE with ingress instead of service

### ISSUE THREAD

**Issue by ismailyenigul** [GoogleCloudPlatform/python-docs-samples#4874]
## In which file did you encounter the issue?

I see that all deployments of ESP in GKE/Kubernetes uses service port with LoadBalancer type.

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/getting-started/deployment.yaml#L27

When you specify type:LoadBalancer in the resource manifest, GKE creates a Service of type LoadBalancer. GKE create  an external network load balancer.
In this case you must handle HTTPS in the container
But, when you specify kind:Ingress in the resource manifest  GKE creates an external HTTP(S) load balancer.

I think ingress is much better than service for the load balancer deployment. In ingress you can also assign static-IP to the load balancer which will not be deleted when you delete/create ingress again.

I am wondering is there any special reason/requirement to deploy service with type Loadbalancer.

Thanks

**Comment by busunkim96** [comment]
@qiwzhang Could you take a look?

**Comment by qiwzhang** [comment]
The GKE deployment samples under `endpoints` folder are to illustrate how ESP container can be deployed as side-car container, they should not be used as best practice on how external traffic should be routed.  There is not any special reasons or requirements to deploy service with type Loadbalancer in these examples.  Users can choose the best external traffic routing methods they see fit.

**Comment by busunkim96** [comment]
Closing since the question has been answered. Thanks @qiwzhang!
