### ISSUE TITLE
[Dataflow] How to pass the `disk_size_gb` parameter?

### ISSUE THREAD

**Issue by sneko** [GoogleCloudPlatform/python-docs-samples#4975]
Hi,

When I try to use `--disk_size_gb 30` to run a flex template I get:
```
ERROR: (gcloud.dataflow.flex-template.run) unrecognized arguments:
  --disk_size_gb
  30
  To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
```
_Same for `--parameters disk_size_gb=30` and `--disk-size-gb 30`_

Is there anything special so it's passed to the pipeline? Should I add this into my `metadata.json` so the CLI validates it and then the pipeline will take it?

Thank you,

**Comment by sneko** [comment]
Hi @davidcavazos ,

I just saw you're the new assignee on this, do you have any idea what's the cause please?

Thank you,

**Comment by busunkim96** [comment]
Hi,

This is the issue tracker for Python code samples published on cloud.google.com. Support channels for the CLI (gcloud) are listed on this page: https://cloud.google.com/sdk/docs/getting-support

**Comment by davidcavazos** [comment]
@MelodyShen, I tried this as well and couldn't get "pre-defined" parameters to work. I think I remember hearing that they were supported, but do you know if there's any special format that they could be supplied?

I guess a workaround would be passing it directly to the PipelineOptions.

```py
import apache_beam as beam
import argparse

parser = argparse.ArgumentParser()
args, pipeline_args = parser.parse_known_args()

options = beam.options.pipeline_options.PipelineOptions(
    args,
    save_main_session=True,
    disk_size_gb=30,
)
with beam.Pipeline(options=options) as pipeline:
   # ...
```

If you needed that to be specified as a parameter, I guess you could always define that as one of your parameters and pass the value from `args` into `disk_size_gb`.

**Comment by MelodyShen** [comment]
Hi @davidcavazos this parameter is not supported by flex templates. It can always be added in parameters with metadata defined in metadata.json.

**Comment by davidcavazos** [comment]
yeah, confirming that adding `disk_size_gb` to the metadata will do the trick.

**Comment by sneko** [comment]
Thanks @MelodyShen and @davidcavazos that's what I thought.

It would be great if Google could gather add these tips somewhere (FAQ...), it would help onboarding Dataflow that has some important specificities :)

Closing since there is at least a working way 👍

**Comment by davidcavazos** [comment]
@rosetn, can we add a note mentioning how to pass [Dataflow pipeline options](https://cloud.google.com/dataflow/docs/guides/specifying-exec-params#setting-other-cloud-dataflow-pipeline-options)?

In summary, if you want them as a constant, you can set them as normal through `PipelineOptions`. And if you want to be able to set them at runtime, you should add them to the `metadata.json` file.

**Comment by rosetn** [comment]
Sure! Can you file a docs issue for this? And feel free to make the edit yourself and add me as a reviewer--it might take TWs a while to get to this.
