### ISSUE TITLE
Speech Streaming Issue

### ISSUE THREAD

**Issue by tthong** [GoogleCloudPlatform/python-docs-samples#498]
Hi all, I can run the samples just fine except for **speech_streaming.py**.

It will only allow up to the first _is_final=true_ result. Then it hangs for a minute or 2 before the following error is shown:

```
Traceback (most recent call last):
  File "speech_streaming.py", line 157, in <module>
    main()
  File "speech_streaming.py", line 149, in main
    request_stream(stop_audio), DEADLINE_SECS))
  File "speech_streaming.py", line 125, in listen_print_loop
    for resp in recognize_stream:
  File "...grpc/beta/_client_adaptations.py", line 153, in next
    return self._next()
  File "...grpc/beta/_client_adaptations.py", line 147, in _next
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="{"created":"@1473093521.319367000","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1473093521.319360000","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}]}")

```
I'm running this on OSX Yosemite 10.10.5 and Python 2.7. Does anyone have any idea regarding the grpc error?

**Comment by jerjou** [comment]
Ah - probably because `single_utterance` is set to True. I wonder why I did that... (anyway, remove it and it should continue transcribing. I'll investigate why I put it there, and if it was for a dumb reason, I'll remove it)

**Comment by jerjou** [comment]
Closing for now. Please reopen if that doesn't fix the issue.
