### ISSUE TITLE
Multiple services example for flexible environment

### ISSUE THREAD

**Issue by travisoneill** [GoogleCloudPlatform/python-docs-samples#499]
You should have one.  It would have made my deployment a lot easier.  I will be happy to make a PR if it is something that you want to add.

**Comment by jonparrott** [comment]
Sounds like a great idea. It seems like I'd like to schedule this as something to do before App Engine flex goes GA. 👍

**Comment by travisoneill** [comment]
Opened up a PR.  I included Express servers in the architecture as well so it could be useful as an example of how to deploy multiple runtimes in one repo as well too.  Would you like me to keep that structure or use Python only since this is the Python docs repo?

**Comment by jonparrott** [comment]
I think it would be best to stick to Python as we're not setup to appropriately test node.js in this repo.

**Comment by travisoneill** [comment]
Will switch it over.

**Comment by travisoneill** [comment]
Also, is there a repo for the code that handles python in the Google Cloud Shell?  You guys have some missing parens on print calls that throw syntax errors (but no lost functionality) on almost every line when running in a python 3 virtual environment.

**Comment by jonparrott** [comment]
Do you have a stacktrace? I can hand it off to the appropriate team.

**Comment by travisoneill** [comment]
Coming from stdin.  not sure how to trace deeper but clear what the error is:

```Welcome to Cloud Shell! Type "help" to get started.
travis_h_oneill@algorithm-arena:~$ cd ~/src/algorithm-arena/default
travis_h_oneill@algorithm-arena:~/src/algorithm-arena/default$ cd flask
travis_h_oneill@algorithm-arena:~/src/algorithm-arena/default/flask$ source evv/bin/activate
-bash: evv/bin/activate: No such file or directory
travis_h_oneill@algorithm-arena:~/src/algorithm-arena/default/flask$ source env/bin/activate                                                                             
  File "<stdin>", line 7
    print config.get('core', 'project')
               ^
SyntaxError: invalid syntax
(env) travis_h_oneill@cloudshell:~/src/algorithm-arena/default/flask$ echo 'hi'
hi
  File "<stdin>", line 7
    print config.get('core', 'project')
               ^
SyntaxError: invalid syntax
(env) travis_h_oneill@cloudshell:~/src/algorithm-arena/default/flask$ echo 'python'
python
  File "<stdin>", line 7
    print config.get('core', 'project')
               ^
SyntaxError: invalid syntax
(env) travis_h_oneill@cloudshell:~/src/algorithm-arena/default/flask$```

**Comment by thecloudist** [comment]
I am trying to reproduce the GoPiGo (Raspberry PI Robot Car) demo that was done in the spring.
So far, I have all the keys, GCP, appengine and everything (I think) properly installed on latest OSX.
Just to try and run any of the GRPC samples gets about the same exceptions - shown below.
Does anyone have experience with this and can help?
Thanks in advance.

_**(grpc) steves-MacBook-Pro:grpc salvideoguy$ sudo python transcribe_async.py gs://voice_test/audio.flac
Traceback (most recent call last):
  File "transcribe_async.py", line 121, in <module>
    main(args.input_uri, args.encoding, args.sample_rate)
  File "transcribe_async.py", line 74, in main
    ), DEADLINE_SECS)
  File "/Users/salvideoguy/pydev/py_projects/google_voice/python-docs-samples/speech/grpc/grpc/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 305, in __call__
    self._request_serializer, self._response_deserializer)
  File "/Users/salvideoguy/pydev/py_projects/google_voice/python-docs-samples/speech/grpc/grpc/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 203, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.PERMISSION_DENIED, details="Google Cloud Speech API has not been used in project google.com:cloudsdktool before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=google.com:cloudsdktool then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.")**_

**Comment by jonparrott** [comment]
that is really strange. Happens with any Python 3 virtualenv?

**Comment by jerjou** [comment]
Looks like this is part of the [cloud shell bashrc](https://github.com/google/appengine-jenkins/blob/master/image/base/devshell/bashrc.google). I submitted a PR google/appengine-jenkins#2

**Comment by jonparrott** [comment]
@jerjou nice! I didn't even know that repo existed. Seems weird that it's on Google and not GoogleCloudPlatform.

**Comment by travisoneill** [comment]
Thats great!  I was stumped after searching the entire GCP repo for that one line of code and never getting a hit.

**Comment by travisoneill** [comment]
@jonparrott Switched over to all Python (w/ a few lines of JS on the front) and pushed.  Please let me know if you would like me to make any changes.
