### ISSUE TITLE
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

### ISSUE THREAD

**Issue by CallLiven** [GoogleCloudPlatform/python-docs-samples#5006]
run demo code : https://github.com/googleapis/python-speech/blob/master/samples/snippets/transcribe_model_selection.py

<img width="1868" alt="image" src="https://user-images.githubusercontent.com/40769240/100100795-5291e100-2e9c-11eb-84f7-56c716d3b536.png">

**Comment by busunkim96** [comment]
Hi,

A 503 is most like a network issue.

> Could you give any details about your networking, e.g. any proxies that might cause problems? Maybe there is a firewall? The error indicates that some network connections might be blocked.

https://stackoverflow.com/questions/58168189/serviceunavailable-503-failed-to-connect-to-all-addresses-during-attempt-to-rec

**Comment by CallLiven** [comment]
How do I verify that

**Comment by CallLiven** [comment]
I am a Chinese user, using the Lantern to access

**Comment by busunkim96** [comment]
You should check if there are any networking settings blocking connections. 503 means the library is unable to make a connection with the backend API. 

One thing you can do is try to load the discovery doc at https://speech.googleapis.com/$discovery/rest?version=v1 (no authorization is required, but it is served at the same endpoint). If you can access that page you should be able to make requests to the library.

```bash
curl "https://speech.googleapis.com/\$discovery/rest?version=v1"
```

```py
>>> import requests
>>> requests.get("https://speech.googleapis.com/$discovery/rest?version=v1")
<Response [200]>
```
 If you have a support contract with Google, feel free to file a ticket. https://cloud.google.com/support

**Comment by CallLiven** [comment]
In different ways, there are different results

1.run at terminal
<img width="604" alt="image" src="https://user-images.githubusercontent.com/40769240/100177475-1d71a700-2f0d-11eb-842e-5ba41dc30e16.png">

2.run pycharm 
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/40769240/100177508-2ebab380-2f0d-11eb-9c7f-b4600c93412a.png">

**Comment by CallLiven** [comment]
run python then will get this result 
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/40769240/100404815-4628a680-309d-11eb-8e46-acde97208801.png">

**Comment by busunkim96** [comment]
Apologies, this one fell off of my radar.

From the second to last post, it looks like there is likely something blocking network connections (https://stackoverflow.com/questions/58168189/serviceunavailable-503-failed-to-connect-to-all-addresses-during-attempt-to-rec describes some possible solutions).

I'm going to close this issue since it has gone stale, but please do open a new issue if you are still experiencing issues.

**Comment by WhitePageWu** [comment]
请问解决这个问题了吗？

**Comment by Larerr** [comment]
请问解决这个问题了吗？或者说有没有办法加proxies呀，感觉有地方加proxies问题就解决了

**Comment by WhitePageWu** [comment]
> 请问解决这个问题了吗？或者说有没有办法加proxies呀，感觉有地方加proxies问题就解决了

可以使用Colab作为转接。如果只是简单调用，用Colab可以连通

**Comment by Larerr** [comment]
@WhitePageWu woc好兄弟，能细说嘛，求求了，woc，请你喝奶茶好兄弟，我的邮箱是wanghb20@bit.edu.cn

**Comment by undefinedcodezhong** [comment]
@Larerr 有问题找llm啊：
```
import os
os.environ['HTTP_PROXY'] = 'http://ip:port'
```
实测可行
