### ISSUE TITLE
TypeError: annotate_video() got an unexpected keyword argument 'video_context'

### ISSUE THREAD

**Issue by piyushflocksend** [GoogleCloudPlatform/python-docs-samples#5012]
## Describe the issue

TypeError: annotate_video() got an unexpected keyword argument 'video_context' This error is coming when am mentioning.

video_client = videointelligence.VideoIntelligenceServiceClient()
features = [videointelligence.Feature.SPEECH_TRANSCRIPTION]

config = videointelligence.SpeechTranscriptionConfig(
    language_code="en-US", enable_automatic_punctuation=True
)
video_context = videointelligence.VideoContext(
    speech_transcription_config=config
)

    

operation = video_client.annotate_video(
    input_uri=path, features=features ,  video_context=video_context
)

**Comment by busunkim96** [comment]
Hi @piyushflocksend,

It looks like our published samples are out of date with the latest release. For now you can check https://github.com/googleapis/python-videointelligence/tree/master/samples. We're working on getting the samples published on cloud.google.com up to date. Apologies for the inconvenience!

**Comment by busunkim96** [comment]
Updated internal doc references in 344891250. cloud.google.com should be up to date by tomorrow.

**Comment by busunkim96** [comment]
Docs are now up-to-date.
