### ISSUE TITLE
Refactor the samples of list_blobs and download_blob_to_file and related files.

### ISSUE THREAD

**Issue by HemangChothani** [GoogleCloudPlatform/python-docs-samples#5031]
## In which file did you encounter the issue?

- In the storage PR [311](https://github.com/googleapis/python-storage/pull/311) blob.list_blobs() and blob.download_blob_to_file() methods is going to deprecate, so change the sample files accordingly. 

## Solution
- Use the methods client.list_blobs() and client.download_blob_to_file()  instead of blob.list_blobs() and blob.download_blob_to_file() .

**Comment by HemangChothani** [comment]
As the related PR merged, I have started working on this issue and will open a PR soon.

**Comment by frankyn** [comment]
Hi @HemangChothani 

For `list_blobs`, I updated samples to reflect the changes.

I think you mean updating this usage: https://github.com/GoogleCloudPlatform/python-docs-
samples/blob/d103a57d66d76a4daa04736d18c2c542d1f7d361/storage/cloud-client/storage_download_public_file.py#L33

**Comment by HemangChothani** [comment]
@frankyn we have moved ` download_to_file` into the client class, ` download_to_filename` is still in the blob class so i think there is no need to update any sample here.

**Comment by frankyn** [comment]
Should this just be closed then?

**Comment by HemangChothani** [comment]
Yes.
