### ISSUE TITLE
Get realtime updates with Cloud Firestore with asyncio

### ISSUE THREAD

**Issue by Podolyan98** [GoogleCloudPlatform/python-docs-samples#5078]
Hi. How can I run this [example][1] through asyncio? The error I got on startup:

    name col_snapshot is not defined

sample:

        async def on_snapshot(col_snapshot, changes, read_time):
            for change in changes:
                if change.type.name == 'ADDED':
                    response = f'New document: {change.document.id}'
                    logger.debug(response)
                elif change.type.name == 'MODIFIED':
                    response = f'Modified document: {change.document.id}'
                    logger.debug(response)
                elif change.type.name == 'REMOVED':
                    response = f'Removed document: {change.document.id}'
                    logger.debug(response)
                    delete_done.set()
    
        col_query = db.collection(u'cities')
        query_watch = col_query.on_snapshot(await on_snapshot(col_snapshot, changes, read_time))

  [1]: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/cb47b2edfda3cda16bbec25a772a4cf657ba268f/firestore/cloud-client/snippets.py#L750-L771

**Comment by crwilcox** [comment]
Deduping this with https://github.com/googleapis/python-firestore/issues/131.

Watch is currently not supported on the async surface as it is a background thread today and wasn't as obvious a benefit to adding async.
