### ISSUE TITLE
Exceptions running speech samples on OSX

### ISSUE THREAD

**Issue by thecloudist** [GoogleCloudPlatform/python-docs-samples#510]
Re: voice API samples:

I am trying to reproduce the GoPiGo (Raspberry PI Robot Car) voice-controlled car demo that was done in the spring. http://bit.ly/2c30Ko6
So far, I have all the keys, GCP, appengine and everything (I think) properly installed on latest OSX.
Just to try and run any of the GRPC samples gets about the same exceptions - shown below.
Does anyone have experience with this and can help?
Thanks in advance.

**(grpc) steves-MacBook-Pro:grpc salvideoguy$ sudo python transcribe_async.py gs://voice_test/audio.flac
Traceback (most recent call last):
File "transcribe_async.py", line 121, in 
main(args.input_uri, args.encoding, args.sample_rate)
File "transcribe_async.py", line 74, in main
), DEADLINE_SECS)
File "/Users/salvideoguy/pydev/py_projects/google_voice/python-docs-samples/speech/grpc/grpc/lib/python2.7/site-packages/grpc/beta/client_adaptations.py", line 305, in __call
self.request_serializer, self._response_deserializer)
File "/Users/salvideoguy/pydev/py_projects/google_voice/python-docs-samples/speech/grpc/grpc/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 203, in _blocking_unary_unary
raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.PERMISSION_DENIED, details="Google Cloud Speech API has not been used in project google.com:cloudsdktool before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=google.com:cloudsdktool then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.")**

**Comment by jerjou** [comment]
Hello - looks like you haven't [set up auth](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech/grpc#authentication) yet - it looks like it's using the auth from the cloudsdktool (ie gcloud) instead of from your project.

**Comment by thecloudist** [comment]
I got this working.  Yesterday, after I posted this issue, I was able to set the GOOGLE_APPLICATION_CREDENTIALS env var correctly to point to my json creds file.
After that, everything including the api-client and the grpc samples worked flawlessly.

Now, I am porting this whole thing to Raspberry Pi on my GoPiGo.
Cheers!
