### ISSUE TITLE
Incredibly slow collectstatic command

### ISSUE THREAD

**Issue by thclark** [GoogleCloudPlatform/python-docs-samples#5174]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/run/django/cloudmigrate.yaml

### Did you change the file? If so, how?

Yes, as I have other build steps and use the europe region, and renamed the `.env` file to make more sense (since it doesn't contain all your settings). But the `collectstatic` step is otherwise essentially the same:
```
  # ... secrets, build, push steps

  # Migrations work like a charm, proving that the environment is set up well. 
  # Although, there is only one transaction to the external service (i.e. from GCB out to Google Cloud SQL),
  # so it could be that the roundtrip time is several seconds which I wouldn't notice once
  - id: 'Apply Migrations'
    name: gcr.io/google-appengine/exec-wrapper
    args:
      [
        '-i',
        '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$SHORT_SHA',
        '-s',
        '${PROJECT_ID}:${_POSTGRES_REGION}:${_POSTGRES_INSTANCE_NAME}',
        '-e',
        'GCLOUD_ENV_SECRET_NAME=${_GCLOUD_ENV_SECRET_NAME}',
        '-e',
        'REDIS_URL=${_REDIS_URL}',
        '--',
        'python',
        'manage.py',
        'migrate',
      ]

  - id: 'Collect Static'
    name: gcr.io/google-appengine/exec-wrapper
    timeout: 86400s
    args:
      [
        '-i',
        '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$SHORT_SHA',
        '-s',
        '${PROJECT_ID}:${_POSTGRES_REGION}:${_POSTGRES_INSTANCE_NAME}',
        '-e',
        'GCLOUD_ENV_SECRET_NAME=${_GCLOUD_ENV_SECRET_NAME}',
        '-e',
        'REDIS_URL=${_REDIS_URL}',
        '--',
        'python',
        'manage.py',
        'collectstatic',
        '--no-input',
      ]

# ... deploy step

# This is required to workaround and wait out the upload
timeout: 86400s

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'

options:
  # Happens with and without this
  machineType: 'N1_HIGHCPU_8'

substitutions:
  _REDIS_URL: 'redis://10.50.192.12:6379'
  _DEPLOY_REGION: europe-west1
  _GCLOUD_ENV_SECRET_NAME: my-env-file-secret-name
  _GCR_HOSTNAME: eu.gcr.io
  _SERVICE_NAME: my-service-name
  _PLATFORM: managed
  _POSTGRES_INSTANCE_NAME: my-postgres-instance-name
  _POSTGRES_REGION: europe-west1
```

## Describe the issue

Secrets, build, push and migrate steps all work fine.

Collectstatic step starts, and *does work*, but takes a **geologically** long time to complete (timed out at 10000s, trying again with a full day timeout).

By comparison, I did the same thing from my local computer, with the same credentials, and collecting c.300 static files (typical of a small django app, there could be many more in some cases)... it took c.20s for them all to end up in my bucket on GCS (I am physically located in Cambridge UK, bucket is in Belgium).

So I think it's something to do with the way traffic is routed out of GCB. Or perhaps with where GCB is located, which I believe is `us-central1`?

**Comment by thclark** [comment]
For google staff: I created a support case #26282882 and will crosspost any outcomes of that.

**Comment by leahecole** [comment]
cc @glasnt

**Comment by glasnt** [comment]
There is the upcoming ability to have Cloud Build run outside of us-central1, see [Worker Pools](https://cloud.google.com/sdk/gcloud/reference/beta/builds/worker-pools/create)

What sort of latency are you seeing per file, if you update `collectstatic` to include `collectstatic --verbosity 2`

**Comment by meredithslota** [comment]
Internal support ticket #26282882 was closed in January due to inactivity. No additional info to go on here.

**Comment by thclark** [comment]
Yeah, we had to work it out ourselves, unfortunately the ticketing system has far too slow a roundtrip (24+ hrs) between messages to be useful in debugging issues. Moving onto the next battle I forgot to cross-post back here.

There's still something weird with cloud-build that's not simply due to geographic proximity. Whenever I call any external service there's some crazy latency; in this case many minutes to upload a few kb file. For comparison I tried collecting from my local machine in UK to a bucket in the US which worked at normal speed; so it's not geographic.

We've managed to work around it here. Our static files change fairly slowly, which is lucky.

- Get configuration right. It's complicated getting the right bucket name set up and ensuring the static root is correct. If it's not correct, the process will hang indefinitely.
- Use collectfast (if you have redis available) to only upload the files that have changed
- Subclass the storage so you can use a different bucket for `static` files (which are made public) than you do for `media` files (which aren't).
- Set a badonkadonk timeout on your collectstatic process. It'll take a long time the first time, thereafter only changed files get uploaded.

### Buckets

I set up two buckets:

- `my-app-bucket` (for media files)
-  `my-app-bucket-static` (for static files)

### In `settings/your-settings-file.py`
```python

# Use GCP storage
DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
GS_BUCKET_NAME = env.str("GOOGLE_BUCKET_PREFIX")
GS_PROJECT_ID = "yourproject"
GS_FILE_OVERWRITE = False
GS_CREDENTIALS = service_account.Credentials.from_service_account_info(
    json.loads(env("GOOGLE_APPLICATION_CREDENTIALS_JSON"))
)

GOOGLE_STORAGE_BASE_URL = "https://storage.googleapis.com"

# MEDIA FILES
MEDIA_URL = f"{GOOGLE_STORAGE_BASE_URL}/{GS_BUCKET_NAME}/"
MEDIA_ROOT = "/media/"

# STATIC FILES

# Static files (CSS, JavaScript, Images)
STATIC_URL = f"{GOOGLE_STORAGE_BASE_URL}/{GS_BUCKET_NAME}-static/"
STATIC_ROOT = "/static/"

# Add extra directories where static assets are
# STATICFILES_DIRS = []

STATICFILES_STORAGE = "settings._storages.StaticRootGoogleCloudStorage"
COLLECTFAST_STRATEGY = "collectfast.strategies.gcloud.GoogleCloudStrategy"
COLLECTFAST_CACHE = "collectfast"
COLLECTFAST_THREADS = 8
```

### In `settings/_storages.py`
```python
from storages.backends.gcloud import GoogleCloudStorage


class StaticRootGoogleCloudStorage(GoogleCloudStorage):
    """ Storage defined with an appended bucket name (called "<bucket>-static")

    We define that static files are stored in a different bucket than the (private) media files, which:
        1. gives us less risk of accidentally setting private files as public
        2. allows us easier visual inspection in the console of what's private and what's public static
        3. allows us to set blanket public ACLs on the static bucket
        4. makes it easier to clean up private files with no entry in the DB

    """

    def get_default_settings(self):
        """ By default, uses the setting "GS_BUCKET_NAME". Append "-static" to that.
        """

        default_settings = super().get_default_settings()
        default_settings["bucket_name"] += "-static"
        return default_settings

```

### In cloudbuild.yaml

```yaml
  - id: 'Collect static'
    name: gcr.io/google-appengine/exec-wrapper
    timeout: 720s
    args:
      [
        '-i',
        '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$SHORT_SHA',
        '-s',
        '${PROJECT_ID}:${_POSTGRES_REGION}:${_POSTGRES_INSTANCE_NAME}',
        '-e',
        'GCLOUD_ENV_SECRET_NAME=IF_YOU_NEED_SECRETS_TO_BOOT_THE_APP',
        '-e',
        'REDIS_URL=${_REDIS_URL}',
        '--',
        'python',
        'manage.py',
        'collectstatic',
        '--noinput'
      ]
```
