### ISSUE TITLE
compose example throws exception. Missing source blob access step

### ISSUE THREAD

**Issue by keegan2149** [GoogleCloudPlatform/python-docs-samples#5180]
## In which file did you encounter the issue?

python-docs-samples/storage/cloud-client/storage_compose_file.py

### Did you change the file? If so, how?

uncommented input variables
select input blobs
moved sources list creation below client instantiation and blob selection
added some whitespace

## Describe the issue

example was didn't work even when input variables were uncommented. Throws an exception because there was no step to select the source blobs.

**Comment by fhinkel** [comment]
@keegan2149 Thanks for raising the issue. Could you post the error messages you get when you try to run it? Thanks.

**Comment by keegan2149** [comment]
> @keegan2149 Thanks for raising the issue. Could you post the error messages you get when you try to run it? Thanks.

(env) username@computer python-docs-samples (master) $ python storage/cloud-client/storage_compose_file.py 
Traceback (most recent call last):
  File "storage/cloud-client/storage_compose_file.py", line 56, in <module>
    bucket_name=sys.argv[1], sources=sys.argv[2], destination_blob_name=sys.argv[3],
IndexError: list index out of range
(env) username@computer python-docs-samples (master) $
