### ISSUE TITLE
Asynchronous way of invoking another cloud function from one cloud function in Python?

### ISSUE THREAD

**Issue by gitshashwat** [GoogleCloudPlatform/python-docs-samples#5223]
Is there a way to do so yet? Like just execute another cloud function and do not wait for its response back?

Lets take a basic example to illustrate:
Let my first cloud function be:
`def challenge(request):
                request_json = request.get_json()
                if request.args and 'message' in request.args:
                    return request.args.get('message')
                elif request_json and 'message' in request_json:
                    return request_json['message']
                else:
                    return f'Hello World!'`

And my second cloud function be:
`def challenge(request):
                    return f'Hello!'
`

I just don't need the respone back from second cloud function, just invoke it from the first. 
Is there any python code to workaround this?

**Comment by ace-n** [comment]
Hi @gitshashwat,

There are a few options here:
1) You can use a [Pub/Sub triggered function](https://cloud.google.com/functions/docs/calling/pubsub), and send a message to its triggering Pub/Sub topic to trigger it (and/or pass inputs to the function).
2) You can send a request without waiting for a response as shown [here](https://stackoverflow.com/questions/27021440/python-requests-dont-wait-for-request-to-finish).

Unless you need your function to be HTTP-triggered, Option 1 is likely the cleaner of the two.

Hope this helps!

**Comment by grant** [comment]
I highly recommend using Pub/Sub to call one function to another:

```py
publisher = pubsub_v1.PublisherClient()
topic_path = publisher.topic_path(project_id, topic_id)

future = publisher.publish(
    topic_path, data, origin="python-sample", username="gcp"
)
print(future.result())
```

https://cloud.google.com/pubsub/docs/publisher

And receiving Pub/Sub functions as Ace mentioned:

https://cloud.google.com/functions/docs/calling/pubsub

---

You can also just use the URL and make a HTTP request to another function.

Please re-open the issue if there are further questions, thanks!
