### ISSUE TITLE
Update Composer KubernetesPodOperator sample code/documentation to include how to work with Volumes/Volume Mounts

### ISSUE THREAD

**Issue by brodiemackenzie** [GoogleCloudPlatform/python-docs-samples#5229]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/composer/workflows/kubernetes_pod_operator.py

### Did you change the file? If so, how?

No change.

## Describe the issue

Can this sample code be updated to include code on how to use Volumes and Volume Mounts with the KubernetesPodOperator with Composer? Such that is aligns more closely with the Airflow documentation (version 1.10.10), see the following link:
[Kubernetes Operator](https://airflow.apache.org/docs/apache-airflow/1.10.10/kubernetes.html?highlight=kubernetes%20pod%20operator#kubernetes-operator) 

I had a partner that struggled to work with Volumes, the K8sPodOperator, and Composer and the lack of documentation on this capability/use case made it difficult to implement.

**Comment by leahecole** [comment]
#5678 and an April 13th update to the [accompanying docs](https://cloud.google.com/composer/docs/how-to/using/using-kubernetes-pod-operator#secret-config) adds some more clarification. An example was hiding in the code prior to April, but wasn't well explained. Hopefully these details clear up some confusion!
