### ISSUE TITLE
Add example for logging in python3.8

### ISSUE THREAD

**Issue by nitishxp** [GoogleCloudPlatform/python-docs-samples#5242]
Hi,

Can you also add logging for python38 cloud functions since by using default logger all logs are mapped without any severity level.

**Comment by ace-n** [comment]
Hi @nitishxp,

Thanks for reporting this. We're aware of the issue and working on resolving it internally (though we're not yet sure how long that will take).

(Assigning to @joelgerard since they're the primary point-of-contact for this.)

**Comment by averikitsch** [comment]
A sample can be found https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/functions/v2/http_logging/main.py
