### ISSUE TITLE
Test failure in dataflow/gpu-workers

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#5247]
[Example build](https://source.cloud.google.com/results/invocations/79b61c4a-f1d6-4e3f-83c5-ce23e48813be/log)

Probably a flake, restarting the build to see.

**Comment by tmatsuo** [comment]
It seems like it always fails.

@davidcavazos Do you have any idea why it fails?

**Comment by tmatsuo** [comment]
I see a dlerror in the log:

```
2021-01-15 22:29:10.524176: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-01-15 22:29:10.524235: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

**Comment by tmatsuo** [comment]
I found a more important error:

```
Startup of the worker pool in zone us-central1-a failed to bring up any of the desired 1 workers. ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS: The zone 'projects/python-docs-samples-tests/zones/us-central1-a' does not have enough resources available to fulfill the request.  '(resource type:compute)'.
```

**Comment by tmatsuo** [comment]
There were leaked GCE instances. I deleted them and I think we're good to go.

**Comment by tmatsuo** [comment]
Now it's constantly passing.

**Comment by davidcavazos** [comment]
Thanks. Sorry, I missed these notifications. The dynamic library warning is normal. It's trying to load GPUs, but the VM that launches the job doesn't have GPUs, but when the workers run the pipeline they should work as expected.

About the quota issue, Valentyn also [mentioned](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5067#discussion_r562166080) that we could change to `us-central1-f` and that could solve that. I applied that in #5275
