### ISSUE TITLE
Test failure in data-science-onramp/data-cleaning

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#5249]
[Build](https://source.cloud.google.com/results/invocations/6c8447ae-c6d1-4a3f-a439-532afe7c1375/targets)

**Comment by leahecole** [comment]
@tmatsuo have you seen this error since? I'm thinking it was just a fluke, but am happy to take a look at this sample if it's something we're seeing repeatedly. I saw a different flake in this sample that I or @bradmiro will take a look at

**Comment by tmatsuo** [comment]
Yeah it's still constantly failing. Failures this morning:
https://source.cloud.google.com/results/invocations/b7321bd3-deaf-408b-a655-b8f6ae70d2e9/targets
https://source.cloud.google.com/results/invocations/a1ee2610-df8c-4a0a-a9a4-227e7a01adc4/targets
https://source.cloud.google.com/results/invocations/0ea93b3f-034e-457e-a6d4-7f91cdbb9e96/targets

**Comment by tmatsuo** [comment]
The log has links to another log entries, which have stack trace. 

Here is an interesting part in the stack trace.
```
Caused by: com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: bigquerystorage.googleapis.com/2607:f8b0:4001:c12:0:0:0:5f:443
Caused by: java.net.SocketException: Network is unreachable
```

**Comment by leahecole** [comment]
known issue being tracked in b/181278351
