### ISSUE TITLE
GCP AI PLatform: Issue creating a custom predictor model version from Pytorch and torchvision

### ISSUE THREAD

**Issue by aktiwa** [GoogleCloudPlatform/python-docs-samples#5257]
Am currently trying to deploy a custom model to AI platform by following **_https://cloud.google.com/ai-platform/prediction/docs/deploying-models#gcloud_1_**. which is based on a combination of pre-trained model from **'Pytorch'** and '**torchvision.tranform'**. Currently, I keep getting below error which happens to be related to 500MB constraint on custom prediction. 
 
**ERROR: (gcloud.beta.ai-platform.versions.create) Create Version failed. Bad model detected with error: Model requires more memory than allowed. Please try to decrease the model size and re-deploy. If you continue to experience errors, please contact support.**
 
**Setup.py**
```
from setuptools import setup
from pathlib import Path

base = Path(__file__).parent
REQUIRED_PACKAGES = [line.strip() for line in open(base/"requirements.txt")]
print(f"\nPackages: {REQUIRED_PACKAGES}\n\n")

# [torch==1.3.0,torchvision==0.4.1, ImageHash==4.2.0
# Pillow==6.2.1,pyvis==0.1.8.2] installs 800mb worth of files

setup(description="Extract features of a image",
      author='Amrit',
      name='test',
      version='0.1',
      install_requires=REQUIRED_PACKAGES,
      project_urls={
                    'Documentation':'https://cloud.google.com/ai-platform/prediction/docs/custom-prediction-routines#tensorflow',
                    'Deploy':'https://cloud.google.com/ai-platform/prediction/docs/deploying-models#gcloud_1',
                    'Ai_platform troubleshooting':'https://cloud.google.com/ai-platform/training/docs/troubleshooting',
                    'Say Thanks!': 'https://medium.com/searce/deploy-your-own-custom-model-on-gcps-ai-platform- 
 7e42a5721b43',
                    'google Torch wheels':"http://storage.googleapis.com/cloud-ai-pytorch/readme.txt",
                    'Torch & torchvision wheels':"https://download.pytorch.org/whl/torch_stable.html "
                    },
    python_requires='~=3.7',
    scripts=['predictor.py', 'preproc.py'])
```

**Steps taken:**
Tried adding ‘torch’ and torchvision directly to ‘REQUIRED_PACKAGES’ list in setup.py file in order to provide pytorch + torchvision as a dependency to be installed while deployment.  I am guessing, Internally Ai platform downloads PyPI package for pytorch which is +500 MB, this results in the failure of our model deployment. If I just deploy the model with 'torch' only and it seems to be working (ofcourse throws error for not able to find library 'torchvision')

**File size**
1)pytorch (**torch-1.3.1+cpu-cp37-cp37m-linux_x86_64.whl** about **111MB**) 
2) torchvision (**torchvision-0.4.1+cpu-cp37-cp37m-linux_x86_64.whl** about **46MB**) from **_https://download.pytorch.org/whl/torch_stable.html_** and stored it on GKS. 
3) The zipped predictor model  file (.tar.gz format) which is the output of  setup.py (**5kb** )
4) A pretrained PyTorch model (size **44MB**)
 
In total, the model dependencies should be less than 250MB but still, keep getting this error. Have also tried to use the torch and torchvision provided from Google mirrored packages  http://storage.googleapis.com/cloud-ai-pytorch/readme.txt, but same memory issue persists. AI platform is quite new for us and would like some input from professional’s. 
 
 
## MORE INFO:

**GCP CLI Input:**
 
**My environment variable:** 
```
BUCKET_NAME= “something”
MODEL_DIR="gs://$BUCKET_NAME/"
VERSION_NAME='v6'
MODEL_NAME="something_model"
STAGING_BUCKET=$MODEL_DIR"staging_area/"
# TORCH_PACKAGE=$MODEL_DIR"package/torch-1.3.1+cpu-cp37-cp37m-linux_x86_64.whl"
# TORCHVISION_PACKAGE=$MODEL_DIR"package/torchvision-0.4.1+cpu-cp37-cp37m-linux_x86_64.whl"
TORCH_PACKAGE="gs://cloud-ai-pytorch/torch-1.3.1+cpu-cp37-cp37m-linux_x86_64.whl"
TORCHVISION_PACKAGE="gs://cloud-ai-pytorch/torchvision-0.4.1+cpu-cp37-cp37m-linux_x86_64.whl"
CUSTOM_CODE_PATH=$STAGING_BUCKET"imt_ai_predict-0.1.tar.gz"
PREDICTOR_CLASS="predictor.MyPredictor"
REGION='europe-west1'
MACHINE_TYPE='mls1-c4-m2'
 
gcloud beta ai-platform versions create $VERSION_NAME   \
--model=$MODEL_NAME   \
--origin=$MODEL_DIR  \
 --runtime-version=2.3  \
 --python-version=3.7   \
--machine-type=$MACHINE_TYPE  \
 --package-uris=$CUSTOM_CODE_PATH,$TORCH_PACKAGE,$TORCHVISION_PACKAGE   \
--prediction-class=$PREDICTOR_CLASS \ 
```
**GCP CLI Output:**
 
```Please specify a region:
 **[1] global**
 [2] asia-east1
 [3] asia-northeast1
 [4] asia-southeast1
 [5] australia-southeast1
 [6] europe-west1
 [7] europe-west2
 [8] europe-west3
 [9] europe-west4
 [10] northamerica-northeast1
 [11] us-central1
 [12] us-east1
 [13] us-east4
 [14] us-west1
 [15] cancel
Please enter your numeric choice:  1
 
To make this the default region, run `gcloud config set ai_platform/region global`.
 
Using endpoint [https://ml.googleapis.com/]
Creating version (this might take a few minutes)......failed.                                                                                                                                            
ERROR: (gcloud.beta.ai-platform.versions.create) Create Version failed. Bad model detected with error: **Model requires more memory than allowed. Please try to decrease the model size and re-deploy. If you continue to experience errors, please contact support.**
```
**My finding:**
Have found articles of people struggling in same ways for pytorch package and made it work by installing torch wheels on the GCS (https://medium.com/searce/deploy-your-own-custom-model-on-gcps-ai-platform- 
 7e42a5721b43).
 Have tried the same approach with torch and torchvision but no luck till now and waiting response from "cloudml-feedback@google.com <cloudml-feedback@google.com>". Any help on getting custom  torch_torchvision based custom predictor working on AI platform that will be great.

**Comment by dizcology** [comment]
Hello @aktiwa: This page should contain an approach that does not run into this issue: https://cloud.google.com/ai-platform/prediction/docs/getting-started-pytorch-container

For more information, please take a look at this comment in another issue: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4046#issuecomment-755716270

**Comment by aktiwa** [comment]
Thank you yu han, will try this method

Amrit

**Comment by dizcology** [comment]
@aktiwa Great!  I will close this issue for now, but please feel free to reopen it if you are still experiencing the issue.
