### ISSUE TITLE
APP Engine remote API on python3.x

### ISSUE THREAD

**Issue by TonyCrespoMe** [GoogleCloudPlatform/python-docs-samples#5264]
## In which file did you encounter the issue?

Attempting to enable remote api for APP Engine for runtime python38 results in an error at time of deploy. 

Wondering if perhaps the remote api feature is not compatible with python3

## Describe the issue

When enabling the feature by adding the remote_api builtin and handler. While deploying i get the error at the bottom. 
builtins:
    - remote_api: on
 handlers:
  - url: /_ah/remote_api(/.*)?
    script: auto

`(gcloud.app.deploy) INVALID_ARGUMENT: script field for handler '/_ah/remote_api(/.*)?' must be set to 'auto' for runtime python38.`

**Comment by engelke** [comment]
The remote_api handler is only available in older App Engine runtimes such as App Engine for Python 2.7. The newer App Engine for Python 3.x runtimes do not support it.

If you need to access services from outside the App Engine environment (such as your own workstation) with Python 3, you can usually find a google.cloud library to accomplish that, such as google.cloud.datastore.
