### ISSUE TITLE
Flaky test in run/django

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#5307]
[an example build](https://source.cloud.google.com/results/invocations/7cc562e3-5d16-4c55-9cc4-6838d5375c11/targets)

**Comment by tmatsuo** [comment]
It fails in teardown. I think the relevant message is `ERROR: (gcloud.sql.databases.delete) HTTPError 409: Operation failed because another operation was already in progress.`

**Comment by tmatsuo** [comment]
Here is my guess what's happening.

1. `gcloud sql databases delete` command send an underlining api request
2. the request errored (probably timeout), but the server got the request and processing
3. `gcloud` automatically retry the request
4. the server returns 409 because it is processing the previous request
5. `gcloud` reports the error

I think it's worth reporting to upstream. 

FYI @dinagraves

**Comment by leahecole** [comment]
Added @glasnt also who is the original author of this sample

**Comment by glasnt** [comment]
I think this sample would benefit from moving to the "setup/cleanup/retry.sh" method of setting up and taking down testing infra ([borrowed from node.js](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/run/idp-sql/test), being used in an [upcoming sample](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5315
)

**Comment by glasnt** [comment]
#5340 is now merged, should fix this issue

**Comment by leahecole** [comment]
I am seeing that [some storage buckets aren't being deleted](https://screenshot.googleplex.com/4opkmbmqQrWfAsF) - could that be an oversight in this refactor?

**Comment by glasnt** [comment]
Good catch, @leahecole; I'll clean that up and submit a PR fix.
