### ISSUE TITLE
Recommendations for distributing open source application based on GCP/Speech/Grpc

### ISSUE THREAD

**Issue by thecloudist** [GoogleCloudPlatform/python-docs-samples#531]
Is there a good way to push my project to a github repo and accommodate gcp/speech/grpc dependencies without pushing a fork of that?

My app README.md  will include procedures for signing up, activating and authenticating with GCP and the Speech API's in order to build this project for themselves.

Ideally, I would want the build to include a git clone step to acquire the GCP stuff and then one to get my code.  At the end of the day, I need to consolidate the setup so they aren't trying to build conflicting environments.

Perhaps, all of this can run under one virtualenv instance.

This will be on a Raspberry PI where I have validated everything so far.

Cheers

**Comment by jerjou** [comment]
A common way to manage dependencies in python is to use a [requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files) file, in which you list your dependencies. Most of the samples in this repo use this method, and provide instructions in the README.md describing how to install them, so you can look at some of them for examples.
