### ISSUE TITLE
Question on google.auth.default() call in run/markdown-preview/editor/render.py

### ISSUE THREAD

**Issue by ajdub508** [GoogleCloudPlatform/python-docs-samples#5393]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/run/markdown-preview/editor/render.py

### Did you change the file? If so, how?

I did not change the file, just have a question on it.

## Describe the issue

What is the purpose of [this call](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/run/markdown-preview/editor/render.py#L37) if the return values are never referenced?
`credentials, project = google.auth.default()`

Also - is it appropriate to ask this type of question by raising an issue here?  If there's a better place for me to ask this question, happy to do so.

**Comment by busunkim96** [comment]
Hi @ajdub508,

> Also - is it appropriate to ask this type of question by raising an issue here? If there's a better place for me to ask this question, happy to do so.

This is the perfect place to ask these sorts of questions. 😄 

Taking a first look at it I don't think the call is necessary in this sample. It looks like the actual authorization happens on the following lines:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/d384d10314f89dba48b68f2874da7e1861a5f9f7/run/markdown-preview/editor/render.py#L38-L41

@averikitsch could you take a look?

**Comment by averikitsch** [comment]
That seems accidentally. Testing now in PR #5396

**Comment by averikitsch** [comment]
The line has been removed from the sample. Please feel free to reopen this issue if you have further questions.
