### ISSUE TITLE
create_login_url - no clear guidance on making a custom login page

### ISSUE THREAD

**Issue by lucasduffey** [GoogleCloudPlatform/python-docs-samples#541]
create_login_url - no clear guidance on making a custom login page

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/users/main.py#L36

**Comment by lucasduffey** [comment]
https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.users#google.appengine.api.users.create_login_url

**Comment by jonparrott** [comment]
@lucasduffey unfortunately, there is no way to customize the login page when using the users service. If you want to have a completely custom login page, you'll need to roll your own or use a third-party library that provides that functionality.
