### ISSUE TITLE
How do I get a large collection from Firestore?

### ISSUE THREAD

**Issue by Podolyan98** [GoogleCloudPlatform/python-docs-samples#5503]
Hello. I got a 503 error while getting a large collection from Firestore through the [stream()](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/54208af42eeea6b2a2e9485158e244516c03ff8c/firestore/cloud-client/snippets.py#L61) method. I've seen this [solution](https://stackoverflow.com/a/61663938/13824551). But I can also use a [listener](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/54208af42eeea6b2a2e9485158e244516c03ff8c/firestore/cloud-client/snippets.py#L747) and a few hours [delay](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/54208af42eeea6b2a2e9485158e244516c03ff8c/firestore/cloud-client/snippets.py#L798)(depending on the collection). What is the best way to avoid the 503 error? Maybe there are other ways?

**Comment by dandhlee** [comment]
@Podolyan98 friendly ping, please take a look at Craig's response!

**Comment by dandhlee** [comment]
Closing the issue for now, please re-open if needed.
