### ISSUE TITLE
broken link in AUTHORING_GUIDE.md

### ISSUE THREAD

**Issue by reyadussalahin** [GoogleCloudPlatform/python-docs-samples#5522]
## In which file did you encounter the issue?
The issues been found in [https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#google-cloud-storage-resources](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#google-cloud-storage-resources)

### Did you change the file? If so, how?
No, I didn't made any changes to this file. I found the file in this status.

## Describe the issue
At the end of the file, in [Google Cloud Storage Resources](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#google-cloud-storage-resources) section, a link is broken. Notice the following line:  

"""
The resources required by tests can usually be found in the ./resources folder inside the sample directory, as in [this example](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/automl/cloud-client/resources).
"""

In the above line `this example` link is broken. It points to [https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/automl/cloud-client/resources](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/automl/cloud-client/resources). But the project has been moved to [https://github.com/googleapis/python-automl/tree/master/samples](https://github.com/googleapis/python-automl/tree/master/samples).

**Comment by dandhlee** [comment]
Thanks for filing this issue!
