### ISSUE TITLE
Investigate using pytest-xdist to parallelize tests

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/python-docs-samples#5623]
> As a side note, I wouldn't see any harm in including `pytest-xdist` and including `PYTEST_ADDOPTS="-n=8"` by default. I don't think it would break any tests. Maybe it would be nice to add that by default, document it and people can "disable it" by setting the `PYTEST_ADDOPTS` variable manually if they really need to.

_Originally posted by @davidcavazos in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5371#r603704679_

**Comment by engelke** [comment]
Looks like this was addressed PR #5371
