### ISSUE TITLE
Speech Cloud API ignores portion of audio

### ISSUE THREAD

**Issue by rxgranda** [GoogleCloudPlatform/python-docs-samples#571]
transcribe_asyn.py of the rest API only recognizes speech up to 20 seconds. The remaining speech of the audio is not recognized

**Comment by puneith** [comment]
@rxgranda Which async version are you using? We can recognize ~80 mins of LINEAR16 audio. Can you send us the audio file you are trying to transcribe.

**Comment by rxgranda** [comment]
[Here ](https://drive.google.com/file/d/0B_YxGlaT9EDoQl9GSm9CM0dlM2c/view?usp=sharing) is an audio file of 59 seconds.  I am using the python example transcribe_async.py, the latest version of the master branch of this repository. The target languageCode is 'es-EC'. 

Audio file: https://drive.google.com/file/d/0B_YxGlaT9EDoQl9GSm9CM0dlM2c/view?usp=sharing

**Comment by jerjou** [comment]
This appears to be the same bug as #530, so closing this as a dupe. Thank you for the file, though - having more examples of when this happens does help the backend team with the issue.
