### ISSUE TITLE
Code Sample to Classify images in a specified source folder and copy these images into resultant label-folders

### ISSUE THREAD

**Issue by vinayakagrawal88** [GoogleCloudPlatform/python-docs-samples#579]
This is a python-code enhancement to build sample application using vision API labeling feature to organize pictures. The code will accept two arguments - 
arg 1 - Source folder containing images 
arg 2 - Destination folder where all the images will be organized under resultant label-folders.

The code will demonstrate the application of vision api labeling feature that can be used to build picture-organization applications.

**Comment by jonparrott** [comment]
HI @vinayakagrawal88, in general we prefer to keep the samples here as simple as possible to demonstrate how to use a particular service. Unless there is a very strong demand for this particular sample, we won't be implementing it. However, we do encourage the community to write additional samples and we can even feature those over at https://github.com/GoogleCloudPlatform/awesome-google-cloud.

**Comment by vinayakagrawal88** [comment]
Thank you
