### ISSUE TITLE
requirements.txt hangs with pip install -r requirements.txt

### ISSUE THREAD

**Issue by thecloudist** [GoogleCloudPlatform/python-docs-samples#585]
Just cloned and merged a fork of the latest python-docs-samples repo.
Cannot successfully get requirements.txt to complete.
I may have to recreate the virtualenv fresh because the 0.18.1 version is what is active in the current virtualenv.  Your latest PB is 0.20.0 and I should be using that.

Update: This runs correctly in a new ve.  
The previous ve was unhappy to have a new gcp setup overlaid. 
My env is pretty fat at this point with paths and such.

What would be nice is to be able to build a slimmer package with only the GCP services needed for a project rather than everything that is in the python-docs-samples repo.  It has a lot of stuff I am not using at the moment.

**Comment by jonparrott** [comment]
@thecloudist glad you got it working.

> What would be nice is to be able to build a slimmer package with only the GCP services needed for a project rather than everything that is in the python-docs-samples repo. It has a lot of stuff I am not using at the moment.

Each individual sample has its own `requirements.txt`. We recently moved our top-level `requirements.txt` under `testing/` specifically for this reason.
