### ISSUE TITLE
python error with latest fork

### ISSUE THREAD

**Issue by thecloudist** [GoogleCloudPlatform/python-docs-samples#586]
I was able to run the latest sample code (unmodified) and get streaming transcripts.
When I go back to my modified source of transcribe_streaming_thread.py where I have had that working under the older master, I now get this error:

 from gcloud.credentials import get_credentials
ImportError: No module named gcloud.credentials

I am sure the GOOGLE_APPLICATION_CREDENTIALS env var is set properly.

I see that you have changed from "from gcloud.credentials import get_credentials" in transcribe_streaming_thread.py to "from google.cloud import credentials" in transcribe_streaming.py.

This indicates that there may possibly be other significant changes to how this works spread throughout the new sample.  

What do you advise to allow me to reach a freeze worthy code state?

Real time streaming voice rec is the holy grail for you (and us) and it would be great if there were a single set of API calls that provides this so we don't have to worry about code changing after we embed it into our applications. You can merrily update your service and we don't have to change our code.

**Comment by jonparrott** [comment]
@thecloudist `gcloud` recently renamed to `google-cloud`. We updated all dependencies in this repo as well as updated the code to match. If you want to use the latest version of `google-cloud-python` you'll need to do the same. If you're okay with using an older version, then [pin your dependencies](http://nvie.com/posts/pin-your-packages/).

Please keep in mind that we constantly update this repository to keep up with client library releases. That doesn't mean your code needs to do the same unless you want to.
