### ISSUE TITLE
Q: Requirements.txt needs to be run each time the virtualenv is invoked?

### ISSUE THREAD

**Issue by thecloudist** [GoogleCloudPlatform/python-docs-samples#589]
I assumed it needed to be run the first time only. 
Also, it looks like you are using sphinx.  Isn't this a self-contained voice rec system?

This is a huge load of stuff being installed since I used it yesterday.
Were there very large changes pushed last night?

Tons of this:

oringssl/ssl/d1_srvr.c -o python_build/temp.linux-armv7l-2.7/third_party/boringssl/ssl/d1_srvr.o -fno-wrapv -fvisibility=hidden -pthread -std=gnu99
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -I/usr/include/python2.7 -c third_party/boringssl/ssl/dtls_record.c -o python_build/temp.linux-armv7l-2.7/third_party/boringssl/ssl/dtls_record.o -fno-wrapv -fvisibility=hidden -pthread -std=gnu99
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -I/usr/include/python2.7 -c third_party/boringssl/ssl/pqueue/pqueue.c -o python_build/temp.linux-armv7l-2.7/third_party/boringssl/ssl/pqueue/pqueue.o -fno-wrapv -fvisibility=hidden -pthread -std=gnu99
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -I/usr/include/python2.7 -c third_party/boringssl/ssl/s3_both.c -o python_build/temp.linux-armv7l-2.7/third_party/boringssl/ssl/s3_both.o -fno-wrapv -fvisibility=hidden -pthread -std=gnu99
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -I/usr/include/python2.7 -c third_party/boringssl/ssl/s3_clnt.c -o python_build/temp.linux-armv7l-2.7/third_party/boringssl/ssl/s3_clnt.o -fno-wrapv -fvisibility=hidden -pthread -std=gnu99

**Comment by jonparrott** [comment]
> Requirements.txt needs to be run each time the virtualenv is invoked?

Yes, you need to run `pip install -r requirements.txt` every time you create a new virtualenv. If you're activating an existing one where you've already installed dependencies, you don't need to do it.

I'm not sure how to answer your section question.

**Comment by thecloudist** [comment]
This was a v.e. that I have been using since yesterday and everything worked. When I tried to run my app today, it didn't get past the creds validation, missing the package that does that. After I reinstalled requirements, it ran again.  Just that it took 20 minutes for requirements to complete.  (on a Raspi)

**Comment by jonparrott** [comment]
@thecloudist did you change the code between then?

**Comment by thecloudist** [comment]
That's just it.  I created a new VM and made the change to  the creds imports to:
'from google.cloud import credentials'.
After creating it, I installed requirements.txt and as I said, everything ran ok.

We can close this until the next time I re-enter the v.m. it does the same thing.
(Hoping it does not)

**Comment by jerjou** [comment]
Did you activate the virtualenv?

Read more about virtualenv [here](https://virtualenv.pypa.io/en/stable/userguide/)
