### ISSUE TITLE
Should UpdateSchemaHandler use get(..) instead of post(..)?

### ISSUE THREAD

**Issue by tanin47** [GoogleCloudPlatform/python-docs-samples#592]
Here: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/ndb/schema_update/main.py#L84

```
class UpdateSchemaHandler(webapp2.RequestHandler):
    """Queues a task to start updating the model schema."""
    def post(self):
        deferred.defer(update_schema_task)
        self.response.write("""
        Schema update started. Check the console for task progress.
        <a href="/">View entities</a>.
        """)
```

In https://cloud.google.com/appengine/articles/update_schema, we say: "When you're ready to kickoff the schema migration, simply upload the new source to your App Engine application using appcfg and visit the /update_schema handler using your favorite web browser."

But we can't fire a POST request by visiting the URL.

**Comment by jonparrott** [comment]
Thanks for reporting!

If you run the sample, it presents a form that lets you do a post request. The docs should be updated.

**Comment by tanin47** [comment]
We eventually run the migration from our local desktop connecting to the prod datastore using remote_api. It might also worth mentioning this in the doc. Thanks for fixing the wording.
