### ISSUE TITLE
transcribe_streaming.py freezes after I use the voice command “exit”

### ISSUE THREAD

**Issue by thetittenquetscher** [GoogleCloudPlatform/python-docs-samples#608]
When running python transcribe_streaming.py

the program freezes after I use the voice command “exit” . It keeps logging "Exiting..". Is this normal ?

<img width="562" alt="screen shot 2016-10-21 at 19 33 50" src="https://cloud.githubusercontent.com/assets/13262717/19614744/7862d40a-97f8-11e6-80b9-cd79fe03fb35.png">

**Comment by puneith** [comment]
@thetittenquetscher We are in the process of pushing a fix soon.

**Comment by puneith** [comment]
@thetittenquetscher Can you please re-try. We have added a fix.

**Comment by puneith** [comment]
Closing this issue, since it has been fixed. Please, re-open another issue if this doesn't work for you.
