### ISSUE TITLE
Add example of reading PubSub Message attribute

### ISSUE THREAD

**Issue by duivesteyn** [GoogleCloudPlatform/python-docs-samples#6080]
Hi
One thing missing from the pubsub example is attributes. Could you please consider adding this?

**Comment by dandhlee** [comment]
Hey @anguillanneuf, assigning to you if you can help take a look :)

**Comment by anguillanneuf** [comment]
Thanks @dandhlee. 

Hi @duivesteyn - we moved Pub/Sub specific [samples](https://github.com/googleapis/python-pubsub/tree/master/samples/snippets) to where its client library code lives so as to test them continuously. Here are the samples for publish with custom attributes and subscribe with custom attributes that you're looking for:

- https://cloud.google.com/pubsub/docs/publisher#using_attributes
- https://cloud.google.com/pubsub/docs/pull#pull-messages-with-custom-attributes
