### ISSUE TITLE
timeout issue with flex-templates/streaming_beam/requirements.txt when installing apache-beam[gcp]==2.29.0

### ISSUE THREAD

**Issue by zhanglingfei** [GoogleCloudPlatform/python-docs-samples#6110]
## In which file did you encounter the issue?
**Path**: python-docs-samples/dataflow/flex-templates/streaming_beam/requirements.txt

**URL**: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dataflow/flex-templates/streaming_beam/requirements.txt

### Did you change the file? If so, how?

Yes! I removed the dependence from requirements.txt and do not use this requirements.txt file. Instead ```run pip install apache-beam[gcp]==2.29.0``` from the Dockerfile in this path <python-docs-samples/dataflow/flex-templates/streaming_beam/Dockerfile>

## Describe the issue

**Current behaviour**:
This issue is posted to stackoverflow as per : https://stackoverflow.com/questions/64813705/dataflow-with-python-flex-template-launcher-timeout

It seems there is a timeout limit to pull files when installing dependencies to dataflow backend when using requirements.txt. So if specifying the dependence of  apache-beam[gcp]==2.29.0 in requirements.txt, the installation and creation of the dataflow job will timeout. However if only specifying the dependence apache-beam[gcp]==2.29.0 in Dockerfile and run pip install. The process will not suffer from time out and succeeded.

I advised the timeout pulling file issue can be clarified with addressing the timeout limit when using requirements.txt file during creating.

**Comment by davidcavazos** [comment]
Yeah, this is a known issue where Dataflow downloads and recompiles all the dependencies. Specifically, `pyarrow` takes a long time to compile, and sometimes hits the timeout. We recently merged a new version of the Dockerfile that pre-downloads the dependencies and then explicitly skips re-downloading them. That should take care of the timeout, but please let us know if that worked for you.

https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5692/files#diff-f57a84e48afcca829480a523a2986e3041a9ffa98676899c35ca524f12da9452

**Comment by stevenzhang-support** [comment]
thanks and the issue should be closed

**Comment by zhanglingfei** [comment]
thanks the issue should be closed
