### ISSUE TITLE
Can I run GRPC streaming analyze just once?

### ISSUE THREAD

**Issue by thecloudist** [GoogleCloudPlatform/python-docs-samples#615]
The multi-threaded version is very complicated. I just want to call for streaming recognize each time I need it rather than having it run as the main continuous loop of my app.

Is there a simple way to do that?

Once my other code is done, it will go back and capture audio, submit it to GRPC and transcribe the results and finish.

The version that records a file and then calls the REST service is not fast enough for near real-time transcription. I need the streaming version.

**Comment by jerjou** [comment]
Yes - remember, this is sample code. It's not a library in itself - you should feel free to change it how you see fit.

Assuming you have `interim_results=False`, `listen_print_loop` doesn't need to be a loop, and it doesn't need to print. It could instead return the result once it's finalized (or you could detect [`END_OF_SPEECH`](https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1beta1#google.cloud.speech.v1beta1.StreamingRecognizeResponse) and return an accumulation of results then). Or you could forego the `listen_print_loop` entirely and simply get the next result by getting the next iterator result - ie `result = next(recognize_stream)`. The main idea is that `recognize_stream` is just an iterator of responses - you should feel free to do anything you want with them.

Depending on if you want to keep the connection, or the microphone, open, you might want to exit the `cloud_speech.beta_create_Speech_stub` or `record_audio` context managers. If you want them both to close after you get a result, you can just rename the `main` function to not be the main function, and call it from your real main function (after modifying it to return results, of course).

**Comment by thecloudist** [comment]
Cheers.  Very helpful.
