### ISSUE TITLE
undefined variable in GAE task queue python sample

### ISSUE THREAD

**Issue by hoonji** [GoogleCloudPlatform/python-docs-samples#6166]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/19b4ece3bd4ebfc761ad45fd1a18a376d050fc22/appengine/flexible/tasks/create_app_engine_queue_task.py#L59

Running code gives error: `NameError: name 'in_seconds' is not defined`

**Comment by dandhlee** [comment]
Hey @hoonji ! Could you help clarify the following:

### Did you change the file? If so, how?

### What commands did you execute before running into this issue?

**Comment by averikitsch** [comment]
Hi @hoonji, If you run the sample [via the command line](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/19b4ece3bd4ebfc761ad45fd1a18a376d050fc22/appengine/flexible/tasks#run-the-sample-using-the-command-line) the function should pass in the variable: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/19b4ece3bd4ebfc761ad45fd1a18a376d050fc22/appengine/flexible/tasks/create_app_engine_queue_task.py#L20
However, I can update the TODO section to make sure this is set:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/19b4ece3bd4ebfc761ad45fd1a18a376d050fc22/appengine/flexible/tasks/create_app_engine_queue_task.py#L31-L35
