### ISSUE TITLE
add sample code for receiving a Pub/Sub notification from Secret Manager

### ISSUE THREAD

**Issue by sigilite** [GoogleCloudPlatform/python-docs-samples#6170]
## In which file did you encounter the issue?

python-secret-manager/samples/snippets/

### Did you change the file? If so, how?

Added a new file `consume_event_notification.py` and a unit test for the new function in `snippets_test.py`

## Describe the issue

Added sample code for consuming a Pub/Sub Event Notification from Secret Manager in a cloud function (see https://cloud.google.com/secret-manager/docs/event-notifications)

**Comment by busunkim96** [comment]
PR: https://github.com/googleapis/python-secret-manager/pull/138
