### ISSUE TITLE
Minimum required composer/airflow versions

### ISSUE THREAD

**Issue by zosoabi** [GoogleCloudPlatform/python-docs-samples#6171]
Hi, unfortunately, the only way to get the minimum required composer/airflow versions is to request for the code change.
Comments would be enough. 

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/28c0501b05ea8883fa42ab3f0a8da44a4a043ed0/composer/tools/composer_db_transfer.py#L1424

**Comment by leahecole** [comment]
Hey! Thanks for this submission. Just to clarify - you're looking for the minimum Composer/Airflow versions you need to run this migration script? If so, they are specified in the [accompanying instructions](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/composer/tools/composer_db_transfer.md). Definitely open to feedback on how to make that more clear and/or discoverable though if it was not easily findable.


I did realize that the README was out of date and said "we have no tools here" which is totally not true - this DB tool is there, so I did make a PR to update that and make it more visible. (#6181)

**Comment by zosoabi** [comment]
Thanks a lot. I'm curious if any alternative to composer_db_transfer solution could you suggest for airflow 1.10.6?

**Comment by leahecole** [comment]
Hi - apologies for delay - playing catchup after being ooo. For 1.10.6, I believe the supported and recommended approach is using the in-place migration capability to get to the bridge releases supported by this utility
