### ISSUE TITLE
problem with ipython

### ISSUE THREAD

**Issue by alexado128** [GoogleCloudPlatform/python-docs-samples#6241]
does anyone know how to exit out of the function? right now I'm in ipython. I copied the code from Google Cloud to install the Cloud Storage client library [https://cloud.google.com/docs/authentication/production#command-line], but I have no idea how to end the function. I tried to do "ctrl d" and "exit" and "exit()" but nothing has worked. 
`pinkshades@cloudhsell:~$ ipython
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: def implicit():
   ...:     from google.cloud import storage
   ...:     storage_client = storage.Client()
   ...:     buckets = list(storage_client.list_buckets())
   ...:     print(buckets)`

**Comment by busunkim96** [comment]
Hi,

I think you need an empty line (to "exit" the function scope) before calling `exit()`. 

This worked for me in Cloud Shell:

```py
busunkim@cloudshell:~ (busun-sandbox)$ ipython
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: def foo():
   ...:     print("hello world")
   ...: 

In [2]: exit()
```

**Comment by busunkim96** [comment]
Hi,

I'm going to close this out now, but please feel free to open a new one if you're still having trouble.

Thanks!
