### ISSUE TITLE
Example for custom container copy train/test/val data?

### ISSUE THREAD

**Issue by awcchungster** [GoogleCloudPlatform/python-docs-samples#6242]
## Describe the issue

I am using a custom training job.

Is there an example that references within the container how to pull data from the google storage URI provided Vertex into the container for training? Vertex splits my dataset files in train, test, val, but it also splits each of the sets into subfiles. I am having a hard time figuring out how to pull all the files neatly into one train, test, val for my python code to read. 

I am running a python-slim docker container, so I want to minimize install dependencies to only python packages. My data type is tabular.

**Comment by dandhlee** [comment]
hey @munkhuushmgl, could you help take a look at this?

**Comment by awcchungster** [comment]
In the training pipeline job, Vertex will create a new folder with my dataset in a folder with the dataset ID and timestamp as the name. Inside, there are the following files automatically split. Is the splitting consistent if I create another dataset with the same input file?

Could I be referred to a code snippet that stitches each file channel into a single file that can be ready by my python code?
My training code is reading in a single CSV. 

 test-00000-of-00004.csv
 test-00001-of-00004.csv
 test-00002-of-00004.csv
 test-00003-of-00004.csv
 training-00000-of-00004.csv
 training-00001-of-00004.csv
 training-00002-of-00004.csv
validation-00000-of-00004.csv
validation-00001-of-00004.csv
 validation-00002-of-00004.csv
 validation-00003-of-00004.csv
training-00003-of-00004.csv
--

**Comment by awcchungster** [comment]
Hi @munkhuushmgl, could I get some help ASAP please?

**Comment by dizcology** [comment]
Regarding stitching the files: If you are reading the csv files into pandas data frames, this might work: https://stackoverflow.com/questions/20906474/import-multiple-csv-files-into-pandas-and-concatenate-into-one-dataframe

You could do something similar with Python csv readers if you prefer not to take pandas as a dependency. 

Regarding split consistency, I am under the impression that the split between train/validate/test is randomized unless your dataset specifies it for every row of data.

**Comment by awcchungster** [comment]
Hi Yu-Han, 

Thanks for the response.

Vertex Training passes in a GS URI with a wildcard at the end. How do I list all the blobs that I need to read in?

"gs://******/dataset-*******-tables-2021-06-28T23:34:46.110658Z/training-*"

Is it possible to show how the prebuilt XGB containers handle this? I'd prefer not to do too much guess work to avoid code breaking in production workflows.

**Comment by dizcology** [comment]
Thank for the additional context. To list all the files on GCS with a given prefix in python, I would suggest using the storage client library:  https://cloud.google.com/storage/docs/listing-objects#storage-list-objects-python

**Comment by awcchungster** [comment]
Hi @dizcology, what the safest way to parse the AIP_TRAINING_DATA_URI format into bucket-name and prefix that can be passed into the listing objects method?

**Comment by awcchungster** [comment]
The `gs://*****/dataset--tables-2021-06-28T23:34:46.110658Z/training-*` with the asterisk breaks convention with Google cloud storage patterns and it's unclear to me how to wrap around

**Comment by tigersoldier** [comment]
The data URIs are following GCS wildcards: https://cloud.google.com/storage/docs/gsutil/addlhelp/WildcardNames

If your container has installed `gsutil`, an easy way to handle them is by invoking `gsutil ls` with the URI:

```python
subprocess.run(['gsutil', 'cp', data_uri], capture_output=True)
```

Then split the lines.

If you don't have `gsutil` installed and want to use the GCS client library, you can remove the `*` and all characters follwing it, then call the [list objects API](https://cloud.google.com/storage/docs/json_api/v1/objects/list) with prefix.

**Comment by dizcology** [comment]
From this codelab: https://codelabs.developers.google.com/codelabs/vertex-ai-custom-code-training#3 (especially the function `load_data_from_gcs`), it seems that dask is able to handle the format (with wildcards) `AIP_TRAINING_DATA_URI` is in.

**Comment by awcchungster** [comment]
Thanks @dizcology! Is there a repository of all the code labs? This would help a lot with figuring out Vertex boilerplate. 

My question is resolved though. Appreciate the help.

**Comment by dizcology** [comment]
@awcchungster I am glad to hear that you were able to resolve the issue! I will close this issue for now but please feel free to reopen if you run into related issues.

Vertex SDK (Python) has its own GitHub repo: https://github.com/googleapis/python-aiplatform. For Vertex AI specific concerns please consider opening issues there. 

Regarding codelabs, I think the simplest option might be to search on the site linked above. For example this search shows several Vertex AI codelabs: https://codelabs.developers.google.com/s/results?q=Vertex%20ai
