### ISSUE TITLE
"Error occurred in the launcher container: Template launch failed. See console logs." in dataflow job 

### ISSUE THREAD

**Issue by Shriyut** [GoogleCloudPlatform/python-docs-samples#6245]
I'm trying to automate the provisioning of dataflow job in https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dataflow/flex-templates/streaming_beam using cloud build, when I run the commands manually I don't get any issue but when I create the job using cloud build I get an error with textpayload as mentioned in the heading.

```
{
insertId: "mhp6ooc19f"
labels: {
dataflow.googleapis.com/job_id: "2021-06-26_14_28_18-8154030066452314415"
dataflow.googleapis.com/job_name: "streaming-beam-job"
dataflow.googleapis.com/log_type: "system"
dataflow.googleapis.com/region: "us-central1"
}
logName: "projects/testproject123456789-313307/logs/dataflow.googleapis.com%2Fjob-message"
receiveTimestamp: "2021-06-26T21:32:46.695137025Z"
resource: {
labels: {
job_id: "2021-06-26_14_28_18-8154030066452314415"
job_name: "streaming-beam-job"
project_id: "testproject123456789-313307"
region: "us-central1"
step_id: ""
}
type: "dataflow_step"
}
severity: "ERROR"
textPayload: "Error occurred in the launcher container: Template launch failed. See console logs."
timestamp: "2021-06-26T21:32:45.774785408Z"
}
```

This was the only error log I got in all of my attempts.
Other logs in dataflow console don't show anything out of the ordinary but 1 log seemed weird to me

"py options not set in envsetup file not set in envextra package not set in env"

Any help would be appreciated

**Comment by dandhlee** [comment]
Hey @davidcavazos, can you help take a look at this problem?

**Comment by dandhlee** [comment]
@Shriyut just to confirm, could you list out the steps you took to provision the dataflow job on Cloud Build? More info would help us be able to track the problem down.

**Comment by davidcavazos** [comment]
@Shriyut, unfortunately it's a known issue the unhelpful error message that you're getting. Right now there is no way of knowing what went wrong without looking into the logs. To access the logs:

1. Navigate into the Dataflow job page, it looks like your job ID is `2021-06-26_14_28_18-8154030066452314415`
2. At the bottom of the job page, to the right of the "Logs" label, click the "Show" button to toggle the "Logs" panel.
3. Click on the "Worker logs" tab at the top left of the Logs panel
4. Click the "View on Logs explorer" button at the top right of the Logs panel
    ![image](https://user-images.githubusercontent.com/2309379/128897073-6e11639b-487f-48ac-8aa0-8ad9641d45a4.png)
5. There you will be able to explore the logs to look for a more descriptive error message. At the left panel under "Log name", some places to look for common errors are `dataflow.googleapis.com/kubelet`, `dataflow.googleapis.com/docker`, `dataflow.googleapis.com/system`, and `dataflow.googleapis.com/worker`.

I hope that helps, please let us know if you find more information.

**Comment by Shriyut** [comment]
Hey guys,
I tried this over a month ago so I don't have the logs in my gcp console right now.
I was trying to run a pipeline using flex template and added all the steps involved in cloudbuild.yaml
I've been sick lately, once I feel better I'll recreate the scenario so that I can share the logs as asked.
Also, if possible I would love to help you guys in anyway possible since I graduated recently and I'm entirely new to this field, it would be a great learning opportunity for me to understand dataflow on a deeper level.

**Comment by davidcavazos** [comment]
Thank you! I hope you feel better soon. No need to rush in recreating this scenario, rest well and take care.

We don't currently have tests failing for this sample either (we had some flaky tests but those were due to the test setup, not the sample code) so we don't suspect this sample is currently broken, but it could very well be that some instruction or explanation is out of date or not clear enough.

We greatly appreciate any help we can get, if you find any way of improving the sample or the instructions we would appreciate it. When we author the tutorials and samples, we do go through all the instructions to make sure to the best of our knowledge that everything is working correctly, but sometimes there are product or service changes that break some things.

**Comment by meredithslota** [comment]
I'm going to close this as we haven't been able to repro it but please reopen if you find it reoccurs. I hope you are feeling better, Shriyut!
