### ISSUE TITLE
"django secrets and samples rework" Breaks Running Django on the App Engine standard environment documentation

### ISSUE THREAD

**Issue by JackRolfe** [GoogleCloudPlatform/python-docs-samples#6255]
## In which file did you encounter the issue?

appengine/standard_python3/django/mysite/settings.py

### Did you change the file? If so, how?

I didn't change the file.

## Describe the issue

The changes to the DATABASES section where the placeholders LINE 90: <your-database-user>, LINE 91: <your-database-password>, and LINE 112: <your-cloudsql-connection-string> are removed breaks the documentation https://cloud.google.com/python/django/appengine?authuser=1#configuring_the_database_settings

The documentation explicitly references these placeholders, as seen in the attached screenshot:

![documentation-error](https://user-images.githubusercontent.com/46526704/123945616-b3107000-d9e1-11eb-9eea-20bab10d7793.PNG)

**Comment by busunkim96** [comment]
It looks like the PR being referenced is https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5784. It looks like the internal changelist has not been submitted, so it may be that the sample is correct but the docs have not yet been updated.

**Comment by AniruddhaChidar** [comment]
I am facing the same issue. Is there some workaround?

**Comment by JackRolfe** [comment]
Hey, yeah you can use the previous version of the settings.py file and then follow the instructions in the documentation.
The previous version can be found by clicking the **History** button on the file then selecting the **View at this point in history** option. The attached files illustrate this process.

If you are using MySQL you will also need to add **mysqlclient==1.4.1** to the **requirements.txt** file or the command **pip install -r requirements.txt** will error.

![image](https://user-images.githubusercontent.com/46526704/124400022-ccf3df00-dd62-11eb-9a01-1bf195472d8b.png)
![image](https://user-images.githubusercontent.com/46526704/124400047-00366e00-dd63-11eb-800c-7eeca99c60ff.png)

**Comment by glasnt** [comment]
Thanks @JackRolfe, and sorry @AniruddhaChidar that you are both experiencing this issue. 

Using the older version of the settings file will work for the current version of the tutorial. We hope to get the new tutorial version updated soon to match the current code in the main branch. 

If you are following the tutorial by cloning the repo, you can add a single line to checkout the previous code version and continue the tutorial as it was: 

```
$ git checkout f917d331853bd2ebf45268d12860346dcd4194c7
```

**Comment by aschroder** [comment]
It looks like the Cloud Run tutorial has been updated with the new database settings here:
https://cloud.google.com/python/django/run#store-secret-values-in-secret-manager

<img width="906" alt="Screen Shot 2021-07-23 at 8 14 03 PM" src="https://user-images.githubusercontent.com/387235/126754808-11c4357d-5b96-4d02-801f-0aed9d809bc0.png">

**Comment by glasnt** [comment]
The tutorial has now been updated, and the sample should now match. Thanks for everyone who reached out!
