### ISSUE TITLE
Can't find Client attribute for translate 

### ISSUE THREAD

**Issue by jlim13** [GoogleCloudPlatform/python-docs-samples#636]
I get an attribute error while trying to call the Client function on the translate object. 
Traceback (most recent call last):
  File "exmp.py", line 49, in <module>
    translate_client = translate.Client(SECRET_KEY)
AttributeError: 'function' object has no attribute 'Client'

**Comment by jonparrott** [comment]
@jlim13 it seems like you overloaded the definition `translate`. Do you mind sharing your entire code?

**Comment by jlim13** [comment]
I originally had "from google.cloud import translate" at the top of my code with the rest of my imports but, put it within my main method like the demo to fix the problem. Why does this happen? 

if __name__ == "__main__":

    from google.cloud import translate

**Comment by jonparrott** [comment]
It's hard to say without seeing all of your code, but likely you had something like this going on:

```python
from google.cloud import translate

def translate():
   pass
```

when you do that, the `translate` function shadows the `translate` module.

**Comment by StarkGang** [comment]
@kelseyhightower u have explained translate as a func

**Comment by StarkGang** [comment]
@theacodes no , he has named translate as function and also imported it 
So it gave error
