### ISSUE TITLE
missing sample for ndb in appengine/flexible

### ISSUE THREAD

**Issue by mattwarrenrnp** [GoogleCloudPlatform/python-docs-samples#644]
## In which file did you encounter the issue?

Trying to find a way to use ndb in the flexible environment.  unsure if ndb is not supported in the flexible environment or if it's missing a sample.

## Describe the issue

missing example for NDB in appengine/flexible

**Comment by jonparrott** [comment]
ndb is not supported outside of the standard environment. If you're interested in this feature please let us know over at https://github.com/GoogleCloudPlatform/google-cloud-python/issues/557.
