### ISSUE TITLE
ha.pool.sks-keyservers.net no longer resolveable 

### ISSUE THREAD

**Issue by m-strzelczyk** [GoogleCloudPlatform/python-docs-samples#6440]
Since this repo uses similar kokoro setup to the one [python-compute](https://github.com/googleapis/python-compute) uses, I figured it will face similar problems as described in https://github.com/googleapis/python-compute/issues/79

I am working on a fix for this, so we don't use the unavailable key server.

**Comment by busunkim96** [comment]
@parthea

**Comment by parthea** [comment]
Hi @m-strzelczyk , 
We're not seeing the issue in this repo, possible because there is no `docs-presubmit` check.

**Comment by m-strzelczyk** [comment]
I know there's no docs-presubmit, but then there is the whole [docker](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/.kokoro/docker) folder that uses fetch_gpg_keys.sh - how does this not break tests for the python-docs-samples? Is this just dead code, no longer used?

**Comment by parthea** [comment]
Great question, @m-strzelczyk. We can try removing the docker folder and see if anything breaks.

**Comment by parthea** [comment]
I can reproduce the failure locally. I'm not sure why we don't see the problem in the pipeline.

**Comment by dandhlee** [comment]
Closing this issue as the PR to fix it was closed, please reopen as needed!
