### ISSUE TITLE
activate virtualenv works well for api-client but not for grpc

### ISSUE THREAD

**Issue by jcastill0** [GoogleCloudPlatform/python-docs-samples#646]
## In which file did you encounter the issue?

speech/grpc$ python transcribe.py

## Describe the issue

After activating the virtual environment I can run python api-client/transcribe.py with no problem, but when I do the same on the grpc executables, it fails with the error below.

Traceback (most recent call last):
  File "transcribe.py", line 20, in <module>
    from google.cloud.credentials import get_credentials
ImportError: No module named google.cloud.credentials

**Comment by jonparrott** [comment]
They have different `requirements.txt`, did you try `pip install requirements.txt` from within the `speech/grpc` folder?

**Comment by jcastill0** [comment]
no. I only did the install requirements from the api-client folder

**Comment by jcastill0** [comment]
my mistake for not doing the additional pip install

**Comment by jonparrott** [comment]
No worries! Glad we could get you unstuck.
