### ISSUE TITLE
gcs_uri error on speech/grpc transcribe call

### ISSUE THREAD

**Issue by jcastill0** [GoogleCloudPlatform/python-docs-samples#647]
## In which file did you encounter the issue?

speech/grpc$ python transcribe.py

## Describe the issue

Trying to transcribe a file that resides on an S3 bucket yields the following error (the file is accessible as you can do a wget on it and it works fine):

(env) vagrant@ubuntu16:~/speech/python/python-docs-samples/speech/grpc$ python transcribe.py https://s3-us-west-1.amazonaws.com/hackthon-audio/Happy-mac.raw
usage: transcribe.py [-h] [--encoding {LINEAR16,FLAC,MULAW,AMR,AMR_WB}]
                     [--sample_rate SAMPLE_RATE]
                     input_uri
transcribe.py: error: argument input_uri: invalid _gcs_uri value: 'https://s3-us-west-1.amazonaws.com/hackthon-audio/Happy-mac.raw'

**Comment by puneith** [comment]
The input_uri needs to be a GCS (Google Cloud Storage) Uri.
