### ISSUE TITLE
Cannot connect to google service account flask api in python

### ISSUE THREAD

**Issue by mariemzyr** [GoogleCloudPlatform/python-docs-samples#6584]
Hello! 
I’m trying to make a **python flask api to create a signed google cloud storage url**. For the moment I can’t even connect to my google credentials, because when I request my API an "internal error 500" comes out making me think that there is an error in my code. Can you help me? Thank you in advance.

![Capture d’écran 2021-08-17 à 10 58 20](https://user-images.githubusercontent.com/73951201/129696141-782d5c70-4e45-4765-8fdf-6943b9acc9a6.png)
![Capture d’écran 2021-08-17 à 11 01 31](https://user-images.githubusercontent.com/73951201/129696584-f5ec920d-22dd-4752-8460-c13f0ff12a07.png)

**Comment by busunkim96** [comment]
Hi @mariemzyr,

The internal server error seems to be raised by your application rather than the Storage API.

Could you try running the code to access the Storage API separately?

**Comment by dandhlee** [comment]
Closing this issue as it has been inactive for quite a while. If you're still running into issues or would like to follow up, please re-open this issue!
