### ISSUE TITLE
CryptographyDeprecationWarning: int_from_bytes is deprecated

### ISSUE THREAD

**Issue by randalb1991** [GoogleCloudPlatform/python-docs-samples#6605]
Executing the IAP sample https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/iap I'm getting the warning:

/usr/local/lib/python3.8/site-packages/google/auth/crypt/es256.py:56: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  r = utils.int_from_bytes(sig_bytes[:32], byteorder="big")

As a consequence, my code is failing. Is Someone else having this error?

**Comment by busunkim96** [comment]
Pending release is https://github.com/googleapis/google-auth-library-python/pull/847

**Comment by engelke** [comment]
Version 2.0.2 of google-auth fixes this, and the requirements.txt file should be updated to reflect that version. PR #6646 makes that change.
