### ISSUE TITLE
AttributeError: '_Environ' object has no attribute 'Env'

### ISSUE THREAD

**Issue by chandrika-D** [GoogleCloudPlatform/python-docs-samples#6663]
Getting this error in settings.py
even i have created .env file also

**Comment by chandrika-D** [comment]
Getting this error in settings.py 
even i have created .env file also

**Comment by dandhlee** [comment]
Hey @chandrika-D! Could you let us know the following to further assist you:

1. Which sample were you trying to use? Any links to a tutorial you're perhaps trying to use?
2. Which commands did you try running?
3. Which environment are you trying to run the samples in? I.e. your own Windows computer, Cloud Console, Mac or Linux.
3. Which files have you modified? And how did you modify the files?

**Comment by chandrika-D** [comment]
I am hosting a django website in a gcloud 
in that need to do some modifications in settings.py file after the modifications i am getting this error 
mine is windows 
i am getting error in this line 
**env = environ.Env(DEBUG=(bool, False))
env_file = os.path.join(BASE_DIR, ".env")**

**Comment by dandhlee** [comment]
How are you importing `_Environ`? Are you doing `from os import environ as _Environ`? If so, you'll need to use 
```
python -m pip install django-environ
```

If not, are you trying to use any of the Samples in this repo? Could you point me to which one you're trying to use?

**Comment by dandhlee** [comment]
Closing the issue as this has been inactive for quite a while. Please re-open this issue if you're still having any trouble or would like to follow up!
