### ISSUE TITLE
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python3/hello_world/main.py

### ISSUE THREAD

**Issue by 0907137723-s** [GoogleCloudPlatform/python-docs-samples#6676]
https://thtopnews.onelink.me/sfeV?pid=app_invites&c=10006236542&af_adset=home&af_ad=invite_Line&af_web_dp=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.thtopnews.app

**Comment by busunkim96** [comment]
Hi,

It's not clear to me what problem you are facing from the title and issue body. If you are experiencing problems, please open a new issue with more details.

Thanks!
