### ISSUE TITLE
'Issuing an asynchronous request' needs a tip for adding protorpc library

### ISSUE THREAD

**Issue by awalias** [GoogleCloudPlatform/python-docs-samples#670]
the page at https://cloud.google.com/appengine/docs/python/issue-requests#issuing_an_asynchronous_request describes how to make async requests, but I had to do a bit of searching to find out that I needed to include:

`- name: protorpc
  version: latest`

in my app.yaml. It's not mentioned.

On live site it gives a:

> ApplicationError: ApplicationError: 9 This api has not been enabled for your application.
at CheckSuccess (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py:134)

if not present

**Comment by jonparrott** [comment]
Huh. Strange. Thanks for reporting!

@ryanmats can you take this?

**Comment by ryanmats** [comment]
@jonparrott sure!

**Comment by ryanmats** [comment]
Hi @awalias . Our sample code seems to work locally and when deployed, and we were unable to reproduce your error. Please let us know if you have any particular code that can reproduce the case!

Thanks.
