### ISSUE TITLE
Version creation failed: user-provided package <> failed to install

### ISSUE THREAD

**Issue by itsciccio** [GoogleCloudPlatform/python-docs-samples#6753]
I'm trying to deploy a fbprophet model on AI Platform. I have successfully managed to train the model, creating a model.pkl file that is automatically uploaded to a cloud storage bucket after the training job is completed. I am following the following tutorial in order to deploy the model using a **custom prediction routine:** https://cloud.google.com/ai-platform/prediction/docs/custom-prediction-routines

That being said, the following is my Predictor class within predictor.py:

```
import pickle 
import pandas as pd
import numpy as np
from fbprophet import Prophet
import os

class Predictor(object):
    def __init__(self, model):
        self._model = model

    def predict(self, instances, **kwargs):
        future = self._model.make_future_dataframe(periods=31, freq='D')
        forecast = self._model.predict(future)
        
        forecast = forecast[['ds','yhat','yhat_lower','yhat_upper']]

        forecast['yhat'] = [max(0,pred) for pred in forecast['yhat']]
        forecast['yhat_lower'] = [max(0,pred) for pred in forecast['yhat_lower']]
        forecast['yhat_upper'] = [max(0,pred) for pred in forecast['yhat_upper']]

        forecast.drop(columns=['ds','yhat','yhat_lower','yhat_upper'], axis=1)

        output = {}
        for index, row in forecast.iterrows():
            row_data = {'prediction':row['yhat'], 'prediction_upper_bound':row['yhat_lower'], 'prediction_lower_bound':row['yhat_upper']}
            date_row = row['ds'].to_pydatetime().strftime("%m-%d-%Y")
            output[date_row] = row_data 

        return output

    @classmethod
    def from_path(cls, model_dir):        
        model_path = os.path.join(model_dir, 'model.pkl')
        model = pickle.load(open(model_path, 'rb'))     

        return cls(model)
```

And the `ai-platform versions create` job:

`gcloud beta ai-platform versions create prophetpred002 --model proph_ga --runtime-version 2.5 --python-version 3.7 --origin gs://internet_ga-data/models --package-uris gs://internet_ga-data/pred_routine/prophet_custom_prediction-0.1.tar.gz --prediction-class predictor.Predictor --machine-type mls1-c1-m2 --region global`

The run-time and python version is identical to the versions submitted in the training job. I have set the machine type as such since it allows for custom predictions.

Nothing too complicated. However, when i submit the job, I get the following error:

`Create Version failed. Bad model detected with error: "Failed to load model: User-provided package test_code-0.1.tar.gz failed to install: Command '['python-default', '-m', 'pip', 'install', '--target=/tmp/custom_lib', '--no-cache-dir', '-b', '/tmp/pip_builds', '/tmp/custom_code/prophet_custom_prediction-0.1.tar.gz']' returned non-zero exit status 1 (Error code: 0)"
`

Also, I have the following setup.py file included in the .tar.gz:

```
from setuptools import find_packages
from setuptools import setup

REQUIRED_PACKAGES = ['pystan==2.19.1.1','fbprophet']

setup(
    name='prophet_custom_prediction',
    version='0.1',
    install_requires=REQUIRED_PACKAGES,
    packages=find_packages(),
    include_package_data=True,
    description='My training application package.',
    scripts=['predictor.py']
) 
```

I included it to make sure that the correct modules are downloaded. I had done the same for the training job submission and it worked like a charm.

Any help on the matter? Is it even possible to deploy an fbprophet model on AI Platform ? (have not found much info about it online) 

--------------------------

Extra info with `--verbosity="debug"`:

> Creating version (this might take a few minutes)......failed.
DEBUG: (gcloud.beta.ai-platform.versions.create) Create Version failed. Bad model detected with error:  "Failed to load model: User-provided package prophet_custom_prediction-0.1.tar.gz failed to install: Command '['python-default', '-m', 'pip', 'install', '--target=/tmp/custom_lib', '--no-cache-dir', '-b', '/tmp/pip_builds', '/tmp/custom_code/prophet_custom_prediction-0.1.tar.gz']' returned non-zero exit status 1. (Error code: 0)"
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/ai_platform/versions/create.py", line 208, in Run
    autoscaling_hidden=False)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/versions_util.py", line 169, in Create
    message='Creating version (this might take a few minutes)...')
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/versions_util.py", line 74, in WaitForOpMaybe
    return operations_client.WaitForOperation(op, message=message).response
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/ml_engine/operations.py", line 113, in WaitForOperation
    sleep_ms=5000)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 264, in WaitFor
    sleep_ms, _StatusUpdate)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 326, in PollUntilDone
    sleep_ms=sleep_ms)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 249, in RetryOnResult
    if not should_retry(result, state):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 320, in _IsNotDone
    return not poller.IsDone(operation)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 122, in IsDone
    raise OperationError(operation.error.message)
googlecloudsdk.api_lib.util.waiter.OperationError: Create Version failed. Bad model detected with error:  "Failed to load model: User-provided package prophet_custom_prediction-0.1.tar.gz failed to install: Command '['python-default', '-m', 'pip', 'install', '--target=/tmp/custom_lib', '--no-cache-dir', '-b', '/tmp/pip_builds', '/tmp/custom_code/prophet_custom_prediction-0.1.tar.gz']' returned non-zero exit status 1. (Error code: 0)"
ERROR: (gcloud.beta.ai-platform.versions.create) Create Version failed. Bad model detected with error:  "Failed to load model: User-provided package prophet_custom_prediction-0.1.tar.gz failed to install: Command '['python-default', '-m', 'pip', 'install', '--target=/tmp/custom_lib', '--no-cache-dir', '-b', '/tmp/pip_builds', '/tmp/custom_code/prophet_custom_prediction-0.1.tar.gz']' returned non-zero exit status 1. (Error code: 0)"

**Comment by busunkim96** [comment]
Hey @GoogleCloudPlatform/ai-platform-samples-owners, I think @itsciccio is using aiplatform through gcloud, could one of you take a look?

**Comment by leahecole** [comment]
Also assigning @nicain for triage in case he knows a specific DPE on the github team to send it to

**Comment by dandhlee** [comment]
Hey @itsciccio, friendly ping to take a look at Karl's suggestion!

**Comment by dandhlee** [comment]
Closing the issue for now, please re-open if needed.
