### ISSUE TITLE
ImportError: cannot import name 'connection' in logs when deploying via App Engine

### ISSUE THREAD

**Issue by jeremykeen** [GoogleCloudPlatform/python-docs-samples#689]
## In which file did you encounter the issue?

python-docs-samples/appengine/flexible/pubsub/main.py

### Did you change the file? If so, how?

No

## Describe the issue

Error when deploying to App Engine: 
`from google.cloud.pubsub.connection import Connection
File "/env/lib/python3.4/site-packages/google/cloud/pubsub/connection.py", line 19, in <module>
from google.cloud import connection as base_connection
ImportError: cannot import name 'connection'`  

In the CLI I eventually get the below error and the app simply is repeatedly relaunching.

`ERROR: (gcloud.app.deploy) Error Response: [13] Timed out when starting VMs.  It's possible that the application code is unhealthy.`

**Comment by jonparrott** [comment]
Hi @jkeenest does this work locally? Can you share the entire stacktrace/deploy output?

**Comment by jkeenest** [comment]
locally run..

`Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from google.cloud import pubsub
  File "C:\Users\keenj\AppData\Local\Programs\Python\Python35-32\lib\site-packages\google\cloud\pubsub\__init__.py", line 27, in <module>
    from google.cloud.pubsub.client import Client
  File "C:\Users\keenj\AppData\Local\Programs\Python\Python35-32\lib\site-packages\google\cloud\pubsub\client.py", line 21, in <module>
    from google.cloud.pubsub.connection import Connection
  File "C:\Users\keenj\AppData\Local\Programs\Python\Python35-32\lib\site-packages\google\cloud\pubsub\connection.py", line 19, in <module>
    from google.cloud import connection as base_connection
ImportError: cannot import name 'connection'`

**Comment by jonparrott** [comment]
Hi Jeremy, it seems you might have an old/broken install of the google cloud libraries. Can you send over the output of `pip freeze`?

You should use a [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/) when working locally, this will ensure the sample has the correct version of the dependencies.

**Comment by jeremykeen** [comment]
Tried again with a new clone and virtualenv locally.  This worked.  Now for deploying in App Engine... I was getting errors from Cloud Compute re: alpha not enabled.  I will try to reproduce.

**Comment by jonparrott** [comment]
Great, I'm gonna close this issue but feel free to reach out if you need anything else.
