### ISSUE TITLE
Cloud run django app cannot contain "authentication" in path

### ISSUE THREAD

**Issue by HuangLiPang** [GoogleCloudPlatform/python-docs-samples#6929]
## In which file did you encounter the issue?
[cloud run django example](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/run/django)

### Did you change the file? If so, how?
Yes, I added django rest framework to the app and added an authentication class in folder `polls/authentication/`

I define the autehntication class in settings.py like this
```
REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = [
    "v3.firebase.auth.FirebaseAuth",
]
```

## Describe the issue

When deploying to cloud run, it will always says ModuleNotFoundError
```
Traceback (most recent call last): 
File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 177, 
in import_from_string return import_string(val) File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, 
in import_string module = import_module(module_path) File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, 
in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1014, 
in _gcd_import File "<frozen importlib._bootstrap>", line 991, in _find_and_load File "<frozen importlib._bootstrap>", line 973, 
in _find_and_load_unlocked ModuleNotFoundError: No module named 'v3.authentication.firebase_auth'
```

This is the actual error message. The app name is `v3` and the authentication class is in the `v3/authentication/firebases_auth.py`.

After I change the folder name `authentication` to `firebase`. It works well.

**Comment by busunkim96** [comment]
Tentatively triaging as `type: question` to appease the bots over the weekend. @glasnt Please change it to the appropriate label after you've reviewed.

**Comment by glasnt** [comment]
Hi @HuangLiPang, are you using any additional packages to get this functionality working?

If you aren't using any packages, then I expect DRF is trying to load a module from the relative filesystem. If you have `authentication` in your filesystem but your module is being referenced with `auth`, then this may not work. 

This question is well outside of the scope of this sample, but I hope the above helps you debug.
