### ISSUE TITLE
PubSub push subscription error: The supplied HTTP URL is not registered in the project that owns the subscription

### ISSUE THREAD

**Issue by jeremykeen** [GoogleCloudPlatform/python-docs-samples#695]
When creating a push subscription for this app, I get the error below caused by the addition of the "-preview" to the address by the GAE Flexible environment.  Removing this allows me to create the subscription but then I get redirect responses.  Is this the correct behavior or does appspot-preview.com need to be added somehow?

`The supplied HTTP URL is not registered in the project that owns the subscription (url="https://<app-id>.appspot-preview.com/pubsub/push?token=1234abc", project_id="<proj-id>").`

## In which file did you encounter the issue?
python-docs-samples\appengine\flexible\pubsub\

**Comment by jonparrott** [comment]
This is a known issue and unfortunately pub/sub push notifications to flex will not work until the redirects are removed.

**Comment by jeremykeen** [comment]
Ok, if that is the case, does the sample python app need to use flex as specified in the app.yaml?

python-docs-samples/appengine/flexible/pubsub/app.yaml

**Comment by jonparrott** [comment]
I'm not sure what you're asking.

**Comment by jeremykeen** [comment]
The sample app that receives push subscriptions uses App Engine Flex which does not work with pub/sub.

**Comment by jonparrott** [comment]
I'm still not completely clear on what you mean, but the sample app will remain as-is in anticipation of the infrastructure bug being fixed.

**Comment by jeremykeen** [comment]
What is the timing of the redirect removal?  Until then, the sample app code does not work with pub/sub because it leverages App Engine Flex.

**Comment by jonparrott** [comment]
No timeline, but it is a high priority issue.

**Comment by jonparrott** [comment]
The redirect should be resolved now, closing.
