### ISSUE TITLE
Add unit tests for datastore/ndb/overview and datastore/ndb/transactions

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#7]

**Comment by tmatsuo** [comment]
@jeffmendoza The top level tox.ini and travis config started working properly. Can you add unit tests for code in these 2 directories so that travis can run your tests?

**Comment by tmatsuo** [comment]
FYI https://github.com/GoogleCloudPlatform/python-docs-samples/pull/18 will allow you to run the tox test against your own project.

**Comment by jeffmendoza** [comment]
Closed with #33
