### ISSUE TITLE
create sql instance code 

### ISSUE THREAD

**Issue by sunset1234321** [GoogleCloudPlatform/python-docs-samples#7010]
there are create computer engine example 

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/compute/api/create_instance.py

is there any example for creating sql instance ?

**Comment by parthea** [comment]
Hi @sunset1234321,

Under https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/cloud-sql, you can choose the specific database type (mysql, postgres or sql-server). There is a link in the README under `client-side-encryption` for creating a new instance however I wasn't able to find any code samples in this repo. This sounds like a great addition, so I'll add the feature request label.

**Comment by m-strzelczyk** [comment]
It seems we don't have a client library for CloudSQL according to this list https://github.com/googleapis/google-cloud-python

I could prepare a sample that uses the REST API directly, without any library wrappers, but I'm not sure that's the goal here.

**Comment by m-strzelczyk** [comment]
We have samples for creating Cloud SQL instances with REST APIs: https://cloud.google.com/sql/docs/mysql/create-instance

We do not have any libraries for programming languages that would make it simpler for the users. I'm closing this issue, as we cannot create samples without proper libraries.
