### ISSUE TITLE
link to writing your first django app dead

### ISSUE THREAD

**Issue by felixfarquharson** [GoogleCloudPlatform/python-docs-samples#7033]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/django

## Describe the issue
the link to the django tutorial on the django site, mentioned in the readme, is dead. the django website says to let them know if its wrong.

**Comment by leahecole** [comment]
I think the hyperlink just needs to be updated to a more recent version of django

**Comment by engelke** [comment]
See PR #7040 for the fix.
