### ISSUE TITLE
Pagination for DICOM datastore

### ISSUE THREAD

**Issue by sukhboldt-rp** [GoogleCloudPlatform/python-docs-samples#7044]
## In which file did you encounter the issue?

python-docs-samples/healthcare/api-client/v1/dicom/dicomweb.py

### Did you change the file? If so, how?

N/A

## Describe the issue

Is there a way to count the number of studies or series in a given DICOM datastore? 

I was able to do this for HL7v2 datastore by using the `list` method, which supports [pagination](https://github.com/googleapis/google-api-python-client/blob/main/docs/pagination.md). I could set the `pageSize` and go through the datastore by the `nextPageToken` until I hit the end, and count message identifiers.

However, for DICOM datastores it seems like `list` method is supported only to list datastores within a given dataset, but not to list things inside the datastore. The current `dicomweb_search_*` methods (in dicomweb.py) return header data instead of identifiers, and they are limited to 100 for studies, and to 1000 for series or instances.

Reading on documentation I notice that there may be ways to slightly increase these limits, but I couldn't find anything on whether I can swift through the DICOM datastore page by page.

My work around has been to export the DICOM datastore into BQ, and do all the counting on BQ. But I was wondering if there are some more direct ways to do this through dicomweb?

thank you for your time!

**Comment by noerog** [comment]
Hi Tuguldur, you can count the entries in the JSON array returned in the response. For example, when searching for instances (https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/healthcare/api-client/v1/dicom/dicomweb.py#L77) you can count the number of entries in response.json() to find the number of instances returned.

You can also do paging using the limit and offset query parameters, which are explained in https://cloud.google.com/healthcare-api/docs/dicom#search_parameters.

**Comment by sukhboldt-rp** [comment]
> Hi Tuguldur, you can count the entries in the JSON array returned in the response. For example, when searching for instances (https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/healthcare/api-client/v1/dicom/dicomweb.py#L77) you can count the number of entries in response.json() to find the number of instances returned.
> 
> You can also do paging using the limit and offset query parameters, which are explained in https://cloud.google.com/healthcare-api/docs/dicom#search_parameters.

thank you @noerog!

I see that my confusion was on not realizing `limit` and `offset` were query parameters. Combining the two in the params dictionary I am now being able to paginate through the DICOM datastore. For some reason I kept thinking these were params to `response()` and was not able to find any docs on it.

All is clear, closing the issue. Thank you again!
