### ISSUE TITLE
Update Python samples for google-cloud to use latest library versions

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/python-docs-samples#708]
We will be updating several of our libraries to a new version imminently: https://github.com/GoogleCloudPlatform/google-cloud-python/releases

Especially important is that BigQuery, Storage, Datastore, and Logging are now at Beta.

We should update all our samples to test against the latest library for each of these APIs.

(and we can update the other samples for all other APIs to use the latest library available as well).

**Comment by jonparrott** [comment]
This is automated. Worst case, it take a day for that to happen.

**Comment by omaray** [comment]
SG.
