### ISSUE TITLE
functions/v2/storage/ missing test

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/python-docs-samples#7126]
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/functions/v2/storage does not have a `requirements.txt` or a test file.

@engelke I've assigned this to you as you were the original author of the sample, but please re-assign it if someone else owns this sample now.

Thanks!

**Comment by engelke** [comment]
Fixed in #7143
