### ISSUE TITLE
compute/xmpp_wikibot missing tests and not compatible with 3.10

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#7141]
Hi! I noticed that [this sample](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/compute/xmpp_wikibot) is failing [Python 3.10 periodic tests](https://fusion2.corp.google.com/invocations/8c16106e-c22b-41c8-8ddf-29af1e77cd1c/targets/cloud-devrel%2Fpython-docs-samples%2Fpython3.10%2Fperiodic;config=default/log) and wanted to highlight a a few things and propose possible solutions

**Problems**
- This sample is missing tests - if it's going to stick around, we should have some system tests for it!
- This sample relies on [a library that is very deprecated](https://github.com/fritzy/SleekXMPP) which is why it does not work for 3.10
- This doesn't appear anywhere in the docs

**Possible solutions**
- Remove this sample - if folks aren't using this sample, the easiest way to update it is to remove it! 😁 
- Update this sample to add a test and a `[noxfile_config.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/noxfile_config.py)` that excludes Python 3.10
- Update this sample to add a test and refactor it to use [slixmpp](https://github.com/poezio/slixmpp)

Please reach out to me or anyone in @GoogleCloudPlatform/python-samples-owners for recommendations and since I know office hours aren't in a great time zone for you also feel free to set up time that is during your work hours to chat if you'd like!

**Comment by m-strzelczyk** [comment]
I think we should just delete this sample. There's not point in showing an example with deprecated library. Especially, since it's not even mentioned in our public docs.

I'll prepare a PR removing it.
