### ISSUE TITLE
Sample app: uploading directly to GCS

### ISSUE THREAD

**Issue by koendewit** [GoogleCloudPlatform/python-docs-samples#716]
There is a sample web app for uploading files **directly** into the **blobstore**, using blobstore.create_upload_url(): https://github.com/GoogleCloudPlatform/python-docs-samples/blob/06d9254ec77955c02f18cd79a57cdfbd64dbf8ea/appengine/standard/blobstore/main.py

There is also a sample web app for uploading a file into **GCS**, but that sample does not use direct upload. The sample app accepts the file, then uploads the contents to GCS: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/85d4b1c52de3b8749c139c63bd9f37fdd85da4c8/appengine/flexible/storage/main.py

Is it possible to provide a sample web app for uploading a file **directly** into **GCS**, using the new Cloud Client Libraries for GCS ?  The advantage of a direct upload to GCS is that it allows uploading large files to App Engine applications. The standard environment has limits on request size (32 MB) and execution time (60s) that don't allow to process upload requests for large files.

**Comment by jonparrott** [comment]
Hi @koendewit this is a fantastic request. This is possible with GCS, but it's not trivial. There's two options:

1. You can start a [resumable upload and then give the upload URL to a client to continue uploading](https://cloud.google.com/storage/docs/access-control/signed-urls#signing-resumable). This works best for mobile clients. There's an [open issue for support on this in the cloud client library](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1240).
2. You can create a [policy document](https://cloud.google.com/storage/docs/xml-api/post-object#policydocument) and use regular HTML forms to do the upload. Here's a new [feature request for this in cloud client library](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2861).

**Comment by jonparrott** [comment]
Update: the latest version of the google-cloud-storage library has the needed helpers to make this happen.

**Comment by claudiadast** [comment]
What would be the best way to upload multiple files directly to GCS using a python client library?

**Comment by jonparrott** [comment]
@claudiadast multiple files at the same time? I'd recommend just using the latest client library with `concurrent.futures.ThreadPoolExecutor` to do them in parallel.

(closing this issue for now, but feel free to comment).
