### ISSUE TITLE
Updating composer and data-science-onramp references to master

### ISSUE THREAD

**Issue by dandhlee** [GoogleCloudPlatform/python-docs-samples#7168]
Hey @leahecole, asking you as the codeowner for both directories.

There are references to `master` in following files:

```
./data-science-onramp/data-processing/process_test.py
./data-science-onramp/data-ingestion/ingestion_test.py
./composer/airflow_1_samples/hadoop_tutorial.py
./composer/workflows/hadoop_tutorial.py
```

I was wondering if the references mentioned can simply be renamed to `main`, or does the API strictly require that option to be called `master_config` or `master_*`? Please take a look! :)

**Comment by leahecole** [comment]
Hi! These references are specifically part of Dataproc configuration and are related to the underlying API, so we unfortunately can't change them yet

**Comment by dandhlee** [comment]
Thanks for looking into it! Much appreciated :)
