### ISSUE TITLE
Getting AttributeError in Streaming API client

### ISSUE THREAD

**Issue by chan71** [GoogleCloudPlatform/python-docs-samples#719]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/grpc/transcribe_streaming.py

### Did you change the file? If so, how? 
No changes to file. 

## Describe the issue
Getting an error when the file is run after setting the environment variable `GOOGLE_APPLICATION_CREDENTIALS`. I'm using Python 2.7.11 on Windows 8.1.

Stack trace: 
```
C:\test>python transcribe_streaming.py
Traceback (most recent call last):
  File "transcribe_streaming.py", line 238, in <module>
    main()
  File "transcribe_streaming.py", line 214, in main
    make_channel('speech.googleapis.com', 443)) as service:
  File "transcribe_streaming.py", line 52, in make_channel
    creds = credentials.get_credentials().create_scoped([SPEECH_SCOPE])
AttributeError: 'Credentials' object has no attribute 'create_scoped'

```

**Comment by jonparrott** [comment]
@chan71 can you give me the output of ```pip freeze```?

**Comment by chan71** [comment]
Please find the output of `pip greeze`

```
C:\windows\system32>pip freeze
enum34==1.1.6
future==0.16.0
futures==3.0.5
gapic-google-cloud-speech-v1beta1==0.14.0
google-auth==0.4.0
google-auth-httplib2==0.0.2
google-cloud-core==0.22.1
google-cloud-speech==0.22.0
google-gax==0.15.0
googleapis-common-protos==1.5.0
grpc-google-cloud-speech-v1beta1==0.11.1
grpcio==1.0.3
httplib2==0.9.2
oauth2client==3.0.0
ply==3.8
protobuf==3.1.0.post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
PyAudio==0.2.9
pysolr==3.6.0
requests==2.12.3
rsa==3.4.2
six==1.10.0
virtualenv==15.1.0
watson-developer-cloud==0.22.0
ws4py==0.3.5
```

**Comment by jonparrott** [comment]
Ah I see, this whole sample needs to be updated to use `google.auth`.

Maybe @jerjou or @ryanmats  can handle it?

We should essentially replace `make_channel` with http://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.grpc.html#google.auth.transport.grpc.secure_authorized_channel

**Comment by chan71** [comment]
Thanks @jonparrott for the direction. I'm trying adding google.auth to the sample myself. Is there any other sample that is up to date with google.auth?

**Comment by jonparrott** [comment]
Not one that users grpc directly.

**Comment by chan71** [comment]
In my attempt at getting google.auth added to transcribe_streaming.py, I modified the code to use google.auth as given in [here](http://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.grpc.html#google.auth.transport.grpc.secure_authorized_channel). 

Installed google-cloud-speech-v1 using `pip install grpc-google-cloud-speech-v1` before running the file. But getting the following error. What could be the reason? 

```
C:\>python transcribe_streaming-new.py
Traceback (most recent call last):
  File "transcribe_streaming-new.py", line 256, in <module>
    main()
  File "transcribe_streaming-new.py", line 231, in main
    with cloud_speech.create_Speech_stub(
AttributeError: 'module' object has no attribute 'create_Speech_stub'
```

**Comment by jonparrott** [comment]
@chan71 seems it was a more significant change than anticipated: We have a PR out to fix this here: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/724

**Comment by chan71** [comment]
Works like a charm. Appreciate your fast turnaround in fixing this @jonparrott and team

**Comment by jonparrott** [comment]
Happy to help!
