### ISSUE TITLE
Bug in app.yaml

### ISSUE THREAD

**Issue by lhmatt** [GoogleCloudPlatform/python-docs-samples#721]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/endpoints-frameworks-v2/echo/app.yaml

## Describe the issue

On line 31 where you define the `ENDPOINTS_SERVICE_NAME` environment variable. The example begins `echo-api.endpoints` but this is not valid. It needs to be `echo.endpoints`.

If you were to simply change the project id in the example then the app would not run as expected - you would get a HTTP 403 error in the logs when trying to fetch the service config.

**Comment by jonparrott** [comment]
@sepehre @saicheems can one of you confirm?

**Comment by sepehre** [comment]
Correct, this is a doc bug. I'll update https://cloud.google.com/endpoints/docs/frameworks/python/quickstart-frameworks-python to say "echo-api.endpoints..." so this sample is consistent with all the others. 

Thanks for letting us know!

**Comment by jonparrott** [comment]
Great, I'll close this bug. :)

Thanks @sepehre and thanks @lhmatt for reporting.
