### ISSUE TITLE
Django configuration should be PROJECT_NUM instead of PROJECT_ID on the sample

### ISSUE THREAD

**Issue by irvifa** [GoogleCloudPlatform/python-docs-samples#7212]
## In which file did you encounter the issue?

https://cloud.google.com/python/django/run

### Did you change the file? If so, how?

Note that a secret in general will have the following form:

```
$ gcloud secrets describe django_settings
createTime: ""
etag: ""
name: projects/<PROJECT_NUM>/secrets/django_settings
replication:
  automatic: {}
````

Hence to make this [config ](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/c68fd4a2373a3258f7f4e2b8c4eecbb771eaf465/run/django/mysite/settings.py#L55) work, I need to change the PROJECT_ID to PROJECT_NUM in this config to make the secret manager work.

```
export GOOGLE_CLOUD_PROJECT=PROJECT_ID
```

to

```
export GOOGLE_CLOUD_PROJECT=PROJECT_NUM
```

## Describe the issue

The secret path is mismatched since it uses project id instead of project num, hence the secret won't be able to be found.

**Comment by glasnt** [comment]
Hi @irvifa 

While `gcloud` returns the resource identifier which includes the project number, you can supply either the project number or the project ID in the path to get the result required. 

You can see this code in action in the [Secret Manger Python library reference documentation](https://cloud.google.com/secret-manager/docs/reference/libraries#using_the_client_library).
