### ISSUE TITLE
Compile errors when installing required module in opennao vm (based on Gentoo OS)

### ISSUE THREAD

**Issue by chan71** [GoogleCloudPlatform/python-docs-samples#723]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/grpc/requirements.txt

### Did you change the file? If so, how?
No

## Describe the issue
In order to run  transcribe_streaming.py, I had to install the following modules among other things as per requirements.txt
grpcio==1.0.3
grpc-google-cloud-speech-v1beta1==0.11.1

When tried to install these on [opennao vm](http://doc.aldebaran.com/2-1/dev/tools/opennao.html) (GNU/Linux distribution based on Gentoo), compiler errors were noted. 
`CompileError: command 'i686-pc-linux-gnu-gcc' failed with exist status 1`

What could be the reason for above modules not getting installed in opennao vm. 

More observations
1. pip.log says 
- pip.log.grpcio at line 2077 shows termination due to stdalign.h 

![grpcio-failed](https://cloud.githubusercontent.com/assets/5590751/21231528/92f7eefe-c30e-11e6-9f70-f6bd05535ad0.jpg)

- pip.log.grpc-google-cloud-speech-v1beta1 at line 1781 shows termination due to stdalign.h 

![grpc-issue](https://cloud.githubusercontent.com/assets/5590751/21231539/9ff0bc08-c30e-11e6-936d-85a1cfa28361.jpg)

- Both module or package terminated due to stdalign.h

2. Installation Steps in OpenNaoVM:
   a. Install portaudio using emerge - OK
   b. Install pyaudio using emerge - OK
   c. Install package as per requirements.txt
        - google-cloud-core==0.22.1 - OK
        - grpcio==1.0.3 - FAIL
        - PyAudio==0.2.9 - OK
        - grpc-google-cloud-speech-v1beta1==0.11.1 - FAIL
        - six==1.10.0 - OK
   d. python transcribe_streaming.py – Throws an error

3. We used the OpenNao VM that define in this URL http://doc.aldebaran.com/1-14/dev/tools/vm-intro.html. We saw “binaries are built for i486 targets” in the snapshot as below but OS is i686. Not sure this cause the error.

![opennao-vm](https://cloud.githubusercontent.com/assets/5590751/21231765/6ddb5290-c30f-11e6-88e3-f985d08de1f7.jpg)

![opennao-vm-machine](https://cloud.githubusercontent.com/assets/5590751/21231715/472b87aa-c30f-11e6-9d6c-47fb4b2d53bb.png)

**Comment by jonparrott** [comment]
@chan71 thanks for the detailed report. 

1. Can you tell me which version of pip you're using? grpcio distributes manylinux wheels, so there shouldn't be any compilation *unless* you have an old pip or a very unique linux environment.
2. If you do need to build grpc, you'll need your distributions' equivalent of debian's build-essential, autoconf, and libtool packages.

**Comment by chan71** [comment]
@jonparrott  you are right. my opennao VM box has pip 1.0.2 where as the windows machine has pip 9.0.1. Does pip 1.0.2 needs compilation? If so, should I upgrade pip in opennao VM and try out?

**Comment by jonparrott** [comment]
@chan71 yeah pip 1.0.2 doesn't have wheel support. I highly, highly recommend updating because 1.0.2 was released in [2011](https://github.com/pypa/pip/releases/tag/1.0.2).

I'm going to go ahead and close this issue, but feel free to continue to comment if you need any more assistance.

**Comment by chan71** [comment]
@jonparrott thanks a lot for your insights into this issue. I will upgrade the pip and let you know.

**Comment by chan71** [comment]
@jonparrott after updating the pip in the opennao VM, we were able to proceed installing `grpcio `and `grpc `packages. We could run the latest sample but it threw an error due to input device (mic) not being present in the vm. I think this is fine. 

![audio-device-error](https://cloud.githubusercontent.com/assets/5590751/21283018/a221db24-c421-11e6-85e6-6d4485a34e07.png)

However, when we tried installing the required package in the NAO Robot we got into few issues as `emerge` package manager is not available in the NAO OS (supposed to be similar to opennao VM). 

These are the steps followed in the installation.
1. Check `pip `version =9.0.1 - OK
2. Install `virtualenv `- OK
3. Install `portaudio `using `emerge `– **Fail as emerge is not available in usr/bin**
4. Install `pyaudio `using `emerge `– Not Started yet
5. Install package as per requirements.txt
        `grpcio==1.0.4` – Not Started yet
        `PyAudio==0.2.9` – Not Started yet
        `grpc-google-cloud-speech-v1beta1==0.14.0` – Not Started yet
        `six==1.10.0` – Not Started yet
        `requests==2.12.4` – Not Started yet
        `google-auth==0.5.0` – Not Started yet
6. `python transcribe_streaming.py` – Not Started yet.

Then we copied the `portaudio `library (portaudio-19_pre20071207.tbz2) from opennao vm to Robot and ran `pip install`.

```
(env) nao [0] ~/googlespeech $ pip install -r requirements.txt
Collecting PyAudio==0.2.9 (from -r requirements.txt (line 2))
/var/persistent/home/nao/googlespeech/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/var/persistent/home/nao/googlespeech/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached PyAudio-0.2.9.tar.gz
Building wheels for collected packages: PyAudio
  Running setup.py bdist_wheel for PyAudio ... error
  Complete output from command /var/persistent/home/nao/googlespeech/env/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/var/volatile/tmp/pip-build-SqC1D8/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp4BLE1Upip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-2.7
  copying src/pyaudio.py -> build/lib.linux-i686-2.7
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-i686-2.7
  creating build/temp.linux-i686-2.7/src
  i686-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c src/_portaudiomodule.c -o build/temp.linux-i686-2.7/src/_portaudiomodule.o
  unable to execute i686-pc-linux-gnu-gcc: No such file or directory
  error: command 'i686-pc-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for PyAudio
  Running setup.py clean for PyAudio
Failed to build PyAudio
Installing collected packages: PyAudio
  Running setup.py install for PyAudio ... error
    Complete output from command /var/persistent/home/nao/googlespeech/env/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/var/volatile/tmp/pip-build-SqC1D8/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dluM0A-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/persistent/home/nao/googlespeech/env/include/site/python2.7/PyAudio:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-2.7
    copying src/pyaudio.py -> build/lib.linux-i686-2.7
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-i686-2.7
    creating build/temp.linux-i686-2.7/src
    i686-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c src/_portaudiomodule.c -o build/temp.linux-i686-2.7/src/_portaudiomodule.o
    unable to execute i686-pc-linux-gnu-gcc: No such file or directory
    error: command 'i686-pc-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/var/persistent/home/nao/googlespeech/env/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/var/volatile/tmp/pip-build-SqC1D8/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dluM0A-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/persistent/home/nao/googlespeech/env/include/site/python2.7/PyAudio" failed with error code 1 in /var/volatile/tmp/pip-build-SqC1D8/PyAudio/

```

Ignoring this error (should not have been done) we ran the `python transcribe_streaming.py` and ended up getting below error.
![stream-callback-error](https://cloud.githubusercontent.com/assets/5590751/21283148/c69f96ba-c423-11e6-9008-60042188033a.png)

We checked if `PyAudio `version is correct using `pip freeze` and found the following packages present in Robot.

```
(env) nao [err 1] ~/googlespeech $ pip freeze
enum34==1.1.6
futures==3.0.5
google-auth==0.5.0
googleapis-common-protos==1.5.0
grpc-google-cloud-speech-v1beta1==0.14.0
grpcio==1.0.4
httplib2==0.9.2
oauth2client==3.0.0
protobuf==3.1.0.post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
requests==2.12.4
rsa==3.4.2
six==1.10.0
```

My question is how to run `pip install -r requirements.txt` without an error so that PyAudio is installed properly. And I hope it will solve this issue. Appreciate any support.

**Comment by chan71** [comment]
@jonparrott can you kindly reopen this issue as I cannot reopen it. As the findings from our tests for now is on Robot is related to those of the previous findings which were related Robot OS VM provided for development.
