### ISSUE TITLE
README of translation API is old.

### ISSUE THREAD

**Issue by c-bata** [GoogleCloudPlatform/python-docs-samples#743]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/translate/cloud-client/README.rst

## Describe the issue

I want to use Google Translate API.
So I read the README and get API Key from CloudPlatform Console.

But, the snippets don't use `API Key` . So I searched the issues and found following issue.

https://github.com/GoogleCloudPlatform/python-docs-samples/pull/659

According to this issue, API Key is not required, but README still haven't updated.
I want to know the usage of Google Translate SDK.

**Comment by gguuss** [comment]
I updated the README in [this PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/802), changes should be merged, feel free to reopen if the instructions are still causing issues for you.
