### ISSUE TITLE
Speech API asynchrecognize returning without transcription

### ISSUE THREAD

**Issue by Aakash282** [GoogleCloudPlatform/python-docs-samples#747]
## In which file did you encounter the issue?

[transcribe_async.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/api-client/transcribe_async.py)

### Did you change the file? If so, how?
No
## Describe the issue
I ran the async transcription but there are no results: 

$> python transcription.py 30\ Second\ Elevator\ Speech.mp3
"name": "2031513765692485155"}
Waiting for server processing...
Waiting for server processing...
Waiting for server processing...
Waiting for server processing...
Waiting for server processing...
{"response": {"@type": "type.googleapis.com/google.cloud.speech.v1beta1.AsyncRecognizeResponse"}, "done": true, "name": "2031513765692485155", "metadata": {"lastUpdateTime": "2017-01-05T21:00:59.102697Z", "@type": "type.googleapis.com/google.cloud.speech.v1beta1.AsyncRecognizeMetadata", "startTime": "2017-01-05T21:00:18.750814Z", "progressPercent": 100}}

Is this because I am giving an mp3? Why isn't including any alternatives?

**Comment by puneith** [comment]
@Aakash282 Checkout the format https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/api-client/transcribe_async.py#L62 and give the raw format as input file.
