### ISSUE TITLE
Investigate into clusters not being deleted for data-science-onramp tests

### ISSUE THREAD

**Issue by dandhlee** [GoogleCloudPlatform/python-docs-samples#7497]
While running the tests several times on `data-science-onramp/` directories, I've frequently noticed the following error message:

```
"grpc_message":"Insufficient 'CPUS' quota. Requested 12.0, available 9.0.","grpc_status":3}"
>
```

related issues: #7489 and #7493. Could you check to see if we're not deleting the clusters properly Leah, and add `finally` blocks or other appropriate measures for possible quota issues if the test is run multiple times?

**Comment by leahecole** [comment]
Looks like I've already figured it out - the issue is with some dataproc samples that then get in the way of these tests. I've added finally blocks to these and there's an open issue in dataproc! https://github.com/googleapis/python-dataproc/issues/321
