### ISSUE TITLE
Can discoverydoccaching be deprecated?

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/python-docs-samples#75]
@tmatsuo in light of your contribution [here](https://github.com/google/google-api-python-client/pull/127), can we remove the `discoverydoccaching` sample?

**Comment by tmatsuo** [comment]
Yes, let me see how soon we can release the next version.

**Comment by jonparrott** [comment]
Great. Let me know when.

**Comment by tmatsuo** [comment]
I've just released 1.4.2. https://github.com/google/google-api-python-client/pull/134

I'll start deprecating many things from next week.

**Comment by jonparrott** [comment]
SGTM. We can close this issue when you're done.

**Comment by tmatsuo** [comment]
Maybe I can simply replace the `discoverydoccaching` sample, with some texts explaining that it's not needed any more.

How does it sound?

**Comment by jonparrott** [comment]
I'd like to remove the folder altogether, and the commit message can mention why it was removed. Not a fan of this repository accumulating historical cruft.

Was the sample linked from any documentation? That would be the only compelling reason I'd see to leave the folder around, and even then, I'd recommend we update the documentation and remove the folder.

**Comment by tmatsuo** [comment]
Sounds good, will do.
