### ISSUE TITLE
Fix django sample for ALLOWED_HOSTS settings

### ISSUE THREAD

**Issue by sakimyto** [GoogleCloudPlatform/python-docs-samples#7516]
## In which file did you encounter the issue?

[in sample/python-docs-samples/appengine/standard_python3/django .](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/022b490b2748b231f40470170fbb64ff5c4f1ce4/appengine/standard_python3/django/mysite/settings.py#L73)

Now, 

```
# settings.py
APPENGINE_URL = urlparse(APPENGINE_URL, "https").geturl()
```

```
> $ALLOWED_HOSTS
["https://example.us.r.appspot.com"] # cause bad request
["example.us.r.appspot.com"] # collect
```

No protocol needed.

> ALLOWED_HOST
> A list of strings representing the host/domain names
> https://docs.djangoproject.com/en/4.0/ref/settings/#allowed-hosts

### Did you change the file? If so, how?

 - I'll try it now.

**Comment by dandhlee** [comment]
Hey @glasnt, could you help take a look?

**Comment by lesteral** [comment]
@sakimyto - thanks for finding/reporting this.  I agreed w/ your proposed fix.  
@glasnt - I believe this issue originated in #7412 - I have added a couple of comments there (hope it's OK to add them there instead of here ...)

**Comment by glasnt** [comment]
Thanks for catching this @sakimyto, and thanks @lesteral for the analysis on the PR!

I'll put a fix together shortly
