### ISSUE TITLE
Built-in memcache seems broken

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/python-docs-samples#752]
## In which file did you encounter the issue?
/appengine/flexible/memcache

I commented out memcache server and uncommented: USE_GAE_MEMCACHE

On deploy and `gcloud app browse` I see: 

error 3 from memcached_get(counter): (0x14b9130) CONNECTION FAILURE(Connection refused),  host: localhost:11211 -> libmemcached/connect.cc:156

**Comment by waprin** [comment]
@jonparrott any ideas?

**Comment by jonparrott** [comment]
@waprin Memcache is alpha and whitelist only right now. That's probably what's up.
