### ISSUE TITLE
In 'Export Data' section you get error 'bucket' not defined

### ISSUE THREAD

**Issue by sjamthe** [GoogleCloudPlatform/python-docs-samples#7605]
## In which file did you encounter the issue?
README.ipynb

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/people-and-planet-ai/geospatial-classification/README.ipynb

### Did you change the file? If so, how?
replace variable name bucket with cloud_storage_bucket

OLD
bucket=bucket
NEW
bucket=cloud_storage_bucket

## Describe the issue
Do this in 6 places 
training_task and validation_task
and in twice in section Run a custom training job
twice in prediction section
Full code below
# Export data

training_task = ee.batch.Export.table.toCloudStorage(
    collection=ee.FeatureCollection(train_features),
    description="Training image export",
    bucket=cloud_storage_bucket,
    fileNamePrefix="geospatial_training",
    selectors=BANDS + [LABEL],
    fileFormat="TFRecord",
)

training_task.start()

validation_task = ee.batch.Export.table.toCloudStorage(
    collection=ee.FeatureCollection(validation_features),
    description="Validation image export",
    bucket=cloud_storage_bucket,
    fileNamePrefix="geospatial_validation",
    selectors= BANDS + [LABEL],
    fileFormat='TFRecord')

validation_task.start()

------- custom training job section
aiplatform.init(project=project, staging_bucket=cloud_storage_bucket)

model = job.run(accelerator_type='NVIDIA_TESLA_K80', accelerator_count=1, args=[f'--bucket={cloud_storage_bucket}'])

---- prediction section
requests.post(
    url=f'{service_url}/predict',
    headers={'Authorization': f'Bearer {identity_token}'},
    json={'data': prediction_data, 'bucket': cloud_storage_bucket},
).json()['predictions']

def get_prediction(lon, lat, start, end):
    prediction_data = get_prediction_data(lon, lat, start, end)
    result = requests.post(
      url=f'{service_url}/predict',
      headers={'Authorization': f'Bearer {identity_token}'},
      json={'data': prediction_data, 'bucket': cloud_storage_bucket},).json()
    return result['predictions']['predictions'][0][0][0][0]

**Comment by davidcavazos** [comment]
Thanks for filing this, we'll fix this.
