### ISSUE TITLE
In geospatial-classification/README.ipynb service_url is returned null thought service is deployed

### ISSUE THREAD

**Issue by sjamthe** [GoogleCloudPlatform/python-docs-samples#7606]
## In which file did you encounter the issue?
people-and-planet-ai/geospatial-classification/README.ipynb

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/people-and-planet-ai/geospatial-classification/README.ipynb

## Describe the issue
The code that returns deployed service URL returns null.
Service was deployed successfully by the Deploy app command as I got the followin output

Building using Dockerfile and deploying container to Cloud Run service [geospatial-service] in project [climatetrace] region [us-central1]
Service [geospatial-service] revision [geospatial-service-00001-leb] has been deployed and is serving 100 percent of traffic.
Service URL: https://geospatial-service-2exggh7ckq-uc.a.run.app/

import subprocess

# Get the web service URL.
#   https://cloud.google.com/sdk/gcloud/reference/run/services/describe
service_url = subprocess.run(
    [ 'gcloud', 'run', 'services', 'describe', 'geospatial-service',
        f'--region={region}',
        f'--format=get(status.url)',
    ],
    capture_output=True,
).stdout.decode('utf-8').strip()
print(f"service_url: {service_url}")

I think there are two problems.
1. The code that deploys service has HARDCODED region=us-central1 but the code that queries service URL uses region variable.
2. Even if you fix region the service name is expected with name space. The following code worked for me
3. 
service_url = subprocess.run(
    [ 'gcloud', 'run', 'services', 'describe', 'namespaces/climatetrace/services/geospatial-service',
      f'--region=us-central1',
     f'--format=get(status.url)',
    ],
    capture_output=True,
).stdout.decode('utf-8').strip()
print(f"service_url: {service_url}")

**Comment by Breathtender** [comment]
Hm, I'll note that I didn't run into an issue with service_url but I did run into an issue where the variable bucket was undefined, which I solved by just adding a line that said bucket=cloud_storage_bucket

**Comment by dandhlee** [comment]
This issue was fixed in #7619. Please feel free to re-open this issue if you run into any further problems!
