### ISSUE TITLE
Missing Folder: media-translation

### ISSUE THREAD

**Issue by gitblair** [GoogleCloudPlatform/python-docs-samples#7612]
Google Cloud Tech YouTube video "How to automatically transcribe your video or audio into text" refers to resources that are not found in this repository.

The media-translation folder is missing.

**Comment by parthea** [comment]
Hello @gitblair ,
Thanks for reporting this issue. The samples for `media-translation` are located [here](https://github.com/googleapis/python-media-translation/tree/main/samples/snippets). I'll open a PR to add the `media-translation` folder along with a README to direct users to the correct location for samples.
