### ISSUE TITLE
Cloud run django example goes into infinite redirect

### ISSUE THREAD

**Issue by shukryzablah** [GoogleCloudPlatform/python-docs-samples#7632]
## In which file did you encounter the issue?

run/django/mysite/settings.py

### Did you change the file? If so, how?

Minor settings changes related to static file usage. Deleted comments.

## Describe the issue

My application was going into an infinite redirect. 

(Adding `SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")` to the production branch of the conditional got things working for me. )

**Comment by glasnt** [comment]
Thanks for the report!

https://docs.djangoproject.com/en/4.0/ref/settings/#secure-ssl-redirect

> If turning this to True causes infinite redirects, it probably means your site is running behind a proxy and can’t tell which requests are secure and which are not. Your proxy likely sets a header to indicate secure requests; you can correct the problem by finding out what that header is and configuring the [SECURE_PROXY_SSL_HEADER](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-SECURE_PROXY_SSL_HEADER) setting accordingly.

I'll confirm in a new deployment and submit a PR if this is indeed the fix.
