### ISSUE TITLE
Clone not available ?

### ISSUE THREAD

**Issue by imneo1** [GoogleCloudPlatform/python-docs-samples#769]
I think the command and error are explaining the issue (Can't clone)

:~$ git clone https://github.com/GoogleCloudPlatform/python-dev-samples/language/sentiment/
Cloning into 'sentiment'...
remote: Not Found
fatal: repository 'https://github.com/GoogleCloudPlatform/python-dev-samples/language/sentiment/' not found

**Comment by jonparrott** [comment]
You should just clone the top-level, then cd into it.

```
git clone https://github.com/GoogleCloudPlatform/python-docs-samples.git
cd python-docs-samples/language/sentiment
```

**Comment by imneo1** [comment]
Yes, please update the instructions
Thank you

**Comment by jonparrott** [comment]
Where did you come across these instructions?

**Comment by imneo1** [comment]
Here under "Download the Code"
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/language/sentiment

**Comment by jerjou** [comment]
Neat - github lets me edit the file directly in the web interface...
