### ISSUE TITLE
idp-sql tested failed for "End user authentication"

### ISSUE THREAD

**Issue by biaojiang** [GoogleCloudPlatform/python-docs-samples#7785]
## Code sample followed
Hi, I followed the tutorial [End user authentication for Cloud Run tutorial ](https://cloud.google.com/run/docs/tutorials/identity-platform#cloudrun_user_auth_secrets-python), but it didn't work with the provided deploying methods: automatic ` "Run on Google Cloud"` or by manual steps.

### File changed
`run/idp-sql/static/config.js`:

`const config = {
  apiKey: 'API_KEY',
  authDomain: 'PROJECT_ID.firebaseapp.com',
};`
The apiKey and authDomain were filled with the values from ` Identity Providers page`. And also copied the snippets from ` "Configure your application"` to the bottom of `static/config.js`.

## End user authentication failed after deploying

The error for ` "Run on Google Cloud"` method, it said:

> the logging failed, please check the browser logs.

The error for the manual deploying methods: when clicking the ` SIGN IN WITH GOOGLE` button, no response.

I tried to comment the `Cloud SQL` code, only to test the authentication, the same results, so, probably something wrong with the  `firebase` or the `config.js`? thanks.

**Comment by averikitsch** [comment]
Hi @biaojiang, thanks for reporting this issue. I am currently debugging the push button to deploy. However, there is a few things you can try in the meantime. 
* Using Chrome Devtools, in the console tab do you see an error? If there is an API error you need to check that the config.js file has the correct values. You also need to make sure you've followed the [finishing touches](https://cloud.google.com/run/docs/tutorials/identity-platform#finishing-touches) section.\
* In the Cloud Run console, you can check if the env vars and Cloud SQL connection is properly set.4
* In the Secret Manager console, you can check if the secret value has the correct JSON object with your values.

**Comment by averikitsch** [comment]
fixed in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/8075
