### ISSUE TITLE
People and Planet AI is throwing lint errors

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#7786]
Hi! Somehow there are some [lint errors](https://fusion2.corp.google.com/invocations/ef909044-1509-49f6-98df-03d3785e59ab/targets/cloud-devrel%2Fpython-docs-samples%2Flint%2Fperiodic/log) in people and planet AI that are continuously failing - please open a PR to correct them or, if there really is no alternative, please add an exception and let @GoogleCloudPlatform/python-samples-owners know!

**Comment by dandhlee** [comment]
Seems like `ANN401 Dynamically typed expressions (typing.Any) are disallowed` has been added since ~1 week ago :/
