### ISSUE TITLE
Cloud Run tests are throwing lint errors

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#7787]
`run/idp-sql` and `run/deployment-previews` are [throwing lint errors](https://fusion2.corp.google.com/invocations/ef909044-1509-49f6-98df-03d3785e59ab/targets/cloud-devrel%2Fpython-docs-samples%2Flint%2Fperiodic/log) - PTAL and correct, or, if we cannot specify a more specific type, exempt the line from lint checking and add a justification in the comment 

cc @GoogleCloudPlatform/aap-dpes

**Comment by glasnt** [comment]
This is being addressed in #7779

**Comment by glasnt** [comment]
This should now be resolved for both, via #7779 and #7789
