### ISSUE TITLE
dev_appserver.py missing

### ISSUE THREAD

**Issue by romanodev** [GoogleCloudPlatform/python-docs-samples#7800]
## Describe the issue

I am following this tutorial:

https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine

To run the app locally, it is recommended to run dev_appserver.py. However, such a file seems not to be there.

As a side note, is there a similar tutorial using Firebase Admin SDK, instead? I noted https://github.com/andrewrosss/flask-firebase-admin

but I was wondering if there is anything official from GCP. Thanks

**Comment by engelke** [comment]
dev_appserver.py is an optional part of the Google Cloud CLI - see https://cloud.google.com/cli. When the CLI is installed, you should be able to run dev_appserver.py from the command line in any of the three supported operating systems. If the component is not installed (it wasn't for me) you will see a message inviting you to install it. That will fail unless you are running with administrator access. In Linux/MacOS run `sudo dev_appserver.py` and then let it install the needed component if not there. In Windows, open a new command prompt by right-clicking that icon and choosing "Run as administrator". If that doesn't work, try reinstalling the Google Cloud CLI using `sudo` or "Run as administrator". Once the update occurs you can run `dev_appserver.py` without administrator privilege.

However, you should reconsider following the instructions you are asking about [in favor of the current instructions](https://cloud.google.com/appengine/docs/standard/python3/authenticating-users#firebase_authentication). The page you are looking at is for App Engine with Python 2.7. The new instructions are for Python 3 and are somewhat different.

[Python 2.7 was sunset](https://www.python.org/doc/sunset-python-2/) by the Python Software Foundation on January 1, 2020. Although [Google continues to support Python 2.7 for App Engine](https://cloud.google.com/appengine/docs/standard/long-term-support#python27), all new apps should be built for Python 3 from the start, and existing [Python 2.7 apps should migrate](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3) if possible. You can do local development of Python 3 apps for App Engine without needing dev_appserver.py in many cases, perhaps including yours.

**Comment by romanodev** [comment]
@engelke, thank you very much for your detailed explanation! It is very helpful
