### ISSUE TITLE
Update comment in dataproc serverless sample to include all variables and link to tutorial

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#7803]
Once cl/440880194 is published, update [`composer/workflows/dataproc_batch_operators.py`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/composer/workflows/dataproc_batch_operators.py) to link to the published tutorial and to include all of the Airflow variables needed

**Comment by dandhlee** [comment]
The tutorial seems public now! (https://cloud.google.com/composer/docs/composer-2/run-dataproc-workloads)

Could you update the link @jsj14?
