### ISSUE TITLE
Move resourcemanger usage to the v3 GAPIC

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/python-docs-samples#7848]
Migrating existing resource manager samples to use the v3 gapic client from https://pypi.org/project/google-cloud-resource-manager instead of googleapiclient.

https://github.com/GoogleCloudPlatform/python-docs-samples/search?q=cloudresourcemanager

**Comment by BigBlackWolf** [comment]
Done in scope of https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11567
