### ISSUE TITLE
How to run the images sample and Unable to find the Python PIL library?

### ISSUE THREAD

**Issue by scheung38** [GoogleCloudPlatform/python-docs-samples#787]
Tried to open at the python-docs-samples/images level i PyCharm:

/api
/guestbook

But not sure how to run it? 

When trying to run main.py:

```
Traceback (most recent call last):
  File "/Users/seb/PycharmProjects/GoogleCloudPlatform/python-docs-samples/appengine/standard/images/api/main.py", line 23, in <module>
    from google.appengine.api import images
ImportError: No module named google.appengine.api

```
Also Unable to find PIL? Even though it is installed with pip?

I did noticed that there is no GAE as its External Libraries, so best practice to open another new Google App Engine app within PyCharm and copy and paste these two directories? Do I need both the /api and /guestbook to run? How to run as there are two main.py in each folder?

Copy and pasted the image/api and image/guestbook into newly created GAE project in PyCharm
but upon running:

`google.appengine.tools.devappserver2.errors.AppConfigNotFoundError: "/Users/seb/PycharmProjects/myphotosharing" is a directory but does not contain app.yaml or app.yml`

**Comment by jonparrott** [comment]
Hi @scheung38!

There are two separate images API samples.

* `/appengine/standard/images/api` is a basic sample showing the functionality of the images API.
* `/appengine/standard/images/guestbook` is a sample that shows the images API in the context of the guestbook example.

You'll need to open and run them separately.

**Comment by scheung38** [comment]
Thanks Jon there any examples showing how to load and persist more than one image as it is limited to just one image that can be loaded?

**Comment by jonparrott** [comment]
@scheung38 not direct examples, but you can upload as many blobs as you want and use them with the images API. Just provide a different blob key.

**Comment by scheung38** [comment]
A different blob key for each image upload? 

Also blobstore and ndb are similar ?

**Comment by jonparrott** [comment]
Yes.
