### ISSUE TITLE
Port code samples of GAE Python bundled APIs from GCS

### ISSUE THREAD

**Issue by jinglundong** [GoogleCloudPlatform/python-docs-samples#7890]
## In which file did you encounter the issue?
N/A. I'm about to add a set of code samples.

### Did you change the file? If so, how?

Yes. `gsutil cp gs://python3-wormhole-api-samples/python3-wormhole-samples.zip .`

## Describe the issue
GAE Python bundled APIs went GA in April. The code samples for these APIs are still in a GCS bucket. 
https://storage.googleapis.com/python3-wormhole-api-samples/python3-wormhole-samples.zip

This issue is to publish these samples to 
[python-docs-samples](https://github.com/GoogleCloudPlatform/python-docs-samples)

**Comment by engelke** [comment]
Done in PR #8070
