### ISSUE TITLE
Add Datastore query samples for IN, NOT_IN, NOT_EQUAL

### ISSUE THREAD

**Issue by jlara310** [GoogleCloudPlatform/python-docs-samples#7899]
## In which file did you encounter the issue?

[python-docs-samples/blob/main/datastore/cloud-client/snippets.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/datastore/cloud-client/snippets.py)

### Did you change the file? If so, how?

No.

## Describe the issue

Add samples to go along with the following update to the Datastore client.
https://github.com/googleapis/python-datastore/pull/287/files#

**Comment by jlara310** [comment]
I'm working on the documentation update for the feature. I can also propose the python snippets to go along with the docs.

**Comment by parthea** [comment]
Hi @jlara310,

Please could you add the samples to the https://github.com/googleapis/python-datastore repository instead of this repo? The samples can serve as additional integration tests. We can also investigate whether any of the the [existing](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/datastore) samples in this repo could also be moved.

**Comment by jlara310** [comment]
Hi @parthea ,
Yes, I can try but I need some guidance. In which file in https://github.com/googleapis/python-datastore should I add the samples?

I might need to add them to this repo first to finish the doc updates. I can then look into moving this and other existing samples.

**Comment by parthea** [comment]
Thanks @jlara310! The samples should be under a [folder](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#folder-location) called `samples`.

**Comment by meredithslota** [comment]
I'm going to close this out as the samples will end up in the other repo; relevant issue is https://github.com/googleapis/python-datastore/issues/311
