### ISSUE TITLE
version mismatch python 3.7 and django 4.0.4

### ISSUE THREAD

**Issue by quteharry19** [GoogleCloudPlatform/python-docs-samples#7948]
## In which file did you encounter the issue?
app.yaml

## Describe the issue
appengine flexible requires python 3.7 and django 4.0.4 requires python 3.8+

#7824

**Comment by dandhlee** [comment]
According to this doc: https://docs.djangoproject.com/en/4.0/releases/4.0/ it seems that Python 3.7 is simply not supported for any 4.0 versions. @pattishin could you help take a look at this issue?

**Comment by engelke** [comment]
Fixed in #8031
