### ISSUE TITLE
Possible duplicate examples for Endpoints on Flex in repo

### ISSUE THREAD

**Issue by DMTSource** [GoogleCloudPlatform/python-docs-samples#795]
I am working with the Quickstarts for Endpoints beta. I was wondering why both docs, [Quickstart for Enpoints on Flex](https://cloud.google.com/endpoints/docs/quickstart-app-engine) and [Quickstart for Endpoints on Compute](https://cloud.google.com/endpoints/docs/quickstart-compute-engine), link to the same example code while separate demos with slight differences exist in the repo. Is "appengine/flexible/endpoints" depreciated?

Both quickstarts call for the use of 'python-docs-samples/endpoints/getting-started'

The two similar examples:
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/flexible/endpoints
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/endpoints/getting-started

**Comment by jonparrott** [comment]
We have a bug to eliminate one: @ryanmats can you speak to this?

**Comment by ryanmats** [comment]
@DMTSource We are in the process of removing "appengine/flexible/endpoints" - it will be removed once we finish changing every relevant link on cloud.google.com.

**Comment by jonparrott** [comment]
This has been resolved.
