### ISSUE TITLE
Land Cover example: `list(CLASSIFICATIONS.values())` does not guaranteed order unless Python >= 3.7

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/python-docs-samples#7969]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/people-and-planet-ai/land-cover-classification/README.ipynb

## Describe the issue
The notebook relies on the fact that `list(CLASSIFICATIONS.values())` returns a guaranteed order. This is only true for Python 3.7+ (https://mail.python.org/pipermail/python-dev/2017-December/151283.html)

**Comment by ivanmkc** [comment]
@davidcavazos  I didn't see an explicit version requirement for your notebook so just flagging this.

**Comment by davidcavazos** [comment]
Python 3.6 [reached its end of life 6 months ago](https://endoflife.date/python), so I think it's safe to assume people will be using Python 3.7+ (?)

**Comment by davidcavazos** [comment]
I'm going to close this since all supported versions of Python should now support ordered dict keys, but please feel free to reopen if you think we should take a different course of action.
