### ISSUE TITLE
Issue in Global Fishing Watch -- timeseries-classification

### ISSUE THREAD

**Issue by skr3178** [GoogleCloudPlatform/python-docs-samples#8043]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/people-and-planet-ai/timeseries-classification
```
from tensorflow import keras

model_dir = f'{storage_path}/training/model'
model = keras.models.load_model(model_dir)

model.summary()
keras.utils.plot_model(model, show_shapes=True)

```

 4 model = keras.models.load_model(model_dir)
      5 
      6 model.summary()

1 frames
[/usr/local/lib/python3.7/dist-packages/keras/saving/save.py](https://localhost:8080/#) in load_model(filepath, custom_objects, compile, options)
    202         if isinstance(filepath_str, str):
    203           if not tf.io.gfile.exists(filepath_str):
--> 204             raise IOError(f'No file or directory found at {filepath_str}')
    205 
    206           if tf.io.gfile.isdir(filepath_str):

OSError: No file or directory found at gs://fishingbucket/samples/global-fishing-watch/training/model. -->

**Comment by dandhlee** [comment]
Hey @skr3178, could you pinpoint to which exact file you're having this issue with? And what commands did you run before running into this issue?

**Comment by skr3178** [comment]
Hi Dan,
The model I am recreating is this YouTube video link :
https://youtu.be/LnEhSVEJUuY

Thank you
Please let me know if more details are necessary.

**Comment by dandhlee** [comment]
Hmm... 
1. Did you copy the training data from [Global Fishing Watch training-data repository](https://github.com/GlobalFishingWatch/training-data) into your Cloud Storage bucket: `gs://fishingbucket/samples/global-fishing-watch/training/model`?
2. I think your `storage_path` might be malformed and contains an extra period(`.`) at the end: `gs://fishingbucket/samples/global-fishing-watch/training/model.`; It should be `gs://fishingbucket/samples/global-fishing-watch/training/model`

Could you confirm that (1) you have *your* bucket set correctly with the test data and that (2) you didn't make a typo when declaring the bucket name?

**Comment by skr3178** [comment]
Hi @dandhlee 
Thank you for replying.

I think it was a mistake in this page when I typed. It looks fine on the the code page which I share below. 

`https://colab.research.google.com/drive/1i_1Cs8uModaV7rFrrIkKTbLTAPB7ESPZ?usp=sharing`
[link to page](https://colab.research.google.com/drive/1i_1Cs8uModaV7rFrrIkKTbLTAPB7ESPZ?usp=sharing)

**Comment by dandhlee** [comment]
I can't seem to figure out what's wrong, other than the project name potentially overlapping that could be causing an issue? @davidcavazos could you help take a look?

**Comment by davidcavazos** [comment]
The errors seems to point that the model directory doesn't exist, which makes me think maybe there was an error while training the model.

Did you run the `{service_url}/train-model` request? Did the Vertex AI training job finish successfully? The training job is responsible for creating the model directory.

**Comment by dandhlee** [comment]
Hey @skr3178, friendly ping. Please take a look at David's message above!

**Comment by skr3178** [comment]
hello @dandhlee, 

It is nice to hear back from you. 
I am trying to rerun the code but face some logistical limitations: 

"error': 'ResourceExhausted:  The following quota metrics exceed quota limits: aiplatform.googleapis.com/custom_model_training_nvidia_t4_gpus"

I will share updates as soon as i can. 
Thanks

**Comment by dandhlee** [comment]
I'll close this issue for now, but if you do have any questions feel free to re-open this issue or create a new issue if you run into other issues.
