### ISSUE TITLE
Update Issue template

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#8059]
We're using an old version of issue templates - should we consider upgrading to the new version? https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

(Is there one in owlbot we should be using?) 

Assigning to @dandhlee for triage and to validate if this is needed

**Comment by dandhlee** [comment]
We should likely add one that includes verbiage about GCP support; as a disclaimer that we can't help debug into GCP issues that's unrelated to samples in this repository. There is a template that OwlBot/some other repositories make use of, let me find that and update it here as well!
