### ISSUE TITLE
Only single deployment preview commit status allowed because context not parameterized

### ISSUE THREAD

**Issue by eltonlaw** [GoogleCloudPlatform/python-docs-samples#8063]
## In which file did you encounter the issue?

run/deployment-previews/check_status.py 

## Describe the issue

When running `set` to set a commit status more than once for a single PR, the most recent `set` invoke will overwrite the status if it has the same context. Which is always `"Deployment Preview"`, just having a different string for the context allows multiples statuses to exist.

**Comment by dandhlee** [comment]
Ace, could you take a look at this and #8064?

**Comment by glasnt** [comment]
I'm not sure if I understand the problem. 

The code _should_ create one tagged revision for one pull request, setting one status. Subsequent commits on that pull request should create a new revision on the service, re-use the same tag, then update the pull request, which should have the same preview URL anyway. With the PR you submitted, do you intend for a PR with N commits to have N status checks for the same URL?

I'm trying out the PR now to confirm

**Comment by glasnt** [comment]
If I create a new project with the code from your PR, I end up with a status on first deploy with link to the revision URL, then any updates change the description but keep the same URL, without creating a new status. 

You can see this example here: https://github.com/glasnt-dev/glasnt-deployprev-8064/pull/1

Can you please clarify the issue that you're encountering? Thanks!

**Comment by eltonlaw** [comment]
@glasnt My codebase has multiple deploys per PR, with the current way it works, so they all run in parallel and whichever finishes last ends up being the commit status with that revision url. I want it to be able to deploy multiple commit statuses.

**Comment by glasnt** [comment]
Ah! If you have multiple _services_ that deploy from the same PR, then yes of course they'd have different URLs. 

The revision URL maps to a Service and PR, and won't change on subsequent commits, so as long as you changed the message to say "Deployment Preview for {service_name}", your use case would then be supported (I worry about introducing hashes into all deployment previews as that would confuse single service users. 

I can suggest the change on your PR, which you are free to accept if it makes sense.

**Comment by eltonlaw** [comment]
Works for me, I committed the suggestion and added another commit removing the import on hashlib and the hash
