### ISSUE TITLE
Import errors in Wildlife Insights -- image-classification

### ISSUE THREAD

**Issue by pravarmahajan** [GoogleCloudPlatform/python-docs-samples#8099]
## In which file did you encounter the issue?

python-docs-samples/tree/main/people-and-planet-ai/image-classification/train_model.py

### Did you change the file? If so, how?

[My fork](https://github.com/GoogleCloudPlatform/python-docs-samples/compare/main...pravarmahajan:main)

## Describe the issue

I am executing the sample notebook [README.ipynb](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/people-and-planet-ai/image-classification/README.ipynb) and running into errors. The errors suggest the mapper function doesn't have access to the external modules.

![Screen Shot 2022-06-17 at 9 06 45 AM](https://user-images.githubusercontent.com/22108888/174335805-518d8499-47ee-49a3-9271-e1be89203e78.png)

So I started adding explicit imports inside each of the mapper functions as shown in my forked version. But in the latest error, the mapper function isn't able to locate a function (`url_get`) which is defined in the same script `train_model.py`.
![Screen Shot 2022-06-17 at 9 10 28 AM](https://user-images.githubusercontent.com/22108888/174336676-e7c00c45-94df-433e-8bc7-840ba1a09189.png)

A few questions here:
1. Is this the right way of doing it? Do we need to add explicit imports inside the mapper function for every external module? If so, what should I do about the function defined in the same script `url_get`?
2. And if so, how are there no import errors for `logging` [here](https://github.com/pravarmahajan/python-docs-samples/blob/5f519b6d637cfb87cf132d2ada4b4dad1f31f12d/people-and-planet-ai/image-classification/train_model.py#L133)?

**Comment by pravarmahajan** [comment]
Yes, I get the errors if I run the sample without any modifications:
![image](https://user-images.githubusercontent.com/22108888/177207874-163fd6a2-0e2e-48a4-994e-79a41e21d46a.png)

I checked the `train_model.py`: The arg `save_main_session=True` is being explicitliy set [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/e7de6165ced359aa355c60fc21a10dda6b4cd8fa/people-and-planet-ai/image-classification/train_model.py#L365)

However, I do notice some error in loading the main session in my worker logs:
![image](https://user-images.githubusercontent.com/22108888/177208081-789a8879-e23c-44f1-b5bb-ff5da581b4e1.png)

It looks like there is some error in reading the attribute `a` defined [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/e7de6165ced359aa355c60fc21a10dda6b4cd8fa/people-and-planet-ai/image-classification/train_model.py#L31)

Any suggestions on what should be done here?

**Comment by davidcavazos** [comment]
It looks like pickling the session failed. Try importing the aiplatform modules locally in the functions that are used instead of importing it globally. I suspect maybe some update made them fail to pickle. The rest of the imported modules seem safe to pickle.

**Comment by pravarmahajan** [comment]
Right. I had explicitly imported aiplotform as well as PIL modules in my [fork](https://github.com/GoogleCloudPlatform/python-docs-samples/compare/main...pravarmahajan:main), because Image and ImageFile modules were having some issues. Now I am stuck at `url_get` function, which is defined within the same script (as pointed in my first post).

**Comment by davidcavazos** [comment]
Can you try removing the global imports for `aiplatform`? I suspect having those modules loaded as part of the main session is causing issues when pickling it.

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/d58ee70c1c6afee0c07a1c4002aaf8e9a7ec99ba/people-and-planet-ai/image-classification/train_model.py#L26-L27

**Comment by davidcavazos** [comment]
Another thing to try is using `--pickle_library=cloudpickle`

**Comment by dandhlee** [comment]
Hey @pravarmahajan, please take a look at David's suggestion and let us know if you're still running into this issue.

**Comment by dandhlee** [comment]
I'll close this issue for now, but feel free to re-open with comments or open a new issue if needed!
