### ISSUE TITLE
ImportError: No module named longrunning

### ISSUE THREAD

**Issue by araa47** [GoogleCloudPlatform/python-docs-samples#811]
## In which file did you encounter the issue?
While running trancribe_streaming.py for speech to text 

### Did you change the file? If so, how?
No

## Describe the issue

Akshays-iMac-2:grpc akshay$ python transcribe_streaming.py
Traceback (most recent call last):
  File "transcribe_streaming.py", line 29, in <module>
    from google.cloud.grpc.speech.v1beta1 import cloud_speech_pb2
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/cloud/grpc/speech/v1beta1/cloud_speech_pb2.py", line 17, in <module>
    from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
ImportError: No module named longrunning

**Comment by jonparrott** [comment]
@araa47 Are you using `virtualenv`? If so, can you tell me the output of `pip freeze`?

**Comment by Neeraj-ky** [comment]
@jonparrott  I am facing same issue when trying to use RPC call for streaming request. 
I am using **virtualenv** and output for **pip freeze** is - 

$ pip freeze
Warning: cannot find svn location for distribute==0.6.24dev-r0
Cython==0.15.1
Django==1.4.22
Fabric==1.8.2
Flask==0.8
FormEncode==1.2.4
GeoIP-Python==1.2.4
GnuPGInterface==0.3.2
Jinja2==2.6
M2Crypto==0.21.1
Mako==0.7.0
MarkupSafe==0.15
MySQL-python==1.2.3
PIL==1.1.7
Paste==1.7.5.1
PyYAML==3.10
Pygments==1.5
SOAPpy==0.12.0
SpeechRecognition==3.6.0
Unidecode==0.04.9
Werkzeug==0.8.3
argparse==1.2.1
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
boto==2.42.0
bpython==0.11
certifi==2016.08.31
chardet==2.0.1
colorama==0.2.4
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
docutils==0.8.1
duplicity==0.6.18
enum34==1.1.6
euca2ools==2.0.2
filechunkio==1.5
fpconst==0.7.2
futures==3.0.5
google-auth==0.7.0
googleapis-common-protos==1.5.2
greenlet==0.4.7
grpc-google-cloud-speech-v1beta1==0.14.0
grpcio==1.1.0
h5py==2.0.1
hiredis==0.1.6
html5lib==0.95
httplib2==0.10.3
iotop==0.4.4
jieba==0.36.2
joblib==0.6.4
jsonschema==2.4.0
logilab-astng==0.23.1
logilab-common==0.58.0
lxml==3.3.1
matplotlib==1.1.1rc2
mecab-python==0.996
medusa==0.5.4
meld3==0.6.5
motor==0.4.1
mysql-connector-python==0.3.2-devel
nltk==2.0.4
nose==1.1.2
numexpr==2.0.1
numpy==1.6.2
oauth2client==3.0.0
ordereddict==1.1
pandas==0.8.0
paramiko==1.10.1
pexpect==2.4
ply==3.4
poster==0.8.1
protobuf==3.2.0
py-bcrypt==0.4
pyasn1==0.2.2
pyasn1-modules==0.0.8
pychecker==0.8.19
pycrypto==2.6
pycurl==7.19.0
pydns==2.3.6
pyflakes==0.5.0
pylint==0.25.1
pymongo==2.8
pyparsing==1.5.6
python-apt==0.8.8.2
python-dateutil==1.5
python-debian==0.1.21
python-debianbts==1.11
python-lzo==1.08
python-snappy==0.4
pytz==2012c
rdiff-backup==1.2.8
redis==2.4.13
reportbug==6.4.4
requests==2.12.4
rsa==3.4.2
s3cmd==1.5.0-rc1
scikit-learn==0.11
scipy==0.10.1
simplejson==2.5.2
singledispatch==3.4.0.3
six==1.10.0
supervisor==3.0a8
tables==2.3.1
tornado==4.3
toro==1.0.1
urllib3==1.7.1
websocket-client==0.37.0
wikitools==1.1.1
wsgiref==0.1.2

**Comment by jonparrott** [comment]
@lukesneeringer any ideas on this?

**Comment by jonparrott** [comment]
also @jerjou

**Comment by jerjou** [comment]
@Neeraj-ky Are you sure you're using a virtualenv? Did you remember to run `your-virtual-env-dir/bin/activate`? For example, here is what my `pip freeze` looks like for running `transcribe_streaming.py`:

```
(venv) jerjou@timbre:~/opensrc/python-docs-samples/speech/grpc$ pip freeze
appdirs==1.4.0
enum34==1.1.6
futures==3.0.5
google-auth==0.6.0
googleapis-common-protos==1.5.2
grpc-google-cloud-speech-v1beta1==0.14.0
grpcio==1.1.0
httplib2==0.10.3
oauth2client==3.0.0
packaging==16.8
protobuf==3.2.0
pyasn1==0.2.2
pyasn1-modules==0.0.8
PyAudio==0.2.10
pyparsing==2.1.10
requests==2.13.0
rsa==3.4.2
six==1.10.0
```

Diffing this against yours, it looks like a couple modules aren't installed (eg `appdirs`, `PyAudio`, etc). Try installing the `speech/grpc/requirements.txt` in a clean virtualenv and see if that works..

**Comment by lukesneeringer** [comment]
`google.longrunning` is provided by the `google-gax` package, which I do not see in the pip freezes being pasted here. It might be that we have a package that depends on it that is not explicitly requiring it?

**Comment by lukesneeringer** [comment]
I am noticing in these freezes:

  * They contain `grpc-google-cloud-speech-v1beta1==0.14.0`; on the current version of speech, this would be `proto-google-cloud-speech-v1beta1==0.15.0`
  * Similarly, `gapic-google-cloud-speech-v1beta1==0.15.0` should be present, and is not, and this would have depended on `google-gax`.

What package are you initially installing?

**Comment by jerjou** [comment]
Closing for now. Please comment with more details if you're still running into this, and we can investigate further.
