### ISSUE TITLE
httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header

### ISSUE THREAD

**Issue by skr3178** [GoogleCloudPlatform/python-docs-samples#8156]
## [File link:](https://colab.research.google.com/drive/1fGOXcnVcYdN47HCEflkqh0N3kTLxyJvE?usp=sharing)
https://colab.research.google.com/drive/1fGOXcnVcYdN47HCEflkqh0N3kTLxyJvE?usp=sharing

## Describe the issue: 
httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.
The following section does not run:
!python create_datasets.py \
    --training-prefix "gs://{bucket}/land-cover/datasets/training/data" \
    --validation-prefix "gs://{bucket}/land-cover/datasets/validation/data" \
    --points-per-region 50 \
    --patch-size 16 \
    --runner "DataflowRunner" \
    --project "{project}" \
    --region "{location}" \
    --temp_location "gs://{bucket}/land-cover/temp" \
    --setup_file "./setup.py"

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by davidcavazos** [comment]
The [`requirements.txt`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/people-and-planet-ai/land-cover-classification/requirements.txt) does include `apache-beam`, and `google-apitools` is included indirectly. After installing the requirements, the Colab runtime has to be restarted for the changes to take effect. Not restarting it makes weird behaviors to happen like errors when importing the libraries.

If `apache-beam` appeared as not installed, that could mean that Colab was left idle for a long time and it deleted the runtime to save resources, so running it again would start with a fresh environment without the dependencies installed.

You can keep installing dependencies throughout the notebook, but you would have to be careful to restart the runtime every time you install something new. That means losing all the variables you have defined and all the cells you have run, so you would have to re-run them from beginning to end.

I see that tests have been passing, which means that the requirements in the requirements file are complete and it can run the notebook from beginning to end. I'll close this for now, but feel free to re-open if things are still not working for you. Or feel free to keep commenting if you have any other questions and I'll do my best to answer them :)
