### ISSUE TITLE
transcribe 3gp audio

### ISSUE THREAD

**Issue by ndy1g14** [GoogleCloudPlatform/python-docs-samples#816]
I cannot manage to transcribe a simple 3gp audio file with the google cloud speech api. Your example is running fine with audio.raw but when I change it to my file it goes wrong.

Recording is made like this in my android device:
```
 mediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
 mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
 mediaRecorder.setAudioEncoder(MediaRecorder.OutputFormat.AMR_NB);
```
I transcribe it like this:

```
import io
import os

# Imports the Google Cloud client library
from google.cloud import speech

# Instantiates a client
speech_client = speech.Client()

# The name of the audio file to transcribe
file_name = os.path.join(
    os.path.dirname(__file__),
    'resources',
    'phone.3gp')

# Loads the audio into memory
with io.open(file_name, 'rb') as audio_file:
    content = audio_file.read()
    audio_sample = speech_client.sample(
        content,
        source_uri=None,
        encoding='AMR',
        sample_rate=8000) #LINEAR16

# Detects speech in the audio file
alternatives = speech_client.speech_api.sync_recognize(audio_sample)

for alternative in alternatives:
    print('Transcript: {}'.format(alternative.transcript))
```

Encoding and sample rate is correct but I get:

```
Traceback (most recent call last):
  File "transcribe.py", line 26, in <module>
    alternatives = speech_client.speech_api.sync_recognize(audio_sample)
  File "C:\Program Files\Anaconda2\lib\site-packages\google\cloud\speech\_gax.py", line 266, in sync_recognize
    raise ValueError('More than one result or none returned from API.')
ValueError: More than one result or none returned from API.
```

**Comment by jonparrott** [comment]
@jerjou @gguuss I don't think the backend accepts .3gp audio, can either of you confirm?

**Comment by jerjou** [comment]
Hm.. this should work. It looks like you're correctly specifying the AMR codec and bitrate.

Oh okay - it looks like it's this bug: [google-cloud-python#2947](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2947). Looks like it's been fixed, although I get other errors when I try to `pip install -e "git+https://github.com/GoogleCloudPlatform/google-cloud-python.git#egg=google-cloud-speech&subdirectory=speech"`. The easiest workaround is probably to use the [`api-client`](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech/api-client) library instead.

**Comment by ndy1g14** [comment]
Thanks for the great responses guys. My problem was that I copy code without looking at it. 

`mediaRecorder.setAudioEncoder(MediaRecorder.OutputFormat.AMR_NB);`

should be 

`mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);`

The constants are different in the documentation.

**Comment by amnanajib** [comment]
could anyone explain to me the following parts:
# The name of the audio file to transcribe
file_name = os.path.join(
    os.path.dirname(__file__),
    'resources',
    'phone.3gp')
and
# Loads the audio into memory
with io.open(file_name, 'rb') as audio_file:
    content = audio_file.read()
    audio_sample = speech_client.sample(
        content,
        source_uri=None,
        encoding='AMR',
        sample_rate=8000) #LINEAR16
