### ISSUE TITLE
Endpoints 2.0 App Engine standard quickstart is broken

### ISSUE THREAD

**Issue by henriquesg** [GoogleCloudPlatform/python-docs-samples#821]
Here's the quickstart:
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/endpoints-frameworks-v2/quickstart

When you deploy this guy, you get the following error:
```ApiConfigurationError: Attempting to implement service authed_greeting, version v1, with multiple classes that are not compatible. See docstring for api() for examples how to implement a multi-class API.```

It seems you can't have more than 1 API/Service with endpoints 2.0.
So I'm not even sure it's a problem with the example itself, but maybe with the endpoints module.

**Comment by jonparrott** [comment]
@sepehre @saicheems any ideas on this one?

**Comment by henriquesg** [comment]
Seems someone created a related issue in google-endpoints:
https://github.com/cloudendpoints/endpoints-python/issues/46

**Comment by jonparrott** [comment]
Great, let's track it there. I'm going to close this issue.
