### ISSUE TITLE
ImportError: cannot import name 'cygrpc' from 'grpc._cython' on 32-bit Raspberry PI 4

### ISSUE THREAD

**Issue by brianreinhold** [GoogleCloudPlatform/python-docs-samples#8256]
Even though this is a complicated program this error occurs right at the start because one of the first things done in the files is to import grpc. I am using python 3.8 on a Raspberry PI 4 but running 32 bit. The file it chokes on is
```cygrpc.cpython-38-arm-linux-gnueabihf.so``` which is 32-bit.
This is the only non-py file in the whole project.

The same program runs fine on a raspberry pi 3 64-bit system. However, it is running python 3.9 and therefore the grpc *.so file in this case is the 64-bit 
```cygrpc.cpython-39-aarch64-linux-gnu.so```

I assume the python interpreter on the 32-bit Raspberry PI 4 is 32 bit, but the 'python3' command by itself does not reveal its bitness even though every post in the world I have seen says it should. All I get is
```Python 3.8.12 (default, May 24 2022, 21:01:23)
[GCC 9.3.0] on linux
```

So when I try and run my program on the Raspberry PI 4, grpc gives the following (its in a virtual environment)
```
(swc_venv) root@raspberrypi4:/usr/lib/swc_venv/lib/python3.8/site-packages/SwcPackage# python3 start_swc.py
Traceback (most recent call last):
  File "start_swc.py", line 1, in <module>
    from Swc.swc import main
  File "/usr/lib/swc_venv/lib/python3.8/site-packages/SwcPackage/Swc/swc.py", line 10, in <module>
    from Swc import udevmodule
  File "/usr/lib/swc_venv/lib/python3.8/site-packages/SwcPackage/Swc/udevmodule.py", line 3, in <module>
    from Swc import swa
  File "/usr/lib/swc_venv/lib/python3.8/site-packages/SwcPackage/Swc/swa.py", line 16, in <module>
    from Swc.sensor_suite_upload import SsUpload       # grpc
  File "/usr/lib/swc_venv/lib/python3.8/site-packages/SwcPackage/Swc/sensor_suite_upload.py", line 4, in <module>
    import grpc
  File "/usr/lib/swc_venv/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/usr/lib/swc_venv/lib/python3.8/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/usr/lib/swc_venv/lib/python3.8/site-packages/grpc/_cython/__init__.py)
```
As you can see the program never gets beyond importing modules.

**Comment by leahecole** [comment]
Hi! Which file is this occurring in?

**Comment by brianreinhold** [comment]
_compression.py line 15 (an import statement)

This is all before the first line of 'written' code is touched - just doing imports.

**Comment by dandhlee** [comment]
Hey @brianreinhold, we can only look into issues which occur for files in this repository. Could you help fill in the template:

Please include as much information as possible:

## In which file from this repository did you encounter the issue?

## Did you change the file? If so, how?

**Comment by brianreinhold** [comment]
Oh, then I filed an incorrect bug. I thought you Google Cloud People were behind grpc. If not, mark this bug as invalid or delete it.
We are using such services through SensorSuite but it is not sensor suite that is causing the issue.

**Comment by dandhlee** [comment]
This is a repository for Python Samples :) I'll close this issue.
If you need support for grpc, please ask in the repository for grpc: https://github.com/grpc/grpc.
