### ISSUE TITLE
Enable ml_engine.online_prediction.predict_test.test_predict_tfrecords

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/python-docs-samples#828]
Once b/35778449 has been fixed. Need to create a model version named `v1tfrecords` using the successful model binaries, and enable `ml_engine.online_prediction.predict_test.test_predict_tfrecords` targeting that model version.

**Comment by engelke** [comment]
Should this be an internal bug instead of Github issue?

**Comment by nnegrey** [comment]
Most of these samples have been migrated to https://github.com/GoogleCloudPlatform/cloudml-samples/
Closing
