### ISSUE TITLE
Generate readme for ml_engine/online_prediction/README.md

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/python-docs-samples#829]
Docs link is available in the README.

**Comment by engelke** [comment]
Should this be tracked by an internal bug instead of here?

**Comment by engelke** [comment]
The creator of the code should update the README or assign someone familiar with it to do so.

**Comment by nnegrey** [comment]
Most of these samples have been migrated to https://github.com/GoogleCloudPlatform/cloudml-samples/
Closing
