### ISSUE TITLE
BQ API issue "no module named cloud"

### ISSUE THREAD

**Issue by edost22** [GoogleCloudPlatform/python-docs-samples#840]
Attempted running the following sample script:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/simple_app.py

I changed the client=bigquery.Client() line to "client = bigquery.Client(project='nodal-nirvana-637')"

Throws the following error:
ImportError: No module named cloud

I have the most recent Google Could SDK, which was initialized and authorized. The BQ CLI works just fine. 
I upgraded google-cloud-bigquery. I have BQ API enabled. 

Please help. From my searches I saw that maybe the most updated version is not installed, but it is.

**Comment by tommy1995** [comment]
hey how did you resolve this issue?

**Comment by jonparrott** [comment]
@tommy1995 if you're experiencing this issue, can you give us the full stack trace and let us know the versions of `google-cloud-bigquery` you have installed?
