### ISSUE TITLE
Old way to specify resources in kubernetes_pod_operator.py

### ISSUE THREAD

**Issue by kenz** [GoogleCloudPlatform/python-docs-samples#8427]
## Is your feature request related to a problem? Please describe.
Yes.

Perhaps the method shown on the page below is outdated.
```Python
resources={'limit_memory': "250M", 'limit_cpu': "100m"},
```
https://cloud.google.com/composer/docs/composer-2/use-kubernetes-pod-operator#kubernetespodoperator_configuration

In the `composer-2.0.28-airflow-2.3.3` this method receives an error.
```
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 858, in __init__
    self.resources = coerce_resources(resources)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 133, in coerce_resources
    return Resources(**resources)
TypeError: __init__() got an unexpected keyword argument 'limit_memory'
```

## Describe the solution you'd like.
Update the documentation

new way
```Python
container_resources = k8s.V1ResourceRequirements(
      limits={'memory': '250M', 'cpu': "100m"},
)
```

## Additional context.
 I referred to the following history
https://github.com/apache/airflow/blob/ea55626d79fdbd96b6d5f371883ac1df2a6313ec/kubernetes_tests/test_kubernetes_pod_operator.py#L366

Thanks!

**Comment by dandhlee** [comment]
I can see that `resources` is deprecated as per the Airflow docs: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/_modules/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.html#KubernetesPodOperator

Leah, please take a look!
