### ISSUE TITLE
Reworking the Compute OSLogin SSH samples and tests

### ISSUE THREAD

**Issue by m-strzelczyk** [GoogleCloudPlatform/python-docs-samples#8429]
After tackling the #7277 issue over many weeks, I decided that it's time to invest a lot more attention to the SSH samples and their tests. I want to use this issue as a tracker for following problems I want to fix:

1. The tests mentioned in #7277 are flaky and evade all fix attempts.
2. The samples in [service_account_ssh.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/compute/oslogin/service_account_ssh.py) have incorrect region tags - they don't start with product prefix.
3. The sample uses the old compute library, while it should be using GAPIC lib.
4. The tests are sometimes leaking resources.

To fix all those issues, I'm going to rewrite the samples using GAPIC library, together with rewriting tests. Hopefully, using a new library will make it easier to properly run tests.

**Comment by m-strzelczyk** [comment]
The code is used on [this page](https://cloud.google.com/compute/docs/tutorials/service-account-ssh)

**Comment by m-strzelczyk** [comment]
Libraries to use:
 * [Python compute](https://github.com/googleapis/python-compute)
 * [Python os-login](https://github.com/googleapis/python-oslogin)

**Comment by m-strzelczyk** [comment]
Change to the docsite requested as cl/487212180

**Comment by m-strzelczyk** [comment]
Turns out, the tests can still be flaky ;( #8476

**Comment by m-strzelczyk** [comment]
Current theory:

The test fails when GCE Enforcer removes the firewall entry allowing port 22 communication with the test instance. As a result the test fails to properly SSH into the instance to execute the simple command. It's not the first time GCE Enforcer has caused issues with our tests unfortunately.

I will probably make this test fail gracefully if it detects that the firewall rule is not present after the failed SSH attempt.

**Comment by nicain** [comment]
Lots of changes on the infrastructure side may have resolved this. Closing to see if this will reoccur.
