### ISSUE TITLE
KubernetesPodOperator in Composer 2

### ISSUE THREAD

**Issue by hblumberg** [GoogleCloudPlatform/python-docs-samples#8449]
Do Cloud Composer 2 users have to be concerned about resource starvation when using the `KubernetesPodOperator`? The [documentation](https://cloud.google.com/composer/docs/composer-2/use-kubernetes-pod-operator) states:

> In Cloud Composer 2, your environment's cluster scales automatically. Extra workloads that you run using KubernetesPodOperator scale independently from your environment. Your environment is not affected by the increased resource demand, but your environment's cluster scales up and down depending on the resource demand.

But the [sample code](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/composer/workflows/kubernetes_pod_operator.py#L80) includes a comment describing the `namespace` argument:

> The namespace to run within Kubernetes, default namespace is `default`. There is the potential for the resource starvation of Airflow workers and scheduler within the Cloud Composer environment

These seem contradictory to me. Thanks in advance for any guidance you can provide!

**Comment by leahecole** [comment]
Great catch @hblumberg - you're spot on. This code was written before Composer 2 was introduced! I updated the comment to clarify that this only applies to Composer 1 environments. Thank you so much for filing an issue 😁

**Comment by hblumberg** [comment]
Fantastic, thank you so much for clarifying!!
