### ISSUE TITLE
Specify python version 3.7

### ISSUE THREAD

**Issue by jvm986** [GoogleCloudPlatform/python-docs-samples#8466]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/2ca8165875b1d93fdee551bdaa4db410e50c8d85/appengine/flexible/django_cloudsql/app.yaml#L25

... should be

```yaml
python_version: 3.7
```

This is because the specified version of `google-cloud-secret-manager==2.12.0` is not supported by the default `python3.6`

Ideally the deployer container would be updated to a more recent version of python (with support for `Django==4.0.4`)

**Comment by dandhlee** [comment]
@glasnt could you help take a look into this?

**Comment by glasnt** [comment]
Specifying `python: 3` in App Engine Flex defaults to `3.6` (https://cloud.google.com/appengine/docs/flexible/python/runtime#interpreter)

We can absolutely bump this to `3.7`, but we can't also bump Django at the same time, as according to https://docs.djangoproject.com/en/4.1/faq/install/#what-python-version-can-i-use-with-django the highest version of Django that Python 3.7 can support is 3.2.  (We could bump Python higher with a custom runtime, but I think that's out of scope)
