### ISSUE TITLE
Analytics sample targets UA instead of GA4.

### ISSUE THREAD

**Issue by NeilFraser** [GoogleCloudPlatform/python-docs-samples#8467]
The sample code to interface with Google Analytics is here:
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/appengine/standard/analytics

Unfortunately that version of Analytics (UA) has been deprecated and will be shut down soon.  The new version of Analytics (GA4) is of course utterly incompatible.

Also relevant is the documentation page:
https://cloud.google.com/appengine/docs/legacy/standard/python/google-analytics
This page has a couple of links to deprecated UA pages.

**Comment by dandhlee** [comment]
Thank Neil for reporting this!

@engelke Charlie, does it make sense to take the sample down once Analytics is shut down?

**Comment by engelke** [comment]
Yes, I think so. What are the arguments against doing that?

**Comment by NeilFraser** [comment]
If the decision is to take it down, then in my opinion it should be taken down now rather than waiting until UA's shutdown in Summer 2023.  This sample helps developers create *new* integrations, not something Google wants to encourage.

Ideally though, this sample would be replaced by one demonstrating how to integrate with GA4.  Though in our case we've determined GA4 to be unusable (adding GA4 support doubled the download size of our site), so we no longer care.

**Comment by engelke** [comment]
Users generally reach this spot via the web docs, and they seem to have plans on when and how to update or remove them. They already have warnings about the old versions being deprecated. I recommend we just leave this folder alone until that time, when they will likely remove any docs that point here.
