### ISSUE TITLE
Google Videointelligence.v1beta1 Usage

### ISSUE THREAD

**Issue by naveensinghal** [GoogleCloudPlatform/python-docs-samples#847]
Hi @gguuss @jonparrott 

I am trying to use Video Intelligence API but getting Import Error in the following two import Statements: 
```
from google.cloud.gapic.videointelligence.v1beta1 import enums
from google.cloud.gapic.videointelligence.v1beta1 import (video_intelligence_service_client)
```

Error:
`ImportError: No module named videointelligence.v1beta1`

Can you please suggest how can this issue be resolved ? 

Thanks

**Comment by jonparrott** [comment]
Hi @naveensinghal, just a sanity check did you run `pip install -r requirements.txt` in a virtualenv?

**Comment by naveensinghal** [comment]
@jonparrott Are you talking about this requirements.txt ? 
Path: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/video/cloud-client/requirements.txt

I haven't done `pip install -r requirements.txt ` for this file yet.

**Comment by jonparrott** [comment]
You definitely need to do that in order to use these samples.

**Comment by naveensinghal** [comment]
@jonparrott Just did that....

Getting a different Error now... [Import Error seems to be fixed though]
```
---> 67     video_client = video_intelligence_service_client.VideoIntelligenceServiceClient()
     68     operation = video_client.annotate_video(path, features)
     69     print('\nProcessing Video for Annotations:')

/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/videointelligence/v1beta1/video_intelligence_service_client.pyc in __init__(self, service_path, port, channel, credentials, ssl_credentials, scopes, client_config, app_name, app_version, lib_name, lib_version, metrics_headers)
    136             client_config,
    137             config.STATUS_CODE_NAMES,
--> 138             metrics_headers=metrics_headers, )
    139         self.video_intelligence_service_stub = config.create_stub(
    140             video_intelligence_pb2.VideoIntelligenceServiceStub,

TypeError: construct_settings() got an unexpected keyword argument 'metrics_headers'

```

Any Suggestions for this ?

**Comment by jonparrott** [comment]
@gguuss any ideas?

**Comment by naveensinghal** [comment]
@jonparrott @gguuss Since the VideoIntelligence API is in Private Beta currently, Can I verify somehow If I have been granted the access yet ? 
[I signed up for the access 3 days ago. But haven't received any confirmation yet]

**Comment by jonparrott** [comment]
@naveensinghal if you haven't heard back yet you probably do not have access. Still, this error is unrelated.

**Comment by naveensinghal** [comment]
@jonparrott Okay. 
Btw, The only setup I have done for this is: 
`pip install https://storage.googleapis.com/videointelligence-alpha/videointelligence-python.zip`

and just ran these two commands from the python shell: 
```
from google.cloud.gapic.videointelligence.v1beta1 import video_intelligence_service_client
video_client = video_intelligence_service_client.VideoIntelligenceServiceClient()
```

and got the above mentioned stack trace Error.

Is there anything else that needs to be done ?

**Comment by gguuss** [comment]
The API definitely will not work until after you have been whitelisted but should not be failing when you are instantiating the client but instead when you create an operation, for example:

```
operation = video_client.annotate_video(path, features)
```

I'm guessing that there is something wrong with the way you have Python configured. Are you using virtual environment and are you on Python 2.x or Python 3.x?

**Comment by naveensinghal** [comment]
@gguuss @jonparrott I am using Virtual Environment & Python 2.7. 
I am trying these two commands in the python shell. (using python manage.py shell). 

```
from google.cloud.gapic.videointelligence.v1beta1 import video_intelligence_service_client
video_client = video_intelligence_service_client.VideoIntelligenceServiceClient()
```

**Comment by jonparrott** [comment]
@naveensinghal I highly recommend you install the requirements.txt in a virtualenv before trying to run the sample. Virtualenv helps isolate system packages and the sample's packages from one another, which is a common case of issues.

**Comment by gguuss** [comment]
The following worked for me from Cloud shell:

```
git clone https://github.com/GoogleCloudPlatform/python-docs-samples
cd python-docs-samples/video/cloud-client
virtualenv env
source env/bin/activate
pip install -r requirements.txt
python analyze.py
```

**Comment by naveensinghal** [comment]
@gguuss @jonparrott  Tried these 6 commands. Got this result: 

`google.gax.errors.RetryError: GaxError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Google Cloud Video Intelligence API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/videointelligence.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.)>)
`

Guess, I still don't have access to the VideoIntelligence API. 

Thanks for your Suggestions.

**Comment by naveensinghal** [comment]
@gguuss @jonparrott 
I am trying to implement VideoIntelligence API in my personal-project. but I am not able to do so yet. [I have the access permissions for VideoIntelligence API for my personal-project]
Please provide some suggestions to make it work.

I tried the following commands:
```
(venv) naveen@naveen:~/Desktop/personal-project/personal$ python manage.py shell
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from google.cloud.gapic.videointelligence.v1beta1 import video_intelligence_service_client
>>> video_client = video_intelligence_service_client.VideoIntelligenceServiceClient()
>>> path = 'gs://demomaker/google_gmail.mp4'
>>> features = [2]
>>> operation = video_client.annotate_video(path, features)

```

But I am getting this as the Error: 
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "personal-project/venv/local/lib/python2.7/site-packages/google/cloud/gapic/videointelligence/v1beta1/video_intelligence_service_client.py", line 234, in annotate_video
    self._annotate_video(request, options), self.operations_client,
  File "personal-project/venv/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 419, in inner
    return api_caller(api_call, this_settings, request)
  File "personal-project/venv/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 407, in base_caller
    return api_call(*args)
  File "personal-project/venv/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 368, in inner
    return a_func(*args, **kwargs)
  File "personal-project/venv/local/lib/python2.7/site-packages/google/gax/retry.py", line 126, in inner
    ' classified as transient', exception)
RetryError: GaxError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Google Cloud Video Intelligence API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/videointelligence.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.)>)

```

It is searching inside 'usable-auth-library' project. Whereas I have access permission for my 'personal-project'. How can I make this work ? 

Any Suggestions please ? 


Thanks

**Comment by jonparrott** [comment]
Hi @naveensinghal, you likely need to setup service account credentials to be able to call, as the credentials provided by `gcloud` can not currently be used with this API.

https://cloud.google.com/vision/docs/common/auth#set_up_a_service_account

**Comment by naveensinghal** [comment]
okay. Got it. 

Thanks,

**Comment by naveensinghal** [comment]
@gguuss @jonparrott 

Hi,
I am trying to use Google Video Intelligence API for SafeContent Detection from python shell. But getting this Error.

```
>>> from google.cloud import videointelligence
>>> video_client = videointelligence.VideoIntelligenceServiceClient()
>>> video_client
<google.cloud.videointelligence_v1.VideoIntelligenceServiceClient object at 0x7f1b5e709bd0>
>>> operation = video_client.annotate_video(path, features)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/videointelligence_v1/gapic/video_intelligence_service_client.py", line 201, in annotate_video
    location_id=location_id)
TypeError: [3] has type list, but expected one of: bytes
```

Any suggestions how to fix this ? 

Thanks
