### ISSUE TITLE
Tests use magic numbers

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/python-docs-samples#85]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/images/tests/test_guestbook.py

Code cleanup: HTTP requests should be named constants. 

Others might feel that HTTP codes are well known enough to not be "magic". I think this would be slight code cleanup but if there's loud objections we can leave it as is.

httplib contains the constants so we can use those.

**Comment by jonparrott** [comment]
I'm closing this as won't fix, because HTTP codes are standardized enough to not be considered magic number IMO.
