### ISSUE TITLE
Address logging v3.2.2 issues in samples

### ISSUE THREAD

**Issue by dandhlee** [GoogleCloudPlatform/python-docs-samples#8513]
Based on #8167, there has been an introduction with a new format of output that's messing with the expected output for the samples in `functions/v2/http_logging`. Few options that Daniel suggested:

```
The easiest solution for testing is probably to use the existing internal flag to disable instrumentation for the tests here: google.cloud.logging_v2._instrumentation_emitted = True. I think changing the tests is also acceptable if that ends up being easier though.
```

**Comment by engelke** [comment]
Closed #8167 by rolling back version just for functions/v2/http-logging.
