### ISSUE TITLE
vision/snippets/document_text/doctext.py: Avoid making the same API request three times

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/python-docs-samples#8543]
Transferred from https://github.com/googleapis/python-vision/pull/358

 > **Is your feature request related to a problem? Please describe.**
When calling render_doc_text, it will make the same API request three times. This is slow, causes network overhead, and triples the processing fees for the API request (if not covered within free usage quota). 
https://github.com/googleapis/python-vision/blob/HEAD/samples/snippets/document_text/doctext.py

> **Describe the solution you'd like**
I would like to make the API request only once and then process the response to this request three times. 

A fix was proposed in https://github.com/googleapis/python-vision/pull/358 but I closed the PR as the repo no longer contains the sample code.

**Comment by dandhlee** [comment]
Balaji, could you help take a look at this and assign an appropriate person for this? We currently only have `GoogleCloudPlatform/ml-apis` listed as the team to help look at `api: vision`.

**Comment by vchudnov-g** [comment]
@balajismaniam Could you weigh in on this, please? Thanks!
