### ISSUE TITLE
Cloud SQL Database, Min. severity: Info

### ISSUE THREAD

**Issue by bugalwena** [GoogleCloudPlatform/python-docs-samples#8545]
Take a look at the logs for Cloud SQL Database (minimum severity: Info) in project analog-grin-346607: https://console.cloud.google.com/logs?advancedFilter=resource.type%3D%22cloudsql_database%22%20AND%20severity%3E%3DINFO%20AND%20timestamp%3E%3D%222022-11-21T16%3A15%3A15.490%2B11%3A00%22%20AND%20timestamp%3C%3D%222022-11-21T16%3A15%3A15.491%2B11%3A00%22&project=analog-grin-346607&src=VESPA

**Comment by dandhlee** [comment]
Hi @bugalwena. If you do not have an issue directly related to a Python samples from this repository, please stop filing issues.
