### ISSUE TITLE
Psycopg2 is not supported, but why is it in this example?

### ISSUE THREAD

**Issue by miratcan** [GoogleCloudPlatform/python-docs-samples#855]
I was trying to use Google Appengine Flask and SQLAlchemy to connect to PostgreSQL server. It was not working because it was giving error something something like can not import psycopg2._psycopg2. After a while I've learned that you have to use Google Appengine with pure Python PostgreSQL driver, which is called PG8000. 

But now I'm seeing psycopg2 in this repository again. It's so confusing. Is psycopg2 supported by GAE or not?

Edit: I'm talking about this: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/flexible/cloudsql/requirements.txt

**Comment by jonparrott** [comment]
@miratcan that sample is for GAE Flexible, which supports any linux-compatible third-party package.

**Comment by aaronkb** [comment]
I have the same problem @miratcan was trying to solve. What are my options if I want to use SQLAlchemy in a Flask service run on App Engine Standard? Is there a way? What's the workaround if there isn't?
