### ISSUE TITLE
   'No such virtualenv or site directory' % path) ValueError: virtualenv: cannot access lib: No such virtualenv or site directory INFO    

### ISSUE THREAD

**Issue by markmark1** [GoogleCloudPlatform/python-docs-samples#857]
## In which file did you encounter the issue?
   'No such virtualenv or site directory' % path)
ValueError: virtualenv: cannot access lib: No such virtualenv or site directory
INFO    

### Did you change the file? If so, how?
no

## Describe the issue
running python-docs-samples/appengine/standard/flask/tutorial

 tutorial (master) $ dev_appserver.py app.yaml
INFO     2017-03-17 01:12:56,992 devappserver2.py:764] Skipping SDK update check.
INFO     2017-03-17 01:12:57,060 api_server.py:268] Starting API server at: http://localhost:56375
INFO     2017-03-17 01:12:57,069 dispatcher.py:199] Starting module "default" running at: http://localhost:8080
INFO     2017-03-17 01:12:57,072 admin_server.py:116] Starting admin server at: http://localhost:8000

gives error

s/google-cloud-sdk/platform/google_appengine/google/appengine/ext/vendor/__init__.py", line 44, in add
    'No such virtualenv or site directory' % path)
ValueError: virtualenv: cannot access lib: No such virtualenv or site directory
INFO     2017-03-17 01:13:10,584 module.py:806] default: "GET / HTTP/1.1" 500 -

ERROR    2017-03-17 01:13:10,573 wsgi.py:263] 
Traceback (most recent call last):
  File "~/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "~/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 351, in __getattr__
    self._update_configs()
  File "~/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 287, in _update_configs
    self._registry.initialize()
  File "~/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 160, in initialize
    import_func(self._modname)
  File "/Users/mark/python-docs-samples/appengine/standard/flask/tutorial/appengine_config.py", line 18, in <module>
    vendor.add('lib')

**Comment by markmark1** [comment]
$ pip install -r requirements.txt -t lib gives following error

Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, filterfalse, map
  File "/usr/local/lib/python2.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named extern

**Comment by jonparrott** [comment]
Looks like you should update your pip.

**Comment by markmark1** [comment]
pip install --upgrade pip

Requirement already up-to-date: pip in
/usr/local/lib/python2.7/site-packages

On Thu, Mar 16, 2017 at 6:19 PM, Jon Wayne Parrott <notifications@github.com
> wrote:

> Looks like you should update your pip.
>

**Comment by jonparrott** [comment]
Maybe upgrade setuptools as well? Seems weird.

**Comment by markmark1** [comment]
error only in flask folder not in hello_world folder if that helps

python-docs-samples/appengine/standard/flask/hello_world
/google-cloud-sdk/platform/google_appengine/google/appengine/ext/vendor/__init__.py", line 44, in add
    'No such virtualenv or site directory' % path)
ValueError: virtualenv: cannot access lib: No such virtualenv or site directory
INFO     2017-03-17 01:38:58,863 module.py:806] default: "GET / HTTP/1.1" 500 -

**Comment by markmark1** [comment]
pip install --upgrade setuptools flask pip
Collecting setuptools
  Using cached setuptools-34.3.2-py2.py3-none-any.whl
Collecting flask
  Using cached Flask-0.12-py2.py3-none-any.whl
Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: six>=1.6.0 in /usr/local/lib/python2.7/site-packages (from setuptools)
Collecting packaging>=16.8 (from setuptools)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from flask)
  Using cached Jinja2-2.9.5-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask)
  Using cached Werkzeug-0.12.1-py2.py3-none-any.whl
Collecting click>=2.0 (from flask)
  Using cached click-6.7-py2.py3-none-any.whl
Requirement already up-to-date: itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from flask)
Collecting pyparsing (from packaging>=16.8->setuptools)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->flask)
  Using cached MarkupSafe-1.0.tar.gz
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, filterfalse, map
  File "/usr/local/lib/python2.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named extern

**Comment by markmark1** [comment]
same error when upgrading setup tools or pip too

**Comment by markmark1** [comment]
i am trying to get flask running on standard environment and have an app engine endpoints auto generated mobile iOS and android starter app skeleton going as seen in the google next videos

**Comment by markmark1** [comment]
Didn't work either

**Comment by markmark1** [comment]
jon, i am trying to get flask running on standard environment and have an app engine endpoints auto generated mobile iOS and android starter app skeleton going as seen in the google next videos
what is the best way to go about this thanks
