### ISSUE TITLE
flex / python. skip_files are being uploaded to appengine.

### ISSUE THREAD

**Issue by yipjustin** [GoogleCloudPlatform/python-docs-samples#859]
## In which file did you encounter the issue?

app.yaml

### Did you change the file? If so, how?

Added the following line

```
skip_files
- ^env/.*$
```

## Describe the issue

I am using the flexible environment. Trying not to include the huge directory generated by virtualenv.

I have added the above lines to app.yaml, but it seems like the file is still being uploaded to appengine.

**Comment by yipjustin** [comment]
issue resolved after using the latest `gcloud` sdk.

**Comment by Avinash-Raj** [comment]
@yipjustin you must include `:` after `skip_files`

```
skip_files:
  - ^env/.*$
```
