### ISSUE TITLE
There has got to be a better way to do bigquery/load_data_by_post

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/python-docs-samples#86]

**Comment by jerjou** [comment]
Haha - what were you thinking? You could do it synchronously as well, I believe, but I imagine that's not what you're getting at.

**Comment by jonparrott** [comment]
I think you already solved this when you re-wrote the sample. Assigning it to you so you could confirm and close.

**Comment by jerjou** [comment]
Oh right. Didn't look at the date on this.
