### ISSUE TITLE
Cloud endpoints with app engine standard environment what is the best way to get started thanks

### ISSUE THREAD

**Issue by markmark1** [GoogleCloudPlatform/python-docs-samples#860]
## In which file did you encounter the issue?
i am trying to get flask running on standard environment and have an app engine endpoints auto generated mobile iOS and android starter app skeleton going as seen in the google next videos
what is the best way to go about this thanks

### Did you change the file? If so, how?
no 

## Describe the issue
need to use samples

**Comment by jonparrott** [comment]
@markmark1 I would start with the documentation here: https://cloud.google.com/endpoints/docs/frameworks/python/about-cloud-endpoints-frameworks

**Comment by markmark1** [comment]
does it work with standard or flex
or both
does it need any specific code to mark api handlers

**Comment by jonparrott** [comment]
@markmark1 the linked documentation is for standard only. Endpoints frameworks are only for standard. The OpenAPI implementation is for non-app engine standard environments: https://cloud.google.com/endpoints/docs/quickstart-app-engine

**Comment by markmark1** [comment]
What's open api How to generate end points for standard






On Mon, Mar 20, 2017 at 2:41 PM -0700, "Jon Wayne Parrott" <notifications@github.com> wrote:












@markmark1 the linked documentation is for standard only. Endpoints frameworks are only for standard. The OpenAPI implementation is for non-app engine standard environments: https://cloud.google.com/endpoints/docs/quickstart-app-engine

**Comment by markmark1** [comment]
Ndb vs db vs gql what's the right way to access data store in python  thanks






On Mon, Mar 20, 2017 at 2:41 PM -0700, "Jon Wayne Parrott" <notifications@github.com> wrote:












@markmark1 the linked documentation is for standard only. Endpoints frameworks are only for standard. The OpenAPI implementation is for non-app engine standard environments: https://cloud.google.com/endpoints/docs/quickstart-app-engine

**Comment by jonparrott** [comment]
Hi @markmark1, in general this repository is for filing issues against the samples. I'd recommend that if you have general questions you try stackoverflow or the GCP Slack.

**Comment by markmark1** [comment]
endpoints-frameworks-v2 (master) $ pwd

python-docs-samples/appengine/standard/endpoints-frameworks-v2





On Mon, Mar 20, 2017 at 3:08 PM, Jon Wayne Parrott <notifications@github.com
