### ISSUE TITLE
Cloud VideoIntelligence API Query

### ISSUE THREAD

**Issue by naveensinghal** [GoogleCloudPlatform/python-docs-samples#865]
@jonparrott @gguuss 

Can you please tell, If there is a way to count the No. of Faces in the Video using Cloud VideoIntelligence API ?

Thanks,

**Comment by gguuss** [comment]
I can't really comment at too much detail on the whitelist API outside of what's in the docs; a [good example](https://cloud.google.com/video-intelligence/) of the API is available on the landing page to give you an idea of how the API works. Try it with the "work" demo video and see if the labels for specific shots get you where you want to be.

If the level of detail is not sufficient for your application, you could extract frames around the sections of interest and then [use the Vision API](https://cloud.google.com/vision/) for counting faces, which it's great at.

**Comment by naveensinghal** [comment]
Vision API can give the correct result for Counting faces in a single Frame. But it doesn't work effectively for multiple frames together.

For Example: if there is a Video/segment with 10 frames and each frame contains 2 same faces throughout. Then the actual total Faces available in the Video would be 2. But Vision API would give 10X2=20 faces. 

Anyways, would try to check again from the VideoIntelligence Doc itself. 

Thanks,

**Comment by indrabayu** [comment]
I don't think this API will give you the number of occurences of a certain entity(ies) in the video.
