### ISSUE TITLE
Cannot import `google-appengine.*` as per `appengine/standard/localtesting/datastore_test.py`

### ISSUE THREAD

**Issue by ericpar** [GoogleCloudPlatform/python-docs-samples#879]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/localtesting/datastore_test.py

### Did you change the file? If so, how?

No.

## Describe the issue

I tried to run the sample but the import failed:

```
from google.appengine.api import memcache
from google.appengine.ext import ndb
from google.appengine.ext import testbed
```

No evidence of this package was found in the repo and the version available in PiPY seems to be rather old (2011).

Searching for the `google.appengine` package led to https://pypi.python.org/pypi/google-appengine but trying installing it on Python 3.5 failed (!):

```
$ pip install googleappengine
Collecting googleappengine
  Could not find a version that satisfies the requirement googleappengine (from versions: )
No matching distribution found for googleappengine
```

**Comment by jonparrott** [comment]
Hi @ericpar, you need to run these samples using the App Engine development server `dev_appserver.py` which provides all of `google.appengine` packages.

https://cloud.google.com/appengine/docs/standard/python/tools/using-local-server

**Comment by ericpar** [comment]
Thank you, @jonparrott .
I installed both The Google Cloud SDK and App Engine SDK for Python but I have no clue where to find this `dev_appserver.py` you are talking about. Would you have any hint for me?

**Comment by minesh1291** [comment]
https://kawashi.me/posts/5654313976201216/add-google-app-engine-standard-python-sdk-to-your-conda-environment
