### ISSUE TITLE
I want to submit a spark job on the dataproc cluster, but with custom job id

### ISSUE THREAD

**Issue by abhishek-ksolve** [GoogleCloudPlatform/python-docs-samples#8885]
I am using this code dataproc/snippets/submit_job_to_cluster.py to submit a job but it is not mentioned how to pass custom job_id, by default it takes job_uuid as job_id.

**Comment by engelke** [comment]
Thanks for opening this issue.

This snippet doesn't reference job_uuid and the only reference to job_id is in download_output, which is not used by other code here. That proc follows the included step near the end of the quickstart, which might be clearer as it is in context.

I'm going to close this issue, but feel free to reopen it and add more details so I can further understand the question.
