### ISSUE TITLE
Trouble deploying hello_world example

### ISSUE THREAD

**Issue by mariusdotspinu** [GoogleCloudPlatform/python-docs-samples#892]
I have followed the instructions from [quickstart](https://cloud.google.com/appengine/docs/standard/python/quickstart) but when I try to deploy, nothing happens.

I have run cmd with administrator rights , like this : 

`C:\Users\Marius\Desktop\Cloud-Computing\HelloWorld\python-docs-samples\appengine\standard\hello_world>dev_appserver.py app.yaml` , but nothing happens.

I know that it is suppose to work using python 2.7.10, however while I was downloading/initializing google cloud sdk , my path was 3.6.x , only afterwards I have changed my path to 2.7.10. 

Do you think this might be the issue ? Should I try setting up a new project again , or is there some work-around that might skip that ?

Thank you.

**Comment by jonparrott** [comment]
@mariusdotspinu "nothing happens"? No output at all?

I would definitely recommend re-installing the cloud sdk with Python 2.7.

**Comment by mariusdotspinu** [comment]
Yeah, no output at all.

Thanks , I will re-install it since there seems to be no other explanation.
