### ISSUE TITLE
How do I input "Context" hints on the new long_running_recognize function?

### ISSUE THREAD

**Issue by gerimo** [GoogleCloudPlatform/python-docs-samples#895]
## In which file did you encounter the issue?

On the previous version I would input a "context" module in "async_recognize()".

**Comment by ryanmats** [comment]
@gerimo According to our google-cloud-python client library source code (https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/sample.py#L135), you can pass in a parameter called speech_contexts.

:param speech_contexts: A list of strings (max 50) containing words and
                                phrases "hints" so that the speech recognition
                                is more likely to recognize them. This can be
                                used to improve the accuracy for specific words
                                and phrases. This can also be used to add new
                                words to the vocabulary of the recognizer.

@gguuss Maybe we should update our google-cloud documentation (https://googlecloudplatform.github.io/google-cloud-python/stable/speech-sample.html) with information about long_running_recognize().

**Comment by gguuss** [comment]
@ryanmats Thanks for the heads up, we are working on it!

**Comment by agsax2002** [comment]
In the old API, the parameter for "async_recognize" is called "speech_context". Looks like the new function adds an 's' to call it "speech_contexts". I got it to work that way.
