### ISSUE TITLE
Unable to build due to invalid github repo name location in cloudbuild preview substitution

### ISSUE THREAD

**Issue by LarryBarker** [GoogleCloudPlatform/python-docs-samples#8970]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/run/deployment-previews/cloudbuild-configurations/cloudbuild-preview.yaml

## Did you change the file? If so, how?

Yes, I tried to hard code the repo name. 

## Describe the issue

Following the tutorial here: https://cloud.google.com/run/docs/tutorials/configure-deployment-previews

The build is failing with the following error:

[_GITHUB_REPO -> $(pull_request.head.repo.full_name)]: generic::invalid_argument: failed ParseJSONPath: head is not found

Thanks!

**Comment by dandhlee** [comment]
For specific GitHub Repositories like using `helloworld-python` from the tutorial page, it seems like you need to use this build file: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/run/deployment-previews/cloudbuild-configurations/cloudbuild.yaml, then connect your GitHub account and then manually select the repository.

Could you try following the steps on https://cloud.google.com/run/docs/tutorials/configure-deployment-previews#retrieve-code but with your own repository name instead of `helloworld-python`?

**Comment by LarryBarker** [comment]
@dandhlee Thanks much for the quick reply. I was able to get past the error above by hard coding the repo name i.e. `owner/name`. The rest of the build completed find, and I do indeed have a preview URL for the revision; however, the last step fails when it tries to update the PR with the preview URL:

```Error finding repo ion-learning/ion-learning. Is it a private repo, and does your token have the correct permissions?: Not Found```

The tutorial also seems a bit out of date as the steps to create the PAT in github are different now. I did create a PAT with access to all repositories, and granted all available permissions. 

I'm wondering if it is expecting the full path to the repo? i.e. https://github.com/ion-learning/ion-learning ?

**Comment by LarryBarker** [comment]
@dandhlee Appears github has two types of PAT now: fine grained and classic. I just created a classic to see if this works. I also updated the `_GITHUB_REPO` variable in `cloudbuild-preview.yaml` to `_GITHUB_REPO: ${REPO_NAME}` because it appears cloud build provides this substitution variable by default now? https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values

However, the error changed: 

```Finished Step #8 - "link revision on pull request"
Step #8 - "link revision on pull request": Error finding repo ion-learning. Is it a private repo, and does your token have the correct permissions?: Not Found
Step #8 - "link revision on pull request": gcr.io/ionplayground-344320/deployment-previews:latest
Step #8 - "link revision on pull request": Status: Downloaded newer image for gcr.io/ionplayground-344320/deployment-previews:latest
Step #8 - "link revision on pull request": Digest: sha256:eb19f7b9860b495070f5522403745c10f183b76b326cd6b373b70d2e6dce4a42```

Notice here, it only has `ion-learning`, which I assume will fail. Testing now though.

**Comment by dandhlee** [comment]
@glasnt, can you help take a look at this?

**Comment by LarryBarker** [comment]
@dandhlee Ok so I was able to get the build to finish successfully and the deploy preview URL to post back to the PR: 

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/28734844/211722309-280f4ecd-dc0e-4930-973c-f088460c053c.png">

This worked after:

1. Create a classic PAT, not fine grained
2. Hardcode the repo name in `cloudbuild-preview.yaml`:

```
substitutions:
  _SERVICE_NAME: ion-learn-app
  _REGION: us-central1
  _GITHUB_REPO: ion-learning/ion-learning
```

As I mentioned, I tried some other substitution variables, namely `$REPO_NAME`, but that only gives us the repo name, not the owner as well. Going to roll with this for now to keep moving, but would love to have some more input from your team. Thanks much for fielding this so quickly!

**Comment by glasnt** [comment]
It looks like you solved it as I was writing this response! I'll still post what I was drafting: 

The hardcoding should have worked; it looks like a recent change altered the value pulled from the event payload (so it can get the information from the `pull_request`. Another issue (from memory) is that `REPO_NAME` is only going to be the repo name, not the full `owner/repo` that's needed to identify a github repo (hence the use of `pull_request.head.repo.full_name`). 

If you hardcode `_GITHUB_REPO` with the full `owner/repo` name, it should work, as long as the github token (either classic or fine grained) as permissions on the repo. Given I can't access https://github.com/ion-learning/ion-learning I presume it's private, so the token used must have more permissions (from the tutorial
"For a private repo: repo ("Full control of private repositories")")

I suspect there may be some payload issues with owner vs contributor payloads (based on what I've seen in other variations of this pattern), so I will have to investigate if that's the issue you're getting (as your repo is owned by an organisation, not yourself)

**Comment by LarryBarker** [comment]
@glasnt Thank you kindly 🙏 Going a bit out of scope here maybe, but it would be super nice to have a comment on the PR with the URL for stakeholders who aren't familiar with Github and may not know to expand PR checks and click details. This is still a leap ahead for us so educating stakeholders on how to find the URL is a small internal change.

**Comment by glasnt** [comment]
@LarryBarker You can adapt the solution to customise this for your user base. 

Add the following after creating the commit status in line https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/run/deployment-previews/check_status.py#L242:

```python
  pull_request = repo.get_issue(int(pull_request))
  pull_request.create_comment(f"View the deployment preview: {revision_url}")
```

Since this is an internal repo, you could also add links to project pages, internal documentation, etc for your stakeholders. 

After making this code update, you'll have to re-run the container build to update the code the trigger users. [From the tutorial](https://cloud.google.com/run/docs/tutorials/configure-deployment-previews#create-a-new-image-for-cloud-build):


```shell
gcloud builds submit --tag gcr.io/$PROJECT_ID/deployment-previews run/deployment-previews
```
