### ISSUE TITLE
Accidentally definition of interval in snippets.py in v3/cloud-client

### ISSUE THREAD

**Issue by meredithslota** [GoogleCloudPlatform/python-docs-samples#8977]
This issue was filed in https://github.com/googleapis/python-monitoring/issues/472 but the impacted code sample has been migrated to https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/monitoring/snippets/v3/cloud-client so copying the issue here. 

From @lennerados:

> Hi, in [this](https://github.com/googleapis/python-monitoring/blob/HEAD/samples/snippets/v3/cloud-client/snippets.py#L92) file on line 92, `interval` is initialized but never used, since it is properly redefined 5 lines later. I think this is not done on purpose and might exist by accident (also because no other example has this definition).
> 
> This code snippet is also on the official [cloud.google.com](https://cloud.google.com/monitoring/custom-metrics/reading-metrics#timeseries-list-data) documentation.

I see that the issue is still showing up in the migrated code snippet: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/monitoring/snippets/v3/cloud-client/snippets.py#L92

I'm closing out the original issue in favor of this one. Thanks!

**Comment by engelke** [comment]
Fixed in PR #8979 8979
