### ISSUE TITLE
TypeError when try to use physical_security_key_ssh.py to get private key

### ISSUE THREAD

**Issue by ENsu** [GoogleCloudPlatform/python-docs-samples#8981]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## In which file did you encounter the issue?
[compute/oslogin/physical_security_key_ssh.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/compute/oslogin/physical_security_key_ssh.py)

## Did you change the file? If so, how?
No I didn't.

## Describe the issue
I ran the comment `python3 SCRIPT_NAME.py --user_key=USER_KEY --ip_address=IP_ADDRESS` [accordingly](https://cloud.google.com/compute/docs/oslogin/security-keys#third-party-tools), however, get the error `TypeError: 'NoneType' object is not iterable`.

I check the code, it seems that the `profile` variable looks fine, but, `profile.get("securityKeys")` gets nothing in return. I think that the format of the `profile` has changed.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by m-strzelczyk** [comment]
Hello @ENsu !

I have checked the script and I recognize the error you are encountering. This error occurs when you try to use the script with an account that has no physical security key assigned to it.

Please check which account you are using for [Default Application Credentials](https://cloud.google.com/docs/authentication/application-default-credentials).

If this is the correct account, you can check if you have security keys assigned to it [here](https://myaccount.google.com/signinoptions/two-step-verification).

When I used the script with account that has a physical key assigned, it worked fine. I will update the script to better communicate in such situations. Please let me know if you have any more issues.
