### ISSUE TITLE
unexpected keyword argument error in transcribe_async.py

### ISSUE THREAD

**Issue by vijayk2000** [GoogleCloudPlatform/python-docs-samples#907]
## In which file did you encounter the issue?

GoogleCloudPlatform/python-docs-samples/transcribe_async.py

### Did you change the file? If so, how?
No

## Describe the issue
When I run the following command in the windows command prompt:
python transcribe_async.py gs://cloud-samples-tests/speech/vr.flac

I am getting a following error:

**Traceback (most recent call last):
  File "transcribe_async.py", line 100, in <module>
    transcribe_gcs(args.path)
  File "transcribe_async.py", line 71, in transcribe_gcs
    sample_rate_hertz=16000)
**TypeError: sample() got an unexpected keyword argument 'sample_rate_hertz'****

**Comment by gguuss** [comment]
It looks like you might somehow be hitting the v1beta1 endpoint instead of the v1 version. Can you try updating the cloud client library to version 0.25.1 or better? If you're interested in which version you currently have on your path, run pip freeze.

**Comment by vijayk2000** [comment]
Hi Gus,
I had upgraded to google-cloud-speech library to version 0.25.1.  Now, I am able to transcribe.  Thank you very much for your suggestion.

**Comment by ruqianq** [comment]
Hi, @gguuss I also have the same issue, I don't know how to update my cloud client library, could you help me with that, I am really new to python. thanks!

**Comment by vijayk2000** [comment]
Hi ruqianq,
 If your OS is Windows, then open the terminal and type the following command:
python -m pip freeze

Check if the Google-cloud-speech version is 0.25.1.  If not then type the following command:
python -m pip install --upgrade google-cloud

After updating the library then re-check if Google-cloud-speech has been updated to v0.25.1.
If this has not been updated then go to the following website:
     https://pypi.python.org/pypi/google-cloud-speech 
and download "google_cloud_speech-0.25.1-py2.py3-none-any.whl (md5)" 
and install it locally from the system using the following command:
python -m pip install --upgrade c:\file path

**Comment by ruqianq** [comment]
Thank you @vijayk2000 !!! It works! I am very appreciated!
