### ISSUE TITLE
ImportError: cannot import name speech

### ISSUE THREAD

**Issue by hoyeunglee** [GoogleCloudPlatform/python-docs-samples#909]
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import speech
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name speech
>>>

**Comment by jonparrott** [comment]
@hoyeunglee can you let us know which version of the library you're using? Run `pip freeze` to get a list of all installed packages and their versions.

@gguuss can you take a look?

**Comment by gguuss** [comment]
@hoyeunglee Did you run `pip install -r requirements.txt` in a virtual environment to install the libraries?

**Comment by engelke** [comment]
This is not occurring any more, and no response, so closing the issue.
