### ISSUE TITLE
Failing test: DLP: test_inspect_bigquery

### ISSUE THREAD

**Issue by Sita04** [GoogleCloudPlatform/python-docs-samples#9164]
Test fails with error "Table not found". Needs inspection.
Skipped in migration PR: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9091/commits/b433f6479df54c1ed3d3677d62fc138208161272

**Comment by kweinmeister** [comment]
@leahecole Just saw this now :)

Here's what I see: dlp_test_project is in the list of opt-out regexes for Reaper (so it does get deleted). However, this test creates a new table here:
```
@pytest.fixture(scope="module")
def bigquery_project():
...
table = bigquery_client.create_table(table)
```

**Comment by msampathkumar** [comment]
Hi @Sita04, can we close this request or is still WIP?

**Comment by rsamborski** [comment]
@annadata Can your team PTAL at this one?

**Comment by Avani-Thakker** [comment]
Hi, the issue mentioned here seems to use some old code. Ideally, this shouldn't have caused an issue since we had mocked this particular test case as part of PR #10455 . Please check.
