### ISSUE TITLE
DLP sample: Better documentation for supported_content_types

### ISSUE THREAD

**Issue by Sita04** [GoogleCloudPlatform/python-docs-samples#9197]
Migrating sample improvement request from python-dlp repository (https://github.com/googleapis/python-dlp/issues/490)

Reported by @GalBezalel-RecoLabs

Is your feature request related to a problem? Please describe.
While working with the python snippet for inspecting a local file, I was surprised by the fact that there were only a handful of [content type indexes](https://github.com/googleapis/python-dlp/blob/4023f60c2047a20ac1f8629654241b5b28198403/samples/snippets/inspect_content.py#L395-L402) given in the snippet, as this mapping seems to lack a lot of other important content types.

Describe the solution you'd like
Thesupported_content_types dictionary in the snippet can either be:

Expended explicitly
Refer to the [relevant proto definition](https://github.com/googleapis/googleapis/blob/9d6497f0f81f000562fc4fc5df8c4fcc8e09e864/google/privacy/dlp/v2/dlp.proto#L828-L874) specifying all other content types.
In addition, it would be preferable if the mapping will be defined outside the inspect_content function in terms of readability and maintainable code.

**Comment by irudykss** [comment]
content type indexes in comming up
