### ISSUE TITLE
app.yaml: the library "httplib2" is not supported

### ISSUE THREAD

**Issue by jin09** [GoogleCloudPlatform/python-docs-samples#924]
## Describe the issue

The code works fine offline but as soon as I deploy the code on the gcloud server the console prompts with an error "app.yaml: the library "httplib2" is not supported"

**Comment by jonparrott** [comment]
Hi @jin09, which sample were you using?

**Comment by jonparrott** [comment]
Hi @jin09, our mailgun sample requires you to [vendor](https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27#vendoring) in httplib2. If you're using our sample, you just need to run `pip install -t lib -r requirements.txt`.
