### ISSUE TITLE
Certificate request Using an auto-generated key.

### ISSUE THREAD

**Issue by Rena-2022** [GoogleCloudPlatform/python-docs-samples#9255]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/privateca/snippets/create_certificate.py#L46

## Did you change the file? If so, how?
Did not change any

## Describe the issue

While requesting a certificate from gcloud-cli via autogenerated key we would just specify the outfiles to get new pub/private key of the certificate files. like this https://cloud.google.com/certificate-authority-service/docs/requesting-certificates#gcloud_1

I am trying to establish the same using this library, but could not able to understand 
[public_key_bytes: public key used in signing the certificates] parameter for create_certificate function https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/privateca/snippets/create_certificate.py#L46

It is referring to create kms-key or use existing one two create public_key. Cant we do this automatically in the same way how gcloud cli does.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by dandhlee** [comment]
Hey @Sita04, can you help take a look at this?

**Comment by rsamborski** [comment]
Hi @Rena-2022,

Thanks for reaching out. I suggest taking a look at our [testing code](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/291e31411bd48a4261a5166bd55f08884e3d4124/privateca/snippets/test_certificates.py#L52C1-L52C1) which shows how to create a private/public key pair using RSA library.

Let me know if this helps to solve the issue you mentioned above.

**Comment by rsamborski** [comment]
Closing as there was no response. @Rena-2022 feel free to reopen if the issue is still valid.
