### ISSUE TITLE
Execute dataflow jobs consecutively?

### ISSUE THREAD

**Issue by belwalshubham** [GoogleCloudPlatform/python-docs-samples#9264]
Hey folks

Here is the apache beam custom pipeline code (dataflow).
```
def run_pipeline(jdbc_url, username, password, types, wisgen_table, recruiter_table, last_sync_table):

options = PipelineOptions()
p = beam.Pipeline(options=options)
 
last_sync_data = (
 p | "Read last sync data" >> ReadFromBigQuery(
                query='SELECT MAX(time) as last_sync FROM '
                '[wisdomcircle-350611:custom_test_data.last_sync]')
 | "Extract last sync time" >> beam.Map(lambda elem: elem['last_sync'])
 )


wisgen_data = p | "wisgen job" >> ReadFromJdbc (
jdbc_url=jdbc_url,
username=username,
password=password,
driver_class_name='org.postgresql.Driver',
query="""SELECT users.id AS user_id, where to_char(users.updated_at,'YYYY-MM-DD HH24:MI:SS') >= '{last_sync_data}' """,
table_name="users"
)

recruiter_data = p | "recruiter job" >> ReadFromJdbc(
jdbc_url=jdbc_url,
username=username,
password=password,
driver_class_name='org.postgresql.Driver',
query="""SELECT users.id AS user_id, where to_char(users.updated_at,'YYYY-MM-DD HH24:MI:SS') >= '{last_sync_data}'""",
table_name="users"
)

wisgen_data | "Convert TableRow to dict(wisgen data)" >> beam.Map(
lambda row: row._asdict()
) | "Write to BigQuery in wisgen data table" >> WriteToBigQuery(
wisgen_table,
write_disposition=beam.io.BigQueryDisposition.WRITE_APPEND,
create_disposition=beam.io.BigQueryDisposition.CREATE_IF_NEEDED,
schema='user_id:INTEGER,full_name:STRING)


recruiter_data | "Convert TableRow to dict(recruiter data)" >> beam.Map(
lambda row: row._asdict())
 | "Write to BigQuery in recruiter data table" >> WriteToBigQuery(
recruiter_table,
write_disposition=beam.io.BigQueryDisposition.WRITE_APPEND,
create_disposition=beam.io.BigQueryDisposition.CREATE_IF_NEEDED,
schema='user_id:INTEGER,full_name:STRING'
)

# this must be runs at last when all obove are finished 
_ = (p
| "Create current timestamp" >> beam.Create([{'time': datetime.datetime.utcnow()}])
| "Write to last_sync" >> WriteToBigQuery,
last_sync_tab
schema='time:TIMESTAMP',
write_disposition=beam.io.BigQueryDisposition.WRITE_TRUNCATE,
create_disposition=beam.io.BigQueryDisposition.CREATE_IF_NEEDED,
)

if __name__ == '__main__':
run_pipeline(
        jdbc_url='xxxx',
        username='xxxx',
        password='xxxx',
        wisgen_table='wisdomcircle-350611:uat_custom_dataset.wisgen_data_table',
        recruiter_table='wisdomcircle-350611:uat_custom_dataset.recruiter_data_table',
        last_sync_table='wisdomcircle-350611:uat_custom_dataset.last_sync',
    )
   ```

The pipeline operates asynchronously or completes all job operations in parallel, but I want to first execute the starting job last_sync_data (which is written at the beginning of the above code), and at last, my timstamp (which is written at the end of the above code) job should run when all the above operations are finished.

Can somebody assist me in rewriting the code I have above to meet my needs ?

**requirement**: `last_sync_data` should run first since it retrieves the last sync time.
`wisgen_data` and `recruiter_data` can run in parallel since they are independent of each other. 
The last job that writes the current timestamp should run only after all previous jobs are finished.

Should this be accomplished using cloud run, if yes then how ? , or is there another option?

**Comment by dazuma** [comment]
@belwalshubham Please don't tag individuals on issues like this. Most of the people you tagged (including myself) do not work in this area and/or are not even at Google anymore.

**Comment by leahecole** [comment]
edited to remove individuals tagged, triaged to proper person

**Comment by davidcavazos** [comment]
Having said that. The second pipeline is just writing a single entry to a table so launching an entire new Dataflow pipeline seems a little wasteful. After running the first pipeline, you could manually write that row using the BigQuery client library. Again, just make sure to keep the process running until the very end.

**Comment by dandhlee** [comment]
I'll close this issue for the same reason as I specified in https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9264.

* Please **only** open issues that pertain to **sample code within the repository**. This repository is **not** a general help section for Google Cloud and/or for Google Cloud for Python.
