### ISSUE TITLE
OSError: Project was not passed and could not be determined from the environment.

### ISSUE THREAD

**Issue by cclauss** [GoogleCloudPlatform/python-docs-samples#929]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/async_query.py#L44

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/snippets.py#L36

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/quickstart.py#L24

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/sync_query.py#L33

(Others...)

### Did you change the file? If so, how?

Nope.

## Describe the issue

If I do not provide a `project` parameter to `bigquery.Client()`, I get:

```
client = bigquery.Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Python/google_cloud/env/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 83, in __init__
    project=project, credentials=credentials, _http=_http)
  File "~/Python/google_cloud/env/lib/python3.6/site-packages/google/cloud/client.py", line 211, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "~/Python/google_cloud/env/lib/python3.6/site-packages/google/cloud/client.py", line 169, in __init__
    raise EnvironmentError('Project was not passed and could not be '
OSError: Project was not passed and could not be determined from the environment.
```

But when I `bigquery.Client(project="My Valid Project")` then the call succeeds.

**Comment by jonparrott** [comment]
@cclauss this is working as intended. If you have gcloud installed, you can do `gcloud config set project <your-project-id>` and it'll be automatically detected. If you're using a service account with `GOOGLE_APPLICATION_CREDENTIALS`, it'll pull the project from the service account.

**Comment by cclauss** [comment]
Thanks @jonparrott that got me unstuck.  Your first suggestion worked but not the second.  Anyway, I can now successfully make queries!  My next snag is SQL syntax errors.

```python
#!/usr/bin/env python
"""
BigQuery does not like the `:` in the line: `[the-psf:pypi.downloads]`
"""

from async_query import async_query

# Third query from https://langui.sh/2016/12/09/data-driven-decisions/

QUERY = """SELECT
  file.project,
  COUNT(*) as total_downloads
FROM
  TABLE_DATE_RANGE(
    [the-psf:pypi.downloads],
    DATE_ADD(CURRENT_TIMESTAMP(), -31, "day"),
    DATE_ADD(CURRENT_TIMESTAMP(), -1, "day")
  )
GROUP BY
  file.project
ORDER BY
  total_downloads DESC
LIMIT 100"""

if __name__ == '__main__':
    async_query(QUERY)
"""
$ python bigquery_pypi.py
Traceback (most recent call last):
  File "bigquery_pypi.py", line 26, in <module>
    async_query(QUERY)
  File "~/Python/google_cloud/async_query.py", line 48, in async_query
    wait_for_job(query_job)
  File "~/Python/google_cloud/async_query.py", line 37, in wait_for_job
    raise RuntimeError(job.errors)
RuntimeError: [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Expected "," or "]" but got ":" at [6:13]'}]
"""
```

**Comment by jonparrott** [comment]
@tswast can verify, but I think you need to make sure you're not using legacy sql.

**Comment by tswast** [comment]
@jonparrott @cclauss That's right. It appears as though your query is using legacy SQL. To update the sample to use legacy SQL, set [use_legacy_sql = True](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/10b9a90e8f6bec63f8aa98a7dbf1338c32e6e9eb/bigquery/cloud-client/async_query.py#L46)

**Comment by tswast** [comment]
See: https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql for more ways to switch between standard and legacy syntax.

**Comment by cclauss** [comment]
PERFECT!!  Thanks guys!
