### ISSUE TITLE
Executing a BigQuery from App Engine fails due to login

### ISSUE THREAD

**Issue by yuri-wisestamp** [GoogleCloudPlatform/python-docs-samples#935]
The BigQuery documentation page sends here when clicking Client Library -> show on GitHub. I didn't find a better place to post.

Trying to run a query that puts filtered data from one dataset to another, using a task on App Engine. The query runs as expected when running from BigQuery console. When running the task from App Engine by accessing the URL of the task, it executes, but gives and error of Login Required:
```
{
    error: {
        errors: [
            {
                domain: "global",
                reason: "required",
                message: "Login Required",
                locationType: "header",
                location: "Authorization"
            }
        ],
        code: 401,
        message: "Login Required"
    }
}
```
I've added the service account to both data sets in BQ, still no luck. Please advise.

**Comment by jonparrott** [comment]
@yufengg can you show us the code you're using to construct a BQ client?

**Comment by yuri-wisestamp** [comment]
@jonparrott sure, here it is:

```
from googleapiclient import discovery
from oauth2client.client import GoogleCredentials

credentials = GoogleCredentials.get_application_default()
self.bigquery = discovery.build('bigquery', 'v2', credentials=credentials)
```

**Comment by jonparrott** [comment]
@yuri-wisestamp that should work, you're using App Engine standard, correct?

@tswast can you think of any reason why BigQuery wouldn't accept app engine's auth?

**Comment by annegentle** [comment]
Stumbled across this while looking into building a simple app, and had a question on best practices. This [example](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/auth_snippets.py) seems to look for credentials in the environment with a `service_account.json` file. Is that the recommended practice?

**Comment by tswast** [comment]
Using the App Engine service account should be fine. The only problem I'd anticipate is that if you do external queries of sheets or drive, the service account won't have the right scopes for those APIs.

**Comment by jonparrott** [comment]
Closing for now.
