### ISSUE TITLE
easy interface to load data into datastore

### ISSUE THREAD

**Issue by itismewxg** [GoogleCloudPlatform/python-docs-samples#940]
## Describe the issue
The link https://cloud.google.com/appengine/docs/standard/python/datastore/creating-entities 
you give under above file(dir) does not exist (404)

btw, it is really hard to find a easy interface to do the loading data to datastore.

**Comment by jonparrott** [comment]
The correct link is https://cloud.google.com/appengine/docs/standard/python/ndb/creating-entities
