### ISSUE TITLE
Google Speech API not working with en-IN

### ISSUE THREAD

**Issue by tcsj** [GoogleCloudPlatform/python-docs-samples#947]
I am trying to do streaming speech recognition using this code:

https://github.com/mainyaa/speech-api-python-demo/blob/master/grpc/transcribe_streaming.py

It works fine with en-US language but when I try to use it with en-IN or any other language such as en-GB , it takes very long time (about 1 minute).

I have tried to port it to the latest SDK but it is having the same issue:

https://gist.github.com/tcsj/94cd5a864c44ca1d79bdce2f1137bfea

**Comment by jonparrott** [comment]
@class, can you take a look?

**Comment by jonparrott** [comment]
@gguuss can you take a look?

**Comment by gguuss** [comment]
@tcsj any reason you can't use [the Cloud client library](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech/cloud-client) instead of the grpc layer?

**Comment by crash13override** [comment]
I'm experiencing this issue also with the NodeJS version.
Sometimes (like 10% of the times) it works and recognize the first sentence, but beside that it never works with any language that is not "en-US"

**Comment by engelke** [comment]
If there are still issues, they may be with the API itself, and not with the sample code in this repository. You can report and track bugs for that at https://cloud.google.com/support/docs/issue-trackers
