### ISSUE TITLE
Outdated ML Engine API version

### ISSUE THREAD

**Issue by nkashy1** [GoogleCloudPlatform/python-docs-samples#949]
## In which file did you encounter the issue?
[File](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/ml_engine/online_prediction/predict.py)

[Line 1](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/ml_engine/online_prediction/predict.py#L46), [Line 2](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/ml_engine/online_prediction/predict.py#L83)

### Did you change the file? If so, how?

No, but I will shortly create a PR to fix this.

## Describe the issue

The samples use version `v1beta1` of the API but the current version is `v1`. Ran into this because there was an issue deploying a model for prediction with `v1beta1` which disappeared in version `v1`.

**Comment by nkashy1** [comment]
[Here is the PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/950)

**Comment by elibixby** [comment]
PR #917 resolves this, but there are testing concerns, where the CI testing tool is inadequate. Thanks for filing!

**Comment by elibixby** [comment]
Fixed via #917 Thanks for the report!
