### ISSUE TITLE
Is a web streaming example available for the Could Speech API?

### ISSUE THREAD

**Issue by dknesek** [GoogleCloudPlatform/python-docs-samples#955]
I am basically looking for how to implement the example on this page: https://cloud.google.com/speech/

Which is this: https://www.gstatic.com/cloud-devrel/ux/speech.min.html

I specifically want to stream from and to a webpage. Any help would be greatly appreciated.

**Comment by jonparrott** [comment]
@gguuss might be able to point you in the right direction.

In general, this sort of broad question is better suited for stackoverflow. :)

**Comment by gguuss** [comment]
I have [a relatively naive sample implemented here](https://github.com/GoogleCloudPlatform/web-docs-samples/tree/master/speech).
