### ISSUE TITLE
Django Tutorial requirements.txt error 

### ISSUE THREAD

**Issue by lanec** [GoogleCloudPlatform/python-docs-samples#956]
## In which file did you encounter the issue?

While going through the process of setting up the Django Tutorial app on my local machine I was asked to install the requirements using pip install -r requirements.txt 

### Did you change the file? If so, how?

I did nothing to modify the files

## Describe the issue

The output from the install presented the following error: 

`Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-xp_b0b6_/mysqlclient/`

## My computer
Mac OS X 10.12.5
Python 3.6.1

**Comment by waprin** [comment]
Have you tried `brew install mysql`?

**Comment by lanec** [comment]
I followed the tutorial provided by Google at: https://cloud.google.com/python/django/flexible-environment

It states that we are going to be using PostgreSQL for local development (and cloud).  I ended up commenting the mysql client out of the requirements.txt and completed the installation from there.

**Comment by hanzvanaardt** [comment]
Remove the mysql installation requirement from the requirements.txt to resolve the issue you are encountering.
