### ISSUE TITLE
`bigtable/autoscaler/README.rst` broken

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/python-docs-samples#957]
[`bigtable/autoscaler/README.rst`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigtable/autoscaler/README.rst) seems to have some issues:

* several links are of the form \`...\`_ (which suggests it's rendering ReST, not HTML); when clicking on them, they don't go anywhere, but to a non-existent (auto-generated?) anchor on the same page

* command line samples seem to have both quoting and `fixed-width font`, is that intentional?

/cc: @waprin

**Comment by waprin** [comment]
Yes I had a broken link in my input and the general template also had a broken links ,thanks for noticing ,made PR to fix.

The code samples should all be fixed width, looks like they all are to me.
