### ISSUE TITLE
quota issues for secret manager

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#9600]
#9556 has failing presubmits because we are exceeding our "write requests per minute" quota, possibly a side effect of #9491

![png](https://user-images.githubusercontent.com/6719667/231491018-21ffb868-2255-4959-a0e8-2875890b7dcd.png)

To access this view, we can go to quotas, then select secret manager write requests per minute, and click on the little graph icon on the right

<img width="1212" alt="Screenshot 2023-04-12 at 10 34 36 AM" src="https://user-images.githubusercontent.com/6719667/231491379-7b852aa3-d0a3-4f93-944d-766198a13fd5.png">

**Comment by engelke** [comment]
Test changes seem to have worked
