### ISSUE TITLE
Documentation is outdated for "enable_word_time_offsets=True"

### ISSUE THREAD

**Issue by atulep** [GoogleCloudPlatform/python-docs-samples#9639]
This is a copy of the https://github.com/googleapis/python-speech/issues/445. The issue is with sample snippets. 

Line no 44 in this file: https://github.com/googleapis/python-speech/blob/HEAD/samples/snippets/transcribe_word_time_offsets.py

It should be enable_word_time_offsets=1

And on another Google documentation page it shows camelCase format! https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig

**Comment by dandhlee** [comment]
Andy, can you help take a look at this?

**Comment by andrewferlitsch** [comment]
@dandhlee I don't oversee code snippets, just notebooks. With the reorgs, I would ask Karl W on whom covers this now.

**Comment by jping0220** [comment]
Hi, I took a little time to look at this problem and ran the test with both "enable_word_time_offsets=1" and "enable_word_time_offsets= True" without any problem. If the problem consistent for you please feel feel to reopen the issue. Thank you
