### ISSUE TITLE
The test project has +400 secrets due to testing that need to be cleaned up

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/python-docs-samples#9643]
Transferring this issue from https://github.com/googleapis/python-secret-manager/issues/55

This issue is related to the samples for secretmanager [here](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/secretmanager/snippets).

>The test project has +2000 secrets due to testing that need to be cleaned up. Tests should be reviewed for proper clean up.

> https://cloud.google.com/secret-manager/docs/creating-and-managing-expiring-secrets adds a feature to set a [TTL](https://google.aip.dev/214) on the Secret resource which schedules the secret for deletion.

> Another alternative is a test case that just lists and deletes secrets older a predefined duration.

The issue is several years old, although there are still a large number of secrets (>400) that could be cleaned up during testing.

**Comment by irudykss** [comment]
TTL update is comming up
