### ISSUE TITLE
Error when running appengine/standard/flask/hello_world sample

### ISSUE THREAD

**Issue by ashamia** [GoogleCloudPlatform/python-docs-samples#970]
## In which file did you encounter the issue?

appengine/standard/flask/hello_world

### Did you change the file? If so, how?

no

## Describe the issue

after cloning the git rep, I did  pip install -t lib -r requirements.txt
and got the following error:

```
File "/Users/assafshamia/Freebird/Techradar/dev/samples/env/lib/python2.7/site-packages/setuptools/py27compat.py", line 7, in <module>
        import six
    ImportError: No module named six

```

**Comment by jonparrott** [comment]
Hi @ashamia, this is due to a bug in [setuptools](https://github.com/pypa/setuptools/issues/1042). You should be able to get this to work if you reinstall setuptools.
