### ISSUE TITLE
Authenticate users locally IAP

### ISSUE THREAD

**Issue by mdepachtere-adeo** [GoogleCloudPlatform/python-docs-samples#9717]
Hello, I already have an API working on app engine and I try to implement a client to this API that will be built as a python library.

I don't have any problem using my API with other app deployed in gcp and I don't have any problem to reach my API through my GCP logged-in browser.

The problem come when I want to use my client locally to reach my API.

I started by using a `make_iap_request` function like we can found in some [repositories](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/145036e004a75e59fb43b86e829f4c01cf57078b/iap/make_iap_request.py#L23). 
When I do such API calls, I get a
```shell
Traceback (most recent call last):
  File "test.py", line 71, in <module>
    make_iap_request(URL, client_id=AUDIENCE)
  File "test.py", line 51, in make_iap_request
    open_id_connect_token = id_token.fetch_id_token(Request(), client_id)
  File "/lib/python3.10/site-packages/google/oauth2/id_token.py", line 339, in fetch_id_token
    id_token_credentials = fetch_id_token_credentials(audience, request=request)
  File "/lib/python3.10/site-packages/google/oauth2/id_token.py", line 296, in fetch_id_token_credentials
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: Neither metadata server or valid service account credentials are found.
```
because I'm not running in a GCP context (metadata server) and I'm not providing any SA credentials (valid service account credentials)

I want the library really easy to use so I want to embed any authentication mechanism in it and not ask for the user to generate a json creds files or anything else.

What is the correct way to authenticate to IAP (or something else if I have to change the way I authenticate) when running the code locally ?

Thank you for your help

**Comment by engelke** [comment]
I'm not clear on *where* you intend to run this code. Right now, you run it on your own workstation. Is that the target environment?

You need to have application default credentials available for an account with the necessary privilege wherever you run the code. On a Google Cloud compute platform, there is a metadata server that provides those automatically. Elsewhere, you'll need to provide them.

The pages at https://cloud.google.com/docs/authentication/application-default-credentials and https://cloud.google.com/docs/authentication/provide-credentials-adc have information on how this works and how to use it.

**Comment by engelke** [comment]
StackOverflow is a good place to find information from other developers who likely have worked on the same kind of issue you have.
