### ISSUE TITLE
StatusCode.DEADLINE_EXCEEDED executing execute_streaming_sql

### ISSUE THREAD

**Issue by dr3x** [GoogleCloudPlatform/python-docs-samples#975]
## In which file did you encounter the issue?

\Lib\site-packages\google\cloud\spanner\database.py

### Did you change the file? If so, how?
no

## Describe the issue

Take a SQL query that works from the UI and execute it via the streaming method and I get the DEADLINE_EXCEEDED error message:

`results = database.spanner_api.execute_streaming_sql(session.name, sql, query_mode=ExecuteSqlRequest.QueryMode.NORMAL)`

```
>>> results.code()
<StatusCode.DEADLINE_EXCEEDED: (4, 'deadline exceeded')>
```

**Comment by jonparrott** [comment]
@lukesneeringer any ideas on this?

**Comment by jabubake** [comment]
@jsimonweb FYI

**Comment by engelke** [comment]
See issue #2211 for status of this.
