### ISSUE TITLE
Example in the code is not relevant

### ISSUE THREAD

**Issue by Thierrynjike** [GoogleCloudPlatform/python-docs-samples#9750]
for this file, [https://github.com/googleapis/python-storage/blob/HEAD/samples/snippets/storage_list_files_with_prefix.py](url) from line 26 to 49, the example used is not relevant because the used prefix is the bucket root.
This is my proposition of more relevant example:
Given the following blobs:
a/b
a/c/x
a/b/d/e
a/b/d/f
if you pass 'd/ as the prefix, you'll get back the following blobs:
d/e
d/f
However, if you pass b/ as the prefix, yo'll get back the following blobs
b/d/e
b/d/f

**Comment by leahecole** [comment]
Hi @Thierrynjike, I've migrated this issue to the repo where the relevant code is and am closing this one. Please subscribe to this issue for further updates. https://github.com/googleapis/python-storage/issues/1020
