### ISSUE TITLE
Invalid command in cloud-client/notification_polling.py

### ISSUE THREAD

**Issue by kislyuk** [GoogleCloudPlatform/python-docs-samples#976]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/cloud-client/notification_polling.py#L34

### Did you change the file? If so, how?

No

## Describe the issue

The command doesn't work:
```
>gsutil notification create -f json -t testtopic gs://testbucket/
CommandException: Invalid subcommand "create" for the notification command.
```

**Comment by engelke** [comment]
The gsutil command does have notification create command. This may have been environmental or an old version issue. Since the command in the file does work now, closing this issue.
