### ISSUE TITLE
Question : I want to use microphone with transcribe_streaming.py. 

### ISSUE THREAD

**Issue by dongkeuny50** [GoogleCloudPlatform/python-docs-samples#978]
## In which file did you encounter the issue?
I think there was a method to use microphone with streaming.py but today 2017/06/11 there is no code for microphone in transcribe_streaming.py. 

## Describe the issue
 If i want to use microphone with transcribe_streaming.py, do i need to write another python code?
Please help me... thank you.

**Comment by jerjou** [comment]
[Here you go!](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming_mic.py)
