### ISSUE TITLE
Unable to use streaming.py to stream IoT data stream in google datastore data into BigQuery 

### ISSUE THREAD

**Issue by evanhenry** [GoogleCloudPlatform/python-docs-samples#980]
## In which file did you encounter the issue?

python-docs-samples/bigquery/api/streaming.py

### Did you change the file? If so, how?

no modification of the file 

## Describe the issue

I cannot figure out how to stream the IoT data that is streaming into datastore into BigQuery. I have set up a empty big query table with an identical schema, but I do not see anyway to specify a path to the datastore data location.

Is it possible to use bigquery.tabledata().insertAll() for streaming a stream in datastore to big query?

**Comment by jonparrott** [comment]
@tswast any ideas?

**Comment by tswast** [comment]
There is no built-in streaming path to go from Datastore to BigQuery as far as I know. What is supported is making a Datastore backup (exported to Cloud Storage) and loading the backup into BigQuery with a load job.

**Comment by evanhenry** [comment]
Tswast. thank you for the quick feedback. 

I was under the impression that it was possible to stream directly into BQ from datastore. 

Do you have any recommendations or ideas on how to create a data pipeline for real-time data analytics from data in datastore? Maybe instead scheduling backups every 1 hour for example? The IoT device is connected through pub/sub, it is possible to go straight from pub/sub to big query instead of to datastore?

Thanks
evan

**Comment by tswast** [comment]
Scheduling backups is an option, though I'd prefer going straight from Pub/Sub to BigQuery.

We have one example with a Pub/Sub subscriber living on Kubernetes and pushing to BigQuery. https://cloud.google.com/solutions/real-time/kubernetes-pubsub-bigquery

You could also use Cloud Dataflow for this, which supports a Pub/Sub source and a BigQuery sink. I'm having trouble digging up an example that does it, unfortunately.

**Comment by tswast** [comment]
For using Dataflow, this appears to be a good guide: https://medium.com/google-cloud/infinite-backup-for-cloud-pub-sub-62021b679c51

**Comment by engelke** [comment]
Previous comments address this issue.
