### ISSUE TITLE
appengine/standard/blobstore/gcs sample app doesn't work

### ISSUE THREAD

**Issue by ukrukarg** [GoogleCloudPlatform/python-docs-samples#983]
## In which file did you encounter the issue?

appengine/standard/blobstore/gcs sample app

### Did you change the file? If so, how?

No

## Describe the issue

After `gcloud app deploy` app fails to serve with error:

> Traceback (most recent call last):
>   File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
>     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
>   File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 351, in __getattr__
>     self._update_configs()
>   File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 287, in _update_configs
>     self._registry.initialize()
>   File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 160, in initialize
>     import_func(self._modname)
>   File "/base/data/home/apps/e~stofe-europe/20170613t121617.401947357178050939/appengine_config.py", line 18, in <module>
>     vendor.add('lib')
>   File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/vendor/__init__.py", line 44, in add
>     'No such virtualenv or site directory' % path)
> ValueError: virtualenv: cannot access lib: No such virtualenv or site directory

**Comment by jonparrott** [comment]
Hi @ukrukarg, did you run `pip install -t lib -r requirements.txt` before deploying?

**Comment by ukrukarg** [comment]
No I didn't.
I'm not actually following the docs, just looking for a sample blobstore app.

Works now.
